// src/lib/exports.ts
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
} from 'docx'
import { saveAs } from 'file-saver'

// ---------- Types aligned to runtime shapes (null-safe on joins) -------------
interface Legend {
  id: string
  score: number
  description: string
  created_at: string
}

interface Category {
  id: string
  name: string
  type: 'ADL' | 'IADL' | string
  ada_definition?: string
  ot_definition?: string
  sort_order?: number
  created_at?: string
}

interface Question {
  id: string
  category_id: string
  question_text: string
  sort_order: number
  created_at?: string
}

interface CategoryWithQuestions extends Category {
  questions: Question[]
}

type FormType = 'ADL' | 'IADL' | 'COMPREHENSIVE' | null | undefined

interface ObservationWithResponses {
  id: string
  user_id: string
  patient_name: string | null
  observation_date: string // YYYY-MM-DD
  date_of_observation?: string | null
  mode_of_observation?: 'In Person' | 'Voice Call' | 'Video Call'
  notes: string | null
  caregiver_name: string | null
  caregiver_email: string | null
  created_at: string
  updated_at: string
  form_type?: FormType
  // Each response may or may not have the joined question/category
  responses: Array<{
    id: string
    observation_id: string
    question_id: string
    score: number
    notes: string | null
    category_notes?: string | null
    created_at: string
    updated_at: string
    question?: {
      id: string
      question_text: string
      sort_order: number
      category?: {
        id: string
        name: string
        type: 'ADL' | 'IADL'
      } | null
    } | null
  }>
}

// ---------- Helpers ----------------------------------------------------------
const formTypeLabel = (t: FormType) =>
  t === 'COMPREHENSIVE' ? 'Comprehensive (ADL + IADL)' : t || '—'

const colorForScore = (score: number) => {
  // hex (no #) strings for docx
  // 1–2 = red-ish, 3 = amber/blue-ish, 4–5 = green-ish
  if (score >= 4) return '059669' // green-600
  if (score >= 3) return '0ea5e9' // sky-500
  return 'dc2626' // red-600
}

const safeFile = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '_')

// ---------- DOCX -------------------------------------------------------------
export const exportToDOCX = async (
  observation: ObservationWithResponses,
  categories: CategoryWithQuestions[],
  legend: Legend[]
) => {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: 'CarerView Observation Report',
                bold: true,
                size: 32,
                color: '2563eb',
              }),
            ],
            spacing: { after: 400 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: 'This report is generated by CarerView, a family caregiving tool. It is designed to be shared with healthcare providers to support clinical decision-making.',
                size: 20,
                italics: true,
                color: '6b7280',
              }),
            ],
            spacing: { after: 400 },
          }),

          new Paragraph({
            children: [new TextRun({ text: 'Person Observed', bold: true, size: 28, underline: {} })],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Name: ${observation.patient_name || 'Not specified'}`,
                size: 24,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Observation Date: ${new Date(observation.observation_date).toLocaleDateString()}`,
                size: 24,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Observation Type: ${formTypeLabel(observation.form_type)}`,
                size: 24,
              }),
            ],
          }),
          ...(observation.mode_of_observation
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `Mode: ${observation.mode_of_observation}`,
                      size: 24,
                    }),
                  ],
                }),
              ]
            : []),
          new Paragraph({
            children: [
              new TextRun({
                text: `Report Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
                size: 24,
              }),
            ],
            spacing: { after: 400 },
          }),

          ...(observation.caregiver_name
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `Observed by: ${observation.caregiver_name}`,
                      size: 24,
                    }),
                  ],
                }),
              ]
            : []),

          ...(observation.notes
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: 'Caregiver Notes',
                      bold: true,
                      size: 28,
                      underline: {},
                    }),
                  ],
                  spacing: { before: 400, after: 200 },
                }),
                new Paragraph({
                  children: [new TextRun({ text: observation.notes, size: 24 })],
                  spacing: { after: 400 },
                }),
              ]
            : []),

          // Assessment Results header
          new Paragraph({
            children: [
              new TextRun({ text: 'Assessment Results', bold: true, size: 28, underline: {} }),
            ],
            spacing: { before: 200, after: 200 },
          }),

          // Results by category
          ...categories.flatMap((category) => {
            const categoryResponses = (observation.responses || []).filter(
              (r) => r.question?.category?.id === category.id
            )
            if (categoryResponses.length === 0) return []

            const categoryNotes =
              categoryResponses.length > 0 ? categoryResponses[0].category_notes : null

            return [
              new Paragraph({
                children: [
                  new TextRun({
                    text: `${category.name} (${category.type ?? 'ADL'})`,
                    bold: true,
                    size: 26,
                    color: '1f2937',
                  }),
                ],
                spacing: { before: 300, after: 200 },
              }),

              new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1 },
                  bottom: { style: BorderStyle.SINGLE, size: 1 },
                  left: { style: BorderStyle.SINGLE, size: 1 },
                  right: { style: BorderStyle.SINGLE, size: 1 },
                  insideHorizontal: { style: BorderStyle.SINGLE, size: 1 },
                  insideVertical: { style: BorderStyle.SINGLE, size: 1 },
                },
                rows: [
                  // header row
                  new TableRow({
                    children: [
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Question', bold: true, size: 22 })],
                          }),
                        ],
                        width: { size: 60, type: WidthType.PERCENTAGE },
                      }),
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Score', bold: true, size: 22 })],
                          }),
                        ],
                        width: { size: 15, type: WidthType.PERCENTAGE },
                      }),
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Description', bold: true, size: 22 })],
                          }),
                        ],
                        width: { size: 25, type: WidthType.PERCENTAGE },
                      }),
                    ],
                  }),
                  // data rows
                  ...categoryResponses.map((response) =>
                    new TableRow({
                      children: [
                        new TableCell({
                          children: [
                            new Paragraph({
                              children: [
                                new TextRun({
                                  text:
                                    response.question?.question_text ||
                                    '(question unavailable)',
                                  size: 20,
                                }),
                              ],
                            }),
                          ],
                        }),
                        new TableCell({
                          children: [
                            new Paragraph({
                              children: [
                                new TextRun({
                                  text: `${response.score}/5`,
                                  bold: true,
                                  size: 20,
                                  color: colorForScore(response.score),
                                }),
                              ],
                            }),
                          ],
                        }),
                        new TableCell({
                          children: [
                            new Paragraph({
                              children: [
                                new TextRun({
                                  text:
                                    legend.find((l) => l.score === response.score)?.description ||
                                    '',
                                  size: 20,
                                }),
                              ],
                            }),
                          ],
                        }),
                      ],
                    })
                  ),
                ],
              }),

              ...(categoryNotes
                ? [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: `${category.name} Category Notes:`,
                          bold: true,
                          size: 22,
                          color: '374151',
                        }),
                      ],
                      spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                      children: [new TextRun({ text: categoryNotes, size: 20, color: '4b5563' })],
                      spacing: { after: 200 },
                    }),
                  ]
                : []),

              new Paragraph({ text: '', spacing: { after: 200 } }),
            ]
          }),

          // Legend
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: 'CARERVIEW 1–5 ADL SCALE',
                bold: true,
                size: 32,
                color: '1f2937',
              }),
            ],
            spacing: { before: 600, after: 200 },
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text:
                  '1 = Needs full help | 2 = Needs a lot of help | 3 = Needs some help | 4 = Mostly on their own | 5 = Fully on their own',
                size: 20,
                color: '374151',
              }),
            ],
            spacing: { after: 300 },
          }),

          new Paragraph({
            children: [new TextRun({ text: 'Scoring Legend', bold: true, size: 28, underline: {} })],
            spacing: { before: 100, after: 200 },
          }),

          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 1 },
              bottom: { style: BorderStyle.SINGLE, size: 1 },
              left: { style: BorderStyle.SINGLE, size: 1 },
              right: { style: BorderStyle.SINGLE, size: 1 },
              insideHorizontal: { style: BorderStyle.SINGLE, size: 1 },
              insideVertical: { style: BorderStyle.SINGLE, size: 1 },
            },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: 'Score', bold: true, size: 22 })],
                      }),
                    ],
                    width: { size: 20, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: 'Description', bold: true, size: 22 })],
                      }),
                    ],
                    width: { size: 80, type: WidthType.PERCENTAGE },
                  }),
                ],
              }),
              ...legend
                .slice()
                .sort((a, b) => a.score - b.score)
                .map((item) =>
                  new TableRow({
                    children: [
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [
                              new TextRun({
                                text: item.score.toString(),
                                bold: true,
                                size: 20,
                                color: colorForScore(item.score),
                              }),
                            ],
                          }),
                        ],
                      }),
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: item.description, size: 20 })],
                          }),
                        ],
                      }),
                    ],
                  })
                ),
            ],
          }),
        ],
      },
    ],
  })

  const buffer = await Packer.toBuffer(doc)
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  })
  const fileName = `observation-${safeFile(observation.patient_name || 'unnamed')}-${
    observation.observation_date
  }.docx`
  saveAs(blob, fileName)
}

// ---------- CSV --------------------------------------------------------------
export const exportToCSV = async (
  observation: ObservationWithResponses,
  categories: CategoryWithQuestions[],
  legend: Legend[]
) => {
  const escapeCSV = (value: unknown): string => {
    const s = (value ?? '').toString()
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"`
      : s
  }

  const headers = [
    'Patient Name',
    'Observation Date',
    'Observation Type',
    'Mode',
    'Category',
    'Category Type',
    'Question',
    'Score',
    'Score Description',
    'Question Notes',
    'Category Notes',
  ]

  const rows: string[][] = []

  ;(observation.responses || []).forEach((response) => {
    const category = response.question?.category
    const legendDescription = legend.find((l) => l.score === response.score)?.description || ''
    rows.push([
      observation.patient_name || 'Unnamed Patient',
      observation.observation_date,
      formTypeLabel(observation.form_type),
      observation.mode_of_observation || '',
      category?.name || '',
      category?.type || '',
      response.question?.question_text || '',
      response.score?.toString() || '',
      legendDescription,
      response.notes || '',
      response.category_notes || '',
    ])
  })

  if (rows.length === 0) {
    rows.push([
      observation.patient_name || 'Unnamed Patient',
      observation.observation_date,
      formTypeLabel(observation.form_type),
      observation.mode_of_observation || '',
      '',
      '',
      'No responses recorded',
      '',
      '',
      '',
      observation.notes || '',
    ])
  }

  const csvContent = [
    ['CarerView Observation Report'],
    ['Generated:', new Date().toLocaleString()],
    ['Person Observed:', observation.patient_name || 'Not specified'],
    ['Observed By:', observation.caregiver_name || ''],
    [''],
    ['Caregiver Notes:', observation.notes || 'None'],
    [''],
    headers,
    ...rows,
    [''],
    ['Scoring Legend:'],
    ['Score', 'Description'],
    ...legend
      .slice()
      .sort((a, b) => a.score - b.score)
      .map((item) => [item.score.toString(), item.description]),
  ]
    .map((row) => row.map(escapeCSV).join(','))
    .join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const fileName = `observation-${safeFile(observation.patient_name || 'unnamed')}-${
    observation.observation_date
  }.csv`
  saveAs(blob, fileName)
}
