/*
  # Memory Book i18n Translation Keys

  ## Summary
  Seeds all `memory_book.*` translation keys into `ui_translations` for all 7 supported
  locales: en, es, it, fr, de, sv, fi.

  ## New Translation Keys (130 keys × 7 locales)
  Covers the complete Memory Book feature surface:
  - Section navigation labels (identity, contacts, medical, preferences)
  - Read-only banner notice
  - Identity section: all field labels, placeholders, empty states, toasts
  - Contacts section: all field labels, placeholders, empty states, toasts, confirm dialog
  - Medical section: all field labels, placeholders, empty states, toasts
  - Preferences section: all field labels, placeholders, empty states, toasts
  - Overview tab: age display, progress panel, incomplete warnings, coming-soon card
  - Shared UI: save, saving, edit, cancel, role badges

  ## Locales
  en (English), es (Spanish), it (Italian), fr (French), de (German), sv (Swedish), fi (Finnish)

  ## Notes
  - Uses ON CONFLICT DO UPDATE so re-running is safe
  - Interpolation placeholders ({patientName}, {count}, {name}, {age}, {completed}, {total})
    are preserved verbatim in all locales
*/

INSERT INTO public.ui_translations (locale, key, value) VALUES

-- SECTION LABELS
('en','memory_book.section_identity','Identity'),
('es','memory_book.section_identity','Identidad'),
('it','memory_book.section_identity','Identità'),
('fr','memory_book.section_identity','Identité'),
('de','memory_book.section_identity','Identität'),
('sv','memory_book.section_identity','Identitet'),
('fi','memory_book.section_identity','Henkilöllisyys'),

('en','memory_book.section_contacts','Contacts'),
('es','memory_book.section_contacts','Contactos'),
('it','memory_book.section_contacts','Contatti'),
('fr','memory_book.section_contacts','Contacts'),
('de','memory_book.section_contacts','Kontakte'),
('sv','memory_book.section_contacts','Kontakter'),
('fi','memory_book.section_contacts','Yhteystiedot'),

('en','memory_book.section_medical','Medical'),
('es','memory_book.section_medical','Médico'),
('it','memory_book.section_medical','Medico'),
('fr','memory_book.section_medical','Médical'),
('de','memory_book.section_medical','Medizinisch'),
('sv','memory_book.section_medical','Medicinsk'),
('fi','memory_book.section_medical','Lääketieteellinen'),

('en','memory_book.section_preferences','Likes & Dislikes'),
('es','memory_book.section_preferences','Gustos y disgustos'),
('it','memory_book.section_preferences','Preferenze'),
('fr','memory_book.section_preferences','Goûts et aversions'),
('de','memory_book.section_preferences','Vorlieben & Abneigungen'),
('sv','memory_book.section_preferences','Gillanden & ogillanden'),
('fi','memory_book.section_preferences','Mieltymykset'),

-- READ-ONLY BANNER
('en','memory_book.readonly_notice','You have view access to this section. Only team owners can make changes.'),
('es','memory_book.readonly_notice','Tienes acceso de solo lectura a esta sección. Solo los propietarios del equipo pueden realizar cambios.'),
('it','memory_book.readonly_notice','Hai accesso in sola lettura a questa sezione. Solo i proprietari del team possono apportare modifiche.'),
('fr','memory_book.readonly_notice','Vous avez un accès en lecture seule à cette section. Seuls les propriétaires de l''équipe peuvent effectuer des modifications.'),
('de','memory_book.readonly_notice','Sie haben Lesezugriff auf diesen Bereich. Nur Teambesitzer können Änderungen vornehmen.'),
('sv','memory_book.readonly_notice','Du har läsåtkomst till det här avsnittet. Endast teamägare kan göra ändringar.'),
('fi','memory_book.readonly_notice','Sinulla on vain lukuoikeus tähän osioon. Vain tiimin omistajat voivat tehdä muutoksia.'),

-- IDENTITY SECTION
('en','memory_book.identity_title','Identity & Profile'),
('es','memory_book.identity_title','Identidad y perfil'),
('it','memory_book.identity_title','Identità e profilo'),
('fr','memory_book.identity_title','Identité et profil'),
('de','memory_book.identity_title','Identität und Profil'),
('sv','memory_book.identity_title','Identitet och profil'),
('fi','memory_book.identity_title','Henkilöllisyys ja profiili'),

('en','memory_book.identity_subtitle','Personal details for {patientName}'),
('es','memory_book.identity_subtitle','Datos personales de {patientName}'),
('it','memory_book.identity_subtitle','Dettagli personali di {patientName}'),
('fr','memory_book.identity_subtitle','Informations personnelles de {patientName}'),
('de','memory_book.identity_subtitle','Persönliche Angaben für {patientName}'),
('sv','memory_book.identity_subtitle','Personuppgifter för {patientName}'),
('fi','memory_book.identity_subtitle','Henkilökohtaiset tiedot henkilölle {patientName}'),

('en','memory_book.identity_empty_owner_title','Add identity information'),
('es','memory_book.identity_empty_owner_title','Agregar información de identidad'),
('it','memory_book.identity_empty_owner_title','Aggiungi informazioni sull''identità'),
('fr','memory_book.identity_empty_owner_title','Ajouter des informations d''identité'),
('de','memory_book.identity_empty_owner_title','Identitätsinformationen hinzufügen'),
('sv','memory_book.identity_empty_owner_title','Lägg till identitetsinformation'),
('fi','memory_book.identity_empty_owner_title','Lisää henkilöllisyystiedot'),

('en','memory_book.identity_empty_owner_desc','Record preferred name, birthplace, cultural background, and a brief personal summary to help caregivers connect meaningfully.'),
('es','memory_book.identity_empty_owner_desc','Registre el nombre preferido, lugar de nacimiento, origen cultural y un breve resumen personal para ayudar a los cuidadores a conectar de manera significativa.'),
('it','memory_book.identity_empty_owner_desc','Registra il nome preferito, il luogo di nascita, il background culturale e un breve riassunto personale per aiutare i caregiver a connettersi in modo significativo.'),
('fr','memory_book.identity_empty_owner_desc','Enregistrez le nom préféré, le lieu de naissance, l''origine culturelle et un bref résumé personnel pour aider les aidants à établir un lien significatif.'),
('de','memory_book.identity_empty_owner_desc','Erfassen Sie bevorzugten Namen, Geburtsort, kulturellen Hintergrund und eine kurze persönliche Zusammenfassung, um Pflegenden eine sinnvolle Verbindung zu ermöglichen.'),
('sv','memory_book.identity_empty_owner_desc','Registrera föredraget namn, födelseort, kulturell bakgrund och en kort personlig sammanfattning för att hjälpa vårdare att skapa meningsfulla kontakter.'),
('fi','memory_book.identity_empty_owner_desc','Kirjaa suosittu nimi, syntymäpaikka, kulttuurinen tausta ja lyhyt henkilökohtainen yhteenveto auttaaksesi hoitajia luomaan merkityksellisiä yhteyksiä.'),

('en','memory_book.identity_empty_member_title','Identity not yet completed'),
('es','memory_book.identity_empty_member_title','Identidad aún no completada'),
('it','memory_book.identity_empty_member_title','Identità non ancora completata'),
('fr','memory_book.identity_empty_member_title','Identité pas encore complétée'),
('de','memory_book.identity_empty_member_title','Identität noch nicht ausgefüllt'),
('sv','memory_book.identity_empty_member_title','Identiteten har inte fyllts i ännu'),
('fi','memory_book.identity_empty_member_title','Henkilöllisyyttä ei ole vielä täytetty'),

('en','memory_book.identity_empty_member_desc','The team owner needs to fill in the identity section before it appears here.'),
('es','memory_book.identity_empty_member_desc','El propietario del equipo debe completar la sección de identidad antes de que aparezca aquí.'),
('it','memory_book.identity_empty_member_desc','Il proprietario del team deve compilare la sezione identità prima che appaia qui.'),
('fr','memory_book.identity_empty_member_desc','Le propriétaire de l''équipe doit remplir la section identité avant qu''elle apparaisse ici.'),
('de','memory_book.identity_empty_member_desc','Der Teambesitzer muss den Identitätsabschnitt ausfüllen, bevor er hier erscheint.'),
('sv','memory_book.identity_empty_member_desc','Teamägaren måste fylla i identitetsavsnittet innan det visas här.'),
('fi','memory_book.identity_empty_member_desc','Tiimin omistajan täytyy täyttää henkilöllisyysosio ennen kuin se näkyy tässä.'),

('en','memory_book.identity_add_btn','Add Identity Details'),
('es','memory_book.identity_add_btn','Agregar detalles de identidad'),
('it','memory_book.identity_add_btn','Aggiungi dettagli identità'),
('fr','memory_book.identity_add_btn','Ajouter les détails d''identité'),
('de','memory_book.identity_add_btn','Identitätsdetails hinzufügen'),
('sv','memory_book.identity_add_btn','Lägg till identitetsuppgifter'),
('fi','memory_book.identity_add_btn','Lisää henkilöllisyystiedot'),

('en','memory_book.field_preferred_name','Preferred Name / Nickname'),
('es','memory_book.field_preferred_name','Nombre preferido / Apodo'),
('it','memory_book.field_preferred_name','Nome preferito / Soprannome'),
('fr','memory_book.field_preferred_name','Nom préféré / Surnom'),
('de','memory_book.field_preferred_name','Bevorzugter Name / Spitzname'),
('sv','memory_book.field_preferred_name','Föredraget namn / Smeknamn'),
('fi','memory_book.field_preferred_name','Suosittu nimi / Lempinimi'),

('en','memory_book.field_preferred_name_placeholder','What name do they prefer?'),
('es','memory_book.field_preferred_name_placeholder','¿Qué nombre prefieren?'),
('it','memory_book.field_preferred_name_placeholder','Quale nome preferiscono?'),
('fr','memory_book.field_preferred_name_placeholder','Quel nom préfèrent-ils ?'),
('de','memory_book.field_preferred_name_placeholder','Welchen Namen bevorzugen sie?'),
('sv','memory_book.field_preferred_name_placeholder','Vilket namn föredrar de?'),
('fi','memory_book.field_preferred_name_placeholder','Mitä nimeä he mieluiten käyttävät?'),

('en','memory_book.field_address_pref','How they like to be addressed'),
('es','memory_book.field_address_pref','Cómo les gusta que se les llame'),
('it','memory_book.field_address_pref','Come preferiscono essere chiamati'),
('fr','memory_book.field_address_pref','Comment ils aiment être appelés'),
('de','memory_book.field_address_pref','Wie sie angesprochen werden möchten'),
('sv','memory_book.field_address_pref','Hur de föredrar att tillfrågas'),
('fi','memory_book.field_address_pref','Miten heitä mieluiten kutsutaan'),

('en','memory_book.field_address_pref_placeholder','e.g. Mrs. Smith, Gran, first name only'),
('es','memory_book.field_address_pref_placeholder','p. ej. Sra. García, Abuela, solo el primer nombre'),
('it','memory_book.field_address_pref_placeholder','es. Sig.ra Rossi, Nonna, solo nome di battesimo'),
('fr','memory_book.field_address_pref_placeholder','ex. Mme Dupont, Grand-mère, prénom seulement'),
('de','memory_book.field_address_pref_placeholder','z.B. Frau Müller, Oma, nur Vorname'),
('sv','memory_book.field_address_pref_placeholder','t.ex. Fru Svensson, Mormor, endast förnamn'),
('fi','memory_book.field_address_pref_placeholder','esim. Rouva Mäkinen, Mummo, vain etunimi'),

('en','memory_book.field_birthplace','Birthplace'),
('es','memory_book.field_birthplace','Lugar de nacimiento'),
('it','memory_book.field_birthplace','Luogo di nascita'),
('fr','memory_book.field_birthplace','Lieu de naissance'),
('de','memory_book.field_birthplace','Geburtsort'),
('sv','memory_book.field_birthplace','Födelseort'),
('fi','memory_book.field_birthplace','Syntymäpaikka'),

('en','memory_book.field_birthplace_placeholder','Town, city, or region'),
('es','memory_book.field_birthplace_placeholder','Pueblo, ciudad o región'),
('it','memory_book.field_birthplace_placeholder','Città, comune o regione'),
('fr','memory_book.field_birthplace_placeholder','Ville, commune ou région'),
('de','memory_book.field_birthplace_placeholder','Ort, Stadt oder Region'),
('sv','memory_book.field_birthplace_placeholder','By, stad eller region'),
('fi','memory_book.field_birthplace_placeholder','Kaupunki, kunta tai alue'),

('en','memory_book.field_relationship_status','Relationship Status'),
('es','memory_book.field_relationship_status','Estado civil'),
('it','memory_book.field_relationship_status','Stato civile'),
('fr','memory_book.field_relationship_status','Situation familiale'),
('de','memory_book.field_relationship_status','Beziehungsstatus'),
('sv','memory_book.field_relationship_status','Civilstånd'),
('fi','memory_book.field_relationship_status','Siviilisääty'),

('en','memory_book.field_relationship_status_placeholder','e.g. Widowed, Married'),
('es','memory_book.field_relationship_status_placeholder','p. ej. Viudo/a, Casado/a'),
('it','memory_book.field_relationship_status_placeholder','es. Vedovo/a, Sposato/a'),
('fr','memory_book.field_relationship_status_placeholder','ex. Veuf/veuve, Marié(e)'),
('de','memory_book.field_relationship_status_placeholder','z.B. Verwitwet, Verheiratet'),
('sv','memory_book.field_relationship_status_placeholder','t.ex. Änka/änkling, Gift'),
('fi','memory_book.field_relationship_status_placeholder','esim. Leski, Naimisissa'),

('en','memory_book.field_cultural_bg','Cultural Background'),
('es','memory_book.field_cultural_bg','Origen cultural'),
('it','memory_book.field_cultural_bg','Sfondo culturale'),
('fr','memory_book.field_cultural_bg','Contexte culturel'),
('de','memory_book.field_cultural_bg','Kultureller Hintergrund'),
('sv','memory_book.field_cultural_bg','Kulturell bakgrund'),
('fi','memory_book.field_cultural_bg','Kulttuurinen tausta'),

('en','memory_book.field_cultural_bg_placeholder','Cultural identity, traditions, practices'),
('es','memory_book.field_cultural_bg_placeholder','Identidad cultural, tradiciones, prácticas'),
('it','memory_book.field_cultural_bg_placeholder','Identità culturale, tradizioni, pratiche'),
('fr','memory_book.field_cultural_bg_placeholder','Identité culturelle, traditions, pratiques'),
('de','memory_book.field_cultural_bg_placeholder','Kulturelle Identität, Traditionen, Praktiken'),
('sv','memory_book.field_cultural_bg_placeholder','Kulturell identitet, traditioner, seder'),
('fi','memory_book.field_cultural_bg_placeholder','Kulttuurinen identiteetti, perinteet, käytännöt'),

('en','memory_book.field_language_prefs','Language / Communication Preferences'),
('es','memory_book.field_language_prefs','Preferencias de idioma / comunicación'),
('it','memory_book.field_language_prefs','Preferenze linguistiche / comunicative'),
('fr','memory_book.field_language_prefs','Préférences linguistiques / de communication'),
('de','memory_book.field_language_prefs','Sprach- / Kommunikationspräferenzen'),
('sv','memory_book.field_language_prefs','Språk- / kommunikationspreferenser'),
('fi','memory_book.field_language_prefs','Kieli- / kommunikointimieltymykset'),

('en','memory_book.field_language_prefs_placeholder','Primary language, communication style'),
('es','memory_book.field_language_prefs_placeholder','Idioma principal, estilo de comunicación'),
('it','memory_book.field_language_prefs_placeholder','Lingua principale, stile comunicativo'),
('fr','memory_book.field_language_prefs_placeholder','Langue principale, style de communication'),
('de','memory_book.field_language_prefs_placeholder','Hauptsprache, Kommunikationsstil'),
('sv','memory_book.field_language_prefs_placeholder','Primärt språk, kommunikationsstil'),
('fi','memory_book.field_language_prefs_placeholder','Ensisijainen kieli, viestintätyyli'),

('en','memory_book.field_about_me','About Me — Personal Summary'),
('es','memory_book.field_about_me','Sobre mí — Resumen personal'),
('it','memory_book.field_about_me','Su di me — Riepilogo personale'),
('fr','memory_book.field_about_me','À propos de moi — Résumé personnel'),
('de','memory_book.field_about_me','Über mich — Persönliche Zusammenfassung'),
('sv','memory_book.field_about_me','Om mig — Personlig sammanfattning'),
('fi','memory_book.field_about_me','Minusta — Henkilökohtainen yhteenveto'),

('en','memory_book.field_about_me_placeholder','What would this person want others to know about them? Describe their personality, passions, and what makes them who they are...'),
('es','memory_book.field_about_me_placeholder','¿Qué querría que otros supieran sobre esta persona? Describe su personalidad, pasiones y lo que la hace ser quien es...'),
('it','memory_book.field_about_me_placeholder','Cosa vorrebbe che gli altri sapessero di questa persona? Descrivi la sua personalità, le sue passioni e ciò che la rende unica...'),
('fr','memory_book.field_about_me_placeholder','Que voudrait que les autres sachent de cette personne ? Décrivez sa personnalité, ses passions et ce qui fait d''elle ce qu''elle est...'),
('de','memory_book.field_about_me_placeholder','Was möchte diese Person, dass andere über sie wissen? Beschreiben Sie ihre Persönlichkeit, Leidenschaften und was sie ausmacht...'),
('sv','memory_book.field_about_me_placeholder','Vad skulle den här personen vilja att andra visste om dem? Beskriv deras personlighet, passioner och vad som gör dem till den de är...'),
('fi','memory_book.field_about_me_placeholder','Mitä tämä henkilö haluaisi muiden tietävän hänestä? Kuvaile hänen persoonallisuuttaan, intohimojaan ja sitä, mikä tekee hänestä juuri hänen...'),

('en','memory_book.label_preferred_name','Preferred Name'),
('es','memory_book.label_preferred_name','Nombre preferido'),
('it','memory_book.label_preferred_name','Nome preferito'),
('fr','memory_book.label_preferred_name','Nom préféré'),
('de','memory_book.label_preferred_name','Bevorzugter Name'),
('sv','memory_book.label_preferred_name','Föredraget namn'),
('fi','memory_book.label_preferred_name','Suosittu nimi'),

('en','memory_book.label_address','How to Address'),
('es','memory_book.label_address','Cómo dirigirse'),
('it','memory_book.label_address','Come rivolgersi'),
('fr','memory_book.label_address','Comment s''adresser'),
('de','memory_book.label_address','Anrede'),
('sv','memory_book.label_address','Hur man tilltalar'),
('fi','memory_book.label_address','Miten puhutella'),

('en','memory_book.label_birthplace','Birthplace'),
('es','memory_book.label_birthplace','Lugar de nacimiento'),
('it','memory_book.label_birthplace','Luogo di nascita'),
('fr','memory_book.label_birthplace','Lieu de naissance'),
('de','memory_book.label_birthplace','Geburtsort'),
('sv','memory_book.label_birthplace','Födelseort'),
('fi','memory_book.label_birthplace','Syntymäpaikka'),

('en','memory_book.label_relationship_status','Relationship Status'),
('es','memory_book.label_relationship_status','Estado civil'),
('it','memory_book.label_relationship_status','Stato civile'),
('fr','memory_book.label_relationship_status','Situation familiale'),
('de','memory_book.label_relationship_status','Beziehungsstatus'),
('sv','memory_book.label_relationship_status','Civilstånd'),
('fi','memory_book.label_relationship_status','Siviilisääty'),

('en','memory_book.label_cultural_bg','Cultural Background'),
('es','memory_book.label_cultural_bg','Origen cultural'),
('it','memory_book.label_cultural_bg','Sfondo culturale'),
('fr','memory_book.label_cultural_bg','Contexte culturel'),
('de','memory_book.label_cultural_bg','Kultureller Hintergrund'),
('sv','memory_book.label_cultural_bg','Kulturell bakgrund'),
('fi','memory_book.label_cultural_bg','Kulttuurinen tausta'),

('en','memory_book.label_language_prefs','Language Preferences'),
('es','memory_book.label_language_prefs','Preferencias de idioma'),
('it','memory_book.label_language_prefs','Preferenze linguistiche'),
('fr','memory_book.label_language_prefs','Préférences linguistiques'),
('de','memory_book.label_language_prefs','Sprachpräferenzen'),
('sv','memory_book.label_language_prefs','Språkpreferenser'),
('fi','memory_book.label_language_prefs','Kielimieltymykset'),

('en','memory_book.label_about_me','About Me'),
('es','memory_book.label_about_me','Sobre mí'),
('it','memory_book.label_about_me','Su di me'),
('fr','memory_book.label_about_me','À propos de moi'),
('de','memory_book.label_about_me','Über mich'),
('sv','memory_book.label_about_me','Om mig'),
('fi','memory_book.label_about_me','Minusta'),

('en','memory_book.toast_identity_saved','Identity saved'),
('es','memory_book.toast_identity_saved','Identidad guardada'),
('it','memory_book.toast_identity_saved','Identità salvata'),
('fr','memory_book.toast_identity_saved','Identité enregistrée'),
('de','memory_book.toast_identity_saved','Identität gespeichert'),
('sv','memory_book.toast_identity_saved','Identitet sparad'),
('fi','memory_book.toast_identity_saved','Henkilöllisyys tallennettu'),

-- CONTACTS SECTION
('en','memory_book.contacts_title','Care Network & Contacts'),
('es','memory_book.contacts_title','Red de cuidados y contactos'),
('it','memory_book.contacts_title','Rete di cura e contatti'),
('fr','memory_book.contacts_title','Réseau de soins et contacts'),
('de','memory_book.contacts_title','Pflegenetzwerk und Kontakte'),
('sv','memory_book.contacts_title','Vårднätverk och kontakter'),
('fi','memory_book.contacts_title','Hoitoverkosto ja yhteystiedot'),

('en','memory_book.contacts_count_one','1 contact on file'),
('es','memory_book.contacts_count_one','1 contacto registrado'),
('it','memory_book.contacts_count_one','1 contatto in archivio'),
('fr','memory_book.contacts_count_one','1 contact enregistré'),
('de','memory_book.contacts_count_one','1 Kontakt gespeichert'),
('sv','memory_book.contacts_count_one','1 kontakt registrerad'),
('fi','memory_book.contacts_count_one','1 yhteystieto tallennettu'),

('en','memory_book.contacts_count_many','{count} contacts on file'),
('es','memory_book.contacts_count_many','{count} contactos registrados'),
('it','memory_book.contacts_count_many','{count} contatti in archivio'),
('fr','memory_book.contacts_count_many','{count} contacts enregistrés'),
('de','memory_book.contacts_count_many','{count} Kontakte gespeichert'),
('sv','memory_book.contacts_count_many','{count} kontakter registrerade'),
('fi','memory_book.contacts_count_many','{count} yhteystietoa tallennettu'),

('en','memory_book.contacts_add_btn','Add Contact'),
('es','memory_book.contacts_add_btn','Agregar contacto'),
('it','memory_book.contacts_add_btn','Aggiungi contatto'),
('fr','memory_book.contacts_add_btn','Ajouter un contact'),
('de','memory_book.contacts_add_btn','Kontakt hinzufügen'),
('sv','memory_book.contacts_add_btn','Lägg till kontakt'),
('fi','memory_book.contacts_add_btn','Lisää yhteystieto'),

('en','memory_book.contacts_add_first_btn','Add First Contact'),
('es','memory_book.contacts_add_first_btn','Agregar primer contacto'),
('it','memory_book.contacts_add_first_btn','Aggiungi primo contatto'),
('fr','memory_book.contacts_add_first_btn','Ajouter le premier contact'),
('de','memory_book.contacts_add_first_btn','Ersten Kontakt hinzufügen'),
('sv','memory_book.contacts_add_first_btn','Lägg till första kontakt'),
('fi','memory_book.contacts_add_first_btn','Lisää ensimmäinen yhteystieto'),

('en','memory_book.contacts_empty_title','No contacts added yet'),
('es','memory_book.contacts_empty_title','Aún no se han agregado contactos'),
('it','memory_book.contacts_empty_title','Nessun contatto aggiunto ancora'),
('fr','memory_book.contacts_empty_title','Aucun contact ajouté pour l''instant'),
('de','memory_book.contacts_empty_title','Noch keine Kontakte hinzugefügt'),
('sv','memory_book.contacts_empty_title','Inga kontakter har lagts till ännu'),
('fi','memory_book.contacts_empty_title','Yhteystietoja ei ole vielä lisätty'),

('en','memory_book.contacts_empty_desc','Add family members, doctors, emergency contacts, and other key support people to help caregivers reach the right person quickly.'),
('es','memory_book.contacts_empty_desc','Agregue familiares, médicos, contactos de emergencia y otras personas clave para ayudar a los cuidadores a comunicarse con la persona correcta rápidamente.'),
('it','memory_book.contacts_empty_desc','Aggiungi familiari, medici, contatti di emergenza e altre figure chiave per aiutare i caregiver a contattare rapidamente la persona giusta.'),
('fr','memory_book.contacts_empty_desc','Ajoutez des membres de la famille, des médecins, des contacts d''urgence et d''autres personnes clés pour aider les aidants à joindre rapidement la bonne personne.'),
('de','memory_book.contacts_empty_desc','Fügen Sie Familienmitglieder, Ärzte, Notfallkontakte und andere wichtige Unterstützungspersonen hinzu, damit Pflegende schnell die richtige Person erreichen können.'),
('sv','memory_book.contacts_empty_desc','Lägg till familjemedlemmar, läkare, nödkontakter och andra viktiga stödpersoner för att hjälpa vårdare att snabbt nå rätt person.'),
('fi','memory_book.contacts_empty_desc','Lisää perheenjäseniä, lääkäreitä, hätäyhteystietoja ja muita avainhenkilöitä, jotta hoitajat voivat nopeasti tavoittaa oikean henkilön.'),

('en','memory_book.contacts_new_heading','New Contact'),
('es','memory_book.contacts_new_heading','Nuevo contacto'),
('it','memory_book.contacts_new_heading','Nuovo contatto'),
('fr','memory_book.contacts_new_heading','Nouveau contact'),
('de','memory_book.contacts_new_heading','Neuer Kontakt'),
('sv','memory_book.contacts_new_heading','Ny kontakt'),
('fi','memory_book.contacts_new_heading','Uusi yhteystieto'),

('en','memory_book.contacts_edit_heading','Edit Contact'),
('es','memory_book.contacts_edit_heading','Editar contacto'),
('it','memory_book.contacts_edit_heading','Modifica contatto'),
('fr','memory_book.contacts_edit_heading','Modifier le contact'),
('de','memory_book.contacts_edit_heading','Kontakt bearbeiten'),
('sv','memory_book.contacts_edit_heading','Redigera kontakt'),
('fi','memory_book.contacts_edit_heading','Muokkaa yhteystietoa'),

('en','memory_book.field_full_name','Full Name *'),
('es','memory_book.field_full_name','Nombre completo *'),
('it','memory_book.field_full_name','Nome completo *'),
('fr','memory_book.field_full_name','Nom complet *'),
('de','memory_book.field_full_name','Vollständiger Name *'),
('sv','memory_book.field_full_name','Fullständigt namn *'),
('fi','memory_book.field_full_name','Koko nimi *'),

('en','memory_book.field_full_name_placeholder','Contact''s full name'),
('es','memory_book.field_full_name_placeholder','Nombre completo del contacto'),
('it','memory_book.field_full_name_placeholder','Nome completo del contatto'),
('fr','memory_book.field_full_name_placeholder','Nom complet du contact'),
('de','memory_book.field_full_name_placeholder','Vollständiger Name des Kontakts'),
('sv','memory_book.field_full_name_placeholder','Kontaktens fullständiga namn'),
('fi','memory_book.field_full_name_placeholder','Yhteystiedon koko nimi'),

('en','memory_book.field_relationship','Relationship'),
('es','memory_book.field_relationship','Relación'),
('it','memory_book.field_relationship','Relazione'),
('fr','memory_book.field_relationship','Relation'),
('de','memory_book.field_relationship','Beziehung'),
('sv','memory_book.field_relationship','Relation'),
('fi','memory_book.field_relationship','Suhde'),

('en','memory_book.field_relationship_placeholder','e.g. Daughter, Family Doctor'),
('es','memory_book.field_relationship_placeholder','p. ej. Hija, Médico de familia'),
('it','memory_book.field_relationship_placeholder','es. Figlia, Medico di famiglia'),
('fr','memory_book.field_relationship_placeholder','ex. Fille, Médecin de famille'),
('de','memory_book.field_relationship_placeholder','z.B. Tochter, Hausarzt'),
('sv','memory_book.field_relationship_placeholder','t.ex. Dotter, Familjeläkare'),
('fi','memory_book.field_relationship_placeholder','esim. Tytär, Perhelääkäri'),

('en','memory_book.field_role','Role'),
('es','memory_book.field_role','Rol'),
('it','memory_book.field_role','Ruolo'),
('fr','memory_book.field_role','Rôle'),
('de','memory_book.field_role','Rolle'),
('sv','memory_book.field_role','Roll'),
('fi','memory_book.field_role','Rooli'),

('en','memory_book.field_role_select','Select role...'),
('es','memory_book.field_role_select','Seleccionar rol...'),
('it','memory_book.field_role_select','Seleziona ruolo...'),
('fr','memory_book.field_role_select','Sélectionner un rôle...'),
('de','memory_book.field_role_select','Rolle auswählen...'),
('sv','memory_book.field_role_select','Välj roll...'),
('fi','memory_book.field_role_select','Valitse rooli...'),

('en','memory_book.field_phone','Phone'),
('es','memory_book.field_phone','Teléfono'),
('it','memory_book.field_phone','Telefono'),
('fr','memory_book.field_phone','Téléphone'),
('de','memory_book.field_phone','Telefon'),
('sv','memory_book.field_phone','Telefon'),
('fi','memory_book.field_phone','Puhelin'),

('en','memory_book.field_email','Email'),
('es','memory_book.field_email','Correo electrónico'),
('it','memory_book.field_email','Email'),
('fr','memory_book.field_email','E-mail'),
('de','memory_book.field_email','E-Mail'),
('sv','memory_book.field_email','E-post'),
('fi','memory_book.field_email','Sähköposti'),

('en','memory_book.field_notes','Notes'),
('es','memory_book.field_notes','Notas'),
('it','memory_book.field_notes','Note'),
('fr','memory_book.field_notes','Notes'),
('de','memory_book.field_notes','Notizen'),
('sv','memory_book.field_notes','Anteckningar'),
('fi','memory_book.field_notes','Muistiinpanot'),

('en','memory_book.field_notes_placeholder','Additional notes about this contact...'),
('es','memory_book.field_notes_placeholder','Notas adicionales sobre este contacto...'),
('it','memory_book.field_notes_placeholder','Note aggiuntive su questo contatto...'),
('fr','memory_book.field_notes_placeholder','Notes supplémentaires sur ce contact...'),
('de','memory_book.field_notes_placeholder','Weitere Notizen zu diesem Kontakt...'),
('sv','memory_book.field_notes_placeholder','Ytterligare anteckningar om denna kontakt...'),
('fi','memory_book.field_notes_placeholder','Lisämuistiinpanoja tästä yhteystiedosta...'),

('en','memory_book.contact_save_btn','Save Contact'),
('es','memory_book.contact_save_btn','Guardar contacto'),
('it','memory_book.contact_save_btn','Salva contatto'),
('fr','memory_book.contact_save_btn','Enregistrer le contact'),
('de','memory_book.contact_save_btn','Kontakt speichern'),
('sv','memory_book.contact_save_btn','Spara kontakt'),
('fi','memory_book.contact_save_btn','Tallenna yhteystieto'),

('en','memory_book.contact_fallback_label','Contact'),
('es','memory_book.contact_fallback_label','Contacto'),
('it','memory_book.contact_fallback_label','Contatto'),
('fr','memory_book.contact_fallback_label','Contact'),
('de','memory_book.contact_fallback_label','Kontakt'),
('sv','memory_book.contact_fallback_label','Kontakt'),
('fi','memory_book.contact_fallback_label','Yhteystieto'),

('en','memory_book.toast_contact_required','Contact name is required'),
('es','memory_book.toast_contact_required','El nombre del contacto es obligatorio'),
('it','memory_book.toast_contact_required','Il nome del contatto è obbligatorio'),
('fr','memory_book.toast_contact_required','Le nom du contact est obligatoire'),
('de','memory_book.toast_contact_required','Kontaktname ist erforderlich'),
('sv','memory_book.toast_contact_required','Kontaktnamn krävs'),
('fi','memory_book.toast_contact_required','Yhteystiedon nimi vaaditaan'),

('en','memory_book.toast_contact_updated','Contact updated'),
('es','memory_book.toast_contact_updated','Contacto actualizado'),
('it','memory_book.toast_contact_updated','Contatto aggiornato'),
('fr','memory_book.toast_contact_updated','Contact mis à jour'),
('de','memory_book.toast_contact_updated','Kontakt aktualisiert'),
('sv','memory_book.toast_contact_updated','Kontakt uppdaterad'),
('fi','memory_book.toast_contact_updated','Yhteystieto päivitetty'),

('en','memory_book.toast_contact_added','Contact added'),
('es','memory_book.toast_contact_added','Contacto agregado'),
('it','memory_book.toast_contact_added','Contatto aggiunto'),
('fr','memory_book.toast_contact_added','Contact ajouté'),
('de','memory_book.toast_contact_added','Kontakt hinzugefügt'),
('sv','memory_book.toast_contact_added','Kontakt tillagd'),
('fi','memory_book.toast_contact_added','Yhteystieto lisätty'),

('en','memory_book.toast_contact_failed','Failed to save contact'),
('es','memory_book.toast_contact_failed','Error al guardar el contacto'),
('it','memory_book.toast_contact_failed','Impossibile salvare il contatto'),
('fr','memory_book.toast_contact_failed','Impossible d''enregistrer le contact'),
('de','memory_book.toast_contact_failed','Kontakt konnte nicht gespeichert werden'),
('sv','memory_book.toast_contact_failed','Det gick inte att spara kontakten'),
('fi','memory_book.toast_contact_failed','Yhteystiedon tallennus epäonnistui'),

('en','memory_book.toast_contact_removed','Contact removed'),
('es','memory_book.toast_contact_removed','Contacto eliminado'),
('it','memory_book.toast_contact_removed','Contatto rimosso'),
('fr','memory_book.toast_contact_removed','Contact supprimé'),
('de','memory_book.toast_contact_removed','Kontakt entfernt'),
('sv','memory_book.toast_contact_removed','Kontakt borttagen'),
('fi','memory_book.toast_contact_removed','Yhteystieto poistettu'),

('en','memory_book.toast_contact_remove_failed','Failed to remove'),
('es','memory_book.toast_contact_remove_failed','Error al eliminar'),
('it','memory_book.toast_contact_remove_failed','Impossibile rimuovere'),
('fr','memory_book.toast_contact_remove_failed','Impossible de supprimer'),
('de','memory_book.toast_contact_remove_failed','Entfernen fehlgeschlagen'),
('sv','memory_book.toast_contact_remove_failed','Det gick inte att ta bort'),
('fi','memory_book.toast_contact_remove_failed','Poistaminen epäonnistui'),

('en','memory_book.confirm_remove_contact','Remove {name} from contacts?'),
('es','memory_book.confirm_remove_contact','¿Eliminar {name} de los contactos?'),
('it','memory_book.confirm_remove_contact','Rimuovere {name} dai contatti?'),
('fr','memory_book.confirm_remove_contact','Supprimer {name} des contacts ?'),
('de','memory_book.confirm_remove_contact','{name} aus den Kontakten entfernen?'),
('sv','memory_book.confirm_remove_contact','Ta bort {name} från kontakterna?'),
('fi','memory_book.confirm_remove_contact','Poistetaanko {name} yhteystiedoista?'),

-- MEDICAL SECTION
('en','memory_book.medical_title','Medical Context'),
('es','memory_book.medical_title','Contexto médico'),
('it','memory_book.medical_title','Contesto medico'),
('fr','memory_book.medical_title','Contexte médical'),
('de','memory_book.medical_title','Medizinischer Kontext'),
('sv','memory_book.medical_title','Medicinskt sammanhang'),
('fi','memory_book.medical_title','Lääketieteellinen asiayhteys'),

('en','memory_book.medical_subtitle','Caregiver-oriented health information — not a clinical record'),
('es','memory_book.medical_subtitle','Información de salud orientada al cuidador — no es un registro clínico'),
('it','memory_book.medical_subtitle','Informazioni sanitarie orientate al caregiver — non un registro clinico'),
('fr','memory_book.medical_subtitle','Informations de santé orientées aidant — pas un dossier clinique'),
('de','memory_book.medical_subtitle','Pflegeorientierte Gesundheitsinformationen — kein klinisches Dokument'),
('sv','memory_book.medical_subtitle','Vårdorienterad hälsoinformation — inte ett kliniskt dokument'),
('fi','memory_book.medical_subtitle','Hoitajalähtöinen terveystieto — ei kliininen asiakirja'),

('en','memory_book.medical_empty_owner_title','Add medical context'),
('es','memory_book.medical_empty_owner_title','Agregar contexto médico'),
('it','memory_book.medical_empty_owner_title','Aggiungi contesto medico'),
('fr','memory_book.medical_empty_owner_title','Ajouter un contexte médical'),
('de','memory_book.medical_empty_owner_title','Medizinischen Kontext hinzufügen'),
('sv','memory_book.medical_empty_owner_title','Lägg till medicinskt sammanhang'),
('fi','memory_book.medical_empty_owner_title','Lisää lääketieteellinen asiayhteys'),

('en','memory_book.medical_empty_owner_desc','Record conditions, allergies, hearing, vision, and medication notes to help caregivers provide safe and informed care.'),
('es','memory_book.medical_empty_owner_desc','Registre condiciones, alergias, notas de audición, visión y medicación para ayudar a los cuidadores a brindar una atención segura e informada.'),
('it','memory_book.medical_empty_owner_desc','Registra condizioni, allergie, note su udito, vista e medicinali per aiutare i caregiver a fornire cure sicure e informate.'),
('fr','memory_book.medical_empty_owner_desc','Enregistrez les affections, allergies, notes sur l''ouïe, la vue et les médicaments pour aider les aidants à fournir des soins sûrs et éclairés.'),
('de','memory_book.medical_empty_owner_desc','Erfassen Sie Erkrankungen, Allergien, Hör- und Sehhinweise sowie Medikamentennotizen, um Pflegenden sichere und informierte Pflege zu ermöglichen.'),
('sv','memory_book.medical_empty_owner_desc','Registrera tillstånd, allergier, hörsel- och synanteckningar samt läkemedelsnoteringar för att hjälpa vårdare att ge säker och välgrundad vård.'),
('fi','memory_book.medical_empty_owner_desc','Kirjaa sairaudet, allergiat, kuulo- ja näköhuomiot sekä lääkitysmuistiinpanot auttaaksesi hoitajia tarjoamaan turvallista ja tietoon perustuvaa hoitoa.'),

('en','memory_book.medical_empty_member_title','Medical information not yet completed'),
('es','memory_book.medical_empty_member_title','Información médica aún no completada'),
('it','memory_book.medical_empty_member_title','Informazioni mediche non ancora completate'),
('fr','memory_book.medical_empty_member_title','Informations médicales pas encore complétées'),
('de','memory_book.medical_empty_member_title','Medizinische Informationen noch nicht ausgefüllt'),
('sv','memory_book.medical_empty_member_title','Medicinsk information har inte fyllts i ännu'),
('fi','memory_book.medical_empty_member_title','Lääketieteellisiä tietoja ei ole vielä täytetty'),

('en','memory_book.medical_empty_member_desc','The team owner needs to fill in the medical section before it appears here.'),
('es','memory_book.medical_empty_member_desc','El propietario del equipo debe completar la sección médica antes de que aparezca aquí.'),
('it','memory_book.medical_empty_member_desc','Il proprietario del team deve compilare la sezione medica prima che appaia qui.'),
('fr','memory_book.medical_empty_member_desc','Le propriétaire de l''équipe doit remplir la section médicale avant qu''elle apparaisse ici.'),
('de','memory_book.medical_empty_member_desc','Der Teambesitzer muss den medizinischen Abschnitt ausfüllen, bevor er hier erscheint.'),
('sv','memory_book.medical_empty_member_desc','Teamägaren måste fylla i det medicinska avsnittet innan det visas här.'),
('fi','memory_book.medical_empty_member_desc','Tiimin omistajan täytyy täyttää lääketieteellinen osio ennen kuin se näkyy tässä.'),

('en','memory_book.medical_add_btn','Add Medical Information'),
('es','memory_book.medical_add_btn','Agregar información médica'),
('it','memory_book.medical_add_btn','Aggiungi informazioni mediche'),
('fr','memory_book.medical_add_btn','Ajouter des informations médicales'),
('de','memory_book.medical_add_btn','Medizinische Informationen hinzufügen'),
('sv','memory_book.medical_add_btn','Lägg till medicinsk information'),
('fi','memory_book.medical_add_btn','Lisää lääketieteelliset tiedot'),

('en','memory_book.field_conditions','Primary Conditions / Diagnosis'),
('es','memory_book.field_conditions','Condiciones principales / Diagnóstico'),
('it','memory_book.field_conditions','Condizioni principali / Diagnosi'),
('fr','memory_book.field_conditions','Affections principales / Diagnostic'),
('de','memory_book.field_conditions','Haupterkrankungen / Diagnose'),
('sv','memory_book.field_conditions','Primära tillstånd / Diagnos'),
('fi','memory_book.field_conditions','Ensisijaiset sairaudet / Diagnoosi'),

('en','memory_book.field_conditions_placeholder','List key conditions relevant to day-to-day care...'),
('es','memory_book.field_conditions_placeholder','Enumere las condiciones clave relevantes para el cuidado diario...'),
('it','memory_book.field_conditions_placeholder','Elenca le condizioni chiave rilevanti per la cura quotidiana...'),
('fr','memory_book.field_conditions_placeholder','Listez les affections clés pertinentes pour les soins quotidiens...'),
('de','memory_book.field_conditions_placeholder','Listen Sie wichtige Erkrankungen auf, die für die tägliche Pflege relevant sind...'),
('sv','memory_book.field_conditions_placeholder','Lista viktiga tillstånd relevanta för den dagliga vården...'),
