('fi','memory_book.field_conditions_placeholder','Luettele päivittäisen hoidon kannalta olennaiset sairaudet...'),

('en','memory_book.field_allergies','Allergies'),
('es','memory_book.field_allergies','Alergias'),
('it','memory_book.field_allergies','Allergie'),
('fr','memory_book.field_allergies','Allergies'),
('de','memory_book.field_allergies','Allergien'),
('sv','memory_book.field_allergies','Allergier'),
('fi','memory_book.field_allergies','Allergiat'),

('en','memory_book.field_allergies_placeholder','Food allergies, medication allergies, environmental allergies...'),
('es','memory_book.field_allergies_placeholder','Alergias alimentarias, a medicamentos, ambientales...'),
('it','memory_book.field_allergies_placeholder','Allergie alimentari, ai farmaci, ambientali...'),
('fr','memory_book.field_allergies_placeholder','Allergies alimentaires, médicamenteuses, environnementales...'),
('de','memory_book.field_allergies_placeholder','Nahrungsmittelallergien, Medikamentenallergien, Umweltallergien...'),
('sv','memory_book.field_allergies_placeholder','Matallergier, läkemedelsallergier, miljöallergier...'),
('fi','memory_book.field_allergies_placeholder','Ruoka-aineallergiat, lääkeallergiat, ympäristöallergiat...'),

('en','memory_book.field_hearing','Hearing Notes'),
('es','memory_book.field_hearing','Notas de audición'),
('it','memory_book.field_hearing','Note sull''udito'),
('fr','memory_book.field_hearing','Notes sur l''ouïe'),
('de','memory_book.field_hearing','Hörhinweise'),
('sv','memory_book.field_hearing','Hörselanteckningar'),
('fi','memory_book.field_hearing','Kuulohuomiot'),

('en','memory_book.field_hearing_placeholder','Hearing aids, preferences, tips...'),
('es','memory_book.field_hearing_placeholder','Audífonos, preferencias, consejos...'),
('it','memory_book.field_hearing_placeholder','Apparecchi acustici, preferenze, consigli...'),
('fr','memory_book.field_hearing_placeholder','Aides auditives, préférences, conseils...'),
('de','memory_book.field_hearing_placeholder','Hörgeräte, Präferenzen, Tipps...'),
('sv','memory_book.field_hearing_placeholder','Hörapparater, preferenser, tips...'),
('fi','memory_book.field_hearing_placeholder','Kuulolaitteet, mieltymykset, vinkit...'),

('en','memory_book.field_vision','Vision Notes'),
('es','memory_book.field_vision','Notas de visión'),
('it','memory_book.field_vision','Note sulla vista'),
('fr','memory_book.field_vision','Notes sur la vue'),
('de','memory_book.field_vision','Sehhinweise'),
('sv','memory_book.field_vision','Synanteckningar'),
('fi','memory_book.field_vision','Näköhuomiot'),

('en','memory_book.field_vision_placeholder','Glasses, impairments, preferences...'),
('es','memory_book.field_vision_placeholder','Gafas, problemas, preferencias...'),
('it','memory_book.field_vision_placeholder','Occhiali, problemi, preferenze...'),
('fr','memory_book.field_vision_placeholder','Lunettes, déficiences, préférences...'),
('de','memory_book.field_vision_placeholder','Brille, Beeinträchtigungen, Präferenzen...'),
('sv','memory_book.field_vision_placeholder','Glasögon, nedsättningar, preferenser...'),
('fi','memory_book.field_vision_placeholder','Silmälasit, näkövammat, mieltymykset...'),

('en','memory_book.field_medications','Medication Notes'),
('es','memory_book.field_medications','Notas de medicación'),
('it','memory_book.field_medications','Note sui farmaci'),
('fr','memory_book.field_medications','Notes sur les médicaments'),
('de','memory_book.field_medications','Medikamentenhinweise'),
('sv','memory_book.field_medications','Läkemedelsanteckningar'),
('fi','memory_book.field_medications','Lääkitysmuistiinpanot'),

('en','memory_book.field_medications_placeholder','Current medications, dosages, timing, administration notes...'),
('es','memory_book.field_medications_placeholder','Medicamentos actuales, dosis, horario, notas de administración...'),
('it','memory_book.field_medications_placeholder','Farmaci attuali, dosaggi, orari, note di somministrazione...'),
('fr','memory_book.field_medications_placeholder','Médicaments actuels, dosages, horaires, notes d''administration...'),
('de','memory_book.field_medications_placeholder','Aktuelle Medikamente, Dosierungen, Zeiten, Verabreichungshinweise...'),
('sv','memory_book.field_medications_placeholder','Aktuella läkemedel, doser, tider, administreringsnoteringar...'),
('fi','memory_book.field_medications_placeholder','Nykyiset lääkkeet, annokset, ajat, annostusmuistiinpanot...'),

('en','memory_book.field_other_medical','Other Medical Considerations'),
('es','memory_book.field_other_medical','Otras consideraciones médicas'),
('it','memory_book.field_other_medical','Altre considerazioni mediche'),
('fr','memory_book.field_other_medical','Autres considérations médicales'),
('de','memory_book.field_other_medical','Andere medizinische Überlegungen'),
('sv','memory_book.field_other_medical','Andra medicinska överväganden'),
('fi','memory_book.field_other_medical','Muut lääketieteelliset huomiot'),

('en','memory_book.field_other_medical_placeholder','Any other health information caregivers should know...'),
('es','memory_book.field_other_medical_placeholder','Cualquier otra información de salud que los cuidadores deban saber...'),
('it','memory_book.field_other_medical_placeholder','Qualsiasi altra informazione sanitaria che i caregiver dovrebbero sapere...'),
('fr','memory_book.field_other_medical_placeholder','Toute autre information de santé que les aidants devraient connaître...'),
('de','memory_book.field_other_medical_placeholder','Alle anderen Gesundheitsinformationen, die Pflegende wissen sollten...'),
('sv','memory_book.field_other_medical_placeholder','All annan hälsoinformation som vårdare bör känna till...'),
('fi','memory_book.field_other_medical_placeholder','Muut terveyteen liittyvät tiedot, jotka hoitajien tulisi tietää...'),

('en','memory_book.toast_medical_saved','Medical information saved'),
('es','memory_book.toast_medical_saved','Información médica guardada'),
('it','memory_book.toast_medical_saved','Informazioni mediche salvate'),
('fr','memory_book.toast_medical_saved','Informations médicales enregistrées'),
('de','memory_book.toast_medical_saved','Medizinische Informationen gespeichert'),
('sv','memory_book.toast_medical_saved','Medicinsk information sparad'),
('fi','memory_book.toast_medical_saved','Lääketieteelliset tiedot tallennettu'),

-- PREFERENCES SECTION
('en','memory_book.prefs_title','Likes, Dislikes & Comforts'),
('es','memory_book.prefs_title','Gustos, disgustos y consuelos'),
('it','memory_book.prefs_title','Piaceri, dispiaceri e conforti'),
('fr','memory_book.prefs_title','Goûts, aversions et réconforts'),
('de','memory_book.prefs_title','Vorlieben, Abneigungen und Trost'),
('sv','memory_book.prefs_title','Gillanden, ogillanden och tröst'),
('fi','memory_book.prefs_title','Mieltymykset, inhokit ja lohdut'),

('en','memory_book.prefs_subtitle','What brings joy, comfort, and what to avoid'),
('es','memory_book.prefs_subtitle','Lo que trae alegría, consuelo y lo que se debe evitar'),
('it','memory_book.prefs_subtitle','Cosa porta gioia, conforto e cosa evitare'),
('fr','memory_book.prefs_subtitle','Ce qui apporte joie, réconfort et ce qu''il faut éviter'),
('de','memory_book.prefs_subtitle','Was Freude und Trost bringt und was vermieden werden sollte'),
('sv','memory_book.prefs_subtitle','Vad som ger glädje, tröst och vad man bör undvika'),
('fi','memory_book.prefs_subtitle','Mikä tuo iloa, lohdutusta ja mitä tulee välttää'),

('en','memory_book.prefs_empty_owner_title','Add likes, dislikes & comforts'),
('es','memory_book.prefs_empty_owner_title','Agregar gustos, disgustos y consuelos'),
('it','memory_book.prefs_empty_owner_title','Aggiungi piaceri, dispiaceri e conforti'),
('fr','memory_book.prefs_empty_owner_title','Ajouter goûts, aversions et réconforts'),
('de','memory_book.prefs_empty_owner_title','Vorlieben, Abneigungen und Trost hinzufügen'),
('sv','memory_book.prefs_empty_owner_title','Lägg till gillanden, ogillanden och tröst'),
('fi','memory_book.prefs_empty_owner_title','Lisää mieltymykset, inhokit ja lohdut'),

('en','memory_book.prefs_empty_owner_desc','Recording what brings comfort, joy, and what to avoid helps every caregiver provide a more personal experience.'),
('es','memory_book.prefs_empty_owner_desc','Registrar lo que trae consuelo, alegría y lo que hay que evitar ayuda a cada cuidador a brindar una experiencia más personal.'),
('it','memory_book.prefs_empty_owner_desc','Registrare ciò che porta conforto, gioia e cosa evitare aiuta ogni caregiver a offrire un''esperienza più personale.'),
('fr','memory_book.prefs_empty_owner_desc','Enregistrer ce qui apporte réconfort, joie et ce qu''il faut éviter aide chaque aidant à offrir une expérience plus personnelle.'),
('de','memory_book.prefs_empty_owner_desc','Das Erfassen von Dingen, die Trost und Freude bringen, sowie was vermieden werden sollte, hilft jedem Pflegenden, eine persönlichere Erfahrung zu bieten.'),
('sv','memory_book.prefs_empty_owner_desc','Att registrera vad som ger tröst, glädje och vad man bör undvika hjälper varje vårdare att ge en mer personlig upplevelse.'),
('fi','memory_book.prefs_empty_owner_desc','Kirjaamalla mikä tuo lohdutusta, iloa ja mitä tulee välttää auttaa jokaista hoitajaa tarjoamaan henkilökohtaisemman kokemuksen.'),

('en','memory_book.prefs_empty_member_title','Preferences not yet completed'),
('es','memory_book.prefs_empty_member_title','Preferencias aún no completadas'),
('it','memory_book.prefs_empty_member_title','Preferenze non ancora completate'),
('fr','memory_book.prefs_empty_member_title','Préférences pas encore complétées'),
('de','memory_book.prefs_empty_member_title','Präferenzen noch nicht ausgefüllt'),
('sv','memory_book.prefs_empty_member_title','Preferenserna har inte fyllts i ännu'),
('fi','memory_book.prefs_empty_member_title','Mieltymyksiä ei ole vielä täytetty'),

('en','memory_book.prefs_empty_member_desc','The team owner needs to fill in the preferences section before it appears here.'),
('es','memory_book.prefs_empty_member_desc','El propietario del equipo debe completar la sección de preferencias antes de que aparezca aquí.'),
('it','memory_book.prefs_empty_member_desc','Il proprietario del team deve compilare la sezione preferenze prima che appaia qui.'),
('fr','memory_book.prefs_empty_member_desc','Le propriétaire de l''équipe doit remplir la section préférences avant qu''elle apparaisse ici.'),
('de','memory_book.prefs_empty_member_desc','Der Teambesitzer muss den Präferenzabschnitt ausfüllen, bevor er hier erscheint.'),
('sv','memory_book.prefs_empty_member_desc','Teamägaren måste fylla i preferensavsnittet innan det visas här.'),
('fi','memory_book.prefs_empty_member_desc','Tiimin omistajan täytyy täyttää mieltymysosio ennen kuin se näkyy tässä.'),

('en','memory_book.prefs_add_btn','Add Preferences'),
('es','memory_book.prefs_add_btn','Agregar preferencias'),
('it','memory_book.prefs_add_btn','Aggiungi preferenze'),
('fr','memory_book.prefs_add_btn','Ajouter des préférences'),
('de','memory_book.prefs_add_btn','Präferenzen hinzufügen'),
('sv','memory_book.prefs_add_btn','Lägg till preferenser'),
('fi','memory_book.prefs_add_btn','Lisää mieltymykset'),

('en','memory_book.field_likes','What they enjoy / makes them happy'),
('es','memory_book.field_likes','Lo que disfrutan / les hace felices'),
('it','memory_book.field_likes','Cosa apprezzano / li rende felici'),
('fr','memory_book.field_likes','Ce qu''ils apprécient / ce qui les rend heureux'),
('de','memory_book.field_likes','Was sie genießen / was sie glücklich macht'),
('sv','memory_book.field_likes','Vad de tycker om / vad som gör dem glada'),
('fi','memory_book.field_likes','Mistä he pitävät / mikä tekee heidät onnelliseksi'),

('en','memory_book.field_likes_placeholder','Activities, topics, experiences they love...'),
('es','memory_book.field_likes_placeholder','Actividades, temas, experiencias que aman...'),
('it','memory_book.field_likes_placeholder','Attività, argomenti, esperienze che amano...'),
('fr','memory_book.field_likes_placeholder','Activités, sujets, expériences qu''ils adorent...'),
('de','memory_book.field_likes_placeholder','Aktivitäten, Themen, Erlebnisse, die sie lieben...'),
('sv','memory_book.field_likes_placeholder','Aktiviteter, ämnen, upplevelser de älskar...'),
('fi','memory_book.field_likes_placeholder','Toiminnot, aiheet, kokemukset joista he pitävät...'),

('en','memory_book.field_dislikes','What they dislike'),
('es','memory_book.field_dislikes','Lo que no les gusta'),
('it','memory_book.field_dislikes','Cosa non gradiscono'),
('fr','memory_book.field_dislikes','Ce qu''ils n''aiment pas'),
('de','memory_book.field_dislikes','Was sie nicht mögen'),
('sv','memory_book.field_dislikes','Vad de ogillar'),
('fi','memory_book.field_dislikes','Mistä he eivät pidä'),

('en','memory_book.field_dislikes_placeholder','Things that cause discomfort or frustration...'),
('es','memory_book.field_dislikes_placeholder','Cosas que causan incomodidad o frustración...'),
('it','memory_book.field_dislikes_placeholder','Cose che causano disagio o frustrazione...'),
('fr','memory_book.field_dislikes_placeholder','Choses qui causent de l''inconfort ou de la frustration...'),
('de','memory_book.field_dislikes_placeholder','Dinge, die Unbehagen oder Frustration verursachen...'),
('sv','memory_book.field_dislikes_placeholder','Saker som orsakar obehag eller frustration...'),
('fi','memory_book.field_dislikes_placeholder','Asiat jotka aiheuttavat epämukavuutta tai turhautumista...'),

('en','memory_book.field_foods_liked','Foods they enjoy'),
('es','memory_book.field_foods_liked','Alimentos que disfrutan'),
('it','memory_book.field_foods_liked','Cibi che gradiscono'),
('fr','memory_book.field_foods_liked','Aliments qu''ils apprécient'),
('de','memory_book.field_foods_liked','Lebensmittel, die sie mögen'),
('sv','memory_book.field_foods_liked','Mat de gillar'),
('fi','memory_book.field_foods_liked','Ruoat joista he pitävät'),

('en','memory_book.field_foods_liked_placeholder','Favourite foods, meals, snacks...'),
('es','memory_book.field_foods_liked_placeholder','Comidas favoritas, platos, bocadillos...'),
('it','memory_book.field_foods_liked_placeholder','Cibi preferiti, pasti, spuntini...'),
('fr','memory_book.field_foods_liked_placeholder','Aliments préférés, repas, collations...'),
('de','memory_book.field_foods_liked_placeholder','Lieblingsessen, Mahlzeiten, Snacks...'),
('sv','memory_book.field_foods_liked_placeholder','Favoritmat, måltider, mellanmål...'),
('fi','memory_book.field_foods_liked_placeholder','Suosikkiruoat, ateriat, välipalat...'),

('en','memory_book.field_foods_disliked','Foods they dislike or avoid'),
('es','memory_book.field_foods_disliked','Alimentos que no les gustan o evitan'),
('it','memory_book.field_foods_disliked','Cibi che non gradiscono o evitano'),
('fr','memory_book.field_foods_disliked','Aliments qu''ils n''aiment pas ou évitent'),
('de','memory_book.field_foods_disliked','Lebensmittel, die sie nicht mögen oder vermeiden'),
('sv','memory_book.field_foods_disliked','Mat de ogillar eller undviker'),
('fi','memory_book.field_foods_disliked','Ruoat joista he eivät pidä tai joita he välttävät'),

('en','memory_book.field_foods_disliked_placeholder','Food dislikes, texture aversions...'),
('es','memory_book.field_foods_disliked_placeholder','Disgusto por alimentos, aversiones a texturas...'),
('it','memory_book.field_foods_disliked_placeholder','Avversioni alimentari, problemi con le consistenze...'),
('fr','memory_book.field_foods_disliked_placeholder','Aversions alimentaires, aversions aux textures...'),
('de','memory_book.field_foods_disliked_placeholder','Abneigungen gegen Lebensmittel, Texturabneigungen...'),
('sv','memory_book.field_foods_disliked_placeholder','Matavsmak, texturavsmak...'),
('fi','memory_book.field_foods_disliked_placeholder','Ruoka-aineiden inhokit, koostumusallergia...'),

('en','memory_book.field_music','Music preferences'),
('es','memory_book.field_music','Preferencias musicales'),
('it','memory_book.field_music','Preferenze musicali'),
('fr','memory_book.field_music','Préférences musicales'),
('de','memory_book.field_music','Musikpräferenzen'),
('sv','memory_book.field_music','Musikpreferenser'),
('fi','memory_book.field_music','Musiikkimieltymykset'),

('en','memory_book.field_music_placeholder','Favourite genres, artists, songs, or instruments...'),
('es','memory_book.field_music_placeholder','Géneros, artistas, canciones o instrumentos favoritos...'),
('it','memory_book.field_music_placeholder','Generi, artisti, canzoni o strumenti preferiti...'),
('fr','memory_book.field_music_placeholder','Genres, artistes, chansons ou instruments préférés...'),
('de','memory_book.field_music_placeholder','Lieblingsgenres, Künstler, Songs oder Instrumente...'),
('sv','memory_book.field_music_placeholder','Favoritgenrer, artister, låtar eller instrument...'),
('fi','memory_book.field_music_placeholder','Suosikkigenret, artistit, kappaleet tai soittimet...'),

('en','memory_book.field_conversation','Good conversation topics'),
('es','memory_book.field_conversation','Buenos temas de conversación'),
('it','memory_book.field_conversation','Buoni argomenti di conversazione'),
('fr','memory_book.field_conversation','Bons sujets de conversation'),
('de','memory_book.field_conversation','Gute Gesprächsthemen'),
('sv','memory_book.field_conversation','Bra samtalsämnen'),
('fi','memory_book.field_conversation','Hyviä keskustelunaiheita'),

('en','memory_book.field_conversation_placeholder','Topics they enjoy talking about — family, history, sport, hobbies...'),
('es','memory_book.field_conversation_placeholder','Temas que disfrutan conversar — familia, historia, deporte, pasatiempos...'),
('it','memory_book.field_conversation_placeholder','Argomenti di cui amano parlare — famiglia, storia, sport, hobby...'),
('fr','memory_book.field_conversation_placeholder','Sujets qu''ils aiment aborder — famille, histoire, sport, loisirs...'),
('de','memory_book.field_conversation_placeholder','Themen, über die sie gerne sprechen — Familie, Geschichte, Sport, Hobbys...'),
('sv','memory_book.field_conversation_placeholder','Ämnen de tycker om att prata om — familj, historia, sport, hobbyer...'),
('fi','memory_book.field_conversation_placeholder','Aiheet joista he pitävät puhua — perhe, historia, urheilu, harrastukset...'),

('en','memory_book.field_comforts','What comforts them when upset'),
('es','memory_book.field_comforts','Qué los consuela cuando están angustiados'),
('it','memory_book.field_comforts','Cosa li conforta quando sono turbati'),
('fr','memory_book.field_comforts','Ce qui les réconforte quand ils sont bouleversés'),
('de','memory_book.field_comforts','Was sie tröstet, wenn sie aufgewühlt sind'),
('sv','memory_book.field_comforts','Vad som tröstar dem när de är upprörda'),
('fi','memory_book.field_comforts','Mikä lohduttaa heitä kun he ovat järkyttyneitä'),

('en','memory_book.field_comforts_placeholder','Music, a specific person, a routine, touch, words...'),
('es','memory_book.field_comforts_placeholder','Música, una persona específica, una rutina, tacto, palabras...'),
('it','memory_book.field_comforts_placeholder','Musica, una persona specifica, una routine, il tocco, le parole...'),
('fr','memory_book.field_comforts_placeholder','Musique, une personne spécifique, une routine, le toucher, des mots...'),
('de','memory_book.field_comforts_placeholder','Musik, eine bestimmte Person, eine Routine, Berührung, Worte...'),
('sv','memory_book.field_comforts_placeholder','Musik, en specifik person, en rutin, beröring, ord...'),
('fi','memory_book.field_comforts_placeholder','Musiikki, tietty henkilö, rutiini, kosketus, sanat...'),

('en','memory_book.field_fears','Fears / distress triggers'),
('es','memory_book.field_fears','Miedos / desencadenantes de angustia'),
('it','memory_book.field_fears','Paure / fattori scatenanti di disagio'),
('fr','memory_book.field_fears','Peurs / déclencheurs de détresse'),
('de','memory_book.field_fears','Ängste / Auslöser von Unbehagen'),
('sv','memory_book.field_fears','Rädslor / utlösare av oro'),
('fi','memory_book.field_fears','Pelot / ahdinkolaukaisijat'),

('en','memory_book.field_fears_placeholder','What causes fear, agitation, or distress...'),
('es','memory_book.field_fears_placeholder','Qué causa miedo, agitación o angustia...'),
('it','memory_book.field_fears_placeholder','Cosa causa paura, agitazione o disagio...'),
('fr','memory_book.field_fears_placeholder','Ce qui cause peur, agitation ou détresse...'),
('de','memory_book.field_fears_placeholder','Was Angst, Unruhe oder Unbehagen verursacht...'),
('sv','memory_book.field_fears_placeholder','Vad som orsakar rädsla, oro eller ångest...'),
('fi','memory_book.field_fears_placeholder','Mikä aiheuttaa pelkoa, levottomuutta tai ahdinkoa...'),

('en','memory_book.field_sensory','Sensory preferences'),
('es','memory_book.field_sensory','Preferencias sensoriales'),
('it','memory_book.field_sensory','Preferenze sensoriali'),
('fr','memory_book.field_sensory','Préférences sensorielles'),
('de','memory_book.field_sensory','Sensorische Präferenzen'),
('sv','memory_book.field_sensory','Sensoriska preferenser'),
('fi','memory_book.field_sensory','Aistilliset mieltymykset'),

('en','memory_book.field_sensory_placeholder','Lighting, noise level, temperature, touch preferences...'),
('es','memory_book.field_sensory_placeholder','Iluminación, nivel de ruido, temperatura, preferencias táctiles...'),
('it','memory_book.field_sensory_placeholder','Illuminazione, livello di rumore, temperatura, preferenze tattili...'),
('fr','memory_book.field_sensory_placeholder','Éclairage, niveau de bruit, température, préférences tactiles...'),
('de','memory_book.field_sensory_placeholder','Beleuchtung, Lärmpegel, Temperatur, Berührungspräferenzen...'),
('sv','memory_book.field_sensory_placeholder','Belysning, ljudnivå, temperatur, berörningspreferenser...'),
('fi','memory_book.field_sensory_placeholder','Valaistus, melutaso, lämpötila, kosketusmieltymykset...'),

('en','memory_book.field_avoid','Things to avoid'),
('es','memory_book.field_avoid','Cosas que evitar'),
('it','memory_book.field_avoid','Cose da evitare'),
('fr','memory_book.field_avoid','Choses à éviter'),
('de','memory_book.field_avoid','Dinge zu vermeiden'),
('sv','memory_book.field_avoid','Saker att undvika'),
('fi','memory_book.field_avoid','Vältettäviä asioita'),

('en','memory_book.field_avoid_placeholder','Topics, situations, people, or environments to avoid...'),
('es','memory_book.field_avoid_placeholder','Temas, situaciones, personas o entornos que se deben evitar...'),
('it','memory_book.field_avoid_placeholder','Argomenti, situazioni, persone o ambienti da evitare...'),
('fr','memory_book.field_avoid_placeholder','Sujets, situations, personnes ou environnements à éviter...'),
('de','memory_book.field_avoid_placeholder','Themen, Situationen, Personen oder Umgebungen zu vermeiden...'),
('sv','memory_book.field_avoid_placeholder','Ämnen, situationer, personer eller miljöer att undvika...'),
('fi','memory_book.field_avoid_placeholder','Aiheet, tilanteet, henkilöt tai ympäristöt joita tulee välttää...'),

('en','memory_book.label_enjoys','Enjoys / Makes Happy'),
('es','memory_book.label_enjoys','Disfruta / Le hace feliz'),
('it','memory_book.label_enjoys','Gradisce / Lo rende felice'),
('fr','memory_book.label_enjoys','Apprécie / Rend heureux'),
('de','memory_book.label_enjoys','Genießt / Macht glücklich'),
('sv','memory_book.label_enjoys','Tycker om / Gör glad'),
('fi','memory_book.label_enjoys','Pitää / Tekee onnelliseksi'),

('en','memory_book.label_dislikes','Dislikes'),
('es','memory_book.label_dislikes','Disgustos'),
('it','memory_book.label_dislikes','Avversioni'),
('fr','memory_book.label_dislikes','Aversions'),
('de','memory_book.label_dislikes','Abneigungen'),
('sv','memory_book.label_dislikes','Ogillanden'),
('fi','memory_book.label_dislikes','Inhokit'),

('en','memory_book.label_foods_liked','Foods Enjoyed'),
('es','memory_book.label_foods_liked','Alimentos que disfruta'),
('it','memory_book.label_foods_liked','Cibi graditi'),
('fr','memory_book.label_foods_liked','Aliments appréciés'),
('de','memory_book.label_foods_liked','Bevorzugte Lebensmittel'),
('sv','memory_book.label_foods_liked','Mat som gillas'),
('fi','memory_book.label_foods_liked','Mieliruoat'),

('en','memory_book.label_foods_disliked','Foods to Avoid'),
('es','memory_book.label_foods_disliked','Alimentos a evitar'),
('it','memory_book.label_foods_disliked','Cibi da evitare'),
('fr','memory_book.label_foods_disliked','Aliments à éviter'),
('de','memory_book.label_foods_disliked','Zu vermeidende Lebensmittel'),
('sv','memory_book.label_foods_disliked','Mat att undvika'),
('fi','memory_book.label_foods_disliked','Vältettävät ruoat'),

('en','memory_book.label_music','Music Preferences'),
('es','memory_book.label_music','Preferencias musicales'),
('it','memory_book.label_music','Preferenze musicali'),
('fr','memory_book.label_music','Préférences musicales'),
('de','memory_book.label_music','Musikpräferenzen'),
('sv','memory_book.label_music','Musikpreferenser'),
('fi','memory_book.label_music','Musiikkimieltymykset'),

('en','memory_book.label_conversation','Good Conversation Topics'),
('es','memory_book.label_conversation','Buenos temas de conversación'),
('it','memory_book.label_conversation','Buoni argomenti di conversazione'),
('fr','memory_book.label_conversation','Bons sujets de conversation'),
('de','memory_book.label_conversation','Gute Gesprächsthemen'),
('sv','memory_book.label_conversation','Bra samtalsämnen'),
('fi','memory_book.label_conversation','Hyviä keskustelunaiheita'),

('en','memory_book.label_comforts','Comforts When Upset'),
('es','memory_book.label_comforts','Consuelos cuando está angustiado'),
('it','memory_book.label_comforts','Conforti quando è turbato'),
('fr','memory_book.label_comforts','Réconforts quand bouleversé'),
('de','memory_book.label_comforts','Trost wenn aufgewühlt'),
('sv','memory_book.label_comforts','Tröst när upprörd'),
('fi','memory_book.label_comforts','Lohdutusta järkytyksessä'),

('en','memory_book.label_fears','Fears / Distress Triggers'),
('es','memory_book.label_fears','Miedos / Desencadenantes de angustia'),
('it','memory_book.label_fears','Paure / Fattori scatenanti'),
('fr','memory_book.label_fears','Peurs / Déclencheurs de détresse'),
('de','memory_book.label_fears','Ängste / Auslöser von Unbehagen'),
('sv','memory_book.label_fears','Rädslor / Utlösare av oro'),
('fi','memory_book.label_fears','Pelot / Ahdinkolaukaisijat'),

('en','memory_book.label_sensory','Sensory Preferences'),
('es','memory_book.label_sensory','Preferencias sensoriales'),
('it','memory_book.label_sensory','Preferenze sensoriali'),
('fr','memory_book.label_sensory','Préférences sensorielles'),
('de','memory_book.label_sensory','Sensorische Präferenzen'),
('sv','memory_book.label_sensory','Sensoriska preferenser'),
('fi','memory_book.label_sensory','Aistilliset mieltymykset'),

('en','memory_book.label_avoid','Things to Avoid'),
('es','memory_book.label_avoid','Cosas que evitar'),
('it','memory_book.label_avoid','Cose da evitare'),
('fr','memory_book.label_avoid','Choses à éviter'),
('de','memory_book.label_avoid','Zu vermeidende Dinge'),
('sv','memory_book.label_avoid','Saker att undvika'),
('fi','memory_book.label_avoid','Vältettäviä asioita'),

('en','memory_book.toast_prefs_saved','Preferences saved'),
('es','memory_book.toast_prefs_saved','Preferencias guardadas'),
('it','memory_book.toast_prefs_saved','Preferenze salvate'),
('fr','memory_book.toast_prefs_saved','Préférences enregistrées'),
('de','memory_book.toast_prefs_saved','Präferenzen gespeichert'),
('sv','memory_book.toast_prefs_saved','Preferenser sparade'),
('fi','memory_book.toast_prefs_saved','Mieltymykset tallennettu'),

-- OVERVIEW TAB
('en','memory_book.overview_age','Age {age}'),
('es','memory_book.overview_age','{age} años'),
('it','memory_book.overview_age','{age} anni'),
('fr','memory_book.overview_age','{age} ans'),
('de','memory_book.overview_age','{age} Jahre'),
('sv','memory_book.overview_age','{age} år'),
('fi','memory_book.overview_age','{age} vuotta'),

('en','memory_book.overview_no_summary','No personal summary added yet.'),
('es','memory_book.overview_no_summary','Aún no se ha agregado un resumen personal.'),
('it','memory_book.overview_no_summary','Nessun riepilogo personale aggiunto ancora.'),
('fr','memory_book.overview_no_summary','Aucun résumé personnel ajouté pour l''instant.'),
('de','memory_book.overview_no_summary','Noch keine persönliche Zusammenfassung hinzugefügt.'),
('sv','memory_book.overview_no_summary','Ingen personlig sammanfattning har lagts till ännu.'),
('fi','memory_book.overview_no_summary','Henkilökohtaista yhteenvetoa ei ole vielä lisätty.'),

('en','memory_book.overview_no_summary_owner_hint',' Add one in the Memory Book tab.'),
('es','memory_book.overview_no_summary_owner_hint',' Agréguelo en la pestaña Libro de memorias.'),
('it','memory_book.overview_no_summary_owner_hint',' Aggiungine uno nella scheda Libro dei ricordi.'),
('fr','memory_book.overview_no_summary_owner_hint',' Ajoutez-en un dans l''onglet Livre de mémoire.'),
('de','memory_book.overview_no_summary_owner_hint',' Fügen Sie eine im Register Erinnerungsbuch hinzu.'),
('sv','memory_book.overview_no_summary_owner_hint',' Lägg till en i fliken Minnesbok.'),
('fi','memory_book.overview_no_summary_owner_hint',' Lisää sellainen Muistokirja-välilehdessä.'),

('en','memory_book.overview_progress_title','Memory Book Progress'),
('es','memory_book.overview_progress_title','Progreso del libro de memorias'),
('it','memory_book.overview_progress_title','Progresso del libro dei ricordi'),
('fr','memory_book.overview_progress_title','Progression du livre de mémoire'),
('de','memory_book.overview_progress_title','Fortschritt im Erinnerungsbuch'),
('sv','memory_book.overview_progress_title','Minnesbokens framsteg'),
('fi','memory_book.overview_progress_title','Muistokirjan edistyminen'),

('en','memory_book.overview_sections_count','{completed}/{total} sections'),
('es','memory_book.overview_sections_count','{completed}/{total} secciones'),
('it','memory_book.overview_sections_count','{completed}/{total} sezioni'),
('fr','memory_book.overview_sections_count','{completed}/{total} sections'),
('de','memory_book.overview_sections_count','{completed}/{total} Abschnitte'),
('sv','memory_book.overview_sections_count','{completed}/{total} avsnitt'),
('fi','memory_book.overview_sections_count','{completed}/{total} osiota'),

('en','memory_book.overview_coming_title','Coming in Phase 2'),
('es','memory_book.overview_coming_title','Disponible en la Fase 2'),
('it','memory_book.overview_coming_title','Disponibile nella Fase 2'),
('fr','memory_book.overview_coming_title','Disponible en Phase 2'),
('de','memory_book.overview_coming_title','Verfügbar in Phase 2'),
('sv','memory_book.overview_coming_title','Kommer i Fas 2'),
('fi','memory_book.overview_coming_title','Saatavilla vaiheessa 2'),

('en','memory_book.overview_coming_desc','Daily Living, Activities, Meals, Behavior & Safety, Journal, and Change Log will be available after Phase 2.'),
('es','memory_book.overview_coming_desc','Vida diaria, actividades, comidas, comportamiento y seguridad, diario y registro de cambios estarán disponibles después de la Fase 2.'),
('it','memory_book.overview_coming_desc','Vita quotidiana, attività, pasti, comportamento e sicurezza, diario e registro delle modifiche saranno disponibili dopo la Fase 2.'),
('fr','memory_book.overview_coming_desc','Vie quotidienne, activités, repas, comportement et sécurité, journal et journal des modifications seront disponibles après la Phase 2.'),
('de','memory_book.overview_coming_desc','Alltag, Aktivitäten, Mahlzeiten, Verhalten & Sicherheit, Tagebuch und Änderungsprotokoll werden nach Phase 2 verfügbar sein.'),
('sv','memory_book.overview_coming_desc','Dagligt liv, aktiviteter, måltider, beteende och säkerhet, journal och ändringslogg kommer att finnas tillgängliga efter Fas 2.'),
('fi','memory_book.overview_coming_desc','Päivittäinen elämä, toiminnot, ateriat, käyttäytyminen ja turvallisuus, päiväkirja ja muutosloki ovat saatavilla vaiheen 2 jälkeen.'),

('en','memory_book.overview_incomplete_title','Memory Book Incomplete'),
('es','memory_book.overview_incomplete_title','Libro de memorias incompleto'),
('it','memory_book.overview_incomplete_title','Libro dei ricordi incompleto'),
('fr','memory_book.overview_incomplete_title','Livre de mémoire incomplet'),
('de','memory_book.overview_incomplete_title','Erinnerungsbuch unvollständig'),
('sv','memory_book.overview_incomplete_title','Minnesboken är ofullständig'),
('fi','memory_book.overview_incomplete_title','Muistokirja on keskeneräinen'),

('en','memory_book.overview_incomplete_desc_one','1 section still needs to be filled in to give caregivers a complete picture.'),
('es','memory_book.overview_incomplete_desc_one','1 sección aún necesita completarse para dar a los cuidadores una imagen completa.'),
('it','memory_book.overview_incomplete_desc_one','1 sezione deve ancora essere compilata per dare ai caregiver un quadro completo.'),
('fr','memory_book.overview_incomplete_desc_one','1 section doit encore être remplie pour donner aux aidants une image complète.'),
('de','memory_book.overview_incomplete_desc_one','1 Abschnitt muss noch ausgefüllt werden, um Pflegenden ein vollständiges Bild zu geben.'),
('sv','memory_book.overview_incomplete_desc_one','1 avsnitt behöver fortfarande fyllas i för att ge vårdare en fullständig bild.'),
('fi','memory_book.overview_incomplete_desc_one','1 osio täytyy vielä täyttää, jotta hoitajille saadaan täydellinen kuva.'),

('en','memory_book.overview_incomplete_desc_many','{count} sections still need to be filled in to give caregivers a complete picture.'),
('es','memory_book.overview_incomplete_desc_many','{count} secciones aún necesitan completarse para dar a los cuidadores una imagen completa.'),
('it','memory_book.overview_incomplete_desc_many','{count} sezioni devono ancora essere compilate per dare ai caregiver un quadro completo.'),
('fr','memory_book.overview_incomplete_desc_many','{count} sections doivent encore être remplies pour donner aux aidants une image complète.'),
('de','memory_book.overview_incomplete_desc_many','{count} Abschnitte müssen noch ausgefüllt werden, um Pflegenden ein vollständiges Bild zu geben.'),
('sv','memory_book.overview_incomplete_desc_many','{count} avsnitt behöver fortfarande fyllas i för att ge vårdare en fullständig bild.'),
('fi','memory_book.overview_incomplete_desc_many','{count} osiota täytyy vielä täyttää, jotta hoitajille saadaan täydellinen kuva.'),

('en','memory_book.overview_not_started','Not started'),
('es','memory_book.overview_not_started','No iniciado'),
('it','memory_book.overview_not_started','Non iniziato'),
('fr','memory_book.overview_not_started','Non commencé'),
('de','memory_book.overview_not_started','Nicht begonnen'),
('sv','memory_book.overview_not_started','Inte påbörjad'),
('fi','memory_book.overview_not_started','Ei aloitettu'),

('en','memory_book.overview_records_one','1 record'),
('es','memory_book.overview_records_one','1 registro'),
('it','memory_book.overview_records_one','1 record'),
('fr','memory_book.overview_records_one','1 entrée'),
('de','memory_book.overview_records_one','1 Eintrag'),
('sv','memory_book.overview_records_one','1 post'),
('fi','memory_book.overview_records_one','1 tietue'),

('en','memory_book.overview_records_many','{count} records'),
('es','memory_book.overview_records_many','{count} registros'),
('it','memory_book.overview_records_many','{count} record'),
('fr','memory_book.overview_records_many','{count} entrées'),
('de','memory_book.overview_records_many','{count} Einträge'),
('sv','memory_book.overview_records_many','{count} poster'),
('fi','memory_book.overview_records_many','{count} tietuetta'),

-- SHARED UI
('en','memory_book.role_owner','Owner'),
('es','memory_book.role_owner','Propietario'),
('it','memory_book.role_owner','Proprietario'),
('fr','memory_book.role_owner','Propriétaire'),
('de','memory_book.role_owner','Eigentümer'),
('sv','memory_book.role_owner','Ägare'),
('fi','memory_book.role_owner','Omistaja'),

('en','memory_book.role_member','Member'),
('es','memory_book.role_member','Miembro'),
('it','memory_book.role_member','Membro'),
('fr','memory_book.role_member','Membre'),
('de','memory_book.role_member','Mitglied'),
('sv','memory_book.role_member','Medlem'),
('fi','memory_book.role_member','Jäsen'),

('en','memory_book.save_changes','Save Changes'),
('es','memory_book.save_changes','Guardar cambios'),
('it','memory_book.save_changes','Salva modifiche'),
('fr','memory_book.save_changes','Enregistrer les modifications'),
('de','memory_book.save_changes','Änderungen speichern'),
('sv','memory_book.save_changes','Spara ändringar'),
('fi','memory_book.save_changes','Tallenna muutokset'),

('en','memory_book.saving','Saving...'),
('es','memory_book.saving','Guardando...'),
('it','memory_book.saving','Salvataggio...'),
('fr','memory_book.saving','Enregistrement...'),
('de','memory_book.saving','Speichern...'),
('sv','memory_book.saving','Sparar...'),
('fi','memory_book.saving','Tallennetaan...'),

('en','memory_book.edit','Edit'),
('es','memory_book.edit','Editar'),
('it','memory_book.edit','Modifica'),
('fr','memory_book.edit','Modifier'),
('de','memory_book.edit','Bearbeiten'),
('sv','memory_book.edit','Redigera'),
('fi','memory_book.edit','Muokkaa'),

('en','memory_book.cancel','Cancel'),
('es','memory_book.cancel','Cancelar'),
('it','memory_book.cancel','Annulla'),
('fr','memory_book.cancel','Annuler'),
('de','memory_book.cancel','Abbrechen'),
('sv','memory_book.cancel','Avbryt'),
('fi','memory_book.cancel','Peruuta')

ON CONFLICT (locale, key) DO UPDATE SET value = EXCLUDED.value;
