# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# No [functions] section on purpose.
# We don't want Netlify to look for serverless functions in this repo anymore.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
