-- Phase 1: Japanese translations for memory_book namespace (313 keys)
INSERT INTO ui_translations (locale, key, value) VALUES
('ja', 'memory_book.cancel', 'キャンセル'),
('ja', 'memory_book.confirm_remove_contact', '{name}を連絡先から削除しますか？'),
('ja', 'memory_book.confirm_remove_provider', '{name}をプロバイダーから削除しますか？'),
('ja', 'memory_book.confirm_remove_social', '{platform}アカウントを削除しますか？'),
('ja', 'memory_book.confirm_remove_sub', '{name}を削除しますか？'),
('ja', 'memory_book.confirm_remove_subscription', '{name}を削除しますか？'),
('ja', 'memory_book.confirm_remove_vehicle', '{name}を削除しますか？'),
('ja', 'memory_book.contact_fallback_label', '連絡先'),
('ja', 'memory_book.contact_save_btn', '連絡先を保存'),
('ja', 'memory_book.contacts_count_many', 'ファイルに{count}件の連絡先'),
('ja', 'memory_book.contacts_count_one', 'ファイルに1件の連絡先'),
('ja', 'memory_book.contacts_edit_heading', '連絡先を編集'),
('ja', 'memory_book.contacts_new_heading', '新しい連絡先'),
('ja', 'memory_book.edit', '編集'),
('ja', 'memory_book.field_about_me_placeholder', 'この人について他の人に知ってほしいことは何ですか？その人の個性、情熱、その人らしさを説明してください...'),
('ja', 'memory_book.field_address', '住所'),
('ja', 'memory_book.field_address_placeholder', 'クリニックの住所'),
('ja', 'memory_book.field_address_pref', '呼ばれ方の好み'),
('ja', 'memory_book.field_address_pref_placeholder', '例：田中さん、おばあちゃん、下の名前のみ'),
('ja', 'memory_book.field_allergies_placeholder', '食物アレルギー、薬アレルギー、環境アレルギー...'),
('ja', 'memory_book.field_auto_pay_bills', '自動支払いの請求'),
('ja', 'memory_book.field_auto_pay_bills_placeholder', '定期的な請求をリストアップ...'),
('ja', 'memory_book.field_avoid', '避けるべきこと'),
('ja', 'memory_book.field_avoid_placeholder', '避けるべきトピック、状況、人、または環境...'),
('ja', 'memory_book.field_bank_name', '銀行 / 口座名'),
('ja', 'memory_book.field_bank_name_placeholder', '例：アカデミー銀行——普通預金'),
('ja', 'memory_book.field_birthplace_placeholder', '町、都市、または地域'),
('ja', 'memory_book.field_comforts', '動揺したときに慰めになること'),
('ja', 'memory_book.field_comforts_placeholder', '音楽、特定の人、ルーティン、タッチ、言葉...'),
('ja', 'memory_book.field_conditions_placeholder', '日々のケアに関連する主要な症状をリストアップ...'),
('ja', 'memory_book.field_conversation_placeholder', '話すのが好きなトピック——家族、歴史、スポーツ、趣味...'),
('ja', 'memory_book.field_coverage_type_placeholder', '例：パートA——入院、パートB——医療'),
('ja', 'memory_book.field_cultural_bg', '文化的背景'),
('ja', 'memory_book.field_cultural_bg_placeholder', '文化的アイデンティティ、伝統、慣行'),
('ja', 'memory_book.field_cultural_prefs', '文化的な好み'),
('ja', 'memory_book.field_dislikes_placeholder', '不快感や不満を引き起こすもの...'),
('ja', 'memory_book.field_email', 'メール'),
('ja', 'memory_book.field_fears', '恐れ / 苦痛のトリガー'),
('ja', 'memory_book.field_fears_placeholder', '恐れ、興奮、または苦痛を引き起こすもの...'),
('ja', 'memory_book.field_foods_disliked', '嫌いな食べ物または避けている食べ物'),
('ja', 'memory_book.field_foods_disliked_placeholder', '食べ物の嫌い、食感の嫌悪...'),
('ja', 'memory_book.field_foods_liked', '好きな食べ物'),
('ja', 'memory_book.field_foods_liked_placeholder', 'お気に入りの食べ物、料理、おやつ...'),
('ja', 'memory_book.field_full_name', '氏名 *'),
('ja', 'memory_book.field_full_name_placeholder', '連絡先の氏名'),
('ja', 'memory_book.field_hearing', '聴覚に関するメモ'),
('ja', 'memory_book.field_hearing_placeholder', '補聴器、好み、ヒント...'),
('ja', 'memory_book.field_income_sources', '月収の源泉'),
('ja', 'memory_book.field_income_sources_placeholder', '収入源をリストアップ...'),
('ja', 'memory_book.field_insurance_notes', '追加メモ'),
('ja', 'memory_book.field_insurance_notes_placeholder', 'その他の保険の詳細や指示...'),
('ja', 'memory_book.field_insurer', '保険会社'),
('ja', 'memory_book.field_insurer_placeholder', '例：国民健康保険、ブルークロス'),
('ja', 'memory_book.field_investment_notes', '投資口座'),
('ja', 'memory_book.field_investment_notes_placeholder', '投資または退職口座に関するメモ...'),
('ja', 'memory_book.field_language_prefs_placeholder', '主要言語、コミュニケーションスタイル'),
('ja', 'memory_book.field_license_plate', 'ナンバープレート'),
('ja', 'memory_book.field_license_plate_placeholder', 'ナンバープレート番号'),
('ja', 'memory_book.field_likes', '楽しんでいること / 幸せにするもの'),
('ja', 'memory_book.field_likes_placeholder', '好きな活動、トピック、経験...'),
('ja', 'memory_book.field_make_model_year', 'メーカー / モデル / 年 *'),
('ja', 'memory_book.field_make_model_year_placeholder', '例：2019年 スバル フォレスター'),
('ja', 'memory_book.field_medications_placeholder', '現在の薬、用量、タイミング、投与に関するメモ...'),
('ja', 'memory_book.field_member_id', '会員ID'),
('ja', 'memory_book.field_member_id_placeholder', '会員または証券ID番号'),
('ja', 'memory_book.field_music', '音楽の好み'),
('ja', 'memory_book.field_music_placeholder', '好きなジャンル、アーティスト、曲、または楽器...'),
('ja', 'memory_book.field_notes', 'メモ'),
('ja', 'memory_book.field_notes_placeholder', 'この連絡先に関する追加メモ...'),
('ja', 'memory_book.field_other_medical', 'その他の医療上の考慮事項'),
('ja', 'memory_book.field_other_medical_placeholder', '介護者が知っておくべきその他の健康情報...'),
('ja', 'memory_book.field_parking_location', '駐車場所'),
('ja', 'memory_book.field_parking_location_placeholder', '例：スペース#9、レベル2、建物A'),
('ja', 'memory_book.field_phone', '電話'),
('ja', 'memory_book.field_plan', 'プラン名'),
('ja', 'memory_book.field_plan_placeholder', 'プラン名または番号'),
('ja', 'memory_book.field_practice_name', '診療所 / クリニック名'),
('ja', 'memory_book.field_practice_name_placeholder', '診療所またはクリニックの名前'),
('ja', 'memory_book.field_preferred_name_placeholder', '彼らが好む名前は何ですか？'),
('ja', 'memory_book.field_provider_address_placeholder', 'クリニックの住所'),
('ja', 'memory_book.field_provider_is_primary', 'プライマリプロバイダーとしてマーク'),
('ja', 'memory_book.field_provider_notes_placeholder', 'このプロバイダーに関する重要なメモ...'),
('ja', 'memory_book.field_provider_primary', 'プライマリプロバイダーとしてマーク'),
('ja', 'memory_book.field_registration_due', '登録期限'),
('ja', 'memory_book.field_relationship', '関係'),
('ja', 'memory_book.field_relationship_placeholder', '例：娘、かかりつけ医'),
('ja', 'memory_book.field_relationship_status_placeholder', '例：配偶者に先立たれた、既婚'),
('ja', 'memory_book.field_role', '役割'),
('ja', 'memory_book.field_role_select', '役割を選択...'),
('ja', 'memory_book.field_sensory', '感覚の好み'),
('ja', 'memory_book.field_sensory_placeholder', '照明、騒音レベル、温度、タッチの好み...'),
('ja', 'memory_book.field_service_provider', 'サービスプロバイダー'),
('ja', 'memory_book.field_service_provider_placeholder', '例：マイク・ショー・スバル、デンバー'),
('ja', 'memory_book.field_social_custom_platform', 'プラットフォーム名 *'),
('ja', 'memory_book.field_social_custom_platform_placeholder', '例：マイスペース、クラブハウス、フリッカー'),
('ja', 'memory_book.field_social_notes_placeholder', '例：娘のジェーンが管理、金庫にパスワードヒント'),
('ja', 'memory_book.field_social_platform', 'プラットフォーム *'),
('ja', 'memory_book.field_social_platform_select', 'プラットフォームを選択'),
('ja', 'memory_book.field_social_url', 'プロフィールURL'),
('ja', 'memory_book.field_social_url_placeholder', '例：https://facebook.com/johndoe'),
('ja', 'memory_book.field_social_username', 'ユーザー名 / ハンドル / メール'),
('ja', 'memory_book.field_social_username_placeholder', '例：@johndoe または john@example.com'),
('ja', 'memory_book.field_specialty', '専門 / 役割'),
('ja', 'memory_book.field_specialty_placeholder', '例：一般医、循環器内科医、歯科医、薬局'),
('ja', 'memory_book.field_sub_category', 'カテゴリ'),
('ja', 'memory_book.field_sub_category_select', 'カテゴリを選択'),
('ja', 'memory_book.field_sub_name', 'サービス名 *'),
('ja', 'memory_book.field_sub_name_placeholder', '例：アマゾンプライム、ネットフリックス、AAA'),
('ja', 'memory_book.field_subscription_category', 'カテゴリ'),
('ja', 'memory_book.field_subscription_name', 'サービス名 *'),
('ja', 'memory_book.field_subscription_name_placeholder', '例：アマゾンプライム、タイムマガジン、AAA'),
('ja', 'memory_book.field_subscription_notes', 'メモ'),
('ja', 'memory_book.field_subscription_notes_placeholder', '口座番号、更新日、またはその他の詳細...'),
('ja', 'memory_book.field_vehicle_make_model', 'メーカー / モデル / 年 *'),
('ja', 'memory_book.field_vehicle_make_model_placeholder', '例：2019年 スバル フォレスター'),
('ja', 'memory_book.field_vehicle_notes', 'メモ'),
('ja', 'memory_book.field_vehicle_notes_placeholder', 'その他の車両に関するメモ...'),
('ja', 'memory_book.field_vehicle_parking', '駐車場所'),
('ja', 'memory_book.field_vehicle_parking_placeholder', '例：スペース#9、レベル2、建物A'),
('ja', 'memory_book.field_vehicle_plate_placeholder', 'ナンバープレート番号'),
('ja', 'memory_book.field_vehicle_reg_due', '登録期限'),
('ja', 'memory_book.field_vehicle_reg_due_placeholder', '年月、例：2026年3月'),
('ja', 'memory_book.field_vehicle_service', 'サービスプロバイダー'),
('ja', 'memory_book.field_vehicle_service_placeholder', '例：マイク・ショー・スバル、デンバー'),
('ja', 'memory_book.field_vision', '視覚に関するメモ'),
('ja', 'memory_book.field_vision_placeholder', 'メガネ、障害、好み...'),
('ja', 'memory_book.finances_empty_owner_desc', '日々の財務管理に役立てるために、銀行の詳細、収入源、自動支払いの請求を記録してください。'),
('ja', 'memory_book.finances_empty_owner_title', '財務概要を追加'),
('ja', 'memory_book.finances_locked_desc', '財務情報はプライバシーのためチームオーナーのみに制限されています。'),
('ja', 'memory_book.finances_locked_title', 'オーナーアクセスのみ'),
('ja', 'memory_book.finances_owner_only_notice', 'このセクションはチームオーナーのみに表示されます。'),
('ja', 'memory_book.finances_subtitle', '銀行、収入源、定期的な請求'),
('ja', 'memory_book.identity_add_btn', 'アイデンティティの詳細を追加'),
('ja', 'memory_book.identity_empty_member_desc', 'チームオーナーがアイデンティティセクションを入力する必要があります。'),
('ja', 'memory_book.identity_empty_member_title', 'アイデンティティはまだ完了していません'),
('ja', 'memory_book.identity_empty_owner_desc', '介護者が意義深くつながれるように、好みの名前、出生地、文化的背景、および簡単な個人的なサマリーを記録してください。'),
('ja', 'memory_book.identity_empty_owner_title', 'アイデンティティ情報を追加'),
('ja', 'memory_book.identity_subtitle', '{residentName}の個人詳細'),
('ja', 'memory_book.identity_title', 'アイデンティティ & プロフィール'),
('ja', 'memory_book.insurance_dental_heading', '歯科 & 視覚保険'),
('ja', 'memory_book.insurance_dental_vision_heading', '歯科 & 視覚保険'),
('ja', 'memory_book.insurance_empty_member_desc', 'チームオーナーが保険セクションを入力する必要があります。'),
('ja', 'memory_book.insurance_empty_member_title', '保険はまだ完了していません'),
('ja', 'memory_book.insurance_empty_owner_desc', '介護者が予約や処方箋のために保険の詳細をすぐに見つけられるように、保険プランを記録してください。'),
('ja', 'memory_book.insurance_empty_owner_title', '保険の詳細を追加'),
('ja', 'memory_book.insurance_primary_heading', 'プライマリ保険'),
('ja', 'memory_book.insurance_secondary_heading', 'セカンダリ保険'),
('ja', 'memory_book.insurance_subtitle', 'プライマリ、セカンダリ、歯科/視覚の補償'),
('ja', 'memory_book.label_about_me', '私について'),
('ja', 'memory_book.label_address', '呼ばれ方'),
('ja', 'memory_book.label_avoid', '避けるべきこと'),
('ja', 'memory_book.label_birthplace', '出生地'),
('ja', 'memory_book.label_comforts', '動揺したときの慰め'),
('ja', 'memory_book.label_conversation', '良い会話トピック'),
('ja', 'memory_book.label_cultural_bg', '文化的背景'),
('ja', 'memory_book.label_dislikes', '嫌いなこと'),
('ja', 'memory_book.label_enjoys', '楽しんでいること / 幸せにするもの'),
('ja', 'memory_book.label_fears', '恐れ / 苦痛のトリガー'),
('ja', 'memory_book.label_foods_disliked', '避けるべき食べ物'),
('ja', 'memory_book.label_foods_liked', '好きな食べ物'),
('ja', 'memory_book.label_language_prefs', '言語の好み'),
('ja', 'memory_book.label_music', '音楽の好み'),
('ja', 'memory_book.label_preferred_name', '好みの名前'),
('ja', 'memory_book.label_relationship_status', '婚姻状況'),
('ja', 'memory_book.label_sensory', '感覚の好み'),
('ja', 'memory_book.medical_add_btn', '医療情報を追加'),
('ja', 'memory_book.medical_empty_member_desc', 'チームオーナーが医療セクションを入力する必要があります。'),
('ja', 'memory_book.medical_empty_member_title', '医療情報はまだ完了していません'),
('ja', 'memory_book.medical_empty_owner_desc', '介護者が安全で十分な情報に基づいたケアを提供できるよう、症状、アレルギー、聴覚、視覚、および薬に関するメモを記録してください。'),
('ja', 'memory_book.medical_empty_owner_title', '医療コンテキストを追加'),
('ja', 'memory_book.medical_subtitle', '介護者向けの健康情報——臨床記録ではない'),
('ja', 'memory_book.overview_age', '{age}歳'),
('ja', 'memory_book.overview_coming_desc', '日常生活、活動、食事、行動と安全、日記、変更ログはフェーズ2後に利用可能になります。'),
('ja', 'memory_book.overview_coming_title', 'フェーズ2で登場'),
('ja', 'memory_book.overview_incomplete_desc_many', '介護者に完全な情報を提供するために、{count}のセクションをまだ入力する必要があります。'),
('ja', 'memory_book.overview_incomplete_desc_one', '介護者に完全な情報を提供するために、1つのセクションをまだ入力する必要があります。'),
('ja', 'memory_book.overview_incomplete_title', 'メモリーブックが未完成'),
('ja', 'memory_book.overview_no_summary', 'まだ個人的なサマリーが追加されていません。'),
('ja', 'memory_book.overview_no_summary_owner_hint', 'メモリーブックタブで追加してください。'),
('ja', 'memory_book.overview_not_started', '未開始'),
('ja', 'memory_book.overview_progress_title', 'メモリーブックの進捗'),
('ja', 'memory_book.overview_records_many', '{count}件の記録'),
('ja', 'memory_book.overview_records_one', '1件の記録'),
('ja', 'memory_book.overview_sections_count', '{completed}/{total}セクション'),
('ja', 'memory_book.prefs_add_btn', '好みを追加'),
('ja', 'memory_book.prefs_empty_member_desc', 'チームオーナーが好みセクションを入力する必要があります。'),
('ja', 'memory_book.prefs_empty_member_title', '好みはまだ完了していません'),
('ja', 'memory_book.prefs_empty_owner_desc', '何が慰め、喜び、避けるべきかを記録することで、すべての介護者がより個人的な体験を提供できます。'),
('ja', 'memory_book.prefs_empty_owner_title', '好き、嫌い & 慰めを追加'),
('ja', 'memory_book.prefs_subtitle', '喜びと慰めをもたらすもの、避けるべきもの'),
('ja', 'memory_book.print_btn', 'メモリーブックを印刷'),
('ja', 'memory_book.print_confidential', '機密——ケアチーム専用'),
('ja', 'memory_book.print_generated', '生成日'),
('ja', 'memory_book.print_no_data', 'まだ情報が記録されていません。'),
('ja', 'memory_book.print_section_contacts', 'ケアネットワーク & 連絡先'),
('ja', 'memory_book.print_section_finances', '収入 & 財務'),
('ja', 'memory_book.print_section_household', '家庭情報'),
('ja', 'memory_book.print_section_identity', 'アイデンティティ & プロフィール'),
('ja', 'memory_book.print_section_insurance', '健康保険'),
('ja', 'memory_book.print_section_medical', '医療コンテキスト'),
('ja', 'memory_book.print_section_preferences', '好き、嫌い & 慰め'),
('ja', 'memory_book.print_section_providers', '医療提供者'),
('ja', 'memory_book.print_section_subscriptions', 'サブスクリプション & 会員'),
('ja', 'memory_book.print_section_vehicle', '車両 & 交通'),
('ja', 'memory_book.print_title', 'メモリーブック'),
('ja', 'memory_book.provider_primary_badge', 'プライマリ'),
('ja', 'memory_book.provider_primary_label', 'プライマリ'),
('ja', 'memory_book.provider_save_btn', 'プロバイダーを保存'),
('ja', 'memory_book.readonly_notice', 'このセクションへの閲覧アクセス権があります。変更できるのはチームオーナーのみです。'),
('ja', 'memory_book.role_member', '介護者'),
('ja', 'memory_book.role_owner', '主介護者'),
('ja', 'memory_book.role_resident', '利用者'),
('ja', 'memory_book.save_changes', '変更を保存'),
('ja', 'memory_book.section_preferences', '好き & 嫌い'),
('ja', 'memory_book.social_add_first_btn', '最初のアカウントを追加'),
('ja', 'memory_book.social_count_many', 'ファイルに{count}件のアカウント'),
('ja', 'memory_book.social_count_one', 'ファイルに1件のアカウント'),
('ja', 'memory_book.social_edit_heading', 'アカウントを編集'),
('ja', 'memory_book.social_empty_desc', '必要なときに家族が管理できるよう、ソーシャルメディアのプロフィール、メールアカウント、およびその他のオンラインサービスを記録してください。'),
('ja', 'memory_book.social_empty_title', 'まだオンラインアカウントが追加されていません'),
('ja', 'memory_book.social_new_heading', '新しいアカウント'),
('ja', 'memory_book.social_title', 'ソーシャルメディア & オンラインアカウント'),
('ja', 'memory_book.sub_cat_delivery', '配達'),
('ja', 'memory_book.sub_cat_health', '健康 & ウェルネス'),
('ja', 'memory_book.sub_cat_music', '音楽'),
('ja', 'memory_book.sub_cat_news', 'ニュース'),
('ja', 'memory_book.sub_cat_other', 'その他'),
('ja', 'memory_book.sub_cat_software', 'ソフトウェア'),
('ja', 'memory_book.sub_cat_streaming', 'ストリーミング'),
('ja', 'memory_book.sub_cat_utility', 'ユーティリティ'),
('ja', 'memory_book.subs_add_btn', 'サブスクリプションを追加'),
('ja', 'memory_book.subs_add_first_btn', '最初のサブスクリプションを追加'),
('ja', 'memory_book.subs_count_many', 'ファイルに{count}件のサブスクリプション'),
('ja', 'memory_book.subs_count_one', 'ファイルに1件のサブスクリプション'),
('ja', 'memory_book.subs_edit_heading', 'サブスクリプションを編集'),
('ja', 'memory_book.subs_empty_desc', 'テレビサービス、雑誌の購読、会員、およびその他の定期的なサービスを追跡して何も失効しないようにしてください。'),
('ja', 'memory_book.subs_empty_title', 'まだサブスクリプションが追加されていません'),
('ja', 'memory_book.subs_new_heading', '新しいサブスクリプション'),
('ja', 'memory_book.subs_title', 'サブスクリプション & 会員'),
('ja', 'memory_book.subscription_cat_magazine', '雑誌'),
('ja', 'memory_book.subscription_cat_membership', '会員'),
('ja', 'memory_book.subscription_cat_other', 'その他'),
('ja', 'memory_book.subscription_cat_tv', 'テレビ / ストリーミング'),
('ja', 'memory_book.subscription_save_btn', 'サブスクリプションを保存'),
('ja', 'memory_book.subscriptions_add_first_btn', '最初のサブスクリプションを追加'),
('ja', 'memory_book.subscriptions_count_many', 'ファイルに{count}件のサブスクリプション'),
('ja', 'memory_book.subscriptions_count_one', 'ファイルに1件のサブスクリプション'),
('ja', 'memory_book.subscriptions_edit_heading', 'サブスクリプションを編集'),
('ja', 'memory_book.subscriptions_empty_desc', 'テレビサービス、雑誌の購読、会員、およびその他の定期的なサービスを追跡して何も失効しないようにしてください。'),
('ja', 'memory_book.subscriptions_empty_title', 'まだサブスクリプションが追加されていません'),
('ja', 'memory_book.subscriptions_new_heading', '新しいサブスクリプション'),
('ja', 'memory_book.subscriptions_subtitle', 'テレビ、雑誌、会員、およびその他の定期的なサービス'),
('ja', 'memory_book.toast_contact_added', '連絡先が追加されました'),
('ja', 'memory_book.toast_contact_failed', '連絡先の保存に失敗しました'),
('ja', 'memory_book.toast_contact_remove_failed', '削除に失敗しました'),
('ja', 'memory_book.toast_contact_removed', '連絡先が削除されました'),
('ja', 'memory_book.toast_contact_required', '連絡先名が必要です'),
('ja', 'memory_book.toast_contact_updated', '連絡先が更新されました'),
('ja', 'memory_book.toast_finances_saved', '財務情報が保存されました'),
('ja', 'memory_book.toast_identity_saved', 'アイデンティティが保存されました'),
('ja', 'memory_book.toast_insurance_saved', '保険情報が保存されました'),
('ja', 'memory_book.toast_medical_saved', '医療情報が保存されました'),
('ja', 'memory_book.toast_prefs_saved', '好みが保存されました'),
('ja', 'memory_book.toast_provider_added', 'プロバイダーが追加されました'),
('ja', 'memory_book.toast_provider_failed', 'プロバイダーの保存に失敗しました'),
('ja', 'memory_book.toast_provider_name_required', 'プロバイダー名が必要です'),
('ja', 'memory_book.toast_provider_remove_failed', 'プロバイダーの削除に失敗しました'),
('ja', 'memory_book.toast_provider_removed', 'プロバイダーが削除されました'),
('ja', 'memory_book.toast_provider_required', 'プロバイダー名が必要です'),
('ja', 'memory_book.toast_provider_updated', 'プロバイダーが更新されました'),
('ja', 'memory_book.toast_social_added', 'アカウントが追加されました'),
('ja', 'memory_book.toast_social_platform_required', 'プラットフォームが必要です'),
('ja', 'memory_book.toast_social_removed', 'アカウントが削除されました'),
('ja', 'memory_book.toast_social_updated', 'アカウントが更新されました'),
('ja', 'memory_book.toast_sub_added', 'サブスクリプションが追加されました'),
('ja', 'memory_book.toast_sub_removed', 'サブスクリプションが削除されました'),
('ja', 'memory_book.toast_sub_required', 'サブスクリプション名が必要です'),
('ja', 'memory_book.toast_sub_updated', 'サブスクリプションが更新されました'),
('ja', 'memory_book.toast_subscription_added', 'サブスクリプションが追加されました'),
('ja', 'memory_book.toast_subscription_failed', 'サブスクリプションの保存に失敗しました'),
('ja', 'memory_book.toast_subscription_name_required', 'サブスクリプション名が必要です'),
('ja', 'memory_book.toast_subscription_remove_failed', 'サブスクリプションの削除に失敗しました'),
('ja', 'memory_book.toast_subscription_removed', 'サブスクリプションが削除されました'),
('ja', 'memory_book.toast_subscription_updated', 'サブスクリプションが更新されました'),
('ja', 'memory_book.toast_vehicle_added', '車両が追加されました'),
('ja', 'memory_book.toast_vehicle_failed', '車両の保存に失敗しました'),
('ja', 'memory_book.toast_vehicle_name_required', '車両のメーカー/モデルが必要です'),
('ja', 'memory_book.toast_vehicle_remove_failed', '車両の削除に失敗しました'),
('ja', 'memory_book.toast_vehicle_removed', '車両が削除されました'),
('ja', 'memory_book.toast_vehicle_required', '車両のメーカー/モデルが必要です'),
('ja', 'memory_book.toast_vehicle_updated', '車両が更新されました'),
('ja', 'memory_book.vehicle_add_first_btn', '最初の車両を追加'),
('ja', 'memory_book.vehicle_count_many', 'ファイルに{count}台の車両'),
('ja', 'memory_book.vehicle_count_one', 'ファイルに1台の車両'),
('ja', 'memory_book.vehicle_edit_heading', '車両を編集'),
('ja', 'memory_book.vehicle_empty_desc', 'すぐに参照できるよう、車両の詳細、ナンバープレート、登録期限、サービスプロバイダーを記録してください。'),
('ja', 'memory_book.vehicle_empty_title', 'まだ車両が追加されていません'),
('ja', 'memory_book.vehicle_new_heading', '新しい車両'),
('ja', 'memory_book.vehicle_reg_due_soon', '登録期限が近づいています'),
('ja', 'memory_book.vehicle_reg_overdue', '登録が期限切れです'),
('ja', 'memory_book.vehicle_reg_soon', '登録期限が近づいています'),
('ja', 'memory_book.vehicle_save_btn', '車両を保存'),
('ja', 'memory_book.vehicle_subtitle', '車の詳細、登録、サービス情報'),
('ja', 'memory_book.vehicles_add_btn', '車両を追加'),
('ja', 'memory_book.vehicles_add_first_btn', '最初の車両を追加'),
('ja', 'memory_book.vehicles_count_many', 'ファイルに{count}台の車両'),
('ja', 'memory_book.vehicles_count_one', 'ファイルに1台の車両'),
('ja', 'memory_book.vehicles_edit_heading', '車両を編集'),
('ja', 'memory_book.vehicles_empty_desc', 'すぐに参照できるよう、車両の詳細、ナンバープレート、登録期限、サービスプロバイダーを記録してください。'),
('ja', 'memory_book.vehicles_empty_title', 'まだ車両が追加されていません'),
('ja', 'memory_book.vehicles_new_heading', '新しい車両'),
('ja', 'memory_book.vehicles_title', '車両 & 交通'),
('ja', 'memory_book.viewing_as', '閲覧中：')
ON CONFLICT (locale, key) DO NOTHING;
