
INSERT INTO ui_translations (locale, key, value) VALUES
-- new_obs namespace
('ja','new_obs.choose_type','記録する観察の種類を選択してください。'),
('ja','new_obs.create_title','新しい観察を作成'),
('ja','new_obs.email_missing','アカウントのメールアドレスが見つかりません。プロフィールを更新してください。'),
('ja','new_obs.loading','新しい観察を準備しています…'),
('ja','new_obs.no_team','最初にファミリーサークルを作成してください。'),
('ja','new_obs.page_title','新しい観察'),
('ja','new_obs.quota_reached','チームクォータに達しました（100回/年）。'),
('ja','new_obs.remaining_prefix','今年の残り観察回数：'),
('ja','new_obs.seat_frozen','シートが凍結されています。オーナーに請求管理を依頼してください。'),
-- obs_edit namespace
('ja','obs_edit.adl_label','日常生活（ADL）'),
('ja','obs_edit.comp_label','総合的評価'),
('ja','obs_edit.fetching','観察を取得しています…'),
('ja','obs_edit.form_adl','ADL'),
('ja','obs_edit.form_comprehensive','総合的評価'),
('ja','obs_edit.form_iadl','IADL'),
('ja','obs_edit.frozen_notice','アカウントが停止されています。現在、観察を編集できません。'),
('ja','obs_edit.iadl_label','生活スキル（IADL）'),
('ja','obs_edit.invalid_type','観察に無効なフォームタイプがあります：'),
('ja','obs_edit.loading','観察を読み込んでいます…'),
('ja','obs_edit.missing_id','URLに観察IDがありません。'),
('ja','obs_edit.observation_label','観察'),
('ja','obs_edit.readonly_notice','あなたは作成者ではないため、この観察を読み取り専用モードで閲覧しています。'),
('ja','obs_edit.render_error','この観察の読み込み中に問題が発生しました。'),
('ja','obs_edit.render_error_detail','ページを更新するか、ダッシュボードに戻ってください。'),
-- obs_form namespace
('ja','obs_form.adl_label','日常生活活動'),
('ja','obs_form.adl_type_label','日常生活動作'),
('ja','obs_form.autosave_hint','少なくとも1つの項目にスコアを入力すると自動保存されます'),
('ja','obs_form.cat_notes_label','{category}のメモ（任意）'),
('ja','obs_form.cat_notes_ph','{category}に関する具体的なメモ…'),
('ja','obs_form.cat_notes_placeholder','このカテゴリーに関する具体的なメモを追加…'),
('ja','obs_form.category_scored','{scored}/{total} スコア済み'),
('ja','obs_form.comprehensive_label','総合的評価（ADL＋IADL）'),
('ja','obs_form.contact_support','この問題が続く場合は、サポートにお問い合わせください。'),
('ja','obs_form.date_invalid','MM/DD/YYYY形式で有効な日付を入力してください'),
('ja','obs_form.date_label','観察日'),
('ja','obs_form.date_placeholder','MM/DD/YYYY'),
('ja','obs_form.date_required','観察日は必須です'),
('ja','obs_form.err_email','アカウントのメールアドレスが見つからないか無効です。サインアウトして再度サインインしてください。'),
('ja','obs_form.err_no_score','保存する前に少なくとも1つのスコアを選択してください。'),
('ja','obs_form.error_loading','観察の質問を読み込めませんでした。もう一度お試しください。'),
('ja','obs_form.form_type_comp','総合的評価（ADL＋IADL）'),
('ja','obs_form.guidance','好きなだけ多く、または少なく記入してください。すべての質問に答える必要はありません — 少数のスコアでも役立ちます。少なくとも1つのスコアを入力すると、45秒ごとに自動保存されます。'),
('ja','obs_form.guidance_bold','ヒント：'),
('ja','obs_form.iadl_label','生活スキル'),
('ja','obs_form.iadl_type_label','手段的日常生活活動'),
('ja','obs_form.last_saved','{time}に最後に保存'),
('ja','obs_form.last_saved_at','最後に保存した時刻'),
('ja','obs_form.loading','観察フォームを読み込んでいます…'),
('ja','obs_form.mode_in_person','対面'),
('ja','obs_form.mode_label','どのように観察しましたか？'),
('ja','obs_form.mode_video','ビデオ通話'),
('ja','obs_form.mode_voice','音声通話'),
('ja','obs_form.more_help','より多くのサポートが必要'),
('ja','obs_form.more_indep','より自立している'),
('ja','obs_form.no_questions','利用可能な質問がありません'),
('ja','obs_form.no_score_hint','この観察を保存するには、上記の少なくとも1つの質問にスコアをつけてください。'),
('ja','obs_form.notes_ph','今日の訪問に関する一般的な観察…'),
('ja','obs_form.patient_label','観察対象者'),
('ja','obs_form.patient_ph','その方のお名前'),
('ja','obs_form.resident_edit_link','編集'),
('ja','obs_form.resident_no_profile_hint','まだ入居者プロファイルが設定されていません。'),
('ja','obs_form.resident_no_profile_link','入居者プロファイルを設定する'),
('ja','obs_form.resident_placeholder','その方のお名前'),
('ja','obs_form.save_changes','変更を保存'),
('ja','obs_form.save_continue','保存して続ける'),
('ja','obs_form.save_failed','自動保存に失敗しました'),
('ja','obs_form.save_obs','観察を保存'),
('ja','obs_form.saved','保存済み'),
('ja','obs_form.saving','保存中…'),
('ja','obs_form.score_ref_header','スコア参照 — 各質問の番号をタップして観察を記録してください'),
('ja','obs_form.scored_count','{scored}/{total} スコア済み'),
('ja','obs_form.title_edit','観察を編集'),
('ja','obs_form.title_new','新しい観察'),
-- obs_list namespace
('ja','obs_list.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','obs_list.delete_title','観察を削除しますか？'),
('ja','obs_list.empty_body','最初の観察を作成して始めましょう。'),
('ja','obs_list.empty_title','観察がまだありません'),
('ja','obs_list.export_csv','CSVとしてエクスポート'),
('ja','obs_list.export_docx','DOCXとしてエクスポート'),
('ja','obs_list.guest_badge','ゲスト'),
('ja','obs_list.load_failed','観察の読み込みに失敗しました'),
('ja','obs_list.loading','観察を読み込んでいます...'),
('ja','obs_list.observed_on','{date}に観察'),
('ja','obs_list.unnamed_resident','名前のない入居者'),
-- view_obs namespace
('ja','view_obs.back_list','リストに戻る'),
('ja','view_obs.caregiver','ケアラー'),
('ja','view_obs.comp_label','総合的評価（ADL＋IADL）'),
('ja','view_obs.csv_label','スプレッドシート（.csv）'),
('ja','view_obs.delete_generic','この観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_title','観察を削除しますか？'),
('ja','view_obs.details_title','観察の詳細'),
('ja','view_obs.docx_label','Wordドキュメント（.docx）'),
('ja','view_obs.load_error','観察を読み込めませんでした。もう一度お試しください。'),
('ja','view_obs.load_failed','観察の読み込みに失敗しました'),
('ja','view_obs.loading','観察を読み込んでいます...'),
('ja','view_obs.mode','観察方法'),
('ja','view_obs.no_resp_body','この観察には記録された回答がありません。'),
('ja','view_obs.no_responses','回答なし'),
('ja','view_obs.not_found','観察が見つかりません'),
('ja','view_obs.notes','メモ'),
('ja','view_obs.obs_date','観察日'),
('ja','view_obs.obs_type','観察タイプ'),
('ja','view_obs.patient_name','患者名'),
('ja','view_obs.print','印刷'),
('ja','view_obs.resident_name','入居者名')
ON CONFLICT (locale, key) DO NOTHING;
