
INSERT INTO ui_translations (locale, key, value) VALUES
-- caregiver
('ja','caregiver.dashboard_title','ダッシュボード'),
('ja','caregiver.delete_failed','観察の削除に失敗しました'),
('ja','caregiver.dementia_desc','グローバル劣化スケール（GDS）— 認知機能低下の7段階'),
('ja','caregiver.dementia_scale','認知症スケール参照'),
('ja','caregiver.export_failed','観察のエクスポートに失敗しました。'),
('ja','caregiver.loading','ケアラーダッシュボードを読み込んでいます...'),
('ja','caregiver.new_observation','新しい観察'),
('ja','caregiver.no_obs_selected','観察が選択されていません'),
('ja','caregiver.obs_deleted','観察が正常に削除されました'),
('ja','caregiver.obs_empty','まだ観察が記録されていません。'),
('ja','caregiver.obs_empty_cta','最初の観察を記録する →'),
('ja','caregiver.obs_view_all','すべての{count}件の観察を見る →'),
('ja','caregiver.payment_success','お支払いが成功しました！サブスクリプションがアクティブになりました。'),
('ja','caregiver.subscriber_tools_heading','サブスクライバーツール'),
('ja','caregiver.subtitle_care_plan','以下にケアプランの進捗が表示されます。'),
('ja','caregiver.subtitle_default','現在のケア活動の概要です。'),
('ja','caregiver.subtitle_memory_book','以下にケアプラン、メモリーブック、観察の進捗が表示されます。'),
('ja','caregiver.subtitle_observations','最近の観察が以下に表示されます。'),
('ja','caregiver.upsell_cp_desc','チームを調整 — 役割、権限、持続可能性'),
('ja','caregiver.upsell_mb_desc','本人を知る — アイデンティティ、健康、好み、連絡先'),
('ja','caregiver.upsell_upgrade_cta','アップグレードしてアクセス'),
('ja','caregiver.view_arrow','表示 →'),
('ja','caregiver.your_obs_body','ケアラーの観察を追跡・管理する'),
('ja','caregiver.your_obs_title','あなたの観察'),
-- dashboard
('ja','dashboard.mb_section_contacts','連絡先'),
('ja','dashboard.mb_section_daily_living','日常生活＆好み'),
('ja','dashboard.mb_section_identity','アイデンティティ'),
('ja','dashboard.mb_section_medical','医療'),
('ja','dashboard.mb_sections_have_content','{total}セクションのうちコンテンツあり'),
('ja','dashboard.mb_subtitle','本人を知る'),
('ja','dashboard.mb_title','メモリーブック'),
('ja','dashboard.medical_allergies','アレルギー'),
('ja','dashboard.medical_conditions','疾患'),
('ja','dashboard.medical_hearing','聴力'),
('ja','dashboard.medical_medications','服薬'),
('ja','dashboard.medical_subtitle','メモリーブックより'),
('ja','dashboard.medical_title','医療サマリー'),
('ja','dashboard.medical_view_link','メモリーブックを見る'),
('ja','dashboard.medical_vision','視力'),
('ja','dashboard.resident_age','{age}歳'),
('ja','dashboard.resident_complete_cta','入居者プロファイルを完成させる →'),
('ja','dashboard.resident_known_as','「{name}」として知られている'),
('ja','dashboard.resident_profile_pct','プロファイル{pct}%完了'),
('ja','dashboard.resident_subtitle','ケアの中心にいる方'),
('ja','dashboard.resident_title','入居者'),
-- admin
('ja','admin.active_caregivers','アクティブなケアラー'),
('ja','admin.admin_label','管理者'),
('ja','admin.admins_only','管理者のみ。'),
('ja','admin.auth_required','認証が必要です。'),
('ja','admin.avg_score','カテゴリー平均スコア'),
('ja','admin.avg_scores_by_category','カテゴリー別平均スコア'),
('ja','admin.checking','セッションを確認中…'),
('ja','admin.delete_user_title','管理者：メールでユーザーを削除'),
('ja','admin.email_ph','user@example.com'),
('ja','admin.error_aggregate','集計データの読み込みに失敗しました'),
('ja','admin.loading','管理者ダッシュボードを読み込んでいます...'),
('ja','admin.loading_aggregate','集計データを読み込んでいます…'),
('ja','admin.loading_editor','翻訳エディターを読み込んでいます…'),
('ja','admin.manage_caregivers','ケアラーを管理する'),
('ja','admin.no_data','データがありません'),
('ja','admin.profile_required','プロファイルが見つかりません。'),
('ja','admin.signed_in_as','サインイン中：'),
('ja','admin.this_week','今週'),
('ja','admin.total_obs','総観察数'),
('ja','admin.trans_empty','翻訳キーが見つかりません。'),
('ja','admin.trans_en_col','英語'),
('ja','admin.trans_es_col','スペイン語'),
('ja','admin.trans_key_col','キー'),
('ja','admin.trans_save_err','保存に失敗しました'),
('ja','admin.trans_saved','保存済み'),
('ja','admin.trans_search_ph','キーまたは値を検索…'),
('ja','admin.trans_title','翻訳管理'),
-- tutorial
('ja','tutorial.bottom_cta','ケアプランを開始する'),
('ja','tutorial.bottom_title','CarerViewサポートの旅を始める'),
('ja','tutorial.callout_body','ガイド付きCarerViewチュートリアルを受けて、ケアプランからメモリーブックまでツールがどのように機能するかを正確に確認してください。約5分かかります。'),
('ja','tutorial.callout_heading','CarerViewを実際に見る'),
('ja','tutorial.cta_restart','チュートリアルを再スタート'),
('ja','tutorial.cta_start','ツアーを開始する'),
('ja','tutorial.nav_step_preview','アプリ機能のガイドツアーを受ける'),
('ja','tutorial.page_subtitle','家族ケアラーのために構築されたコアツールの5ステップクイックウォークスルー。'),
('ja','tutorial.page_title','CarerViewプロセス'),
('ja','tutorial.public_description','数分でメモリーブック、ケアプラン、観察、チームツールをウォークスルー。'),
('ja','tutorial.skip','ツアーをスキップ'),
('ja','tutorial.skip_aria','チュートリアルをスキップ'),
('ja','tutorial.skip_btn','ツアーをスキップ'),
('ja','tutorial.step_label','ステップ {current}/{total}'),
('ja','tutorial.step5_body','ケアはより多くの手で機能します。家族やその他のケアラーをファミリーサークルに追加して、全員が情報を共有し負担を分担できるようにします。'),
('ja','tutorial.step5_title','チームを招待する'),
-- policy (long-form — use abbreviated Japanese summaries for key privacy sections)
('ja','policy.back_home','ホームに戻る'),
('ja','policy.being_finalized','このポリシーは確定中です。近日中にご確認ください。'),
('ja','policy.data_notice','このデータポリシーは、CarerViewがアプリケーションに入力したケアデータ — 観察、評価、ケアを受ける方の個人情報を含む — をどのように扱うかを説明します。このデータの所有権は常にあなたに帰属します。CarerViewはあなたに代わってデータ処理者として機能し、あなたのケアデータをサービス運営以外の目的に使用することは決してありません。このポリシーはプライバシーポリシーとともにお読みください。'),
('ja','policy.data_s1_body','CarerViewで作成するケアデータ — 日々の観察、活動スコア、メモ、評価の回答、ケア受益者に関して記録する個人・医療情報を含む — はあなたのものです。あなたはこのコンテンツのデータ管理者です。CarerViewはあなたの指示にのみ従って処理します。CarerViewはケア記録の内容を商業目的で読んだり、分析したり、使用したりしません。ケアデータが健康または障害に関連する場合、英国GDPR第9条の特別カテゴリーデータとして扱われ、追加の技術的保護措置とアクセス制御で保護されます。'),
('ja','policy.data_s1_title','あなたが作成するデータ'),
('ja','policy.data_s2_body','CarerViewはあなたのケアデータを第三者に販売、賃貸、またはライセンスすることは決してありません。ただし以下の場合を除き、外部組織とケアデータを共有しません：(a) サービス提供に厳密に必要な範囲でサブプロセッサー（ホスティングプロバイダー等）と、拘束力のあるデータ処理契約の下で；(b) あなたがアカウントに招待した他のチームメンバーへのアクセスを明示的に許可した場合；(c) 裁判所命令または規制当局によって法的に強制される場合（この場合、法律の許す範囲でお知らせします）。個人またはケア受益者が特定できない完全に匿名化された集計統計データを、社内サービス改善目的のみに使用する場合があります。'),
('ja','policy.data_s2_title','データの共有'),
('ja','policy.data_s3_body','あなたのケアデータは、CarerViewアカウントがアクティブな間保持されます。アカウントを削除すると、アカウント閉鎖後30日以内に関連するすべてのケアデータを永久かつ取り消し不能で削除します。ただし、法的義務を遵守するために長期間特定の記録を保持する必要がある場合を除きます（例：サブスクリプションに関連する財務記録）。特定のデータの早期削除を希望する場合は、CarerView@GrifDigi.comまでお問い合わせください。バックアップは30日ローリングサイクルで削除され、削除開始後最大30日間残留コピーが存在する場合があります。'),
('ja','policy.data_s3_title','データの保持'),
('ja','policy.data_s4_body','CarerViewに入力したすべてのケアデータの完全でポータブルなコピーを受け取る権利があります。アカウント設定エリアからいつでもデータの完全なエクスポートを生成してダウンロードできます。エクスポートは構造化された形式（DOCX）で提供されます。エクスポートの頻度に制限はなく、費用はかかりません。エクスポートファイルはオンデマンドで生成され、ダウンロード後はサーバーに保存されません。別の形式でのエクスポートが必要な場合や、セルフサービスエクスポートに問題がある場合は、CarerView@GrifDigi.comまでお問い合わせください。'),
('ja','policy.data_s4_title','データのエクスポート'),
('ja','policy.data_s5_body','CarerViewはケア観察および記録ツールです。EU医療機器規則2017/745、英国MDR 2002、またはそれに相当する法律の下での登録済み医療機器、臨床意思決定支援システム、または診断機器ではありません。CarerViewに記録される情報はケアラーによる観察を反映しており、臨床評価または医学的診断として解釈されるべきではありません。CarerView内のいかなる内容も医療アドバイスを構成しません。アプリケーション内の評価スケールおよびスコアリングツールは情報補助としてのみ提供されており、臨床またはケアの決定の唯一の根拠として使用してはなりません。ケアを受ける方に関する医療指導については、常に資格を持つ医療専門家に相談してください。'),
('ja','policy.data_s5_title','健康情報免責事項'),
('ja','policy.priv_notice','このプライバシーポリシーは、CarerView（GrifDigi Ltdが運営）がサービスを使用する際に個人データをどのように収集、使用、保存、保護するかを説明します。英国一般データ保護規則（UK GDPR）および2018年データ保護法に準拠して発行されています。GrifDigi Ltdはあなたが提供する個人データに関してデータ管理者として機能します。このポリシーについてご質問がある場合は、CarerView@GrifDigi.comまでお問い合わせください。'),
('ja','policy.priv_s1_body','以下のカテゴリーの個人データを収集します：(a) アカウントデータ — 登録時の名前、メールアドレス、パスワード；(b) ケア観察データ — ケアを受ける方について入力した構造化観察、メモ、スコア、評価；(c) チームとプロファイルデータ — アカウントに関連するケアラーとケア受益者について提供する情報；(d) 使用・技術データ — サービスの運営と改善のために自動的に収集されるIPアドレス、ブラウザタイプ、デバイス識別子、ログデータ。処理の合法的根拠：契約の履行（サービス提供）；正当な利益（サービスセキュリティの維持と不正防止）；健康関連ケアデータが入力された場合、UK GDPR第9条の要件に従ったあなたの明示的な同意。'),
('ja','policy.priv_s1_title','収集するデータ'),
('ja','policy.priv_s2_body','個人データを以下の目的に使用します：(a) アカウントの作成・管理とアイデンティティ認証；(b) ケア観察の保存・表示を含むCarerViewサービスの提供；(c) アカウント確認、パスワードリセット、サブスクリプション通知などのトランザクションコミュニケーションの送信；(d) 決済プロセッサーStripeを通じた安全な決済処理；(e) サービスパフォーマンスの監視と改善、技術的問題の診断、新機能の開発；(f) 規制当局や法執行機関からの合法的な要求への対応を含む法的義務の遵守。あなたに法的またはそれに類する重大な影響を与える自動意思決定やプロファイリングに個人データを使用することはありません。'),
('ja','policy.priv_s2_title','データの使用方法'),
('ja','policy.priv_s3_body','あなたのデータはSupabase, Inc.が提供するインフラストラクチャに保存され、欧州経済地域と英国内のAmazon Web Services（AWS）データセンターでホストされています。すべてのデータはTLS 1.2以上を使用して転送中に暗号化され、AES-256を使用して保存中に暗号化されます。個人データへのアクセスは、必要最小限の原則に基づいて権限を持つ人員に制限され、多要素認証で保護されています。不正アクセス、偶発的な損失、破壊、変更から保護するための適切な技術的・組織的措置を維持しています。あなたの権利と自由にリスクをもたらす可能性のある個人データ漏洩が発生した場合、漏洩を認識してから72時間以内に情報委員会（ICO）に通知し、法律で要求される場合は速やかにあなたに伝達します。'),
('ja','policy.priv_s3_title','データの保存とセキュリティ'),
('ja','policy.priv_s4_body','UK GDPRの下で、個人データに関して以下の権利を有します：(a) アクセスの権利 — 保有する個人データのコピーを要求できます；(b) 修正の権利 — 不正確または不完全なデータの修正を求めることができます；(c) 消去の権利 — 処理を継続する正当な理由がない場合に個人データの削除を要求できます；(d) 制限の権利 — 特定の状況においてデータの処理制限を求めることができます；(e) データポータビリティの権利 — 構造化された、一般的に使用される、機械可読形式で個人データを受け取ることができます；(f) 異議申し立ての権利 — 正当な利益に基づく処理に異議を申し立てることができます；(g) 自動化意思決定に関する権利 — あなたに重大な影響を与える完全に自動化された決定に従わない権利があります。これらの権利を行使するには、CarerView@GrifDigi.comにお問い合わせください。また、適用法に従ってデータが取り扱われていないと判断した場合、ico.org.ukでICOに苦情を申し立てる権利があります。'),
('ja','policy.priv_s4_title','あなたの権利'),
('ja','policy.priv_s5_body','CarerViewはトラッキング、広告、または分析Cookieを使用しません。サードパーティのCookieをデバイスに配置しません。認証サービスがアクティブなセッション中のサインイン状態を維持するためだけに、厳密に必要なセッションCookieが設定される場合があります。これらはブラウザを閉じるかサインアウトすると削除されます。Cookieを通じて第三者に個人データが送信されることはなく、このポリシーの結果としてCookieの同意バナーは必要ありません。'),
('ja','policy.priv_s5_title','Cookie'),
('ja','policy.questions','ご質問は以下にお問い合わせください'),
-- about
('ja','about.body_p4','私たちの目標は、介護に伴うストレス、孤立、そして静かな圧倒感を和らげることです。ケアラーに明確さがあれば、ケアを受ける方はより良く、より一貫した、より思いやりのある注目を受けられると信じています — そして家族は最も重要なことに集中できます：一緒に過ごす時間に。'),
('ja','about.body_p5','CarerViewは単なるツール以上のものです。母の記憶を称え、同じ旅を歩む他の方々を助けることで、どの家族も一人でそれを乗り越えなくていいようにするための私たちの方法です。'),
('ja','about.cta_body','より明確に、より自信を持ち、より孤立せずに介護をするためにCarerViewを使用している家族に参加してください。新しいケアラーの旅を始め、メモリーブックを構築し、観察を追跡し始めましょう — すべて一か所で。'),
('ja','about.cta_button','始める'),
('ja','about.feature1_body','家族ケアラーになって初めて気づくことは、ガイドがないということです。CarerViewの新しいケアラーガイドは、重要な決断、連絡先、文書、介護手配について説明します — 圧倒的な最初の数週間に重要なことが見落とされないように。'),
('ja','about.feature1_title','新しいケアラーのスタート'),
('ja','about.feature2_body','ケアを受ける方の生きた記録 — アイデンティティ、生い立ち、日常の好み、医療背景、そして彼らにとって重要なルーティン。すべての家族と専門ケアラーが、診断だけでなく、この人が誰であるかという同じ理解から始められます。'),
('ja','about.feature2_title','メモリーブック'),
('ja','about.feature3_body','医療専門家が使用するのと同じADLおよびIADLスケールを使用した、毎日または毎週の構造化されたチェックイン。時間とともに、個々のエントリーが意味のあるトレンド記録を構築します — かかりつけ医、専門家、またはケアチームと共有して、実際に何が変化しているのか、いつから始まったのかを示すことができます。'),
('ja','about.feature3_title','観察'),
('ja','about.features_heading','3つのツール。1つの明確な全体像。'),
('ja','about.origin_heading','CarerViewの始まり'),
('ja','about.page_title','CarerViewについて'),
-- accept_invite
('ja','accept_invite.error_consumed_body','この招待リンクはすでに使用されています。別のチームに参加するつもりだった場合は、新しいリンクを依頼してください。'),
('ja','accept_invite.error_consumed_title','招待がすでに使用済み'),
('ja','accept_invite.error_expired_body','この招待リンクは期限切れです。チームオーナーに新しいリンクを送ってもらってください。'),
('ja','accept_invite.error_expired_title','招待リンクが期限切れ'),
('ja','accept_invite.error_title','参加できません'),
('ja','accept_invite.failed','チームへの参加中に問題が発生しました。もう一度お試しください。'),
('ja','accept_invite.invalid','招待トークンがないか無効です'),
('ja','accept_invite.joining','チームに参加しています…'),
('ja','accept_invite.return_home','ホームに戻る'),
('ja','accept_invite.success','チームへの参加に成功しました。リダイレクトしています…')
ON CONFLICT (locale, key) DO NOTHING;
