
INSERT INTO ui_translations (locale, key, value) VALUES
('ja','landing.alone_body','介護には心配、疑問、そして無数の小さな決断が伴います。CarerViewは穏やかで一貫したフレームワークを提供します — 「たぶん…」を、誰もが理解できる共有された事実に置き換えられます。'),
('ja','landing.alone_title','あなたは一人ではありません。'),
('ja','landing.careplan_after_b1','権限文書は記録され、アクセス可能で、必要になる前に確認済み'),
('ja','landing.careplan_after_b2','すべてのチームメンバーが自分の責任を把握 — 重複なし、抜け漏れなし、争いなし'),
('ja','landing.careplan_after_b3','ケアラーのストレスを監視 — ケアを行う人もサポートが必要なときにプランが警告'),
('ja','landing.careplan_after_label','CarerView使用時'),
('ja','landing.careplan_before_b1','病院の待合室で法的文書を探し回る'),
('ja','landing.careplan_before_b2','誰が何に責任を持つか合意がないために兄弟姉妹が口論になる'),
('ja','landing.careplan_before_b3','バックアップもなく、誰にも気づかれずにプライマリケアラーが燃え尽きる'),
('ja','landing.careplan_before_label','プランなしの場合'),
('ja','landing.careplan_engine_body','ほとんどのケアのギャップは危機を引き起こすまで見えません。CarerViewのデシジョンエンジンはあなたのプランをスキャンし、深刻度別にリスクをフラグ立て — チームが緊急事態の最中ではなく、前に行動できるようにします。'),
('ja','landing.careplan_engine_title','CarerViewはあなたのプランを読み取り、不足しているものを教えます'),
('ja','landing.careplan_eyebrow','ケアプラン'),
('ja','landing.careplan_gap_crit_label','重要'),
('ja','landing.careplan_gap_imp_label','重要度高'),
('ja','landing.careplan_gap_mon_label','要監視'),
('ja','landing.careplan_gap1','バックアップケアラーが特定されていない'),
('ja','landing.careplan_gap2','医療権限が文書化されていない'),
('ja','landing.careplan_gap3','プライマリケアラーのストレスレベル：高'),
('ja','landing.careplan_gap4','健康調整の担当者が割り当てられていない'),
('ja','landing.careplan_s1_desc','現在の状況は？今すぐ決断すべきことは何か？'),
('ja','landing.careplan_s1_label','状況'),
('ja','landing.careplan_s2_desc','誰が医療上の決定を下せるか？誰が財務を管理するか？法的文書は整っているか？'),
('ja','landing.careplan_s2_label','権限'),
('ja','landing.careplan_s3_desc','個人ケア、健康調整、財務、精神的サポート、レスパイトの担当者は誰か？担当者がいないことは責任がないことを意味します。'),
('ja','landing.careplan_s3_label','責任'),
('ja','landing.careplan_s4_desc','現在の居住状況は安全で持続可能か？ニーズが変化するにつれて何を変える必要があるか？'),
('ja','landing.careplan_s4_label','居住環境'),
('ja','landing.careplan_s5_desc','プライマリケアラーはこれを続けられるか？バックアップカバー、レスパイト時間、ケアを行う人へのサポートはあるか？'),
('ja','landing.careplan_s5_label','持続可能性'),
('ja','landing.careplan_s6_desc','プランの見直しはいつ必要か？誰がレビューを呼びかけ、ニーズが変化する中でチームはどのように足並みを揃えるか？'),
('ja','landing.careplan_s6_label','レビュー'),
('ja','landing.cta_begin','今日から観察を始める'),
('ja','landing.cta_why','あなたの家族がCarerViewを必要とする理由'),
('ja','landing.feat1_body','日常生活活動のコア項目について、数分で今日の様子をメモしましょう。簡単なチェックインや完全な観察をいつでも作成できます。'),
('ja','landing.feat1_title','シンプルなチェックイン'),
('ja','landing.feat2_body','今日だけでなく、日数・週数・月数にわたる変化を観察します。パターンがルーティンやサポートを調整するタイミングを示します。'),
('ja','landing.feat2_title','信頼できるトレンド'),
('ja','landing.feat3_body','曖昧な記憶ではなく、具体的な観察を持って受診する。'),
('ja','landing.feat3_title','診察を有意義に'),
('ja','landing.feat4_body','兄弟姉妹やサポーターを同じ事実と言葉で一致させる。'),
('ja','landing.feat4_title','家族間の摩擦を減らす'),
('ja','landing.feat5_body','穏やかなトレンドがルーティン、服薬、サポートを調整するタイミングを示します。'),
('ja','landing.feat5_title','小さな変化を早期に発見'),
('ja','landing.feat6_body','今日できることに焦点を当てながら、サポートが必要な部分を観察する。'),
('ja','landing.feat6_title','大切な方を尊重する'),
('ja','landing.getstarted_body','アカウントを作成するか、サインインしてケアラーダッシュボードに戻ります。'),
('ja','landing.getstarted_title','今日から始める'),
('ja','landing.hero_body','ほとんどの家族は計画なしに介護を始めます — 誰が医療権限を持つか、プライマリケアラーが疲れたときに誰が引き継ぐか、ケアを受ける方が実際に何を望んでいるかが不明確なまま。CarerViewはチームに構造化された計画、共有された観察、そしてすべての人を調整し大切な方を中心に置くフィードバックループを提供します。'),
('ja','landing.hero_intro','大切な方が在宅ケアを必要とするとき、家族はしばしば重要な問いに直面します：誰が医療上の決定を下すか？誰がバックアップサポートを提供するか？その方の希望、好み、ケアニーズは何か？共有されたケアプランは、家族が介護の課題に対して情報を持ち、足並みを揃え、準備できるよう助けます。'),
('ja','landing.hero_pillar_tagline','計画・調整・観察・改善'),
('ja','landing.mb_team_note','すべてのチームメンバーが自分の責任を把握しています。メモリーブックはそれをうまく行うためのコンテキストを即座に、セットアップ不要で提供します。'),
('ja','landing.newcarer_body','法的権限とチームの役割から健康調整と持続可能な計画まで、新しい家族ケアラーが理解する必要があるすべてをカバーする8つのモジュール。登録不要。'),
('ja','landing.newcarer_cta','ケアラーガイドを探索する'),
('ja','landing.newcarer_eyebrow','介護が初めての方へ'),
('ja','landing.newcarer_module1','全体像'),
('ja','landing.newcarer_module2','ケアプラン'),
('ja','landing.newcarer_module3','チームの役割'),
('ja','landing.newcarer_module4','居住環境'),
('ja','landing.newcarer_module5','法的権限'),
('ja','landing.newcarer_module6','健康調整'),
('ja','landing.newcarer_module7','持続可能性'),
('ja','landing.newcarer_module8','レビューと更新'),
('ja','landing.newcarer_title','無料のケアラーガイドから始める'),
('ja','landing.pillar_coord_b1','メモリーブックはすべてのチームメンバーに即座のコンテキストを提供 — その方が誰か、誰に電話すべきか、何を注意すべきか、何が安心させるか'),
('ja','landing.pillar_coord_b2','責任が割り当てられ — すべてのチームメンバーが自分の担当を正確に把握し、ケアの重複と抜け漏れを削減'),
('ja','landing.pillar_coord_b3','ファミリーサークルは最大3人のケアラーを共有観察、週次ダイジェスト、役割ベースのアクセスで繋げる'),
('ja','landing.pillar_coord_subtitle','チーム全体を同じページに'),
('ja','landing.pillar_coord_title','調整'),
('ja','landing.pillar_obs_b1','作業療法に基づくシンプルな1〜5のADLスケール — 専門用語なし、チーム全体のための明確な共通言語'),
('ja','landing.pillar_obs_b2','日数・週数・月数にわたるトレンド — パターンがルーティン、服薬、介護体制を調整するタイミングを示す'),
('ja','landing.pillar_obs_b3','曖昧な記憶ではなく、具体的な観察を持って診察に臨む。PDFまたはDOCXへワンクリックで書き出し'),
('ja','landing.pillar_obs_subtitle','変化を追跡 — プランを正確に保つ'),
('ja','landing.pillar_obs_title','観察'),
('ja','landing.pillar_plan_b1','6つの構造化セクション：状況、権限、責任、居住環境、持続可能性、レビュー'),
('ja','landing.pillar_plan_b2','デシジョンエンジンが危機になる前にギャップをフラグ立て — 「バックアップケアラーが特定されていない」や「医療権限が文書化されていない」'),
('ja','landing.pillar_plan_b3','ケアラーの持続可能性もプランの一部 — ストレスレベル、バックアップカバー、レスパイトはケア受益者のニーズと並行して追跡される'),
('ja','landing.pillar_plan_subtitle','チームの運営計画を構築する'),
('ja','landing.pillar_plan_title','計画'),
('ja','landing.pillar_review_b1','プランは文書ではなく、生きたシステムです。CarerViewは観察がレビューのタイミングを示すときに知らせます'),
('ja','landing.pillar_review_b2','5つのレビュートリガー：健康変化、新しいケアラー、居住環境の変化、ケアラーストレス閾値、または四半期定期レビュー'),
('ja','landing.pillar_review_b3','介護が初めての方へ：無料8モジュールガイドが法的権限から持続可能な計画まですべてをカバー'),
('ja','landing.pillar_review_subtitle','家族のニーズとともに進化する生きたプラン'),
('ja','landing.pillar_review_title','更新・改善'),
('ja','landing.pillars_body','CarerViewはすべてのケアチームが必要とする4つのこと — 明確なプラン、調整されたチーム、継続的な観察、そして物事が変化するときにプランを最新に保つ方法 — を統合します。'),
('ja','landing.pillars_eyebrow','CarerViewシステム'),
('ja','landing.pillars_title','家族介護のための完全なシステム'),
('ja','landing.privacy_promise','プライバシーポリシーを読む'),
('ja','landing.sample_subtitle','「心配です」から「変化がありました」へ。'),
('ja','landing.sample_title','たった1回の観察がもたらす違いを見る'),
('ja','landing.scale_body','シンプルな1〜5のスケールで、日常生活活動の変化を明確かつ一貫して観察・伝達できます。'),
('ja','landing.scale_eyebrow','日常生活活動'),
('ja','landing.scale_more_help','より多くの自立が可能'),
('ja','landing.scale_more_indep','より多くの介助が必要'),
('ja','landing.scale_summary','「完全自立」から「全介助」まで — 日常生活活動を観察するための明確なフレームワーク'),
('ja','landing.scale_title','CarerView 1〜5スケール'),
('ja','landing.scenario1_body','3つの都市に3人の兄弟姉妹、デイリーケアが必要な1人の親。CarerViewはすべての人が同じ観察、同じプラン、同じメモリーブックにアクセスできるようにします — 誰も異なるバージョンの出来事から作業しません。遠方の兄弟姉妹は電話する前ではなく、後に確認します。'),
('ja','landing.scenario1_title','遠距離家族の調整'),
('ja','landing.scenario2_body','退院指示が一度に届く — 服薬、フォローアップ、制限事項、何かあったときの連絡先。CarerViewはその混乱を構造化されたプランに変えます：責任を割り当て、初日から観察を開始し、何か変化があれば早期警告フラグを立てます。退院後の最初の2週間は最もリスクの高い期間です。CarerViewはまさにその瞬間に構造をもたらします。'),
('ja','landing.scenario2_title','退院後の在宅計画'),
('ja','landing.scenario3_body','複数の有償ケアラーがシフトを共有する場合、一貫した引き継ぎが重要です。メモリーブックはすべてのケアラー — 新しいものも戻ってきたものも — が書類ではなく、その人を知って来ることを意味します。各シフトの観察が共有記録を構築します。誰も同じ質問を2回しません。'),
('ja','landing.scenario3_title','交代制有償ケアラー'),
('ja','landing.scenarios_eyebrow','CarerViewの使われ方'),
('ja','landing.scenarios_title','現実の状況。本物の調整。'),
('ja','landing.sustainability_b1','プライマリケアラーのストレスレベル追跡'),
('ja','landing.sustainability_b2','バックアップケアラーの特定とバックアッププランの文書化'),
('ja','landing.sustainability_b3','レスパイト時間の計画 — 介護が長期的に持続可能であり続けるために'),
('ja','landing.sustainability_eyebrow','ケアラーの健康'),
('ja','landing.sustainability_title','ケアラーの限界を考慮しないプランは完全なプランではない'),
('ja','landing.testimonial_loc','コロラド州デンバー'),
('ja','landing.testimonial_name','Billy G.'),
('ja','landing.testimonial_quote','兄と2人のいとこが叔母のプライマリケアラーです。独立能力についての感情が多くの口論を引き起こしていました。CarerViewはすべての状況の観察を議論するための共通で使いやすいシステムを持てるので好きです。'),
('ja','landing.testimonial2_loc','英国マンチェスター'),
('ja','landing.testimonial2_name','Sarah M.'),
('ja','landing.testimonial2_quote','母は金曜日の午後に大量の指示書とともに退院し、誰が何をするのか誰も明確ではありませんでした。CarerViewはその週に本当の計画を立てるのを助けてくれました — 責任を割り当て、権限を整理し、みんながようやく同じページに。'),
('ja','landing.trust_title','あなたの家族のストーリーはあなたのもの'),
('ja','landing.trust1_body','家族の情報を完全に管理'),
('ja','landing.trust1_title','データはあなたのもの'),
('ja','landing.trust2_body','あなたが招待した人だけと共有'),
('ja','landing.trust2_title','デフォルトでプライベート'),
('ja','landing.trust3_body','常に暗号化され保護されている'),
('ja','landing.trust3_title','安全なストレージ'),
('ja','landing.vital_note','あなたの観察はケアプランに不可欠です！'),
('ja','landing.why_body','家族、臨床医、在宅ケアラーを同じページに乗せる一貫したフレームワーク。'),
('ja','landing.why_eyebrow','なぜ機能するのか'),
('ja','landing.why_title','混乱が減る — ケアの共通言語')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
('ja','why.adl_1','入浴・身の回りの衛生'),
('ja','why.adl_2','着替え・身だしなみ'),
('ja','why.adl_3','食事・飲み物'),
('ja','why.adl_4','トイレ・排泄管理'),
('ja','why.adl_5','移動・移乗'),
('ja','why.adl_6','安全意識'),
('ja','why.adl_title','日常生活活動'),
('ja','why.careplan_body','CarerViewのケアプランは重要なすべての側面をカバーします — ケア受益者のニーズだけでなく、チームのキャパシティ、法的権限構造、そしてプランを最新に保つメカニズム。各セクションは、家族が数ヶ月後に必要だったと気づく質問をします。'),
('ja','why.careplan_eyebrow','ケアプラン'),
('ja','why.careplan_title','家族のために構築されたプロフェッショナルグレードのフレームワーク'),
('ja','why.cta_begin','今すぐ観察を始める'),
('ja','why.cta_signin','サインイン'),
('ja','why.cta_trend_body','CarerViewはすべての家族ケアラーに構造化されたフレームワーク、調整ハブ、そすべてを最新に保つ観察を提供します。無料で始められます — クレジットカード不要。'),
('ja','why.cta_trend_title','プランを構築。チームを調整。重要なことを追跡。'),
('ja','why.custom_note','観察はカスタマイズ可能なので、CarerViewはあなたの家族の現実に合わせられます。'),
('ja','why.engine_body','ケアプランを構築するにつれて、CarerViewのデシジョンエンジンが不足しているものを読み取り、深刻度別にフラグを立てます。重要なギャップ — 医療権限の不備やバックアップケアラーの不在など — が最初に表示されます。重要なギャップ — 未割り当ての責任など — が続きます。プランは後で心配することではなく、最初に何をすべきかを教えてくれます。'),
('ja','why.engine_title','デシジョンエンジン：危機になる前にギャップを発見'),
('ja','why.faq6_a','デシジョンエンジンは、構築中のケアプランをスキャンして不足または不完全なセクションを特定する組み込みの分析ツールです。深刻度別にギャップをフラグ立てします — 重要（今すぐ対処）、重要度高（近いうちに対処）、要監視（注意を払い続ける）。これは医療ツールではなく — チームが最も重要なことに集中するための調整ツールです。'),
('ja','why.faq6_q','CarerViewのデシジョンエンジンとは何ですか？'),
('ja','why.faq7_a','ケアプランダッシュボードには、セクションと深刻度別にグループ分けされた検出されたギャップのサマリーが表示されます。各ギャップにはリスクの短い説明と推奨アクションステップが含まれます。最も緊急なギャップが上部にハイライトされます。任意の順序でギャップに取り組めます — プランはそれらに対処するにつれてリアルタイムで更新されます。'),
('ja','why.faq7_q','CarerViewはどのようにプランにギャップがあることを教えてくれますか？'),
('ja','why.hero_title','介護の組織化はストレスです！'),
('ja','why.hero_title_line2','CarerViewが調和をもたらします…'),
('ja','why.how1_body','日常生活活動のコア項目について、数分で今日の様子をメモしましょう。簡単なチェックインや完全な観察をいつでも作成できます。'),
('ja','why.how1_title','シンプルな観察'),
('ja','why.how2_body','明確な言葉 — 医療専門用語なし — 家族が理解できる作業療法のベストプラクティスに基づいています。'),
('ja','why.how2_title','簡単な1〜5スケール'),
('ja','why.how3_body','今日の感じだけでなく、日数・週数・月数にわたる変化を観察します。観察されたトレンドがルーティンやサポートを調整するタイミングを示します。'),
('ja','why.how3_title','信頼できるトレンド'),
('ja','why.how4_body','家族や臨床医と個人の観察を共有して、同じ定義とデータから議論を始めます。'),
('ja','why.how4_title','みんなを一致させる'),
('ja','why.iadl_1','服薬管理'),
('ja','why.iadl_2','食事・買い物'),
('ja','why.iadl_3','家事・洗濯'),
('ja','why.iadl_4','財務・事務処理'),
('ja','why.iadl_5','コミュニケーション・記憶'),
('ja','why.iadl_6','交通・買い物'),
('ja','why.iadl_title','手段的活動'),
('ja','why.newcarer_body','無料の8モジュールケアラーガイドは、家族介護のすべての側面を説明します — 役割が実際に何を含むかを理解することから、持続可能な長期計画を立てることまで。登録前に使用するか、ケアシステムを構築しながらCarerViewとともに使用してください。'),
('ja','why.newcarer_cta','CarerView無料の新しいケアラーガイドを探索する'),
('ja','why.newcarer_title','介護が初めての方へ。ここから始めてください。'),
('ja','why.persona1_b1','一か所で更新を見る — 情報を探し回る必要なし。'),
('ja','why.persona1_b2','電話や訪問の準備のためにトレンドを確認する。'),
('ja','why.persona1_b3','各人が見る必要があるものだけを共有する。'),
('ja','why.persona1_quote','「外出中です。状況から取り残されるのが嫌でした。CarerViewで電話する前に最新の観察を確認できます。」'),
('ja','why.persona1_title','遠距離家族の調整'),
('ja','why.persona2_b1','起きたことをリアルタイムで記録する。'),
('ja','why.persona2_b2','実際のメモから診察用サマリーを作成する。'),
('ja','why.persona2_b3','共有コンテキストでより落ち着いた決断をする。'),
('ja','why.persona2_quote','「子供たちと母の診察の間に詳細を忘れてしまいます。CarerViewがパターンを記録するので、医師に明確なメモを持参できます。」'),
('ja','why.persona2_title','サンドイッチ世代のケアラー'),
('ja','why.persona3_b1','初日から責任が割り当てられ — 誰も取り残されない'),
('ja','why.persona3_b2','観察がすぐに始まり — 何か変化があれば早期警告'),
('ja','why.persona3_b3','フォローアップ診察で共有するための臨床医向けサマリー'),
('ja','why.persona3_quote','退院日は圧倒されました。CarerViewは大量の指示書を本物の計画に変えるのを助けてくれました — 48時間以内に全員が自分の役割を把握しました。'),
('ja','why.persona3_title','退院の管理'),
('ja','why.persona4_b1','ストレスレベルが追跡され、ケアラーだけでなくチーム全体に見える'),
('ja','why.persona4_b2','限界点の前にバックアップケアラーが特定され計画が文書化される'),
('ja','why.persona4_b3','事実に基づいて公平に — 口論ではなく — 責任が再分配される'),
('ja','why.persona4_quote','一人ですべてをやっていて、誰にも見えていませんでした。CarerViewが私の状況を家族の他のメンバーに見えるようにしてくれました — そしてそのとき、ようやく物事が変わり始めました。'),
('ja','why.persona4_title','燃え尽きそうなプライマリケアラー'),
('ja','why.personas_title','本物の介護状況のために構築された'),
('ja','why.shared_lang_title','4つの柱。1つの調整されたケアシステム。'),
('ja','why.sustainability_body','ケアラーの燃え尽きは家族介護における最大のリスクの一つ — 通常、手遅れになるまで見えません。CarerViewの持続可能性セクションはプライマリケアラーのストレスレベル、バックアップカバー、レスパイト計画を追跡します。プランがリスクをフラグ立てすると、危機が会話を強制する前にチームが知ります。'),
('ja','why.sustainability_eyebrow','ケアラーの健康'),
('ja','why.sustainability_title','CarerViewはケア受益者だけでなく、ケアラーも追跡します'),
('ja','why.track_body','実際の日常生活を反映するシンプルな生活カテゴリー'),
('ja','why.track_title','観察する内容')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- new_obs namespace
('ja','new_obs.choose_type','記録する観察の種類を選択してください。'),
('ja','new_obs.create_title','新しい観察を作成'),
('ja','new_obs.email_missing','アカウントのメールアドレスが見つかりません。プロフィールを更新してください。'),
('ja','new_obs.loading','新しい観察を準備しています…'),
('ja','new_obs.no_team','最初にファミリーサークルを作成してください。'),
('ja','new_obs.page_title','新しい観察'),
('ja','new_obs.quota_reached','チームクォータに達しました（100回/年）。'),
('ja','new_obs.remaining_prefix','今年の残り観察回数：'),
('ja','new_obs.seat_frozen','シートが凍結されています。オーナーに請求管理を依頼してください。'),
-- obs_edit namespace
('ja','obs_edit.adl_label','日常生活（ADL）'),
('ja','obs_edit.comp_label','総合的評価'),
('ja','obs_edit.fetching','観察を取得しています…'),
('ja','obs_edit.form_adl','ADL'),
('ja','obs_edit.form_comprehensive','総合的評価'),
('ja','obs_edit.form_iadl','IADL'),
('ja','obs_edit.frozen_notice','アカウントが停止されています。現在、観察を編集できません。'),
('ja','obs_edit.iadl_label','生活スキル（IADL）'),
('ja','obs_edit.invalid_type','観察に無効なフォームタイプがあります：'),
('ja','obs_edit.loading','観察を読み込んでいます…'),
('ja','obs_edit.missing_id','URLに観察IDがありません。'),
('ja','obs_edit.observation_label','観察'),
('ja','obs_edit.readonly_notice','あなたは作成者ではないため、この観察を読み取り専用モードで閲覧しています。'),
('ja','obs_edit.render_error','この観察の読み込み中に問題が発生しました。'),
('ja','obs_edit.render_error_detail','ページを更新するか、ダッシュボードに戻ってください。'),
-- obs_form namespace
('ja','obs_form.adl_label','日常生活活動'),
('ja','obs_form.adl_type_label','日常生活動作'),
('ja','obs_form.autosave_hint','少なくとも1つの項目にスコアを入力すると自動保存されます'),
('ja','obs_form.cat_notes_label','{category}のメモ（任意）'),
('ja','obs_form.cat_notes_ph','{category}に関する具体的なメモ…'),
('ja','obs_form.cat_notes_placeholder','このカテゴリーに関する具体的なメモを追加…'),
('ja','obs_form.category_scored','{scored}/{total} スコア済み'),
('ja','obs_form.comprehensive_label','総合的評価（ADL＋IADL）'),
('ja','obs_form.contact_support','この問題が続く場合は、サポートにお問い合わせください。'),
('ja','obs_form.date_invalid','MM/DD/YYYY形式で有効な日付を入力してください'),
('ja','obs_form.date_label','観察日'),
('ja','obs_form.date_placeholder','MM/DD/YYYY'),
('ja','obs_form.date_required','観察日は必須です'),
('ja','obs_form.err_email','アカウントのメールアドレスが見つからないか無効です。サインアウトして再度サインインしてください。'),
('ja','obs_form.err_no_score','保存する前に少なくとも1つのスコアを選択してください。'),
('ja','obs_form.error_loading','観察の質問を読み込めませんでした。もう一度お試しください。'),
('ja','obs_form.form_type_comp','総合的評価（ADL＋IADL）'),
('ja','obs_form.guidance','好きなだけ多く、または少なく記入してください。すべての質問に答える必要はありません — 少数のスコアでも役立ちます。少なくとも1つのスコアを入力すると、45秒ごとに自動保存されます。'),
('ja','obs_form.guidance_bold','ヒント：'),
('ja','obs_form.iadl_label','生活スキル'),
('ja','obs_form.iadl_type_label','手段的日常生活活動'),
('ja','obs_form.last_saved','{time}に最後に保存'),
('ja','obs_form.last_saved_at','最後に保存した時刻'),
('ja','obs_form.loading','観察フォームを読み込んでいます…'),
('ja','obs_form.mode_in_person','対面'),
('ja','obs_form.mode_label','どのように観察しましたか？'),
('ja','obs_form.mode_video','ビデオ通話'),
('ja','obs_form.mode_voice','音声通話'),
('ja','obs_form.more_help','より多くのサポートが必要'),
('ja','obs_form.more_indep','より自立している'),
('ja','obs_form.no_questions','利用可能な質問がありません'),
('ja','obs_form.no_score_hint','この観察を保存するには、上記の少なくとも1つの質問にスコアをつけてください。'),
('ja','obs_form.notes_ph','今日の訪問に関する一般的な観察…'),
('ja','obs_form.patient_label','観察対象者'),
('ja','obs_form.patient_ph','その方のお名前'),
('ja','obs_form.resident_edit_link','編集'),
('ja','obs_form.resident_no_profile_hint','まだ入居者プロファイルが設定されていません。'),
('ja','obs_form.resident_no_profile_link','入居者プロファイルを設定する'),
('ja','obs_form.resident_placeholder','その方のお名前'),
('ja','obs_form.save_changes','変更を保存'),
('ja','obs_form.save_continue','保存して続ける'),
('ja','obs_form.save_failed','自動保存に失敗しました'),
('ja','obs_form.save_obs','観察を保存'),
('ja','obs_form.saved','保存済み'),
('ja','obs_form.saving','保存中…'),
('ja','obs_form.score_ref_header','スコア参照 — 各質問の番号をタップして観察を記録してください'),
('ja','obs_form.scored_count','{scored}/{total} スコア済み'),
('ja','obs_form.title_edit','観察を編集'),
('ja','obs_form.title_new','新しい観察'),
-- obs_list namespace
('ja','obs_list.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','obs_list.delete_title','観察を削除しますか？'),
('ja','obs_list.empty_body','最初の観察を作成して始めましょう。'),
('ja','obs_list.empty_title','観察がまだありません'),
('ja','obs_list.export_csv','CSVとしてエクスポート'),
('ja','obs_list.export_docx','DOCXとしてエクスポート'),
('ja','obs_list.guest_badge','ゲスト'),
('ja','obs_list.load_failed','観察の読み込みに失敗しました'),
('ja','obs_list.loading','観察を読み込んでいます...'),
('ja','obs_list.observed_on','{date}に観察'),
('ja','obs_list.unnamed_resident','名前のない入居者'),
-- view_obs namespace
('ja','view_obs.back_list','リストに戻る'),
('ja','view_obs.caregiver','ケアラー'),
('ja','view_obs.comp_label','総合的評価（ADL＋IADL）'),
('ja','view_obs.csv_label','スプレッドシート（.csv）'),
('ja','view_obs.delete_generic','この観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_title','観察を削除しますか？'),
('ja','view_obs.details_title','観察の詳細'),
('ja','view_obs.docx_label','Wordドキュメント（.docx）'),
('ja','view_obs.load_error','観察を読み込めませんでした。もう一度お試しください。'),
('ja','view_obs.load_failed','観察の読み込みに失敗しました'),
('ja','view_obs.loading','観察を読み込んでいます...'),
('ja','view_obs.mode','観察方法'),
('ja','view_obs.no_resp_body','この観察には記録された回答がありません。'),
('ja','view_obs.no_responses','回答なし'),
('ja','view_obs.not_found','観察が見つかりません'),
('ja','view_obs.notes','メモ'),
('ja','view_obs.obs_date','観察日'),
('ja','view_obs.obs_type','観察タイプ'),
('ja','view_obs.patient_name','患者名'),
('ja','view_obs.print','印刷'),
('ja','view_obs.resident_name','入居者名')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- account_menu
('ja','account_menu.billing','請求を管理する'),
('ja','account_menu.delete_acct','アカウントを削除'),
('ja','account_menu.manage','アカウントを管理する'),
('ja','account_menu.manage_account','アカウントを管理する'),
('ja','account_menu.restart_tutorial','チュートリアルを再スタート'),
('ja','account_menu.sign_out','サインアウト'),
('ja','account_menu.tutorial','チュートリアルを再スタート'),
-- active_cg
('ja','active_cg.loading','管理者ビューを読み込んでいます…'),
-- auth_callback
('ja','auth_callback.verifying','リンクを確認しています…'),
-- community_banner
('ja','community_banner.tagline_after','経験を共有し、質問をして、実践的な知恵を見つけましょう。'),
('ja','community_banner.tagline_before','家族と在宅ケアラーのために。'),
-- community
('ja','community.help_type_desc.emotional_support','聞いてもらったり、気持ちを認めてもらいたい'),
('ja','community.help_type_desc.practical_tips','うまくいくアドバイスや戦略を探している'),
('ja','community.help_type_desc.question','助けが必要な具体的な質問がある'),
('ja','community.help_type_desc.resource','役立つものを見つけたので共有したい'),
('ja','community.help_type_desc.similar_experiences','同じような経験をした人はいますか？'),
('ja','community.join.benefit.anonymous','プライバシーが必要なときに匿名で投稿'),
('ja','community.join.benefit.connect','本当に理解してくれるケアラーとつながる'),
('ja','community.join.benefit.share','経験を共有してピアサポートを得る'),
('ja','community.join.inline.description','コミュニティに参加して投稿し、他のケアラーとつながりましょう。'),
('ja','community.loading','コミュニティを読み込んでいます…'),
('ja','community.new_post.anonymous_active_desc','ハンドルは他のユーザーに表示されません。モデレーションのためにアイデンティティは内部で記録されます。'),
('ja','community.new_post.anonymous_desc','コミュニティハンドルが表示されます。他のユーザーから隠すにはトグルしてください。'),
('ja','community.profile.avatar_preview','アバターのプレビュー'),
('ja','community.reply_anon_active_title','匿名モードがオン'),
('ja','community.reply_anon_inactive_title','匿名で投稿'),
-- export
('ja','export.csv_resident_name','入居者名'),
('ja','export.unnamed_resident','名前のない入居者'),
-- family_setup
('ja','family_setup.body','ファミリーサークルプランには最大3名のケアラーが含まれます。共有チームを作成して始めましょう。'),
('ja','family_setup.create_btn','ファミリーサークルを作成'),
('ja','family_setup.creating','作成中…'),
('ja','family_setup.loading','読み込み中…'),
('ja','family_setup.resident_label','誰のケアをしていますか？'),
('ja','family_setup.resident_placeholder','例：お母さん、お父さん、田中さん'),
('ja','family_setup.resident_required','ケアをする方の名前を入力してください。'),
('ja','family_setup.team_name_ph','家族チーム名'),
('ja','family_setup.title','ファミリーサークルを設定する'),
-- footer
('ja','footer.about_link','CarerViewについて'),
('ja','footer.copyright','© {year} CarerView.com | 全著作権所有 | GrifDigi社'),
('ja','footer.location_nz','ニュージーランド、クライストチャーチ'),
('ja','footer.location_us','コロラド州デンバー、USA'),
('ja','footer.locations','所在地：'),
('ja','footer.policies','ポリシー'),
('ja','footer.pricing_link','料金プラン'),
('ja','footer.resources_heading','リソース'),
('ja','footer.suggestions','ご提案・ご質問？'),
('ja','footer.tutorial_link','CarerViewチュートリアル'),
-- lang
('ja','lang.current','言語'),
('ja','lang.switch_aria','言語を切り替える'),
-- nav
('ja','nav.family_circle','ファミリーサークル'),
('ja','nav.home_aria','CarerViewホーム'),
('ja','nav.logo_aria','CarerViewロゴ'),
('ja','nav.manage_billing','請求を管理する'),
('ja','nav.memory_book_short','メモリーブック'),
('ja','nav.toggle_menu','ナビゲーションメニューを切り替える'),
('ja','nav.tutorial_short','チュートリアル'),
('ja','nav.welcome','ようこそ'),
('ja','nav.why_carerview','CarerViewについて'),
-- plan_pill
('ja','plan_pill.family','ファミリーサークル'),
('ja','plan_pill.primary','プライマリ'),
-- reset_pw
('ja','reset_pw.confirm_ph','新しいパスワードを再入力'),
('ja','reset_pw.err_mismatch','パスワードが一致しません。もう一度お試しください。'),
('ja','reset_pw.err_too_short','パスワードは8文字以上である必要があります。'),
('ja','reset_pw.new_pw_label','新しいパスワード'),
('ja','reset_pw.new_pw_ph','新しいパスワードを入力'),
('ja','reset_pw.no_token','リカバリートークンが見つかりませんでした。新しいパスワードリセットを要求してください。'),
('ja','reset_pw.submit_btn','パスワードを更新'),
('ja','reset_pw.submitting','更新中…'),
('ja','reset_pw.success','パスワードが正常に更新されました！サインインにリダイレクトしています...'),
-- scale
('ja','scale.1','完全自立'),
('ja','scale.2','困難だが自立'),
('ja','scale.3','サポートありで自立'),
('ja','scale.4','常時共同作業'),
('ja','scale.5','全介助'),
-- team_guard
('ja','team_guard.upgrade_body_default','ファミリーサークルプランでは、共有ケアチームを構築し、家族を招待し、全員を同じページに保つことができます。'),
('ja','team_guard.upgrade_body_primary','プライマリケアラープランはソロケアラーに最適です。ファミリーサークルプランにアップグレードして、家族を招待し、介護の旅を共に分かち合いましょう。'),
('ja','team_guard.upgrade_cta','ファミリーサークルにアップグレード'),
('ja','team_guard.upgrade_title','ファミリーサークルはチーム機能です'),
-- team
('ja','team.caregivers_title','ケアラー'),
('ja','team.copy_link_note','今すぐメールにコピーしてください。'),
('ja','team.invite_email_ph','caregiver@email'),
('ja','team.invite_expires_on','このリンクは{date}に失効します。その後、新しい招待を生成する必要があります。'),
('ja','team.invite_link_label','招待リンク：'),
('ja','team.loading','読み込み中…'),
('ja','team.no_members','メンバーがまだいません。'),
('ja','team.no_team','最初にファミリーサークルを作成してください。'),
('ja','team.title','ファミリーサークル'),
-- welcome
('ja','welcome.dismiss_aria','ウェルカムメッセージを閉じる')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- billing
('ja','billing.loading','請求情報を読み込んでいます…'),
('ja','billing.manage_btn','請求を管理する'),
('ja','billing.not_active','アクティブなサブスクリプションなし'),
('ja','billing.period_ends','現在の期間終了'),
('ja','billing.portal_failed','請求ポータルを開けませんでした。もう一度お試しください。'),
('ja','billing.status_label','ステータス：'),
('ja','billing.title','請求とサブスクリプション'),
-- public.caregiver_resources
('ja','public.caregiver_resources.bridge_heading','あなたは一人ではありません'),
('ja','public.caregiver_resources.bridge_intro_1','多くのケアラーは同じ場所から始まります — 不確かで、圧倒され、方向を探しています。'),
('ja','public.caregiver_resources.bridge_intro_2','ガイドを読むことも役立ちますが、同じ経験をしている人々の声を聞くことも助けになります。'),
('ja','public.caregiver_resources.bridge_view_discussion','ディスカッションを見る'),
('ja','public.caregiver_resources.final_cta_body','他の方から学んでください。そして、CarerViewで自分のケアプランをコントロールしましょう。'),
('ja','public.caregiver_resources.final_cta_heading','読むだけでなく — ケアの整理を始めましょう'),
('ja','public.caregiver_resources.final_cta_primary_btn','始める'),
('ja','public.caregiver_resources.final_cta_secondary_btn','コミュニティを探索する'),
('ja','public.caregiver_resources.hero_heading','認知症・記憶ケアのためのケアラーリソース'),
('ja','public.caregiver_resources.hero_intro_1','記憶障害や認知症のある方のケアが初めての場合、圧倒されるかもしれません。すべてを自分で解決する必要はありません。'),
('ja','public.caregiver_resources.hero_intro_2','以下は、何を期待するか、先を計画する方法、サポートを受ける方法を理解するのに役立つ信頼できる組織と政府リソースです。'),
('ja','public.caregiver_resources.how_to_bullet_1','政府ガイドから始めて状態を理解する'),
('ja','public.caregiver_resources.how_to_bullet_2','サポートと現実世界の助けのために非営利団体を利用する'),
('ja','public.caregiver_resources.how_to_bullet_3','準備ができたら地域のサービスとサポートグループを探す'),
('ja','public.caregiver_resources.how_to_closing','一度にすべてを使用する必要はありません。1つから始めて積み重ねていってください。'),
('ja','public.caregiver_resources.how_to_heading','これらのリソースの使い方'),
('ja','public.caregiver_resources.how_to_intro','各リソースは異なる目的に役立ちます：'),
('ja','public.caregiver_resources.meta_desc','認知症・記憶ケアのための信頼できるケアラーリソース。新しいケアラーが始めるためのシンプルなガイド、サポート団体、計画ツール。'),
('ja','public.caregiver_resources.mid_cta_body','ガイドは役立ちますが、実際の経験も重要です。他のケアラーが何を質問し、共有しているかを見てください。'),
('ja','public.caregiver_resources.mid_cta_btn','コミュニティを探索する'),
('ja','public.caregiver_resources.mid_cta_heading','他のケアラーから学ぶ'),
('ja','public.caregiver_resources.page_title','認知症・記憶ケアのためのケアラーリソース | CarerView'),
('ja','public.caregiver_resources.res1_desc','認知症ケアが初めての方向けに設計された米国政府ウェブサイト。何を期待するか、どのように準備するか、どこでサポートを受けるかを説明します。次に何をすべきかわからない場合に最適な出発点の一つです。'),
('ja','public.caregiver_resources.res1_domain','alzheimers.gov'),
('ja','public.caregiver_resources.res1_title','Alzheimers.gov'),
('ja','public.caregiver_resources.res2_desc','アルツハイマーと記憶に関する疾患について、明確で研究に基づいた情報を提供します。介護、健康変化、ケアラーとしての自己ケアに関する実用的なガイドが含まれています。'),
('ja','public.caregiver_resources.res2_domain','nia.nih.gov'),
('ja','public.caregiver_resources.res2_title','米国老年医学研究所'),
('ja','public.caregiver_resources.res3_desc','ケアラーサポート、教育、24時間365日のヘルプラインを提供する主要な非営利団体。地域のサポートグループを見つけ、いつでも誰かと話し、ケアの異なる段階のステップバイステップガイドにアクセスできます。'),
('ja','public.caregiver_resources.res3_domain','alz.org'),
('ja','public.caregiver_resources.res3_title','アルツハイマー協会'),
('ja','public.caregiver_resources.res4_desc','教育、記憶スクリーニング、コミュニティプログラムを含むケアラーへの実用的なサポートに焦点を当てています。実践的なガイダンスと精神的サポートを求める家族に役立ちます。'),
('ja','public.caregiver_resources.res4_domain','alzfdn.org'),
('ja','public.caregiver_resources.res4_title','アメリカアルツハイマー財団'),
('ja','public.caregiver_resources.res5_desc','認知症のある方のケアを含むすべてのタイプのケアラーへのサポートを提供します。長期計画、ケアラーの権利、時間をかけたストレス管理に強い焦点を当てています。'),
('ja','public.caregiver_resources.res5_domain','caregiver.org'),
('ja','public.caregiver_resources.res5_title','家族ケアラーアライアンス'),
-- public.community
('ja','public.community.join_modal_body','無料アカウントを作成して、質問をし、経験を共有し、他のケアラーとつながりましょう。'),
('ja','public.community.join_modal_create_btn','無料アカウントを作成'),
('ja','public.community.join_modal_signin_btn','サインイン'),
('ja','public.community.join_modal_title','コミュニティに参加する'),
('ja','public.community.popular_topics_heading','人気のスタータートピック'),
('ja','public.community.popular_topics_intro','ケアラーが始めたばかりのときに最もよく聞く質問。'),
('ja','public.community.topic1_excerpt','突然、記憶障害のある親の責任を負うことになり、何を最初に優先すべきかわかりません。'),
('ja','public.community.topic1_title','ケアラーになったばかりです。どこから始めればいいですか？'),
('ja','public.community.topic2_excerpt','自宅での管理と外部の助けを得ることの間で決断しようとしています。'),
('ja','public.community.topic2_title','より多くのケアが必要なタイミングをどうやって知ることができますか？'),
('ja','public.community.topic3_excerpt','振り返ってみると、もっと早く計画しておけばよかったと思うことは何ですか？'),
('ja','public.community.topic3_title','新しいケアラーとして何に驚きましたか？'),
('ja','public.community.topics_browse_all','すべてを閲覧'),
('ja','public.community.topics_see_resources','リソースを見る')
ON CONFLICT (locale, namespace, key) DO NOTHING;
-- Add why.faq1-5 and FAQ section heading keys that were hardcoded in WhyCarerView.tsx
-- English rows (canonical source text)
INSERT INTO ui_translations (locale, key, value) VALUES
  ('en', 'why.faq_section_title', 'Frequently Asked Questions'),
  ('en', 'why.faq_section_subtitle', 'Common questions about CarerView, care planning, and coordination.'),
  ('en', 'why.faq1_q', 'What is an Activities of Daily Living (ADL) assessment?'),
  ('en', 'why.faq1_a', 'An Activities of Daily Living (ADL) assessment measures how well a person can perform basic self-care tasks such as bathing, dressing, eating, and moving around. CarerView uses a simple 1-5 scale so family caregivers can track these changes consistently over time and share meaningful reports with healthcare providers.'),
  ('en', 'why.faq2_q', 'How does CarerView help family caregivers track changes in a loved one?'),
  ('en', 'why.faq2_a', 'CarerView provides structured observation forms covering ADL and IADL activities. You record a quick 1-5 score and optional notes for each check-in. Over time, these build into a clear picture of what''s changing — so you can spot trends, adjust care plans, and arrive at doctor appointments with specific, documented observations rather than vague impressions.'),
  ('en', 'why.faq3_q', 'Can multiple family members use CarerView together?'),
  ('en', 'why.faq3_a', 'Yes. The Family Circle plan allows you to invite siblings, spouses, or professional in-home carers to a shared care view. Everyone sees the same observations and can add their own. This eliminates the friction that commonly causes stress in families sharing caregiving responsibilities.'),
  ('en', 'why.faq4_q', 'Can I share CarerView observation reports with doctors or care professionals?'),
  ('en', 'why.faq4_a', 'Yes. CarerView can export your observation history as a DOCX or CSV file that you can bring to GP appointments, specialist consultations, or care reviews. Having a written record of changes over weeks and months is far more useful to healthcare providers than trying to recall how things were three months ago.'),
  ('en', 'why.faq5_q', 'How is CarerView different from a general care notes app?'),
  ('en', 'why.faq5_a', 'CarerView is a full care coordination system — not just a notes app. It includes a structured Care Plan with six sections, a Decision Engine that flags missing pieces by severity, a Memory Book that gives every team member instant context, and an observation framework based on the ADL and IADL scales used by healthcare professionals.')
ON CONFLICT (locale, namespace, key) DO NOTHING;

-- Japanese translations
INSERT INTO ui_translations (locale, key, value) VALUES
  ('ja', 'why.faq_section_title', 'よくある質問'),
  ('ja', 'why.faq_section_subtitle', 'CarerView、ケアプランニング、コーディネーションに関するよくある質問。'),
  ('ja', 'why.faq1_q', '日常生活動作（ADL）評価とは何ですか？'),
  ('ja', 'why.faq1_a', '日常生活動作（ADL）評価は、入浴・着替え・食事・移動などの基本的なセルフケア動作をどの程度できるかを測定するものです。CarerViewでは1〜5のシンプルなスケールを使い、家族介護者が経時的に変化を一貫して記録し、医療従事者に意味のある報告書を共有できます。'),
  ('ja', 'why.faq2_q', 'CarerViewは、家族介護者が愛する人の変化を追跡するのにどのように役立ちますか？'),
  ('ja', 'why.faq2_a', 'CarerViewは、ADLとIADL活動を対象とした構造化された観察フォームを提供します。チェックインごとに1〜5のスコアと任意のメモを記録します。時間の経過とともに何が変化しているかの明確な全体像が形成され、傾向の把握、ケアプランの調整、そして漠然とした印象ではなく具体的な記録を持って医師の予約に臨むことができます。'),
  ('ja', 'why.faq3_q', '複数の家族がCarerViewを一緒に使用できますか？'),
  ('ja', 'why.faq3_a', 'はい。ファミリーサークルプランでは、兄弟姉妹、配偶者、または専門の在宅介護者を共有のケアビューに招待できます。全員が同じ観察記録を見て、それぞれが追加することもできます。これにより、介護の責任を分担する家族間でよく起こる摩擦をなくすことができます。'),
  ('ja', 'why.faq4_q', 'CarerViewの観察レポートを医師や介護専門家と共有できますか？'),
  ('ja', 'why.faq4_a', 'はい。CarerViewは観察履歴をDOCXまたはCSVファイルとしてエクスポートでき、かかりつけ医の予約、専門医の診察、またはケアレビューに持参できます。数週間から数ヶ月にわたる変化の書面記録は、3ヶ月前の状態を思い出そうとするよりも、医療従事者にとってはるかに役立ちます。'),
  ('ja', 'why.faq5_q', 'CarerViewは一般的なケアメモアプリとどう違うのですか？'),
  ('ja', 'why.faq5_a', 'CarerViewは単なるメモアプリではなく、総合的なケアコーディネーションシステムです。6つのセクションからなる構造化されたケアプラン、欠けている部分を重要度別にフラグ立てするデシジョンエンジン、チームメンバー全員に即座にコンテキストを提供するメモリーブック、そして医療専門家が使用するADLおよびIADLスケールに基づいた観察フレームワークが含まれています。')
ON CONFLICT (locale, namespace, key) DO NOTHING;
