
INSERT INTO ui_translations (locale, namespace, key, value) VALUES

-- ─────────────── ENGLISH ───────────────
('en', 'common', 'dementia.page_title',      'Dementia Reference Scale'),
('en', 'common', 'dementia.signs_symptoms',  'Signs & Symptoms'),
('en', 'common', 'dementia.expected_duration','Expected Duration'),
('en', 'common', 'dementia.not_applicable',  'Not applicable'),
('en', 'common', 'dementia.note_4',          'At this stage the person may be aware of their difficulties but tries to conceal or minimise them. A physician can detect problems through clinical interview.'),
('en', 'common', 'dementia.note_5',          'The person can no longer survive without some assistance. They retain knowledge of major personal facts (their name, their children''s names) but may have forgotten their address or phone number.'),
('en', 'common', 'dementia.note_6',          'The person is largely unaware of recent events and experiences. They require significant assistance with all activities of daily living and may require full-time supervision.'),
('en', 'common', 'dementia.note_7',          'All verbal abilities are lost over the course of this stage. Basic psychomotor skills are lost and the person is bedridden. Comfort-focused care is the priority.'),
('en', 'common', 'dementia.about_title',     'About the Global Deterioration Scale (GDS)'),
('en', 'common', 'dementia.about_p1',        'The Global Deterioration Scale (GDS), developed by Dr. Barry Reisberg, provides caregivers with an overview of the stages of cognitive function for those suffering from a primary degenerative dementia such as Alzheimer''s disease.'),
('en', 'common', 'dementia.about_p2',        'The scale defines 7 stages from no cognitive decline to very severe cognitive decline. The GDS is most relevant for individuals with Alzheimer''s disease and may not apply to other forms of dementia.'),
('en', 'common', 'dementia.stages_13',       'Stages 1–3'),
('en', 'common', 'dementia.stages_13_desc',  'No Dementia'),
('en', 'common', 'dementia.stage_4',         'Stage 4'),
('en', 'common', 'dementia.stage_4_desc',    'Early-Stage Dementia'),
('en', 'common', 'dementia.stages_56',       'Stages 5–6'),
('en', 'common', 'dementia.stages_56_desc',  'Mid-Stage Dementia'),
('en', 'common', 'dementia.stage_7',         'Stage 7'),
('en', 'common', 'dementia.stage_7_desc',    'Late-Stage Dementia'),
('en', 'common', 'dementia.seven_stages',    'The Seven Stages'),
('en', 'common', 'dementia.disclaimer_label','Disclaimer:'),
('en', 'common', 'dementia.disclaimer_body', 'This scale is a clinical reference tool intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Please consult a qualified healthcare provider for any medical concerns.'),

-- ─────────────── SPANISH ───────────────
('es', 'common', 'dementia.page_title',      'Escala de Referencia de Demencia'),
('es', 'common', 'dementia.signs_symptoms',  'Signos y Síntomas'),
('es', 'common', 'dementia.expected_duration','Duración Esperada'),
('es', 'common', 'dementia.not_applicable',  'No aplicable'),
('es', 'common', 'dementia.note_4',          'En esta etapa la persona puede ser consciente de sus dificultades pero intenta ocultarlas o minimizarlas. Un médico puede detectar problemas mediante una entrevista clínica.'),
('es', 'common', 'dementia.note_5',          'La persona ya no puede sobrevivir sin cierta asistencia. Conserva conocimientos de hechos personales importantes, pero puede haber olvidado su dirección o teléfono.'),
('es', 'common', 'dementia.note_6',          'La persona tiene poca conciencia de los eventos y experiencias recientes. Requiere asistencia significativa en todas las actividades de la vida diaria y puede necesitar supervisión continua.'),
('es', 'common', 'dementia.note_7',          'Todas las habilidades verbales se pierden durante esta etapa. Se pierden las habilidades psicomotoras básicas y la persona queda postrada en cama. La atención centrada en el confort es la prioridad.'),
('es', 'common', 'dementia.about_title',     'Acerca de la Escala de Deterioro Global (GDS)'),
('es', 'common', 'dementia.about_p1',        'La Escala de Deterioro Global (GDS), desarrollada por el Dr. Barry Reisberg, proporciona a los cuidadores una visión general de las etapas de la función cognitiva para quienes padecen demencia degenerativa primaria como el Alzheimer.'),
('es', 'common', 'dementia.about_p2',        'La escala define 7 etapas, desde ningún deterioro cognitivo hasta un deterioro cognitivo muy grave. La GDS es más relevante para personas con Alzheimer y puede no aplicarse a otras formas de demencia.'),
('es', 'common', 'dementia.stages_13',       'Etapas 1–3'),
('es', 'common', 'dementia.stages_13_desc',  'Sin Demencia'),
('es', 'common', 'dementia.stage_4',         'Etapa 4'),
('es', 'common', 'dementia.stage_4_desc',    'Demencia Temprana'),
('es', 'common', 'dementia.stages_56',       'Etapas 5–6'),
('es', 'common', 'dementia.stages_56_desc',  'Demencia en Etapa Media'),
('es', 'common', 'dementia.stage_7',         'Etapa 7'),
('es', 'common', 'dementia.stage_7_desc',    'Demencia en Etapa Tardía'),
('es', 'common', 'dementia.seven_stages',    'Las Siete Etapas'),
('es', 'common', 'dementia.disclaimer_label','Aviso:'),
('es', 'common', 'dementia.disclaimer_body', 'Esta escala es una herramienta de referencia clínica destinada únicamente a fines informativos. No sustituye el consejo, diagnóstico o tratamiento médico profesional. Consulte a un proveedor de salud calificado para cualquier preocupación médica.'),

-- ─────────────── FRENCH ───────────────
('fr', 'common', 'dementia.page_title',      'Échelle de Référence de la Démence'),
('fr', 'common', 'dementia.signs_symptoms',  'Signes et Symptômes'),
('fr', 'common', 'dementia.expected_duration','Durée Attendue'),
('fr', 'common', 'dementia.not_applicable',  'Non applicable'),
('fr', 'common', 'dementia.note_4',          'À ce stade, la personne peut être consciente de ses difficultés mais tente de les dissimuler ou de les minimiser. Un médecin peut détecter des problèmes lors d''un entretien clinique.'),
('fr', 'common', 'dementia.note_5',          'La personne ne peut plus survivre sans une certaine assistance. Elle conserve la connaissance de faits personnels importants, mais peut avoir oublié son adresse ou son numéro de téléphone.'),
('fr', 'common', 'dementia.note_6',          'La personne est largement inconsciente des événements et expériences récents. Elle nécessite une aide importante pour toutes les activités de la vie quotidienne et peut nécessiter une surveillance permanente.'),
('fr', 'common', 'dementia.note_7',          'Toutes les capacités verbales sont perdues au cours de ce stade. Les compétences psychomotrices de base disparaissent et la personne est alitée. Les soins axés sur le confort sont la priorité.'),
('fr', 'common', 'dementia.about_title',     'À propos de l''Échelle de Détérioration Globale (GDS)'),
('fr', 'common', 'dementia.about_p1',        'L''Échelle de Détérioration Globale (GDS), développée par le Dr Barry Reisberg, donne aux aidants un aperçu des stades de la fonction cognitive pour les personnes souffrant d''une démence dégénérative primaire telle que la maladie d''Alzheimer.'),
('fr', 'common', 'dementia.about_p2',        'L''échelle définit 7 stades, allant d''aucun déclin cognitif à un déclin cognitif très sévère. La GDS est la plus pertinente pour les personnes atteintes de la maladie d''Alzheimer et peut ne pas s''appliquer à d''autres formes de démence.'),
('fr', 'common', 'dementia.stages_13',       'Stades 1–3'),
('fr', 'common', 'dementia.stages_13_desc',  'Pas de Démence'),
('fr', 'common', 'dementia.stage_4',         'Stade 4'),
('fr', 'common', 'dementia.stage_4_desc',    'Démence au Stade Précoce'),
('fr', 'common', 'dementia.stages_56',       'Stades 5–6'),
('fr', 'common', 'dementia.stages_56_desc',  'Démence au Stade Intermédiaire'),
('fr', 'common', 'dementia.stage_7',         'Stade 7'),
('fr', 'common', 'dementia.stage_7_desc',    'Démence au Stade Avancé'),
('fr', 'common', 'dementia.seven_stages',    'Les Sept Stades'),
('fr', 'common', 'dementia.disclaimer_label','Avertissement :'),
('fr', 'common', 'dementia.disclaimer_body', 'Cette échelle est un outil de référence clinique destiné uniquement à des fins d''information. Elle ne remplace pas les conseils médicaux professionnels, le diagnostic ou le traitement. Veuillez consulter un professionnel de santé qualifié pour toute préoccupation médicale.'),

-- ─────────────── GERMAN ───────────────
('de', 'common', 'dementia.page_title',      'Demenz-Referenzskala'),
('de', 'common', 'dementia.signs_symptoms',  'Anzeichen und Symptome'),
('de', 'common', 'dementia.expected_duration','Erwartete Dauer'),
('de', 'common', 'dementia.not_applicable',  'Nicht zutreffend'),
('de', 'common', 'dementia.note_4',          'In diesem Stadium ist sich die Person ihrer Schwierigkeiten möglicherweise bewusst, versucht sie jedoch zu verbergen oder zu minimieren. Ein Arzt kann Probleme im klinischen Interview erkennen.'),
('de', 'common', 'dementia.note_5',          'Die Person kann nicht mehr ohne Unterstützung auskommen. Sie kennt noch wichtige persönliche Fakten, hat aber möglicherweise ihre Adresse oder Telefonnummer vergessen.'),
('de', 'common', 'dementia.note_6',          'Die Person ist sich jüngster Ereignisse und Erfahrungen weitgehend nicht bewusst. Sie benötigt erhebliche Unterstützung bei allen Aktivitäten des täglichen Lebens und möglicherweise Rund-um-die-Uhr-Betreuung.'),
('de', 'common', 'dementia.note_7',          'Im Verlauf dieses Stadiums gehen alle verbalen Fähigkeiten verloren. Grundlegende psychomotorische Fähigkeiten werden verloren und die Person ist bettlägerig. Komfortzentrierte Pflege hat Priorität.'),
('de', 'common', 'dementia.about_title',     'Über die Globale Verschlechterungsskala (GDS)'),
('de', 'common', 'dementia.about_p1',        'Die Globale Verschlechterungsskala (GDS), entwickelt von Dr. Barry Reisberg, bietet Pflegenden einen Überblick über die Stufen der kognitiven Funktion bei Personen mit einer primären degenerativen Demenz wie der Alzheimer-Krankheit.'),
('de', 'common', 'dementia.about_p2',        'Die Skala definiert 7 Stufen von keinem kognitiven Abbau bis hin zu sehr schwerem kognitiven Abbau. Die GDS ist am relevantesten für Personen mit Alzheimer und gilt möglicherweise nicht für andere Demenzformen.'),
('de', 'common', 'dementia.stages_13',       'Stufen 1–3'),
('de', 'common', 'dementia.stages_13_desc',  'Keine Demenz'),
('de', 'common', 'dementia.stage_4',         'Stufe 4'),
('de', 'common', 'dementia.stage_4_desc',    'Frühstadium der Demenz'),
('de', 'common', 'dementia.stages_56',       'Stufen 5–6'),
('de', 'common', 'dementia.stages_56_desc',  'Mittleres Demenzstadium'),
('de', 'common', 'dementia.stage_7',         'Stufe 7'),
('de', 'common', 'dementia.stage_7_desc',    'Spätstadium der Demenz'),
('de', 'common', 'dementia.seven_stages',    'Die Sieben Stufen'),
('de', 'common', 'dementia.disclaimer_label','Haftungsausschluss:'),
('de', 'common', 'dementia.disclaimer_body', 'Diese Skala ist ein klinisches Referenzwerkzeug, das nur zu Informationszwecken gedacht ist. Sie ersetzt nicht professionellen medizinischen Rat, Diagnose oder Behandlung. Bitte wenden Sie sich bei medizinischen Fragen an einen qualifizierten Gesundheitsdienstleister.'),

-- ─────────────── ITALIAN ───────────────
('it', 'common', 'dementia.page_title',      'Scala di Riferimento per la Demenza'),
('it', 'common', 'dementia.signs_symptoms',  'Segni e Sintomi'),
('it', 'common', 'dementia.expected_duration','Durata Prevista'),
('it', 'common', 'dementia.not_applicable',  'Non applicabile'),
('it', 'common', 'dementia.note_4',          'In questa fase la persona può essere consapevole delle proprie difficoltà ma cerca di nasconderle o minimizzarle. Un medico può rilevare problemi attraverso un colloquio clinico.'),
('it', 'common', 'dementia.note_5',          'La persona non può più sopravvivere senza un certo aiuto. Conserva la conoscenza di fatti personali importanti, ma può aver dimenticato il proprio indirizzo o numero di telefono.'),
('it', 'common', 'dementia.note_6',          'La persona è in gran parte inconsapevole degli eventi e delle esperienze recenti. Richiede un aiuto significativo in tutte le attività della vita quotidiana e può richiedere una supervisione a tempo pieno.'),
('it', 'common', 'dementia.note_7',          'Nel corso di questa fase tutte le capacità verbali vengono perse. Le abilità psicomotorie di base vengono meno e la persona è costretta a letto. L''assistenza focalizzata sul comfort è la priorità.'),
('it', 'common', 'dementia.about_title',     'Informazioni sulla Scala di Deterioramento Globale (GDS)'),
('it', 'common', 'dementia.about_p1',        'La Scala di Deterioramento Globale (GDS), sviluppata dal Dr. Barry Reisberg, fornisce ai caregiver una panoramica degli stadi della funzione cognitiva per coloro che soffrono di una demenza degenerativa primaria come la malattia di Alzheimer.'),
('it', 'common', 'dementia.about_p2',        'La scala definisce 7 stadi, dall''assenza di declino cognitivo al declino cognitivo molto grave. La GDS è più pertinente per le persone con Alzheimer e potrebbe non applicarsi ad altre forme di demenza.'),
('it', 'common', 'dementia.stages_13',       'Stadi 1–3'),
('it', 'common', 'dementia.stages_13_desc',  'Nessuna Demenza'),
('it', 'common', 'dementia.stage_4',         'Stadio 4'),
('it', 'common', 'dementia.stage_4_desc',    'Demenza in Fase Iniziale'),
('it', 'common', 'dementia.stages_56',       'Stadi 5–6'),
('it', 'common', 'dementia.stages_56_desc',  'Demenza in Fase Intermedia'),
('it', 'common', 'dementia.stage_7',         'Stadio 7'),
('it', 'common', 'dementia.stage_7_desc',    'Demenza in Fase Avanzata'),
('it', 'common', 'dementia.seven_stages',    'I Sette Stadi'),
('it', 'common', 'dementia.disclaimer_label','Avviso:'),
('it', 'common', 'dementia.disclaimer_body', 'Questa scala è uno strumento di riferimento clinico destinato esclusivamente a scopi informativi. Non sostituisce il consiglio medico professionale, la diagnosi o il trattamento. Si prega di consultare un operatore sanitario qualificato per qualsiasi preoccupazione medica.'),

-- ─────────────── SWEDISH ───────────────
('sv', 'common', 'dementia.page_title',      'Referensskala för Demens'),
('sv', 'common', 'dementia.signs_symptoms',  'Tecken och Symptom'),
('sv', 'common', 'dementia.expected_duration','Förväntad Varaktighet'),
('sv', 'common', 'dementia.not_applicable',  'Ej tillämpligt'),
('sv', 'common', 'dementia.note_4',          'I detta skede kan personen vara medveten om sina svårigheter men försöker dölja eller minimera dem. En läkare kan upptäcka problem vid en klinisk intervju.'),
('sv', 'common', 'dementia.note_5',          'Personen kan inte längre klara sig utan viss hjälp. De behåller kunskap om viktiga personliga fakta, men kan ha glömt sin adress eller sitt telefonnummer.'),
('sv', 'common', 'dementia.note_6',          'Personen är till stor del omedveten om nyliga händelser och upplevelser. De behöver betydande hjälp med alla vardagsaktiviteter och kan behöva tillsyn dygnet runt.'),
('sv', 'common', 'dementia.note_7',          'Alla verbala förmågor förloras under loppet av detta stadium. Grundläggande psykomotoriska färdigheter försvinner och personen är sängbunden. Komfortfokuserad vård är prioriteten.'),
('sv', 'common', 'dementia.about_title',     'Om den Globala Försämringsskalan (GDS)'),
('sv', 'common', 'dementia.about_p1',        'Den Globala Försämringsskalan (GDS), utvecklad av Dr. Barry Reisberg, ger vårdgivare en översikt över stadierna av kognitiv funktion för dem som lider av en primär degenerativ demens som Alzheimers sjukdom.'),
('sv', 'common', 'dementia.about_p2',        'Skalan definierar 7 stadier från ingen kognitiv försämring till mycket svår kognitiv försämring. GDS är mest relevant för personer med Alzheimers sjukdom och kanske inte gäller för andra former av demens.'),
('sv', 'common', 'dementia.stages_13',       'Stadier 1–3'),
('sv', 'common', 'dementia.stages_13_desc',  'Ingen Demens'),
('sv', 'common', 'dementia.stage_4',         'Stadium 4'),
('sv', 'common', 'dementia.stage_4_desc',    'Tidig Demens'),
('sv', 'common', 'dementia.stages_56',       'Stadier 5–6'),
('sv', 'common', 'dementia.stages_56_desc',  'Medelsvår Demens'),
('sv', 'common', 'dementia.stage_7',         'Stadium 7'),
('sv', 'common', 'dementia.stage_7_desc',    'Sen Demens'),
('sv', 'common', 'dementia.seven_stages',    'De Sju Stadierna'),
('sv', 'common', 'dementia.disclaimer_label','Ansvarsfriskrivning:'),
('sv', 'common', 'dementia.disclaimer_body', 'Denna skala är ett kliniskt referensverktyg avsett enbart för informationsändamål. Det ersätter inte professionell medicinsk rådgivning, diagnos eller behandling. Konsultera en kvalificerad vårdgivare för eventuella medicinska frågor.'),

-- ─────────────── FINNISH ───────────────
('fi', 'common', 'dementia.page_title',      'Dementian Viiteasteikko'),
('fi', 'common', 'dementia.signs_symptoms',  'Merkit ja Oireet'),
('fi', 'common', 'dementia.expected_duration','Odotettu Kesto'),
('fi', 'common', 'dementia.not_applicable',  'Ei sovellettavissa'),
('fi', 'common', 'dementia.note_4',          'Tässä vaiheessa henkilö saattaa olla tietoinen vaikeuksistaan, mutta yrittää peittää tai vähätellä niitä. Lääkäri voi havaita ongelmia kliinisessä haastattelussa.'),
('fi', 'common', 'dementia.note_5',          'Henkilö ei enää pysty selviytymään ilman tukea. Hän muistaa tärkeitä henkilökohtaisia tietoja, mutta saattaa olla unohtanut osoitteensa tai puhelinnumeronsa.'),
('fi', 'common', 'dementia.note_6',          'Henkilö on suurelta osin tietämätön viimeaikaisista tapahtumista ja kokemuksista. Hän tarvitsee merkittävää apua kaikissa päivittäisissä toiminnoissa ja saattaa tarvita ympärivuorokautista valvontaa.'),
('fi', 'common', 'dementia.note_7',          'Kaikki kielelliset kyvyt menetetään tämän vaiheen aikana. Peruspyrkomotoriset taidot häviävät ja henkilö on vuodepotilas. Mukavuuteen keskittyvä hoito on ensisijaista.'),
('fi', 'common', 'dementia.about_title',     'Tietoa Globaalista Heikentymisasteikosta (GDS)'),
('fi', 'common', 'dementia.about_p1',        'Globaali Heikentymisasteikko (GDS), jonka kehitti tri Barry Reisberg, antaa hoitajille yleiskatsauksen kognitiivisen toiminnan vaiheista henkilöillä, jotka kärsivät ensisijaisesta rappeutuvasta dementiasta, kuten Alzheimerin taudista.'),
('fi', 'common', 'dementia.about_p2',        'Asteikko määrittelee 7 vaihetta, jotka vaihtelevat ei kognitiivista heikkenemistä erittäin vakavaan kognitiiviseen heikkenemiseen. GDS on merkityksellisin Alzheimerin tautia sairastaville henkilöille, eikä se välttämättä koske muita dementian muotoja.'),
('fi', 'common', 'dementia.stages_13',       'Vaiheet 1–3'),
('fi', 'common', 'dementia.stages_13_desc',  'Ei Dementiaa'),
('fi', 'common', 'dementia.stage_4',         'Vaihe 4'),
('fi', 'common', 'dementia.stage_4_desc',    'Varhainen Dementia'),
('fi', 'common', 'dementia.stages_56',       'Vaiheet 5–6'),
('fi', 'common', 'dementia.stages_56_desc',  'Keskivaikea Dementia'),
('fi', 'common', 'dementia.stage_7',         'Vaihe 7'),
('fi', 'common', 'dementia.stage_7_desc',    'Myöhäinen Dementia'),
('fi', 'common', 'dementia.seven_stages',    'Seitsemän Vaihetta'),
('fi', 'common', 'dementia.disclaimer_label','Vastuuvapauslauseke:'),
('fi', 'common', 'dementia.disclaimer_body', 'Tämä asteikko on kliininen viitetyökalu, joka on tarkoitettu vain tiedotustarkoituksiin. Se ei korvaa ammattimaista lääketieteellistä neuvontaa, diagnoosia tai hoitoa. Ota yhteyttä pätevään terveydenhuollon tarjoajaan kaikissa lääketieteellisissä kysymyksissä.')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
