
INSERT INTO ui_translations (locale, namespace, key, value) VALUES
-- SPANISH (es) - community.* keys in common namespace
('es','common','community.title','Foro de la Comunidad'),
('es','common','community.subtitle','Conecta con otros cuidadores'),
('es','common','community.join','Unirse a la comunidad'),
('es','common','community.sign_in_to_post','Inicia sesión para publicar'),
('es','common','community.new_post','Nueva publicación'),
('es','common','community.post_placeholder','Comparte algo con la comunidad...'),
('es','common','community.reply_placeholder','Escribe una respuesta...'),
('es','common','community.reply','Responder'),
('es','common','community.replies','Respuestas'),
('es','common','community.like','Me gusta'),
('es','common','community.likes','Me gusta'),
('es','common','community.share','Compartir'),
('es','common','community.report','Reportar'),
('es','common','community.delete','Eliminar'),
('es','common','community.edit','Editar'),
('es','common','community.cancel','Cancelar'),
('es','common','community.save','Guardar'),
('es','common','community.post','Publicar'),
('es','common','community.posted_by','Publicado por'),
('es','common','community.anonymous','Anónimo'),
('es','common','community.load_more','Cargar más'),
('es','common','community.no_posts','Aún no hay publicaciones. ¡Sé el primero en compartir!'),
('es','common','community.room_all','Todos'),
('es','common','community.room_general','General'),
('es','common','community.room_tips','Consejos y trucos'),
('es','common','community.room_support','Apoyo emocional'),
('es','common','community.room_resources','Recursos'),
('es','common','community.report_sent','Reporte enviado. Gracias.'),
('es','common','community.post_deleted','Publicación eliminada.'),
('es','common','community.post_saved','Publicación guardada.'),
-- SPANISH - public.community namespace
('es','public.community','heading','Comunidad de CarerView'),
('es','public.community','subheading','Únete a miles de cuidadores que se apoyan mutuamente'),
('es','public.community','members_count','miembros activos'),
('es','public.community','posts_count','publicaciones esta semana'),
('es','public.community','cta_join','Unirse ahora'),
('es','public.community','cta_sign_in','Iniciar sesión'),
('es','public.community','stats_heading','Nuestra comunidad en cifras'),
-- SPANISH - footer
('es','common','footer.tagline','Apoyo a los cuidadores, en todo momento'),
('es','common','footer.privacy','Política de privacidad'),
('es','common','footer.terms','Términos de uso'),
('es','common','footer.contact','Contacto'),
('es','common','footer.copyright','Todos los derechos reservados'),
-- FRENCH (fr) - community.* keys in common namespace
('fr','common','community.title','Forum de la Communauté'),
('fr','common','community.subtitle','Connectez-vous avec d''autres aidants'),
('fr','common','community.join','Rejoindre la communauté'),
('fr','common','community.sign_in_to_post','Connectez-vous pour publier'),
('fr','common','community.new_post','Nouvelle publication'),
('fr','common','community.post_placeholder','Partagez quelque chose avec la communauté...'),
('fr','common','community.reply_placeholder','Rédigez une réponse...'),
('fr','common','community.reply','Répondre'),
('fr','common','community.replies','Réponses'),
('fr','common','community.like','J''aime'),
('fr','common','community.likes','J''aime'),
('fr','common','community.share','Partager'),
('fr','common','community.report','Signaler'),
('fr','common','community.delete','Supprimer'),
('fr','common','community.edit','Modifier'),
('fr','common','community.cancel','Annuler'),
('fr','common','community.save','Enregistrer'),
('fr','common','community.post','Publier'),
('fr','common','community.posted_by','Publié par'),
('fr','common','community.anonymous','Anonyme'),
('fr','common','community.load_more','Charger plus'),
('fr','common','community.no_posts','Pas encore de publications. Soyez le premier à partager!'),
('fr','common','community.room_all','Tous'),
('fr','common','community.room_general','Général'),
('fr','common','community.room_tips','Astuces et conseils'),
('fr','common','community.room_support','Soutien émotionnel'),
('fr','common','community.room_resources','Ressources'),
('fr','common','community.report_sent','Signalement envoyé. Merci.'),
('fr','common','community.post_deleted','Publication supprimée.'),
('fr','common','community.post_saved','Publication enregistrée.'),
-- FRENCH - public.community namespace
('fr','public.community','heading','Communauté CarerView'),
('fr','public.community','subheading','Rejoignez des milliers d''aidants qui se soutiennent mutuellement'),
('fr','public.community','members_count','membres actifs'),
('fr','public.community','posts_count','publications cette semaine'),
('fr','public.community','cta_join','Rejoindre maintenant'),
('fr','public.community','cta_sign_in','Se connecter'),
('fr','public.community','stats_heading','Notre communauté en chiffres'),
-- FRENCH - footer
('fr','common','footer.tagline','Soutenir les aidants, à tout moment'),
('fr','common','footer.privacy','Politique de confidentialité'),
('fr','common','footer.terms','Conditions d''utilisation'),
('fr','common','footer.contact','Contact'),
('fr','common','footer.copyright','Tous droits réservés'),
-- GERMAN (de) - community.* keys in common namespace
('de','common','community.title','Community-Forum'),
('de','common','community.subtitle','Verbinde dich mit anderen Pflegepersonen'),
('de','common','community.join','Der Community beitreten'),
('de','common','community.sign_in_to_post','Anmelden zum Posten'),
('de','common','community.new_post','Neuer Beitrag'),
('de','common','community.post_placeholder','Teile etwas mit der Community...'),
('de','common','community.reply_placeholder','Schreibe eine Antwort...'),
('de','common','community.reply','Antworten'),
('de','common','community.replies','Antworten'),
('de','common','community.like','Gefällt mir'),
('de','common','community.likes','Gefällt mir'),
('de','common','community.share','Teilen'),
('de','common','community.report','Melden'),
('de','common','community.delete','Löschen'),
('de','common','community.edit','Bearbeiten'),
('de','common','community.cancel','Abbrechen'),
('de','common','community.save','Speichern'),
('de','common','community.post','Posten'),
('de','common','community.posted_by','Gepostet von'),
('de','common','community.anonymous','Anonym'),
('de','common','community.load_more','Mehr laden'),
('de','common','community.no_posts','Noch keine Beiträge. Sei der Erste, der teilt!'),
('de','common','community.room_all','Alle'),
('de','common','community.room_general','Allgemein'),
('de','common','community.room_tips','Tipps und Tricks'),
('de','common','community.room_support','Emotionale Unterstützung'),
('de','common','community.room_resources','Ressourcen'),
('de','common','community.report_sent','Meldung gesendet. Danke.'),
('de','common','community.post_deleted','Beitrag gelöscht.'),
('de','common','community.post_saved','Beitrag gespeichert.'),
-- GERMAN - public.community namespace
('de','public.community','heading','CarerView Community'),
('de','public.community','subheading','Schließe dich Tausenden von Pflegepersonen an'),
('de','public.community','members_count','aktive Mitglieder'),
('de','public.community','posts_count','Beiträge diese Woche'),
('de','public.community','cta_join','Jetzt beitreten'),
('de','public.community','cta_sign_in','Anmelden'),
('de','public.community','stats_heading','Unsere Community in Zahlen'),
-- GERMAN - footer
('de','common','footer.tagline','Unterstützung für Pflegepersonen, jederzeit'),
('de','common','footer.privacy','Datenschutzrichtlinie'),
('de','common','footer.terms','Nutzungsbedingungen'),
('de','common','footer.contact','Kontakt'),
('de','common','footer.copyright','Alle Rechte vorbehalten'),
-- ITALIAN (it) - community.* keys in common namespace
('it','common','community.title','Forum della Comunità'),
('it','common','community.subtitle','Connettiti con altri assistenti'),
('it','common','community.join','Unisciti alla comunità'),
('it','common','community.sign_in_to_post','Accedi per pubblicare'),
('it','common','community.new_post','Nuova pubblicazione'),
('it','common','community.post_placeholder','Condividi qualcosa con la comunità...'),
('it','common','community.reply_placeholder','Scrivi una risposta...'),
('it','common','community.reply','Rispondi'),
('it','common','community.replies','Risposte'),
('it','common','community.like','Mi piace'),
('it','common','community.likes','Mi piace'),
('it','common','community.share','Condividi'),
('it','common','community.report','Segnala'),
('it','common','community.delete','Elimina'),
('it','common','community.edit','Modifica'),
('it','common','community.cancel','Annulla'),
('it','common','community.save','Salva'),
('it','common','community.post','Pubblica'),
('it','common','community.posted_by','Pubblicato da'),
('it','common','community.anonymous','Anonimo'),
('it','common','community.load_more','Carica altri'),
('it','common','community.no_posts','Ancora nessuna pubblicazione. Sii il primo a condividere!'),
('it','common','community.room_all','Tutti'),
('it','common','community.room_general','Generale'),
('it','common','community.room_tips','Suggerimenti e trucchi'),
('it','common','community.room_support','Supporto emotivo'),
('it','common','community.room_resources','Risorse'),
('it','common','community.report_sent','Segnalazione inviata. Grazie.'),
('it','common','community.post_deleted','Pubblicazione eliminata.'),
('it','common','community.post_saved','Pubblicazione salvata.'),
-- ITALIAN - public.community namespace
('it','public.community','heading','Comunità CarerView'),
('it','public.community','subheading','Unisciti a migliaia di assistenti che si supportano a vicenda'),
('it','public.community','members_count','membri attivi'),
('it','public.community','posts_count','pubblicazioni questa settimana'),
('it','public.community','cta_join','Unisciti ora'),
('it','public.community','cta_sign_in','Accedi'),
('it','public.community','stats_heading','La nostra comunità in numeri'),
-- ITALIAN - footer
('it','common','footer.tagline','Supporto per i caregivers, in ogni momento'),
('it','common','footer.privacy','Informativa sulla privacy'),
('it','common','footer.terms','Termini di utilizzo'),
('it','common','footer.contact','Contatti'),
('it','common','footer.copyright','Tutti i diritti riservati'),
-- SWEDISH (sv) - community.* keys in common namespace
('sv','common','community.title','Gemenskapsforum'),
('sv','common','community.subtitle','Knyt kontakt med andra vårdgivare'),
('sv','common','community.join','Gå med i gemenskapen'),
('sv','common','community.sign_in_to_post','Logga in för att posta'),
('sv','common','community.new_post','Nytt inlägg'),
('sv','common','community.post_placeholder','Dela något med gemenskapen...'),
('sv','common','community.reply_placeholder','Skriv ett svar...'),
('sv','common','community.reply','Svara'),
('sv','common','community.replies','Svar'),
('sv','common','community.like','Gilla'),
('sv','common','community.likes','Gillar'),
('sv','common','community.share','Dela'),
('sv','common','community.report','Rapportera'),
('sv','common','community.delete','Ta bort'),
('sv','common','community.edit','Redigera'),
('sv','common','community.cancel','Avbryt'),
('sv','common','community.save','Spara'),
('sv','common','community.post','Posta'),
('sv','common','community.posted_by','Postat av'),
('sv','common','community.anonymous','Anonym'),
('sv','common','community.load_more','Ladda mer'),
('sv','common','community.no_posts','Inga inlägg ännu. Var den första att dela!'),
('sv','common','community.room_all','Alla'),
('sv','common','community.room_general','Allmänt'),
('sv','common','community.room_tips','Tips och tricks'),
('sv','common','community.room_support','Emotionellt stöd'),
('sv','common','community.room_resources','Resurser'),
('sv','common','community.report_sent','Rapport skickad. Tack.'),
('sv','common','community.post_deleted','Inlägg raderat.'),
('sv','common','community.post_saved','Inlägg sparat.'),
-- SWEDISH - public.community namespace
('sv','public.community','heading','CarerView-gemenskapen'),
('sv','public.community','subheading','Gå med tusentals vårdgivare som stöttar varandra'),
('sv','public.community','members_count','aktiva medlemmar'),
('sv','public.community','posts_count','inlägg denna vecka'),
('sv','public.community','cta_join','Gå med nu'),
('sv','public.community','cta_sign_in','Logga in'),
('sv','public.community','stats_heading','Vår gemenskap i siffror'),
-- SWEDISH - footer
('sv','common','footer.tagline','Stöd för vårdgivare, när som helst'),
('sv','common','footer.privacy','Integritetspolicy'),
('sv','common','footer.terms','Användarvillkor'),
('sv','common','footer.contact','Kontakt'),
('sv','common','footer.copyright','Alla rättigheter förbehållna'),
-- FINNISH (fi) - community.* keys in common namespace
('fi','common','community.title','Yhteisöfoorumi'),
('fi','common','community.subtitle','Yhdistä muiden hoitajien kanssa'),
('fi','common','community.join','Liity yhteisöön'),
('fi','common','community.sign_in_to_post','Kirjaudu sisään julkaistaksesi'),
('fi','common','community.new_post','Uusi julkaisu'),
('fi','common','community.post_placeholder','Jaa jotain yhteisölle...'),
('fi','common','community.reply_placeholder','Kirjoita vastaus...'),
('fi','common','community.reply','Vastaa'),
('fi','common','community.replies','Vastaukset'),
('fi','common','community.like','Tykkää'),
('fi','common','community.likes','Tykkäykset'),
('fi','common','community.share','Jaa'),
('fi','common','community.report','Ilmianna'),
('fi','common','community.delete','Poista'),
('fi','common','community.edit','Muokkaa'),
('fi','common','community.cancel','Peruuta'),
('fi','common','community.save','Tallenna'),
('fi','common','community.post','Julkaise'),
('fi','common','community.posted_by','Julkaissut'),
('fi','common','community.anonymous','Anonyymi'),
('fi','common','community.load_more','Lataa lisää'),
('fi','common','community.no_posts','Ei vielä julkaisuja. Ole ensimmäinen jakamaan!'),
('fi','common','community.room_all','Kaikki'),
('fi','common','community.room_general','Yleinen'),
('fi','common','community.room_tips','Vinkit ja niksit'),
('fi','common','community.room_support','Henkinen tuki'),
('fi','common','community.room_resources','Resurssit'),
('fi','common','community.report_sent','Ilmianto lähetetty. Kiitos.'),
('fi','common','community.post_deleted','Julkaisu poistettu.'),
('fi','common','community.post_saved','Julkaisu tallennettu.'),
-- FINNISH - public.community namespace
('fi','public.community','heading','CarerView-yhteisö'),
('fi','public.community','subheading','Liity tuhansien toisiaan tukevien hoitajien joukkoon'),
('fi','public.community','members_count','aktiivista jäsentä'),
('fi','public.community','posts_count','julkaisua tällä viikolla'),
('fi','public.community','cta_join','Liity nyt'),
('fi','public.community','cta_sign_in','Kirjaudu sisään'),
('fi','public.community','stats_heading','Yhteisömme numeroina'),
-- FINNISH - footer
('fi','common','footer.tagline','Tukea hoitajille, milloin tahansa'),
('fi','common','footer.privacy','Tietosuojakäytäntö'),
('fi','common','footer.terms','Käyttöehdot'),
('fi','common','footer.contact','Yhteystiedot'),
('fi','common','footer.copyright','Kaikki oikeudet pidätetään'),
-- JAPANESE (ja) - community.* keys in common namespace
('ja','common','community.title','コミュニティフォーラム'),
('ja','common','community.subtitle','他のケアラーとつながる'),
('ja','common','community.join','コミュニティに参加する'),
('ja','common','community.sign_in_to_post','投稿するにはサインイン'),
('ja','common','community.new_post','新しい投稿'),
('ja','common','community.post_placeholder','コミュニティと何かを共有してください...'),
('ja','common','community.reply_placeholder','返信を書いてください...'),
('ja','common','community.reply','返信'),
('ja','common','community.replies','返信'),
('ja','common','community.like','いいね'),
('ja','common','community.likes','いいね'),
('ja','common','community.share','シェア'),
('ja','common','community.report','報告'),
('ja','common','community.delete','削除'),
('ja','common','community.edit','編集'),
('ja','common','community.cancel','キャンセル'),
('ja','common','community.save','保存'),
('ja','common','community.post','投稿'),
('ja','common','community.posted_by','投稿者'),
('ja','common','community.anonymous','匿名'),
('ja','common','community.load_more','もっと読み込む'),
('ja','common','community.no_posts','まだ投稿がありません。最初にシェアしてみましょう！'),
('ja','common','community.room_all','すべて'),
('ja','common','community.room_general','一般'),
('ja','common','community.room_tips','ヒントとコツ'),
('ja','common','community.room_support','心のサポート'),
('ja','common','community.room_resources','リソース'),
('ja','common','community.report_sent','報告を送信しました。ありがとうございます。'),
('ja','common','community.post_deleted','投稿を削除しました。'),
('ja','common','community.post_saved','投稿を保存しました。'),
-- JAPANESE - public.community namespace
('ja','public.community','heading','CarerViewコミュニティ'),
('ja','public.community','subheading','互いにサポートし合う何千人ものケアラーに参加しよう'),
('ja','public.community','members_count','アクティブなメンバー'),
('ja','public.community','posts_count','今週の投稿'),
('ja','public.community','cta_join','今すぐ参加'),
('ja','public.community','cta_sign_in','サインイン'),
('ja','public.community','stats_heading','コミュニティの数字'),
-- JAPANESE - footer
('ja','common','footer.tagline','ケアラーへのサポート、いつでも'),
('ja','common','footer.privacy','プライバシーポリシー'),
('ja','common','footer.terms','利用規約'),
('ja','common','footer.contact','お問い合わせ'),
('ja','common','footer.copyright','全著作権所有'),
-- footer namespace (single key) for all non-EN locales
('es','footer','copyright','© CarerView. Todos los derechos reservados.'),
('fr','footer','copyright','© CarerView. Tous droits réservés.'),
('de','footer','copyright','© CarerView. Alle Rechte vorbehalten.'),
('it','footer','copyright','© CarerView. Tutti i diritti riservati.'),
('sv','footer','copyright','© CarerView. Alla rättigheter förbehållna.'),
('fi','footer','copyright','© CarerView. Kaikki oikeudet pidätetään.'),
('ja','footer','copyright','© CarerView. 全著作権所有。')
ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
