
INSERT INTO ui_translations (locale, namespace, key, value) VALUES
  ('en', 'common', 'policy.priv_notice',
   'This Privacy Policy explains how CarerView (operated by GrifDigi Ltd) collects, uses, stores, and protects your personal data when you use our service. It is issued in compliance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018. GrifDigi Ltd acts as the data controller in respect of personal data you provide to us. If you have any questions about this policy, please contact us at CarerView@GrifDigi.com.'),

  ('en', 'common', 'policy.priv_s1_body',
   'We collect the following categories of personal data: (a) Account data — your name, email address, and password when you register; (b) Care observation data — structured observations, notes, scores, and assessments you enter about the person in your care; (c) Team and profile data — information you provide about caregivers and care recipients associated with your account; (d) Usage and technical data — IP address, browser type, device identifiers, and log data collected automatically to operate and improve the service. Our lawful bases for processing are: performance of a contract (providing you the service you signed up for); legitimate interests (maintaining service security and preventing fraud); and, where health-related care data is entered, your explicit consent as required under Article 9 UK GDPR.'),

  ('en', 'common', 'policy.priv_s2_body',
   'We use your personal data to: (a) create and manage your account and authenticate your identity; (b) deliver the CarerView service, including storing and displaying your care observations; (c) send transactional communications such as account confirmations, password resets, and subscription notifications; (d) process payments securely through our payment processor, Stripe; (e) monitor and improve service performance, diagnose technical issues, and develop new features; (f) comply with our legal obligations, including responding to lawful requests from regulators or law enforcement authorities. We do not use your personal data for automated decision-making or profiling that produces legal or similarly significant effects.'),

  ('en', 'common', 'policy.priv_s3_body',
   'Your data is stored on infrastructure provided by Supabase, Inc., hosted on Amazon Web Services (AWS) data centres located within the European Economic Area and the United Kingdom. All data is encrypted in transit using TLS 1.2 or higher and encrypted at rest using AES-256. Access to personal data is restricted to authorised personnel on a need-to-know basis and protected by multi-factor authentication. We maintain appropriate technical and organisational measures to protect against unauthorised access, accidental loss, destruction, or alteration. In the event of a personal data breach that is likely to result in a risk to your rights and freedoms, we will notify the Information Commissioner''s Office (ICO) within 72 hours of becoming aware of the breach and will communicate the breach to you without undue delay where required by law.'),

  ('en', 'common', 'policy.priv_s4_body',
   'Under UK GDPR, you have the following rights in relation to your personal data: (a) Right of access — you may request a copy of the personal data we hold about you; (b) Right to rectification — you may ask us to correct inaccurate or incomplete data; (c) Right to erasure — you may request deletion of your personal data where there is no legitimate reason for us to continue processing it; (d) Right to restriction — you may ask us to restrict processing of your data in certain circumstances; (e) Right to data portability — you may receive your personal data in a structured, commonly used, machine-readable format; (f) Right to object — you may object to processing based on our legitimate interests; (g) Rights related to automated decision-making — you have the right not to be subject to solely automated decisions that significantly affect you. To exercise any of these rights, please contact us at CarerView@GrifDigi.com. You also have the right to lodge a complaint with the Information Commissioner''s Office (ICO) at ico.org.uk if you believe we have not handled your data in accordance with applicable law.'),

  ('en', 'common', 'policy.priv_s5_title', 'Cookies'),

  ('en', 'common', 'policy.priv_s5_body',
   'CarerView does not use tracking, advertising, or analytics cookies. We do not place any third-party cookies on your device. Strictly necessary session cookies may be set by our authentication service solely to maintain your logged-in state during an active session; these are deleted when you close your browser or sign out. No personal data is transmitted to third parties through cookies, and no cookie consent banner is required as a result of this policy.'),

  ('en', 'common', 'policy.data_notice',
   'This Data Policy explains how CarerView handles the care data you enter into the application — including observations, assessments, and personal details about the person in your care. You retain ownership of this data at all times. CarerView acts as a data processor on your behalf, and we will never use your care data for any purpose other than operating the service you have subscribed to. This policy should be read alongside our Privacy Policy.'),

  ('en', 'common', 'policy.data_s1_body',
   'The care data you create in CarerView — including daily observations, activity scores, notes, responses to assessment questions, and any personal or medical information you choose to record about a care recipient — remains yours. You are the data controller for this content; CarerView processes it solely on your instructions. We do not read, analyse, or use the substance of your care records for any commercial purpose. Where care data relates to health or disability, it is treated as special category data under Article 9 UK GDPR and protected accordingly with additional technical safeguards and access controls.'),

  ('en', 'common', 'policy.data_s2_body',
   'CarerView will never sell, rent, or license your care data to any third party. We will not share your care data with any external organisation except: (a) with sub-processors (such as our hosting provider) strictly as necessary to deliver the service, under binding data processing agreements; (b) where you explicitly grant access to other team members you invite to your account; or (c) where we are legally compelled to do so by a court order or regulatory authority, in which case we will notify you to the extent permitted by law. We may use fully anonymised, aggregated statistical data — from which no individual or care recipient can be identified — for internal service improvement purposes only.'),

  ('en', 'common', 'policy.data_s3_body',
   'Your care data is retained for as long as your CarerView account remains active. If you delete your account, we will permanently and irreversibly delete all associated care data within 30 days of account closure, except where we are required to retain certain records for a longer period to comply with legal obligations (for example, financial records related to a subscription). You may request early deletion of specific data at any time by contacting CarerView@GrifDigi.com. Backups are purged on a rolling 30-day cycle, meaning residual copies may persist for up to 30 days after deletion is initiated.'),

  ('en', 'common', 'policy.data_s4_body',
   'You have the right to a complete, portable copy of all care data you have entered into CarerView. You can generate and download a full export of your data at any time from the account settings area. Exports are provided in a structured format (DOCX). There is no limit on how frequently you may export your data, and no fee is charged for doing so. Exported files are generated on demand and are not stored on our servers after download. If you require an export in a different format or experience difficulties with the self-service export, please contact CarerView@GrifDigi.com.'),

  ('en', 'common', 'policy.data_s5_body',
   'CarerView is a care observation and record-keeping tool. It is not a registered medical device, clinical decision-support system, or diagnostic instrument under the Medical Devices Regulation (EU) 2017/745, UK MDR 2002, or any equivalent legislation. The information recorded in CarerView reflects observations made by caregivers and should not be interpreted as clinical assessments or medical diagnoses. Nothing within CarerView constitutes medical advice. Assessment scales and scoring tools within the application are provided as informational aids only and must not be used as the sole basis for clinical or care decisions. Always consult a qualified healthcare professional for medical guidance relating to the person in your care.')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
