/*
  # Memory Book public page content refresh

  Updates the Memory Book marketing page with Care Book content and additional FAQs.
*/

INSERT INTO ui_translations (key, locale, value) VALUES

('mb_page.eyebrow',        'en', 'Memory Book & Care Book'),
('mb_page.hero_title',     'en', 'Everything your care team needs — in one place'),
('mb_page.hero_body',      'en', 'When a new caregiver walks in, they should not have to guess. The Memory Book captures who your loved one is, what they need, and what brings them comfort. The Care Book keeps every household detail — insurance, finances, providers, and more — organised and accessible. Together, they cover every dimension of confident caregiving.'),
('mb_page.mock_tab_daily',     'en', 'Daily Living'),
('mb_page.mock_tab_household', 'en', 'Household'),
('mb_page.benefits_title',    'en', 'Why families rely on Memory Book & Care Book'),
('mb_page.benefits_subtitle', 'en', 'Two tools, one care team. Everything documented once — available to everyone the moment they join.'),
('mb_page.benefit1_title',    'en', 'Instant care context'),
('mb_page.benefit1_body',     'en', 'Any new caregiver — a respite worker, a sibling visiting from abroad — walks in with everything they need to provide good care from the first moment.'),
('mb_page.benefit2_title',    'en', 'No more searching'),
('mb_page.benefit2_body',     'en', 'Every contact, provider, insurance policy, and utility account in one place. Find the right number in seconds, not minutes.'),
('mb_page.benefit3_title',    'en', 'Safer handovers'),
('mb_page.benefit3_body',     'en', 'Medical notes, allergies, daily living independence levels, and care considerations are always on hand. Informed transitions mean fewer gaps and fewer risks.'),
('mb_page.benefit4_title',    'en', 'Personal dignity'),
('mb_page.benefit4_body',     'en', 'Beyond clinical facts, the Memory Book captures the person — their story, their preferences, what brings them joy. Care becomes more than task completion.'),
('mb_page.benefit5_title',    'en', 'Household continuity'),
('mb_page.benefit5_body',     'en', 'The Care Book means a caregiver stepping in during a crisis can find the insurance card, call the right plumber, and manage bills — without burdening the family.'),
('mb_page.features_title',    'en', 'Two tools. A complete picture.'),
('mb_page.features_subtitle', 'en', 'The Memory Book covers who your loved one is and how to care for them. The Care Book covers everything that keeps their household running.'),
('mb_page.pillar_mb_label',    'en', 'Memory Book'),
('mb_page.pillar_mb_heading',  'en', 'The personal care profile'),
('mb_page.pillar_mb_body',     'en', 'A living record of who your loved one is — their identity, their care network, their medical context, how they manage daily tasks, and what brings them comfort.'),
('mb_page.feat_identity_title', 'en', 'Identity & Personal Profile'),
('mb_page.feat_identity_body',  'en', 'Capture who your loved one is — not just their name, but their story. This section helps every caregiver connect with the person behind the care plan.'),
('mb_page.feat_identity_f1',    'en', 'Preferred name and how they like to be addressed'),
('mb_page.feat_identity_f2',    'en', 'Birthplace, cultural background, and languages spoken'),
('mb_page.feat_identity_f3',    'en', 'Relationship status'),
('mb_page.feat_identity_f4',    'en', 'Language and communication preferences'),
('mb_page.feat_identity_f5',    'en', 'Personal summary — in their own words'),
('mb_page.feat_contacts_title', 'en', 'Care Network & Contacts'),
('mb_page.feat_contacts_body',  'en', 'Store every person in your loved one''s support network — family, doctors, specialists, and emergency contacts — each tagged by role.'),
('mb_page.feat_contacts_f1',    'en', 'Family members with relationship labels'),
('mb_page.feat_contacts_f2',    'en', 'GPs, specialists, and healthcare providers'),
('mb_page.feat_contacts_f3',    'en', 'Neighbours, friends, and community support'),
('mb_page.feat_contacts_f4',    'en', 'Role tags: primary carer, emergency, backup, medical, and more'),
('mb_page.feat_medical_title', 'en', 'Medical Context'),
('mb_page.feat_medical_body',  'en', 'Not a clinical record — a practical caregiver reference. Document what in-home and family carers actually need to know to provide safe, confident care.'),
('mb_page.feat_medical_f1',    'en', 'Primary conditions and diagnoses'),
('mb_page.feat_medical_f2',    'en', 'Allergies — food, medication, and environmental'),
('mb_page.feat_medical_f3',    'en', 'Current medications with dosage and administration notes'),
('mb_page.feat_medical_f4',    'en', 'Hearing and vision notes'),
('mb_page.feat_medical_f5',    'en', 'Healthcare providers: GPs, specialists, and clinic contacts'),
('mb_page.feat_daily_title', 'en', 'Daily Living — ADL & IADL'),
('mb_page.feat_daily_body',  'en', 'Track independence levels across activities of daily living and household tasks. Every caregiver knows exactly how much support is needed — and where.'),
('mb_page.feat_daily_f1',    'en', 'Bathing, dressing, grooming, mobility, and transfers'),
('mb_page.feat_daily_f2',    'en', 'Eating, continence, and toileting support needs'),
('mb_page.feat_daily_f3',    'en', 'Meal preparation, medication management, and housekeeping'),
('mb_page.feat_daily_f4',    'en', 'Shopping, finances, transportation, and communication'),
('mb_page.feat_daily_f5',    'en', 'Five independence levels: from fully independent to fully dependent'),
('mb_page.feat_prefs_title', 'en', 'Likes, Dislikes & Comforts'),
('mb_page.feat_prefs_body',  'en', 'The details that transform care from functional to personal. Knowing what soothes, what to avoid, and what sparks a genuine smile makes every interaction better.'),
('mb_page.feat_prefs_f1',    'en', 'Activities, topics, and experiences they enjoy'),
('mb_page.feat_prefs_f2',    'en', 'Food preferences and things to avoid'),
('mb_page.feat_prefs_f3',    'en', 'Music preferences and favourite conversation topics'),
('mb_page.feat_prefs_f4',    'en', 'What comforts them when upset'),
('mb_page.feat_prefs_f5',    'en', 'Sensory preferences and distress triggers'),
('mb_page.pillar_cb_label',   'en', 'Care Book'),
('mb_page.pillar_cb_heading', 'en', 'The household & logistics record'),
('mb_page.pillar_cb_body',    'en', 'A structured record of every practical detail that keeps your loved one''s household running — insurance policies, finances, vehicles, subscriptions, home service providers, and online accounts.'),
('mb_page.feat_insurance_title', 'en', 'Insurance Policies'),
('mb_page.feat_insurance_body',  'en', 'Store every policy in one place so caregivers and family members can find the right coverage information instantly — especially when it matters most.'),
('mb_page.feat_insurance_f1',    'en', 'Health, dental, and vision insurance'),
('mb_page.feat_insurance_f2',    'en', 'Medicare Parts A, B, and D'),
('mb_page.feat_insurance_f3',    'en', 'Long-term care and life insurance'),
('mb_page.feat_insurance_f4',    'en', 'Home, auto, and supplemental policies'),
('mb_page.feat_insurance_f5',    'en', 'Policy numbers, member IDs, and coverage notes'),
('mb_page.feat_finances_title', 'en', 'Finances & Income'),
('mb_page.feat_finances_body',  'en', 'An owner-only record of banking, income sources, auto-pay bills, and investments — so nothing falls through the cracks during a care transition.'),
('mb_page.feat_finances_f1',    'en', 'Checking, savings, and banking accounts'),
('mb_page.feat_finances_f2',    'en', 'Income: Social Security, pensions, VA benefits, and more'),
('mb_page.feat_finances_f3',    'en', 'Auto-pay bills: mortgage, utilities, insurance, subscriptions'),
('mb_page.feat_finances_f4',    'en', 'Investments: brokerage, retirement accounts, and real estate'),
('mb_page.feat_providers_title', 'en', 'Home Service Providers'),
('mb_page.feat_providers_body',  'en', 'Keep every utility and maintenance provider on file — account numbers, phone numbers, and websites — so the right call gets made without a search.'),
('mb_page.feat_providers_f1',    'en', 'Electricity, water, gas, and waste removal'),
('mb_page.feat_providers_f2',    'en', 'Internet, home phone, and mobile'),
('mb_page.feat_providers_f3',    'en', 'Plumber, electrician, HVAC, and lawn care'),
('mb_page.feat_providers_f4',    'en', 'Pest control, handyman, and other maintenance contacts'),
('mb_page.feat_vehicles_title', 'en', 'Vehicles & Vehicle Care'),
('mb_page.feat_vehicles_body',  'en', 'Track vehicles and the service providers who maintain them — with automatic alerts when registration is due.'),
('mb_page.feat_vehicles_f1',    'en', 'Make, model, year, and licence plate'),
('mb_page.feat_vehicles_f2',    'en', 'Registration due date with auto-alerts at 60 days'),
('mb_page.feat_vehicles_f3',    'en', 'Parking location and service provider'),
('mb_page.feat_vehicles_f4',    'en', 'Oil change, tires, brakes, inspection, and dealer contacts'),
('mb_page.feat_subs_title', 'en', 'Subscriptions & Online Accounts'),
('mb_page.feat_subs_body',  'en', 'A clear record of streaming services, software licences, and online accounts — so nothing is forgotten and nothing auto-renews unexpectedly.'),
('mb_page.feat_subs_f1',    'en', 'Streaming, music, and news subscriptions'),
('mb_page.feat_subs_f2',    'en', 'Health & wellness, delivery, and utility services'),
('mb_page.feat_subs_f3',    'en', 'Social media, email, and cloud storage accounts'),
('mb_page.feat_subs_f4',    'en', '20+ platform suggestions for quick entry'),
('mb_page.access_title', 'en', 'Built for the team. Visible to everyone.'),
('mb_page.access_body',  'en', 'The team owner builds and maintains both the Memory Book and the Care Book. Every caregiver you invite — family members, in-home workers, or support people — can view them the moment they join, with no setup required. The Finances section remains owner-only for privacy.'),
('mb_page.access_cta',   'en', 'Start Your Free Account'),
('mb_page.access_plans', 'en', 'View Plans & Pricing'),
('mb_page.personas_title',    'en', 'Who benefits'),
('mb_page.personas_subtitle', 'en', 'From the overnight carer arriving for the first time to a sibling managing a crisis from overseas.'),
('mb_page.persona1_title',    'en', 'The overnight respite carer'),
('mb_page.persona1_quote',    'en', '"I used to dread covering for a family I didn''t know. Now I check the Memory Book before I arrive."'),
('mb_page.persona1_b1',       'en', 'Knows preferred routines, bedtime comforts, and communication style before walking in'),
('mb_page.persona1_b2',       'en', 'Can find emergency contacts without waking anyone up'),
('mb_page.persona1_b3',       'en', 'Understands medication needs and daily living support levels from the first night'),
('mb_page.persona2_title',    'en', 'The sibling managing from overseas'),
('mb_page.persona2_quote',    'en', '"I visit twice a year and felt like a stranger. The Memory Book and Care Book close that gap."'),
('mb_page.persona2_b1',       'en', 'Catches up on medical and daily living context without a long family debrief'),
('mb_page.persona2_b2',       'en', 'Finds insurance, utilities, and provider contacts to handle logistics remotely'),
('mb_page.persona2_b3',       'en', 'Knows what Mum enjoys now — and what to avoid — before every visit'),
('mb_page.persona3_title',    'en', 'The primary caregiver'),
('mb_page.persona3_quote',    'en', '"I am the memory bank. These tools mean I don''t have to explain everything every time."'),
('mb_page.persona3_b1',       'en', 'Documents everything once — not a dozen times across texts and phone calls'),
('mb_page.persona3_b2',       'en', 'Shares the care burden without losing control of accuracy'),
('mb_page.persona3_b3',       'en', 'Reduces the emotional load of constant communication and repeated handovers'),
('mb_page.persona4_title',    'en', 'The family member handling a care transition'),
('mb_page.persona4_quote',    'en', '"Dad had a fall. I had to make a dozen decisions in hours. The Care Book meant I had the answers."'),
('mb_page.persona4_b1',       'en', 'Insurance details and healthcare providers available immediately'),
('mb_page.persona4_b2',       'en', 'Utility and maintenance contacts on hand for managing the household remotely'),
('mb_page.persona4_b3',       'en', 'Medical context and emergency contacts accessible to every family member in the room'),
('mb_page.faq_title',    'en', 'Frequently Asked Questions'),
('mb_page.faq_subtitle', 'en', 'Common questions about the Memory Book and Care Book features.'),
('mb_page.faq1_q', 'en', 'What is the Memory Book and who can see it?'),
('mb_page.faq1_a', 'en', 'The Memory Book is a structured care profile for your loved one covering identity, contacts, medical context, daily living independence levels, and personal preferences. The team owner builds and updates it. Every caregiver you invite can view it instantly — no separate setup required.'),
('mb_page.faq2_q', 'en', 'What is the Care Book?'),
('mb_page.faq2_a', 'en', 'The Care Book is the household and logistics companion to the Memory Book. It stores insurance policies, financial accounts, auto-pay bills, subscriptions, home service providers, vehicles, vehicle care contacts, and online accounts — all in one organised place. It is included in the same plan as the Memory Book.'),
('mb_page.faq3_q', 'en', 'Which plan includes the Memory Book and Care Book?'),
('mb_page.faq3_a', 'en', 'Both tools are available on the Primary Caregiver and Family Circle plans. The Family Circle plan is designed for teams — up to 3 caregivers sharing a single Memory Book and Care Book, with all team members able to view both the moment they join.'),
('mb_page.faq4_q', 'en', 'Can team members edit the Memory Book or Care Book?'),
('mb_page.faq4_a', 'en', 'Currently, only the team owner can create and edit entries. All other team members have read-only access to the Memory Book and Care Book (except the Finances section, which is owner-only). This keeps the records accurate with one person responsible for updates.'),
('mb_page.faq5_q', 'en', 'Is the Memory Book a medical record?'),
('mb_page.faq5_a', 'en', 'No. The Memory Book is a practical caregiving reference — not a clinical document. It captures information that helps caregivers provide safe, informed, and personal care. For formal medical records, please refer to your loved one''s healthcare providers.'),
('mb_page.faq6_q', 'en', 'Who can see the Finances section?'),
('mb_page.faq6_a', 'en', 'The Finances section is visible only to the team owner. Team members who join your care team can see all other sections of the Care Book, but the Finances section is kept private to protect sensitive financial information.'),
('mb_page.faq7_q', 'en', 'Is my loved one''s information private and secure?'),
('mb_page.faq7_a', 'en', 'Yes. All information is only visible to members of your care team — people you have explicitly invited. It is stored securely on encrypted infrastructure. CarerView never shares your data with third parties and you retain full ownership of everything you enter.'),
('mb_page.faq8_q', 'en', 'Can I print the Memory Book?'),
('mb_page.faq8_a', 'en', 'Yes. The team owner can print a formatted version of the Memory Book from the Overview tab. This is useful for appointments, hospital visits, or providing a physical copy to a new in-home carer.'),
('mb_page.cta_title', 'en', 'Start building your loved one''s Memory Book and Care Book today'),
('mb_page.cta_body',  'en', 'Create a free account and explore CarerView — or choose a paid plan to unlock both the Memory Book and Care Book and share them with your care team.')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();