-- Translation Batch 2: caregiver.* and dashboard.* keys for all 7 non-EN locales

INSERT INTO public.ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- SPANISH (es) — caregiver + dashboard
-- ============================================================
('es','common','caregiver.dashboard_title','Panel de control'),
('es','common','caregiver.delete_failed','Error al eliminar la observación'),
('es','common','caregiver.dementia_desc','Escala de Deterioro Global (GDS) — 7 etapas de deterioro cognitivo'),
('es','common','caregiver.dementia_ref_body','Ver guía detallada sobre etapas de demencia y necesidades de cuidado'),
('es','common','caregiver.dementia_ref_title','Escala de Referencia de Demencia'),
('es','common','caregiver.dementia_scale','Referencia de Escala de Demencia'),
('es','common','caregiver.export_failed','Error al exportar la observación.'),
('es','common','caregiver.free_obs_remaining_one','1 observación gratuita restante (últimos 12 meses)'),
('es','common','caregiver.free_obs_remaining_other','{{count}} observaciones gratuitas restantes (últimos 12 meses)'),
('es','common','caregiver.legend_load_failed','Error al cargar la leyenda de puntuación'),
('es','common','caregiver.loading','Cargando panel de cuidador...'),
('es','common','caregiver.locked_panel_cta','Desbloquear con un plan de pago'),
('es','common','caregiver.new_obs_btn','Nueva Observación'),
('es','common','caregiver.new_observation','Nueva Observación'),
('es','common','caregiver.no_obs_selected','Ninguna observación seleccionada'),
('es','common','caregiver.obs_delete_failed','Error al eliminar la observación. Por favor intenta de nuevo.'),
('es','common','caregiver.obs_deleted','Observación eliminada correctamente'),
('es','common','caregiver.obs_empty','No hay observaciones registradas todavía.'),
('es','common','caregiver.obs_empty_cta','Registra tu primera observación →'),
('es','common','caregiver.obs_load_failed','Error al cargar la observación'),
('es','common','caregiver.obs_not_found','Observación no encontrada'),
('es','common','caregiver.obs_view_all','Ver todas las {count} observaciones →'),
('es','common','caregiver.observations_body','Un registro de tus evaluaciones de cuidado a lo largo del tiempo'),
('es','common','caregiver.observations_title','Tus Observaciones'),
('es','common','caregiver.payment_success','¡Pago exitoso! Tu suscripción ya está activa.'),
('es','common','caregiver.subscriber_tools_heading','Herramientas de suscriptor'),
('es','common','caregiver.subtitle_care_plan','A continuación se muestra el progreso de tu plan de cuidado.'),
('es','common','caregiver.subtitle_default','Aquí tienes un resumen de tus actividades de cuidado actuales.'),
('es','common','caregiver.subtitle_memory_book','A continuación se muestra el progreso de tu plan de cuidado, libro de memoria y observaciones.'),
('es','common','caregiver.subtitle_observations','A continuación se muestran tus observaciones recientes.'),
('es','common','caregiver.upsell_cp_desc','Coordina al equipo — roles, autoridad, sostenibilidad'),
('es','common','caregiver.upsell_mb_desc','Conoce a la persona — identidad, salud, preferencias, contactos'),
('es','common','caregiver.upsell_upgrade_cta','Actualizar para acceder'),
('es','common','caregiver.view_arrow','Ver →'),
('es','common','caregiver.your_obs_body','Registra y gestiona tus observaciones de cuidador'),
('es','common','caregiver.your_obs_title','Tus Observaciones'),
('es','common','dashboard.mb_section_contacts','Contactos'),
('es','common','dashboard.mb_section_daily_living','Vida Cotidiana y Preferencias'),
('es','common','dashboard.mb_section_identity','Identidad'),
('es','common','dashboard.mb_section_medical','Médico'),
('es','common','dashboard.mb_sections_have_content','de {total} secciones tienen contenido'),
('es','common','dashboard.mb_subtitle','Conocer a la persona'),
('es','common','dashboard.mb_title','Libro de Memoria'),
('es','common','dashboard.medical_allergies','Alergias'),
('es','common','dashboard.medical_conditions','Condiciones'),
('es','common','dashboard.medical_hearing','Audición'),
('es','common','dashboard.medical_medications','Medicamentos'),
('es','common','dashboard.medical_subtitle','Del Libro de Memoria'),
('es','common','dashboard.medical_title','Resumen Médico'),
('es','common','dashboard.medical_view_link','Ver Libro de Memoria'),
('es','common','dashboard.medical_vision','Visión'),
('es','common','dashboard.resident_age','Edad {age}'),
('es','common','dashboard.resident_complete_cta','Completar el perfil del residente →'),
('es','common','dashboard.resident_known_as','Conocido como \"{name}\"'),
('es','common','dashboard.resident_profile_pct','Perfil {pct}% completo'),
('es','common','dashboard.resident_subtitle','Persona en el centro del cuidado'),
('es','common','dashboard.resident_title','Residente'),

-- ============================================================
-- FRENCH (fr) — caregiver + dashboard
-- ============================================================
('fr','common','caregiver.dashboard_title','Tableau de bord'),
('fr','common','caregiver.delete_failed','Échec de la suppression de l''observation'),
('fr','common','caregiver.dementia_desc','Échelle de Détérioration Globale (GDS) — 7 stades de déclin cognitif'),
('fr','common','caregiver.dementia_ref_body','Voir les conseils détaillés sur les stades de démence et les besoins de soins'),
('fr','common','caregiver.dementia_ref_title','Échelle de référence de la démence'),
('fr','common','caregiver.dementia_scale','Référence de l''échelle de démence'),
('fr','common','caregiver.export_failed','Échec de l''exportation de l''observation.'),
('fr','common','caregiver.free_obs_remaining_one','1 observation gratuite restante (12 derniers mois)'),
('fr','common','caregiver.free_obs_remaining_other','{{count}} observations gratuites restantes (12 derniers mois)'),
('fr','common','caregiver.legend_load_failed','Échec du chargement de la légende des scores'),
('fr','common','caregiver.loading','Chargement du tableau de bord du soignant...'),
('fr','common','caregiver.locked_panel_cta','Débloquer avec un forfait payant'),
('fr','common','caregiver.new_obs_btn','Nouvelle observation'),
('fr','common','caregiver.new_observation','Nouvelle observation'),
('fr','common','caregiver.no_obs_selected','Aucune observation sélectionnée'),
('fr','common','caregiver.obs_delete_failed','Échec de la suppression de l''observation. Veuillez réessayer.'),
('fr','common','caregiver.obs_deleted','Observation supprimée avec succès'),
('fr','common','caregiver.obs_empty','Aucune observation enregistrée pour l''instant.'),
('fr','common','caregiver.obs_empty_cta','Enregistrer votre première observation →'),
('fr','common','caregiver.obs_load_failed','Échec du chargement de l''observation'),
('fr','common','caregiver.obs_not_found','Observation introuvable'),
('fr','common','caregiver.obs_view_all','Voir toutes les {count} observations →'),
('fr','common','caregiver.observations_body','Un historique de vos évaluations de soins au fil du temps'),
('fr','common','caregiver.observations_title','Vos observations'),
('fr','common','caregiver.payment_success','Paiement réussi ! Votre abonnement est maintenant actif.'),
('fr','common','caregiver.subscriber_tools_heading','Outils abonné'),
('fr','common','caregiver.subtitle_care_plan','La progression de votre plan de soins est affichée ci-dessous.'),
('fr','common','caregiver.subtitle_default','Voici un résumé de vos activités de soins actuelles.'),
('fr','common','caregiver.subtitle_memory_book','La progression de votre plan de soins, livre de mémoire et observations est affichée ci-dessous.'),
('fr','common','caregiver.subtitle_observations','Vos observations récentes sont affichées ci-dessous.'),
('fr','common','caregiver.upsell_cp_desc','Coordonner l''équipe — rôles, autorité, durabilité'),
('fr','common','caregiver.upsell_mb_desc','Connaître la personne — identité, santé, préférences, contacts'),
('fr','common','caregiver.upsell_upgrade_cta','Passer à la version supérieure pour accéder'),
('fr','common','caregiver.view_arrow','Voir →'),
('fr','common','caregiver.your_obs_body','Suivre et gérer vos observations de soignant'),
('fr','common','caregiver.your_obs_title','Vos observations'),
('fr','common','dashboard.mb_section_contacts','Contacts'),
('fr','common','dashboard.mb_section_daily_living','Vie quotidienne et préférences'),
('fr','common','dashboard.mb_section_identity','Identité'),
('fr','common','dashboard.mb_section_medical','Médical'),
('fr','common','dashboard.mb_sections_have_content','de {total} sections ont du contenu'),
('fr','common','dashboard.mb_subtitle','Connaître la personne'),
('fr','common','dashboard.mb_title','Livre de mémoire'),
('fr','common','dashboard.medical_allergies','Allergies'),
('fr','common','dashboard.medical_conditions','Conditions'),
('fr','common','dashboard.medical_hearing','Audition'),
('fr','common','dashboard.medical_medications','Médicaments'),
('fr','common','dashboard.medical_subtitle','Du livre de mémoire'),
('fr','common','dashboard.medical_title','Résumé médical'),
('fr','common','dashboard.medical_view_link','Voir le livre de mémoire'),
('fr','common','dashboard.medical_vision','Vision'),
('fr','common','dashboard.resident_age','Âge {age}'),
('fr','common','dashboard.resident_complete_cta','Compléter le profil du résident →'),
('fr','common','dashboard.resident_known_as','Connu sous le nom de \"{name}\"'),
('fr','common','dashboard.resident_profile_pct','Profil complété à {pct}%'),
('fr','common','dashboard.resident_subtitle','La personne au cœur des soins'),
('fr','common','dashboard.resident_title','Résident'),

-- ============================================================
-- GERMAN (de) — caregiver + dashboard
-- ============================================================
('de','common','caregiver.dashboard_title','Dashboard'),
('de','common','caregiver.delete_failed','Beobachtung konnte nicht gelöscht werden'),
('de','common','caregiver.dementia_desc','Globale Verschlechterungsskala (GDS) — 7 Stufen des kognitiven Abbaus'),
('de','common','caregiver.dementia_ref_body','Detaillierte Anleitung zu Demenzstadien und Pflegebedarf anzeigen'),
('de','common','caregiver.dementia_ref_title','Demenz-Referenzskala'),
('de','common','caregiver.dementia_scale','Demenz-Skalenreferenz'),
('de','common','caregiver.export_failed','Beobachtung konnte nicht exportiert werden.'),
('de','common','caregiver.free_obs_remaining_one','1 kostenlose Beobachtung verbleibend (letzte 12 Monate)'),
('de','common','caregiver.free_obs_remaining_other','{{count}} kostenlose Beobachtungen verbleibend (letzte 12 Monate)'),
('de','common','caregiver.legend_load_failed','Punkte-Legende konnte nicht geladen werden'),
('de','common','caregiver.loading','Pflege-Dashboard wird geladen...'),
('de','common','caregiver.locked_panel_cta','Mit einem kostenpflichtigen Plan freischalten'),
('de','common','caregiver.new_obs_btn','Neue Beobachtung'),
('de','common','caregiver.new_observation','Neue Beobachtung'),
('de','common','caregiver.no_obs_selected','Keine Beobachtung ausgewählt'),
('de','common','caregiver.obs_delete_failed','Beobachtung konnte nicht gelöscht werden. Bitte versuche es erneut.'),
('de','common','caregiver.obs_deleted','Beobachtung erfolgreich gelöscht'),
('de','common','caregiver.obs_empty','Noch keine Beobachtungen aufgezeichnet.'),
('de','common','caregiver.obs_empty_cta','Erste Beobachtung aufzeichnen →'),
('de','common','caregiver.obs_load_failed','Beobachtung konnte nicht geladen werden'),
('de','common','caregiver.obs_not_found','Beobachtung nicht gefunden'),
('de','common','caregiver.obs_view_all','Alle {count} Beobachtungen anzeigen →'),
('de','common','caregiver.observations_body','Eine Aufzeichnung deiner Pflegebewertungen im Laufe der Zeit'),
('de','common','caregiver.observations_title','Deine Beobachtungen'),
('de','common','caregiver.payment_success','Zahlung erfolgreich! Dein Abonnement ist jetzt aktiv.'),
('de','common','caregiver.subscriber_tools_heading','Abonnenten-Tools'),
('de','common','caregiver.subtitle_care_plan','Unten wird der Fortschritt deines Pflegeplans angezeigt.'),
('de','common','caregiver.subtitle_default','Hier ist eine Zusammenfassung deiner aktuellen Pflegeaktivitäten.'),
('de','common','caregiver.subtitle_memory_book','Unten wird der Fortschritt deines Pflegeplans, Erinnerungsbuchs und deiner Beobachtungen angezeigt.'),
('de','common','caregiver.subtitle_observations','Unten werden deine neuesten Beobachtungen angezeigt.'),
('de','common','caregiver.upsell_cp_desc','Team koordinieren — Rollen, Befugnisse, Nachhaltigkeit'),
('de','common','caregiver.upsell_mb_desc','Die Person kennenlernen — Identität, Gesundheit, Vorlieben, Kontakte'),
('de','common','caregiver.upsell_upgrade_cta','Upgrade für den Zugang'),
('de','common','caregiver.view_arrow','Anzeigen →'),
('de','common','caregiver.your_obs_body','Pflege-Beobachtungen verwalten und nachverfolgen'),
('de','common','caregiver.your_obs_title','Deine Beobachtungen'),
('de','common','dashboard.mb_section_contacts','Kontakte'),
('de','common','dashboard.mb_section_daily_living','Alltag & Vorlieben'),
('de','common','dashboard.mb_section_identity','Identität'),
('de','common','dashboard.mb_section_medical','Medizinisch'),
('de','common','dashboard.mb_sections_have_content','von {total} Abschnitten haben Inhalt'),
('de','common','dashboard.mb_subtitle','Die Person kennen'),
('de','common','dashboard.mb_title','Erinnerungsbuch'),
('de','common','dashboard.medical_allergies','Allergien'),
('de','common','dashboard.medical_conditions','Erkrankungen'),
('de','common','dashboard.medical_hearing','Gehör'),
('de','common','dashboard.medical_medications','Medikamente'),
('de','common','dashboard.medical_subtitle','Aus dem Erinnerungsbuch'),
('de','common','dashboard.medical_title','Medizinische Zusammenfassung'),
('de','common','dashboard.medical_view_link','Erinnerungsbuch anzeigen'),
('de','common','dashboard.medical_vision','Sehvermögen'),
('de','common','dashboard.resident_age','Alter {age}'),
('de','common','dashboard.resident_complete_cta','Bewohnerprofil vervollständigen →'),
('de','common','dashboard.resident_known_as','Bekannt als \"{name}\"'),
('de','common','dashboard.resident_profile_pct','Profil zu {pct}% vollständig'),
('de','common','dashboard.resident_subtitle','Person im Mittelpunkt der Pflege'),
('de','common','dashboard.resident_title','Bewohner'),

-- ============================================================
-- ITALIAN (it) — caregiver + dashboard
-- ============================================================
('it','common','caregiver.dashboard_title','Dashboard'),
('it','common','caregiver.delete_failed','Impossibile eliminare l''osservazione'),
('it','common','caregiver.dementia_desc','Scala di Deterioramento Globale (GDS) — 7 stadi di declino cognitivo'),
('it','common','caregiver.dementia_ref_body','Visualizza la guida dettagliata sugli stadi della demenza e le esigenze di cura'),
('it','common','caregiver.dementia_ref_title','Scala di Riferimento per la Demenza'),
('it','common','caregiver.dementia_scale','Riferimento scala demenza'),
('it','common','caregiver.export_failed','Impossibile esportare l''osservazione.'),
('it','common','caregiver.free_obs_remaining_one','1 osservazione gratuita rimanente (ultimi 12 mesi)'),
('it','common','caregiver.free_obs_remaining_other','{{count}} osservazioni gratuite rimanenti (ultimi 12 mesi)'),
('it','common','caregiver.legend_load_failed','Impossibile caricare la legenda dei punteggi'),
('it','common','caregiver.loading','Caricamento dashboard caregiver...'),
('it','common','caregiver.locked_panel_cta','Sblocca con un piano a pagamento'),
('it','common','caregiver.new_obs_btn','Nuova Osservazione'),
('it','common','caregiver.new_observation','Nuova Osservazione'),
('it','common','caregiver.no_obs_selected','Nessuna osservazione selezionata'),
('it','common','caregiver.obs_delete_failed','Impossibile eliminare l''osservazione. Riprova.'),
('it','common','caregiver.obs_deleted','Osservazione eliminata con successo'),
('it','common','caregiver.obs_empty','Nessuna osservazione registrata ancora.'),
('it','common','caregiver.obs_empty_cta','Registra la prima osservazione →'),
('it','common','caregiver.obs_load_failed','Impossibile caricare l''osservazione'),
('it','common','caregiver.obs_not_found','Osservazione non trovata'),
('it','common','caregiver.obs_view_all','Vedi tutte le {count} osservazioni →'),
('it','common','caregiver.observations_body','Un registro delle tue valutazioni di cura nel tempo'),
('it','common','caregiver.observations_title','Le tue osservazioni'),
('it','common','caregiver.payment_success','Pagamento riuscito! Il tuo abbonamento è ora attivo.'),
('it','common','caregiver.subscriber_tools_heading','Strumenti abbonato'),
('it','common','caregiver.subtitle_care_plan','Di seguito viene mostrato il progresso del tuo piano di cura.'),
('it','common','caregiver.subtitle_default','Ecco un riepilogo delle tue attività di cura attuali.'),
('it','common','caregiver.subtitle_memory_book','Di seguito viene mostrato il progresso del tuo piano di cura, libro dei ricordi e osservazioni.'),
('it','common','caregiver.subtitle_observations','Di seguito vengono mostrate le tue osservazioni recenti.'),
('it','common','caregiver.upsell_cp_desc','Coordina il team — ruoli, autorità, sostenibilità'),
('it','common','caregiver.upsell_mb_desc','Conosci la persona — identità, salute, preferenze, contatti'),
('it','common','caregiver.upsell_upgrade_cta','Aggiorna per accedere'),
('it','common','caregiver.view_arrow','Vedi →'),
('it','common','caregiver.your_obs_body','Tieni traccia e gestisci le tue osservazioni di caregiver'),
('it','common','caregiver.your_obs_title','Le tue osservazioni'),
('it','common','dashboard.mb_section_contacts','Contatti'),
('it','common','dashboard.mb_section_daily_living','Vita Quotidiana e Preferenze'),
('it','common','dashboard.mb_section_identity','Identità'),
('it','common','dashboard.mb_section_medical','Medico'),
('it','common','dashboard.mb_sections_have_content','di {total} sezioni hanno contenuto'),
('it','common','dashboard.mb_subtitle','Conoscere la persona'),
('it','common','dashboard.mb_title','Libro dei Ricordi'),
('it','common','dashboard.medical_allergies','Allergie'),
('it','common','dashboard.medical_conditions','Condizioni'),
('it','common','dashboard.medical_hearing','Udito'),
('it','common','dashboard.medical_medications','Farmaci'),
('it','common','dashboard.medical_subtitle','Dal Libro dei Ricordi'),
('it','common','dashboard.medical_title','Riepilogo Medico'),
('it','common','dashboard.medical_view_link','Vedi Libro dei Ricordi'),
('it','common','dashboard.medical_vision','Vista'),
('it','common','dashboard.resident_age','Età {age}'),
('it','common','dashboard.resident_complete_cta','Completa il profilo del residente →'),
('it','common','dashboard.resident_known_as','Conosciuto come \"{name}\"'),
('it','common','dashboard.resident_profile_pct','Profilo {pct}% completo'),
('it','common','dashboard.resident_subtitle','La persona al centro delle cure'),
('it','common','dashboard.resident_title','Residente'),

-- ============================================================
-- SWEDISH (sv) — caregiver + dashboard
-- ============================================================
('sv','common','caregiver.dashboard_title','Instrumentpanel'),
('sv','common','caregiver.delete_failed','Det gick inte att ta bort observationen'),
('sv','common','caregiver.dementia_desc','Global Deterioration Scale (GDS) — 7 stadier av kognitiv nedgång'),
('sv','common','caregiver.dementia_ref_body','Visa detaljerad vägledning om demenssstadier och vårdbehov'),
('sv','common','caregiver.dementia_ref_title','Referensskala för demens'),
('sv','common','caregiver.dementia_scale','Referens för demensskala'),
('sv','common','caregiver.export_failed','Det gick inte att exportera observationen.'),
('sv','common','caregiver.free_obs_remaining_one','1 gratis observation kvar (rullande 12 månader)'),
('sv','common','caregiver.free_obs_remaining_other','{{count}} gratis observationer kvar (rullande 12 månader)'),
('sv','common','caregiver.legend_load_failed','Det gick inte att läsa in poänglegendens'),
('sv','common','caregiver.loading','Laddar vårdgivarens instrumentpanel...'),
('sv','common','caregiver.locked_panel_cta','Lås upp med ett betalt abonnemang'),
('sv','common','caregiver.new_obs_btn','Ny observation'),
('sv','common','caregiver.new_observation','Ny observation'),
('sv','common','caregiver.no_obs_selected','Ingen observation vald'),
('sv','common','caregiver.obs_delete_failed','Det gick inte att ta bort observationen. Försök igen.'),
('sv','common','caregiver.obs_deleted','Observation raderad'),
('sv','common','caregiver.obs_empty','Inga observationer registrerade ännu.'),
('sv','common','caregiver.obs_empty_cta','Registrera din första observation →'),
('sv','common','caregiver.obs_load_failed','Det gick inte att läsa in observationen'),
('sv','common','caregiver.obs_not_found','Observation hittades inte'),
('sv','common','caregiver.obs_view_all','Visa alla {count} observationer →'),
('sv','common','caregiver.observations_body','En historik över dina vårdutredningar över tid'),
('sv','common','caregiver.observations_title','Dina observationer'),
('sv','common','caregiver.payment_success','Betalning lyckades! Ditt abonnemang är nu aktivt.'),
('sv','common','caregiver.subscriber_tools_heading','Abonnentverktyg'),
('sv','common','caregiver.subtitle_care_plan','Framstegen i din vårdplan visas nedan.'),
('sv','common','caregiver.subtitle_default','Här är en sammanfattning av dina aktuella vårdaktiviteter.'),
('sv','common','caregiver.subtitle_memory_book','Framstegen i din vårdplan, minnesbok och observationer visas nedan.'),
('sv','common','caregiver.subtitle_observations','Dina senaste observationer visas nedan.'),
('sv','common','caregiver.upsell_cp_desc','Koordinera teamet — roller, befogenhet, hållbarhet'),
('sv','common','caregiver.upsell_mb_desc','Lär känna personen — identitet, hälsa, preferenser, kontakter'),
('sv','common','caregiver.upsell_upgrade_cta','Uppgradera för åtkomst'),
('sv','common','caregiver.view_arrow','Visa →'),
('sv','common','caregiver.your_obs_body','Spåra och hantera dina vårdgivarobservationer'),
('sv','common','caregiver.your_obs_title','Dina observationer'),
('sv','common','dashboard.mb_section_contacts','Kontakter'),
('sv','common','dashboard.mb_section_daily_living','Dagligt liv & preferenser'),
('sv','common','dashboard.mb_section_identity','Identitet'),
('sv','common','dashboard.mb_section_medical','Medicinskt'),
('sv','common','dashboard.mb_sections_have_content','av {total} avsnitt har innehåll'),
('sv','common','dashboard.mb_subtitle','Lär känna personen'),
('sv','common','dashboard.mb_title','Minnesbok'),
('sv','common','dashboard.medical_allergies','Allergier'),
('sv','common','dashboard.medical_conditions','Tillstånd'),
('sv','common','dashboard.medical_hearing','Hörsel'),
('sv','common','dashboard.medical_medications','Mediciner'),
('sv','common','dashboard.medical_subtitle','Från minnesboken'),
('sv','common','dashboard.medical_title','Medicinsk sammanfattning'),
('sv','common','dashboard.medical_view_link','Visa minnesbok'),
('sv','common','dashboard.medical_vision','Syn'),
('sv','common','dashboard.resident_age','Ålder {age}'),
('sv','common','dashboard.resident_complete_cta','Slutför boendeprofilen →'),
('sv','common','dashboard.resident_known_as','Känd som \"{name}\"'),
('sv','common','dashboard.resident_profile_pct','Profil {pct}% klar'),
('sv','common','dashboard.resident_subtitle','Personen i centrum av vården'),
('sv','common','dashboard.resident_title','Boende'),

-- ============================================================
-- FINNISH (fi) — caregiver + dashboard
-- ============================================================
('fi','common','caregiver.dashboard_title','Kojelauta'),
('fi','common','caregiver.delete_failed','Havainnon poistaminen epäonnistui'),
('fi','common','caregiver.dementia_desc','Globaali rappeutumisasteikko (GDS) — 7 kognitiivisen heikkenemisen vaihetta'),
('fi','common','caregiver.dementia_ref_body','Katso yksityiskohtainen ohje dementiavaiheista ja hoitotarpeista'),
('fi','common','caregiver.dementia_ref_title','Dementian viiteasteikko'),
('fi','common','caregiver.dementia_scale','Dementian asteikkoviite'),
('fi','common','caregiver.export_failed','Havainnon vieminen epäonnistui.'),
('fi','common','caregiver.free_obs_remaining_one','1 ilmainen havainto jäljellä (viimeiset 12 kuukautta)'),
('fi','common','caregiver.free_obs_remaining_other','{{count}} ilmaista havaintoa jäljellä (viimeiset 12 kuukautta)'),
('fi','common','caregiver.legend_load_failed','Pistemäärän legendan lataaminen epäonnistui'),
('fi','common','caregiver.loading','Ladataan hoitajan kojelautaa...'),
('fi','common','caregiver.locked_panel_cta','Avaa maksullisella suunnitelmalla'),
('fi','common','caregiver.new_obs_btn','Uusi havainto'),
('fi','common','caregiver.new_observation','Uusi havainto'),
('fi','common','caregiver.no_obs_selected','Ei valittua havaintoa'),
('fi','common','caregiver.obs_delete_failed','Havainnon poistaminen epäonnistui. Yritä uudelleen.'),
('fi','common','caregiver.obs_deleted','Havainto poistettu onnistuneesti'),
('fi','common','caregiver.obs_empty','Ei havaintoja tallennettu vielä.'),
('fi','common','caregiver.obs_empty_cta','Tallenna ensimmäinen havainto →'),
('fi','common','caregiver.obs_load_failed','Havainnon lataaminen epäonnistui'),
('fi','common','caregiver.obs_not_found','Havaintoa ei löydy'),
('fi','common','caregiver.obs_view_all','Näytä kaikki {count} havaintoa →'),
('fi','common','caregiver.observations_body','Kirjaus hoitoarvioinneistasi ajan myötä'),
('fi','common','caregiver.observations_title','Havaintosi'),
('fi','common','caregiver.payment_success','Maksu onnistui! Tilauksesi on nyt aktiivinen.'),
('fi','common','caregiver.subscriber_tools_heading','Tilaajan työkalut'),
('fi','common','caregiver.subtitle_care_plan','Hoitosuunnitelmasi edistyminen näytetään alla.'),
('fi','common','caregiver.subtitle_default','Tässä on yhteenveto nykyisistä hoitoaktiviteeteistasi.'),
('fi','common','caregiver.subtitle_memory_book','Hoitosuunnitelmasi, muistokirjasi ja havaintojesi edistyminen näytetään alla.'),
('fi','common','caregiver.subtitle_observations','Viimeisimmät havaintosi näytetään alla.'),
('fi','common','caregiver.upsell_cp_desc','Koordinoi tiimi — roolit, auktoriteetti, kestävyys'),
('fi','common','caregiver.upsell_mb_desc','Tunne henkilö — identiteetti, terveys, mieltymykset, yhteystiedot'),
('fi','common','caregiver.upsell_upgrade_cta','Päivitä käyttääksesi'),
('fi','common','caregiver.view_arrow','Näytä →'),
('fi','common','caregiver.your_obs_body','Seuraa ja hallitse hoitajahavaintojasi'),
('fi','common','caregiver.your_obs_title','Havaintosi'),
('fi','common','dashboard.mb_section_contacts','Yhteystiedot'),
('fi','common','dashboard.mb_section_daily_living','Arki ja mieltymykset'),
('fi','common','dashboard.mb_section_identity','Identiteetti'),
('fi','common','dashboard.mb_section_medical','Lääketieteellinen'),
('fi','common','dashboard.mb_sections_have_content','{total}:sta osiosta sisältää tietoa'),
('fi','common','dashboard.mb_subtitle','Tuntea henkilö'),
('fi','common','dashboard.mb_title','Muistokirja'),
('fi','common','dashboard.medical_allergies','Allergiat'),
('fi','common','dashboard.medical_conditions','Sairaudet'),
('fi','common','dashboard.medical_hearing','Kuulo'),
('fi','common','dashboard.medical_medications','Lääkkeet'),
('fi','common','dashboard.medical_subtitle','Muistokirjasta'),
('fi','common','dashboard.medical_title','Lääketieteellinen yhteenveto'),
('fi','common','dashboard.medical_view_link','Näytä muistokirja'),
('fi','common','dashboard.medical_vision','Näkö'),
('fi','common','dashboard.resident_age','Ikä {age}'),
('fi','common','dashboard.resident_complete_cta','Täydennä asukkaan profiili →'),
('fi','common','dashboard.resident_known_as','Tunnetaan nimellä \"{name}\"'),
('fi','common','dashboard.resident_profile_pct','Profiili {pct}% valmis'),
('fi','common','dashboard.resident_subtitle','Hoidon keskipisteenä oleva henkilö'),
('fi','common','dashboard.resident_title','Asukas'),

-- ============================================================
-- JAPANESE (ja) — caregiver + dashboard
-- ============================================================
('ja','common','caregiver.dashboard_title','ダッシュボード'),
('ja','common','caregiver.delete_failed','観察を削除できませんでした'),
('ja','common','caregiver.dementia_desc','全体的な悪化スケール（GDS）— 認知機能低下の7段階'),
('ja','common','caregiver.dementia_ref_body','認知症の段階とケアのニーズに関する詳細なガイダンスを見る'),
('ja','common','caregiver.dementia_ref_title','認知症参照スケール'),
('ja','common','caregiver.dementia_scale','認知症スケール参照'),
('ja','common','caregiver.export_failed','観察のエクスポートに失敗しました。'),
('ja','common','caregiver.free_obs_remaining_one','残り1回の無料観察（過去12か月間）'),
('ja','common','caregiver.free_obs_remaining_other','残り{{count}}回の無料観察（過去12か月間）'),
('ja','common','caregiver.legend_load_failed','スコア凡例を読み込めませんでした'),
('ja','common','caregiver.loading','ケアギバーダッシュボードを読み込み中...'),
('ja','common','caregiver.locked_panel_cta','有料プランでロック解除'),
('ja','common','caregiver.new_obs_btn','新しい観察'),
('ja','common','caregiver.new_observation','新しい観察'),
('ja','common','caregiver.no_obs_selected','観察が選択されていません'),
('ja','common','caregiver.obs_delete_failed','観察を削除できませんでした。もう一度お試しください。'),
('ja','common','caregiver.obs_deleted','観察を正常に削除しました'),
('ja','common','caregiver.obs_empty','まだ観察が記録されていません。'),
('ja','common','caregiver.obs_empty_cta','最初の観察を記録する →'),
('ja','common','caregiver.obs_load_failed','観察を読み込めませんでした'),
('ja','common','caregiver.obs_not_found','観察が見つかりません'),
('ja','common','caregiver.obs_view_all','すべての{count}件の観察を表示 →'),
('ja','common','caregiver.observations_body','時間の経過とともにケア評価の記録'),
('ja','common','caregiver.observations_title','あなたの観察'),
('ja','common','caregiver.payment_success','お支払いが完了しました！サブスクリプションが有効になりました。'),
('ja','common','caregiver.subscriber_tools_heading','サブスクライバーツール'),
('ja','common','caregiver.subtitle_care_plan','ケアプランの進捗状況が以下に表示されます。'),
('ja','common','caregiver.subtitle_default','現在のケア活動の概要をご覧ください。'),
('ja','common','caregiver.subtitle_memory_book','ケアプラン、思い出の本、観察の進捗状況が以下に表示されます。'),
('ja','common','caregiver.subtitle_observations','最新の観察が以下に表示されます。'),
('ja','common','caregiver.upsell_cp_desc','チームを調整する — 役割、権限、持続可能性'),
('ja','common','caregiver.upsell_mb_desc','人を知る — アイデンティティ、健康、好み、連絡先'),
('ja','common','caregiver.upsell_upgrade_cta','アクセスするためにアップグレード'),
('ja','common','caregiver.view_arrow','見る →'),
('ja','common','caregiver.your_obs_body','ケアギバーの観察を追跡・管理する'),
('ja','common','caregiver.your_obs_title','あなたの観察'),
('ja','common','dashboard.mb_section_contacts','連絡先'),
('ja','common','dashboard.mb_section_daily_living','日常生活と好み'),
('ja','common','dashboard.mb_section_identity','アイデンティティ'),
('ja','common','dashboard.mb_section_medical','医療'),
('ja','common','dashboard.mb_sections_have_content','{total}セクションのうちコンテンツあり'),
('ja','common','dashboard.mb_subtitle','人を知る'),
('ja','common','dashboard.mb_title','思い出の本'),
('ja','common','dashboard.medical_allergies','アレルギー'),
('ja','common','dashboard.medical_conditions','状態'),
('ja','common','dashboard.medical_hearing','聴覚'),
('ja','common','dashboard.medical_medications','薬'),
('ja','common','dashboard.medical_subtitle','思い出の本より'),
('ja','common','dashboard.medical_title','医療サマリー'),
('ja','common','dashboard.medical_view_link','思い出の本を見る'),
('ja','common','dashboard.medical_vision','視力'),
('ja','common','dashboard.resident_age','年齢 {age}'),
('ja','common','dashboard.resident_complete_cta','居住者プロファイルを完成させる →'),
('ja','common','dashboard.resident_known_as','\"{name}\"として知られている'),
('ja','common','dashboard.resident_profile_pct','プロファイル{pct}%完成'),
('ja','common','dashboard.resident_subtitle','ケアの中心にいる人'),
('ja','common','dashboard.resident_title','居住者')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
