
INSERT INTO ui_translations (locale, namespace, key, value) VALUES
-- SPANISH (es) - new_carer namespace structural/navigation keys
('es','new_carer','page_title','Guía para Nuevos Cuidadores'),
('es','new_carer','intro_heading','Bienvenido a CarerView'),
('es','new_carer','intro_subheading','Tu guía paso a paso para comenzar'),
('es','new_carer','cta_try_free','Prueba CarerView gratis'),
('es','new_carer','cta_get_started','Comenzar'),
('es','new_carer','cta_learn_more','Saber más'),
('es','new_carer','nav_back','Atrás'),
('es','new_carer','nav_next','Siguiente'),
('es','new_carer','nav_skip','Omitir'),
('es','new_carer','section_what_is_caring','¿Qué es el cuidado?'),
('es','new_carer','section_getting_organised','Organizarse'),
('es','new_carer','section_daily_routines','Rutinas diarias'),
('es','new_carer','section_health_and_medication','Salud y medicación'),
('es','new_carer','section_emotional_wellbeing','Bienestar emocional'),
('es','new_carer','section_legal_and_financial','Legal y finanzas'),
('es','new_carer','section_support_networks','Redes de apoyo'),
('es','new_carer','section_technology','Tecnología para cuidadores'),
('es','new_carer','section_self_care','Cuidado personal'),
('es','new_carer','section_next_steps','Próximos pasos'),
('es','new_carer','read_more','Leer más'),
('es','new_carer','read_less','Leer menos'),
('es','new_carer','table_of_contents','Tabla de contenidos'),
('es','new_carer','progress_label','Tu progreso'),
('es','new_carer','completed_label','Completado'),
('es','new_carer','time_to_read','Tiempo de lectura'),
('es','new_carer','minutes_abbr','min'),
('es','new_carer','tip_label','Consejo'),
('es','new_carer','important_label','Importante'),
('es','new_carer','note_label','Nota'),
('es','new_carer','checklist_heading','Lista de verificación'),
('es','new_carer','checklist_mark_done','Marcar como completado'),
('es','new_carer','download_pdf','Descargar PDF'),
('es','new_carer','print_page','Imprimir página'),
('es','new_carer','share_page','Compartir'),
('es','new_carer','feedback_helpful','¿Te fue útil esto?'),
('es','new_carer','feedback_yes','Sí'),
('es','new_carer','feedback_no','No'),
-- FRENCH (fr)
('fr','new_carer','page_title','Guide pour les Nouveaux Aidants'),
('fr','new_carer','intro_heading','Bienvenue sur CarerView'),
('fr','new_carer','intro_subheading','Votre guide étape par étape pour commencer'),
('fr','new_carer','cta_try_free','Essayez CarerView gratuitement'),
('fr','new_carer','cta_get_started','Commencer'),
('fr','new_carer','cta_learn_more','En savoir plus'),
('fr','new_carer','nav_back','Retour'),
('fr','new_carer','nav_next','Suivant'),
('fr','new_carer','nav_skip','Passer'),
('fr','new_carer','section_what_is_caring','Qu''est-ce que le soin?'),
('fr','new_carer','section_getting_organised','S''organiser'),
('fr','new_carer','section_daily_routines','Routines quotidiennes'),
('fr','new_carer','section_health_and_medication','Santé et médicaments'),
('fr','new_carer','section_emotional_wellbeing','Bien-être émotionnel'),
('fr','new_carer','section_legal_and_financial','Juridique et finances'),
('fr','new_carer','section_support_networks','Réseaux de soutien'),
('fr','new_carer','section_technology','Technologie pour aidants'),
('fr','new_carer','section_self_care','Prendre soin de soi'),
('fr','new_carer','section_next_steps','Prochaines étapes'),
('fr','new_carer','read_more','Lire la suite'),
('fr','new_carer','read_less','Réduire'),
('fr','new_carer','table_of_contents','Table des matières'),
('fr','new_carer','progress_label','Votre progression'),
('fr','new_carer','completed_label','Terminé'),
('fr','new_carer','time_to_read','Temps de lecture'),
('fr','new_carer','minutes_abbr','min'),
('fr','new_carer','tip_label','Conseil'),
('fr','new_carer','important_label','Important'),
('fr','new_carer','note_label','Note'),
('fr','new_carer','checklist_heading','Liste de contrôle'),
('fr','new_carer','checklist_mark_done','Marquer comme terminé'),
('fr','new_carer','download_pdf','Télécharger PDF'),
('fr','new_carer','print_page','Imprimer la page'),
('fr','new_carer','share_page','Partager'),
('fr','new_carer','feedback_helpful','Cela vous a-t-il été utile?'),
('fr','new_carer','feedback_yes','Oui'),
('fr','new_carer','feedback_no','Non'),
-- GERMAN (de)
('de','new_carer','page_title','Leitfaden für neue Pflegepersonen'),
('de','new_carer','intro_heading','Willkommen bei CarerView'),
('de','new_carer','intro_subheading','Ihre Schritt-für-Schritt-Anleitung zum Einstieg'),
('de','new_carer','cta_try_free','CarerView kostenlos testen'),
('de','new_carer','cta_get_started','Loslegen'),
('de','new_carer','cta_learn_more','Mehr erfahren'),
('de','new_carer','nav_back','Zurück'),
('de','new_carer','nav_next','Weiter'),
('de','new_carer','nav_skip','Überspringen'),
('de','new_carer','section_what_is_caring','Was ist Pflege?'),
('de','new_carer','section_getting_organised','Organisation'),
('de','new_carer','section_daily_routines','Tagesroutinen'),
('de','new_carer','section_health_and_medication','Gesundheit und Medikamente'),
('de','new_carer','section_emotional_wellbeing','Emotionales Wohlbefinden'),
('de','new_carer','section_legal_and_financial','Rechtliches und Finanzielles'),
('de','new_carer','section_support_networks','Unterstützungsnetzwerke'),
('de','new_carer','section_technology','Technologie für Pflegepersonen'),
('de','new_carer','section_self_care','Selbstfürsorge'),
('de','new_carer','section_next_steps','Nächste Schritte'),
('de','new_carer','read_more','Mehr lesen'),
('de','new_carer','read_less','Weniger anzeigen'),
('de','new_carer','table_of_contents','Inhaltsverzeichnis'),
('de','new_carer','progress_label','Ihr Fortschritt'),
('de','new_carer','completed_label','Abgeschlossen'),
('de','new_carer','time_to_read','Lesezeit'),
('de','new_carer','minutes_abbr','Min.'),
('de','new_carer','tip_label','Tipp'),
('de','new_carer','important_label','Wichtig'),
('de','new_carer','note_label','Hinweis'),
('de','new_carer','checklist_heading','Checkliste'),
('de','new_carer','checklist_mark_done','Als erledigt markieren'),
('de','new_carer','download_pdf','PDF herunterladen'),
('de','new_carer','print_page','Seite drucken'),
('de','new_carer','share_page','Teilen'),
('de','new_carer','feedback_helpful','War das hilfreich?'),
('de','new_carer','feedback_yes','Ja'),
('de','new_carer','feedback_no','Nein'),
-- ITALIAN (it)
('it','new_carer','page_title','Guida per i Nuovi Assistenti'),
('it','new_carer','intro_heading','Benvenuto su CarerView'),
('it','new_carer','intro_subheading','La tua guida passo dopo passo per iniziare'),
('it','new_carer','cta_try_free','Prova CarerView gratuitamente'),
('it','new_carer','cta_get_started','Inizia'),
('it','new_carer','cta_learn_more','Scopri di più'),
('it','new_carer','nav_back','Indietro'),
('it','new_carer','nav_next','Avanti'),
('it','new_carer','nav_skip','Salta'),
('it','new_carer','section_what_is_caring','Cos''è l''assistenza?'),
('it','new_carer','section_getting_organised','Organizzarsi'),
('it','new_carer','section_daily_routines','Routine quotidiane'),
('it','new_carer','section_health_and_medication','Salute e farmaci'),
('it','new_carer','section_emotional_wellbeing','Benessere emotivo'),
('it','new_carer','section_legal_and_financial','Legale e finanze'),
('it','new_carer','section_support_networks','Reti di supporto'),
('it','new_carer','section_technology','Tecnologia per assistenti'),
('it','new_carer','section_self_care','Cura di sé'),
('it','new_carer','section_next_steps','Prossimi passi'),
('it','new_carer','read_more','Leggi di più'),
('it','new_carer','read_less','Leggi di meno'),
('it','new_carer','table_of_contents','Indice'),
('it','new_carer','progress_label','Il tuo progresso'),
('it','new_carer','completed_label','Completato'),
('it','new_carer','time_to_read','Tempo di lettura'),
('it','new_carer','minutes_abbr','min'),
('it','new_carer','tip_label','Suggerimento'),
('it','new_carer','important_label','Importante'),
('it','new_carer','note_label','Nota'),
('it','new_carer','checklist_heading','Lista di controllo'),
('it','new_carer','checklist_mark_done','Segna come completato'),
('it','new_carer','download_pdf','Scarica PDF'),
('it','new_carer','print_page','Stampa pagina'),
('it','new_carer','share_page','Condividi'),
('it','new_carer','feedback_helpful','Questo è stato utile?'),
('it','new_carer','feedback_yes','Sì'),
('it','new_carer','feedback_no','No'),
-- SWEDISH (sv)
('sv','new_carer','page_title','Guide för nya vårdgivare'),
('sv','new_carer','intro_heading','Välkommen till CarerView'),
('sv','new_carer','intro_subheading','Din steg-för-steg-guide för att komma igång'),
('sv','new_carer','cta_try_free','Prova CarerView gratis'),
('sv','new_carer','cta_get_started','Kom igång'),
('sv','new_carer','cta_learn_more','Läs mer'),
('sv','new_carer','nav_back','Tillbaka'),
('sv','new_carer','nav_next','Nästa'),
('sv','new_carer','nav_skip','Hoppa över'),
('sv','new_carer','section_what_is_caring','Vad är omsorg?'),
('sv','new_carer','section_getting_organised','Att organisera sig'),
('sv','new_carer','section_daily_routines','Dagliga rutiner'),
('sv','new_carer','section_health_and_medication','Hälsa och mediciner'),
('sv','new_carer','section_emotional_wellbeing','Emotionellt välbefinnande'),
('sv','new_carer','section_legal_and_financial','Juridik och ekonomi'),
('sv','new_carer','section_support_networks','Stödnätverk'),
('sv','new_carer','section_technology','Teknik för vårdgivare'),
('sv','new_carer','section_self_care','Egenvård'),
('sv','new_carer','section_next_steps','Nästa steg'),
('sv','new_carer','read_more','Läs mer'),
('sv','new_carer','read_less','Läs mindre'),
('sv','new_carer','table_of_contents','Innehållsförteckning'),
('sv','new_carer','progress_label','Ditt framsteg'),
('sv','new_carer','completed_label','Slutfört'),
('sv','new_carer','time_to_read','Lästid'),
('sv','new_carer','minutes_abbr','min'),
('sv','new_carer','tip_label','Tips'),
('sv','new_carer','important_label','Viktigt'),
('sv','new_carer','note_label','Notering'),
('sv','new_carer','checklist_heading','Checklista'),
('sv','new_carer','checklist_mark_done','Markera som klart'),
('sv','new_carer','download_pdf','Ladda ner PDF'),
('sv','new_carer','print_page','Skriv ut sida'),
('sv','new_carer','share_page','Dela'),
('sv','new_carer','feedback_helpful','Var detta till hjälp?'),
('sv','new_carer','feedback_yes','Ja'),
('sv','new_carer','feedback_no','Nej'),
-- FINNISH (fi)
('fi','new_carer','page_title','Opas uusille hoitajille'),
('fi','new_carer','intro_heading','Tervetuloa CarerView''hin'),
('fi','new_carer','intro_subheading','Askel askeleelta -oppaasi aloittamiseen'),
('fi','new_carer','cta_try_free','Kokeile CarerView''ta ilmaiseksi'),
('fi','new_carer','cta_get_started','Aloita'),
('fi','new_carer','cta_learn_more','Lue lisää'),
('fi','new_carer','nav_back','Takaisin'),
('fi','new_carer','nav_next','Seuraava'),
('fi','new_carer','nav_skip','Ohita'),
('fi','new_carer','section_what_is_caring','Mitä hoitaminen on?'),
('fi','new_carer','section_getting_organised','Järjestäytyminen'),
('fi','new_carer','section_daily_routines','Päivittäiset rutiinit'),
('fi','new_carer','section_health_and_medication','Terveys ja lääkitys'),
('fi','new_carer','section_emotional_wellbeing','Emotionaalinen hyvinvointi'),
('fi','new_carer','section_legal_and_financial','Oikeudelliset ja taloudelliset asiat'),
('fi','new_carer','section_support_networks','Tukiverkostot'),
('fi','new_carer','section_technology','Teknologia hoitajille'),
('fi','new_carer','section_self_care','Itsestä huolehtiminen'),
('fi','new_carer','section_next_steps','Seuraavat askeleet'),
('fi','new_carer','read_more','Lue lisää'),
('fi','new_carer','read_less','Lue vähemmän'),
('fi','new_carer','table_of_contents','Sisällysluettelo'),
('fi','new_carer','progress_label','Edistymisesi'),
('fi','new_carer','completed_label','Valmis'),
('fi','new_carer','time_to_read','Lukuaika'),
('fi','new_carer','minutes_abbr','min'),
('fi','new_carer','tip_label','Vinkki'),
('fi','new_carer','important_label','Tärkeää'),
('fi','new_carer','note_label','Huomio'),
('fi','new_carer','checklist_heading','Tarkistuslista'),
('fi','new_carer','checklist_mark_done','Merkitse tehdyksi'),
('fi','new_carer','download_pdf','Lataa PDF'),
('fi','new_carer','print_page','Tulosta sivu'),
('fi','new_carer','share_page','Jaa'),
('fi','new_carer','feedback_helpful','Oliko tästä hyötyä?'),
('fi','new_carer','feedback_yes','Kyllä'),
('fi','new_carer','feedback_no','Ei'),
-- JAPANESE (ja)
('ja','new_carer','page_title','新しいケアラーのためのガイド'),
('ja','new_carer','intro_heading','CarerViewへようこそ'),
('ja','new_carer','intro_subheading','始めるためのステップバイステップガイド'),
('ja','new_carer','cta_try_free','CarerViewを無料で試す'),
('ja','new_carer','cta_get_started','始める'),
('ja','new_carer','cta_learn_more','詳しく見る'),
('ja','new_carer','nav_back','戻る'),
('ja','new_carer','nav_next','次へ'),
('ja','new_carer','nav_skip','スキップ'),
('ja','new_carer','section_what_is_caring','介護とは何か'),
('ja','new_carer','section_getting_organised','整理整頓'),
('ja','new_carer','section_daily_routines','日常のルーティン'),
('ja','new_carer','section_health_and_medication','健康と投薬'),
('ja','new_carer','section_emotional_wellbeing','心理的健康'),
('ja','new_carer','section_legal_and_financial','法律と財務'),
('ja','new_carer','section_support_networks','サポートネットワーク'),
('ja','new_carer','section_technology','ケアラーのためのテクノロジー'),
('ja','new_carer','section_self_care','セルフケア'),
('ja','new_carer','section_next_steps','次のステップ'),
('ja','new_carer','read_more','もっと読む'),
('ja','new_carer','read_less','折りたたむ'),
('ja','new_carer','table_of_contents','目次'),
('ja','new_carer','progress_label','あなたの進捗'),
('ja','new_carer','completed_label','完了'),
('ja','new_carer','time_to_read','読了時間'),
('ja','new_carer','minutes_abbr','分'),
('ja','new_carer','tip_label','ヒント'),
('ja','new_carer','important_label','重要'),
('ja','new_carer','note_label','メモ'),
('ja','new_carer','checklist_heading','チェックリスト'),
('ja','new_carer','checklist_mark_done','完了としてマーク'),
('ja','new_carer','download_pdf','PDFをダウンロード'),
('ja','new_carer','print_page','ページを印刷'),
('ja','new_carer','share_page','共有'),
('ja','new_carer','feedback_helpful','これは役に立ちましたか？'),
('ja','new_carer','feedback_yes','はい'),
('ja','new_carer','feedback_no','いいえ')
ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
