
INSERT INTO ui_translations (locale, key, value) VALUES
('ja','landing.alone_body','介護には心配、疑問、そして無数の小さな決断が伴います。CarerViewは穏やかで一貫したフレームワークを提供します — 「たぶん…」を、誰もが理解できる共有された事実に置き換えられます。'),
('ja','landing.alone_title','あなたは一人ではありません。'),
('ja','landing.careplan_after_b1','権限文書は記録され、アクセス可能で、必要になる前に確認済み'),
('ja','landing.careplan_after_b2','すべてのチームメンバーが自分の責任を把握 — 重複なし、抜け漏れなし、争いなし'),
('ja','landing.careplan_after_b3','ケアラーのストレスを監視 — ケアを行う人もサポートが必要なときにプランが警告'),
('ja','landing.careplan_after_label','CarerView使用時'),
('ja','landing.careplan_before_b1','病院の待合室で法的文書を探し回る'),
('ja','landing.careplan_before_b2','誰が何に責任を持つか合意がないために兄弟姉妹が口論になる'),
('ja','landing.careplan_before_b3','バックアップもなく、誰にも気づかれずにプライマリケアラーが燃え尽きる'),
('ja','landing.careplan_before_label','プランなしの場合'),
('ja','landing.careplan_engine_body','ほとんどのケアのギャップは危機を引き起こすまで見えません。CarerViewのデシジョンエンジンはあなたのプランをスキャンし、深刻度別にリスクをフラグ立て — チームが緊急事態の最中ではなく、前に行動できるようにします。'),
('ja','landing.careplan_engine_title','CarerViewはあなたのプランを読み取り、不足しているものを教えます'),
('ja','landing.careplan_eyebrow','ケアプラン'),
('ja','landing.careplan_gap_crit_label','重要'),
('ja','landing.careplan_gap_imp_label','重要度高'),
('ja','landing.careplan_gap_mon_label','要監視'),
('ja','landing.careplan_gap1','バックアップケアラーが特定されていない'),
('ja','landing.careplan_gap2','医療権限が文書化されていない'),
('ja','landing.careplan_gap3','プライマリケアラーのストレスレベル：高'),
('ja','landing.careplan_gap4','健康調整の担当者が割り当てられていない'),
('ja','landing.careplan_s1_desc','現在の状況は？今すぐ決断すべきことは何か？'),
('ja','landing.careplan_s1_label','状況'),
('ja','landing.careplan_s2_desc','誰が医療上の決定を下せるか？誰が財務を管理するか？法的文書は整っているか？'),
('ja','landing.careplan_s2_label','権限'),
('ja','landing.careplan_s3_desc','個人ケア、健康調整、財務、精神的サポート、レスパイトの担当者は誰か？担当者がいないことは責任がないことを意味します。'),
('ja','landing.careplan_s3_label','責任'),
('ja','landing.careplan_s4_desc','現在の居住状況は安全で持続可能か？ニーズが変化するにつれて何を変える必要があるか？'),
('ja','landing.careplan_s4_label','居住環境'),
('ja','landing.careplan_s5_desc','プライマリケアラーはこれを続けられるか？バックアップカバー、レスパイト時間、ケアを行う人へのサポートはあるか？'),
('ja','landing.careplan_s5_label','持続可能性'),
('ja','landing.careplan_s6_desc','プランの見直しはいつ必要か？誰がレビューを呼びかけ、ニーズが変化する中でチームはどのように足並みを揃えるか？'),
('ja','landing.careplan_s6_label','レビュー'),
('ja','landing.cta_begin','今日から観察を始める'),
('ja','landing.cta_why','あなたの家族がCarerViewを必要とする理由'),
('ja','landing.feat1_body','日常生活活動のコア項目について、数分で今日の様子をメモしましょう。簡単なチェックインや完全な観察をいつでも作成できます。'),
('ja','landing.feat1_title','シンプルなチェックイン'),
('ja','landing.feat2_body','今日だけでなく、日数・週数・月数にわたる変化を観察します。パターンがルーティンやサポートを調整するタイミングを示します。'),
('ja','landing.feat2_title','信頼できるトレンド'),
('ja','landing.feat3_body','曖昧な記憶ではなく、具体的な観察を持って受診する。'),
('ja','landing.feat3_title','診察を有意義に'),
('ja','landing.feat4_body','兄弟姉妹やサポーターを同じ事実と言葉で一致させる。'),
('ja','landing.feat4_title','家族間の摩擦を減らす'),
('ja','landing.feat5_body','穏やかなトレンドがルーティン、服薬、サポートを調整するタイミングを示します。'),
('ja','landing.feat5_title','小さな変化を早期に発見'),
('ja','landing.feat6_body','今日できることに焦点を当てながら、サポートが必要な部分を観察する。'),
('ja','landing.feat6_title','大切な方を尊重する'),
('ja','landing.getstarted_body','アカウントを作成するか、サインインしてケアラーダッシュボードに戻ります。'),
('ja','landing.getstarted_title','今日から始める'),
('ja','landing.hero_body','ほとんどの家族は計画なしに介護を始めます — 誰が医療権限を持つか、プライマリケアラーが疲れたときに誰が引き継ぐか、ケアを受ける方が実際に何を望んでいるかが不明確なまま。CarerViewはチームに構造化された計画、共有された観察、そしてすべての人を調整し大切な方を中心に置くフィードバックループを提供します。'),
('ja','landing.hero_intro','大切な方が在宅ケアを必要とするとき、家族はしばしば重要な問いに直面します：誰が医療上の決定を下すか？誰がバックアップサポートを提供するか？その方の希望、好み、ケアニーズは何か？共有されたケアプランは、家族が介護の課題に対して情報を持ち、足並みを揃え、準備できるよう助けます。'),
('ja','landing.hero_pillar_tagline','計画・調整・観察・改善'),
('ja','landing.mb_team_note','すべてのチームメンバーが自分の責任を把握しています。メモリーブックはそれをうまく行うためのコンテキストを即座に、セットアップ不要で提供します。'),
('ja','landing.newcarer_body','法的権限とチームの役割から健康調整と持続可能な計画まで、新しい家族ケアラーが理解する必要があるすべてをカバーする8つのモジュール。登録不要。'),
('ja','landing.newcarer_cta','ケアラーガイドを探索する'),
('ja','landing.newcarer_eyebrow','介護が初めての方へ'),
('ja','landing.newcarer_module1','全体像'),
('ja','landing.newcarer_module2','ケアプラン'),
('ja','landing.newcarer_module3','チームの役割'),
('ja','landing.newcarer_module4','居住環境'),
('ja','landing.newcarer_module5','法的権限'),
('ja','landing.newcarer_module6','健康調整'),
('ja','landing.newcarer_module7','持続可能性'),
('ja','landing.newcarer_module8','レビューと更新'),
('ja','landing.newcarer_title','無料のケアラーガイドから始める'),
('ja','landing.pillar_coord_b1','メモリーブックはすべてのチームメンバーに即座のコンテキストを提供 — その方が誰か、誰に電話すべきか、何を注意すべきか、何が安心させるか'),
('ja','landing.pillar_coord_b2','責任が割り当てられ — すべてのチームメンバーが自分の担当を正確に把握し、ケアの重複と抜け漏れを削減'),
('ja','landing.pillar_coord_b3','ファミリーサークルは最大3人のケアラーを共有観察、週次ダイジェスト、役割ベースのアクセスで繋げる'),
('ja','landing.pillar_coord_subtitle','チーム全体を同じページに'),
('ja','landing.pillar_coord_title','調整'),
('ja','landing.pillar_obs_b1','作業療法に基づくシンプルな1〜5のADLスケール — 専門用語なし、チーム全体のための明確な共通言語'),
('ja','landing.pillar_obs_b2','日数・週数・月数にわたるトレンド — パターンがルーティン、服薬、介護体制を調整するタイミングを示す'),
('ja','landing.pillar_obs_b3','曖昧な記憶ではなく、具体的な観察を持って診察に臨む。PDFまたはDOCXへワンクリックで書き出し'),
('ja','landing.pillar_obs_subtitle','変化を追跡 — プランを正確に保つ'),
('ja','landing.pillar_obs_title','観察'),
('ja','landing.pillar_plan_b1','6つの構造化セクション：状況、権限、責任、居住環境、持続可能性、レビュー'),
('ja','landing.pillar_plan_b2','デシジョンエンジンが危機になる前にギャップをフラグ立て — 「バックアップケアラーが特定されていない」や「医療権限が文書化されていない」'),
('ja','landing.pillar_plan_b3','ケアラーの持続可能性もプランの一部 — ストレスレベル、バックアップカバー、レスパイトはケア受益者のニーズと並行して追跡される'),
('ja','landing.pillar_plan_subtitle','チームの運営計画を構築する'),
('ja','landing.pillar_plan_title','計画'),
('ja','landing.pillar_review_b1','プランは文書ではなく、生きたシステムです。CarerViewは観察がレビューのタイミングを示すときに知らせます'),
('ja','landing.pillar_review_b2','5つのレビュートリガー：健康変化、新しいケアラー、居住環境の変化、ケアラーストレス閾値、または四半期定期レビュー'),
('ja','landing.pillar_review_b3','介護が初めての方へ：無料8モジュールガイドが法的権限から持続可能な計画まですべてをカバー'),
('ja','landing.pillar_review_subtitle','家族のニーズとともに進化する生きたプラン'),
('ja','landing.pillar_review_title','更新・改善'),
('ja','landing.pillars_body','CarerViewはすべてのケアチームが必要とする4つのこと — 明確なプラン、調整されたチーム、継続的な観察、そして物事が変化するときにプランを最新に保つ方法 — を統合します。'),
('ja','landing.pillars_eyebrow','CarerViewシステム'),
('ja','landing.pillars_title','家族介護のための完全なシステム'),
('ja','landing.privacy_promise','プライバシーポリシーを読む'),
('ja','landing.sample_subtitle','「心配です」から「変化がありました」へ。'),
('ja','landing.sample_title','たった1回の観察がもたらす違いを見る'),
('ja','landing.scale_body','シンプルな1〜5のスケールで、日常生活活動の変化を明確かつ一貫して観察・伝達できます。'),
('ja','landing.scale_eyebrow','日常生活活動'),
('ja','landing.scale_more_help','より多くの自立が可能'),
('ja','landing.scale_more_indep','より多くの介助が必要'),
('ja','landing.scale_summary','「完全自立」から「全介助」まで — 日常生活活動を観察するための明確なフレームワーク'),
('ja','landing.scale_title','CarerView 1〜5スケール'),
('ja','landing.scenario1_body','3つの都市に3人の兄弟姉妹、デイリーケアが必要な1人の親。CarerViewはすべての人が同じ観察、同じプラン、同じメモリーブックにアクセスできるようにします — 誰も異なるバージョンの出来事から作業しません。遠方の兄弟姉妹は電話する前ではなく、後に確認します。'),
('ja','landing.scenario1_title','遠距離家族の調整'),
('ja','landing.scenario2_body','退院指示が一度に届く — 服薬、フォローアップ、制限事項、何かあったときの連絡先。CarerViewはその混乱を構造化されたプランに変えます：責任を割り当て、初日から観察を開始し、何か変化があれば早期警告フラグを立てます。退院後の最初の2週間は最もリスクの高い期間です。CarerViewはまさにその瞬間に構造をもたらします。'),
('ja','landing.scenario2_title','退院後の在宅計画'),
('ja','landing.scenario3_body','複数の有償ケアラーがシフトを共有する場合、一貫した引き継ぎが重要です。メモリーブックはすべてのケアラー — 新しいものも戻ってきたものも — が書類ではなく、その人を知って来ることを意味します。各シフトの観察が共有記録を構築します。誰も同じ質問を2回しません。'),
('ja','landing.scenario3_title','交代制有償ケアラー'),
('ja','landing.scenarios_eyebrow','CarerViewの使われ方'),
('ja','landing.scenarios_title','現実の状況。本物の調整。'),
('ja','landing.sustainability_b1','プライマリケアラーのストレスレベル追跡'),
('ja','landing.sustainability_b2','バックアップケアラーの特定とバックアッププランの文書化'),
('ja','landing.sustainability_b3','レスパイト時間の計画 — 介護が長期的に持続可能であり続けるために'),
('ja','landing.sustainability_eyebrow','ケアラーの健康'),
('ja','landing.sustainability_title','ケアラーの限界を考慮しないプランは完全なプランではない'),
('ja','landing.testimonial_loc','コロラド州デンバー'),
('ja','landing.testimonial_name','Billy G.'),
('ja','landing.testimonial_quote','兄と2人のいとこが叔母のプライマリケアラーです。独立能力についての感情が多くの口論を引き起こしていました。CarerViewはすべての状況の観察を議論するための共通で使いやすいシステムを持てるので好きです。'),
('ja','landing.testimonial2_loc','英国マンチェスター'),
('ja','landing.testimonial2_name','Sarah M.'),
('ja','landing.testimonial2_quote','母は金曜日の午後に大量の指示書とともに退院し、誰が何をするのか誰も明確ではありませんでした。CarerViewはその週に本当の計画を立てるのを助けてくれました — 責任を割り当て、権限を整理し、みんながようやく同じページに。'),
('ja','landing.trust_title','あなたの家族のストーリーはあなたのもの'),
('ja','landing.trust1_body','家族の情報を完全に管理'),
('ja','landing.trust1_title','データはあなたのもの'),
('ja','landing.trust2_body','あなたが招待した人だけと共有'),
('ja','landing.trust2_title','デフォルトでプライベート'),
('ja','landing.trust3_body','常に暗号化され保護されている'),
('ja','landing.trust3_title','安全なストレージ'),
('ja','landing.vital_note','あなたの観察はケアプランに不可欠です！'),
('ja','landing.why_body','家族、臨床医、在宅ケアラーを同じページに乗せる一貫したフレームワーク。'),
('ja','landing.why_eyebrow','なぜ機能するのか'),
('ja','landing.why_title','混乱が減る — ケアの共通言語')
ON CONFLICT (locale, key) DO NOTHING;
