
INSERT INTO ui_translations (key, locale, value) VALUES
('care_plan.print', 'en', 'Print'),
('care_plan.print_summary', 'en', 'Print summary'),
('care_plan.edit_care_plan', 'en', 'Edit Care Plan'),
('care_plan.summary_title', 'en', 'Care Plan Summary'),
('care_plan.summary_breadcrumb', 'en', 'Summary'),
('care_plan.summary_for_resident', 'en', 'For {name} · {completed} of {total} sections complete'),
('care_plan.resident_fallback', 'en', 'resident'),
('care_plan.generated_on', 'en', 'Generated {date}'),
('care_plan.not_filled_in', 'en', 'not filled in'),
('care_plan.situation_current', 'en', 'Current situation'),
('care_plan.situation_trigger', 'en', 'What triggered the need for more care'),
('care_plan.situation_concerns', 'en', 'Key concerns'),
('care_plan.situation_anticipated', 'en', 'Anticipated changes (6–12 months)'),
('care_plan.situation_urgent', 'en', 'Most urgent decisions'),
('care_plan.auth_health', 'en', 'Health decision authority'),
('care_plan.auth_financial', 'en', 'Financial authority'),
('care_plan.auth_legal', 'en', 'Legal documents'),
('care_plan.auth_preferences', 'en', 'Care preferences documented'),
('care_plan.auth_records', 'en', 'Organised records'),
('care_plan.auth_emergency', 'en', 'Emergency readiness'),
('care_plan.resp_household', 'en', 'Household support'),
('care_plan.resp_personal_care', 'en', 'Personal care'),
('care_plan.resp_emotional', 'en', 'Emotional support'),
('care_plan.resp_health', 'en', 'Health coordination'),
('care_plan.resp_scheduling', 'en', 'Appointments'),
('care_plan.resp_admin', 'en', 'Administration'),
('care_plan.resp_respite', 'en', 'Backup / respite'),
('care_plan.owner_label', 'en', 'Owner'),
('care_plan.backup_label', 'en', 'Backup'),
('care_plan.living_arrangement_label', 'en', 'Arrangement'),
('care_plan.living_resident_home', 'en', 'Resident stays in their own home'),
('care_plan.living_family_home', 'en', 'Resident moves into a family home'),
('care_plan.living_paid_in_home', 'en', 'Paid in-home support'),
('care_plan.living_assisted', 'en', 'Assisted living or residential care'),
('care_plan.living_undecided', 'en', 'Undecided / still assessing'),
('care_plan.living_working_label', 'en', 'Working'),
('care_plan.living_safety', 'en', 'Safety concerns'),
('care_plan.living_alternatives', 'en', 'Alternatives being considered'),
('care_plan.living_triggers', 'en', 'Triggers for change'),
('care_plan.living_constraints', 'en', 'Financial / family constraints'),
('care_plan.sust_primary', 'en', 'Primary caregiver'),
('care_plan.sust_hours', 'en', 'Available hours'),
('care_plan.sust_stress_level', 'en', 'Stress level'),
('care_plan.sust_stress_factors', 'en', 'Stress factors'),
('care_plan.sust_backup', 'en', 'Backup caregiver'),
('care_plan.sust_respite', 'en', 'Respite plan'),
('care_plan.sust_threshold', 'en', 'Sustainability threshold'),
('care_plan.review_frequency_label', 'en', 'Frequency'),
('care_plan.review_next_date_label', 'en', 'Next review'),
('care_plan.review_owner_label', 'en', 'Review owner'),
('care_plan.review_triggers_label', 'en', 'Unscheduled triggers'),
('care_plan.review_decisions_label', 'en', 'Decisions to revisit'),
('care_hub.title', 'en', 'Care Hub'),
('resident_profile.title', 'en', 'Resident Profile'),
('resident_profile.subtitle', 'en', 'The single source of truth for the person at the centre of your care.'),
('resident_profile.no_resident_title', 'en', 'No resident found'),
('resident_profile.no_resident_body', 'en', 'Set up your Family Circle first to create a resident profile.'),
('resident_profile.edit_profile', 'en', 'Edit Profile'),
('resident_profile.shared_notice_prefix', 'en', 'This profile is shared across the'),
('resident_profile.shared_notice_suffix', 'en', 'and Observations. Keeping it complete helps the whole team stay aligned.'),
('resident_profile.memory_book_link', 'en', 'Memory Book'),
('resident_profile.care_plan_link', 'en', 'Care Plan'),
('resident_profile.edit_form_title', 'en', 'Edit Resident Profile'),
('resident_profile.edit_form_subtitle', 'en', 'Changes sync automatically to the Memory Book Identity section.'),
('resident_profile.section_core_identity', 'en', 'Core Identity'),
('resident_profile.section_background', 'en', 'Background & Context'),
('resident_profile.section_about', 'en', 'About'),
('resident_profile.full_name_label', 'en', 'Full Name *'),
('resident_profile.full_name_placeholder', 'en', 'Legal full name'),
('resident_profile.preferred_name_label', 'en', 'Preferred Name'),
('resident_profile.preferred_name_placeholder', 'en', 'What they like to be called'),
('resident_profile.dob_label', 'en', 'Date of Birth'),
('resident_profile.gender_label', 'en', 'Gender'),
('resident_profile.gender_male', 'en', 'Male'),
('resident_profile.gender_female', 'en', 'Female'),
('resident_profile.gender_non_binary', 'en', 'Non-binary'),
('resident_profile.gender_prefer_not', 'en', 'Prefer not to say'),
('resident_profile.birthplace_label', 'en', 'Birthplace'),
('resident_profile.birthplace_placeholder', 'en', 'City, country'),
('resident_profile.address_label', 'en', 'Lives At / Address Preference'),
('resident_profile.address_placeholder', 'en', 'Home, care facility, etc.'),
('resident_profile.relationship_label', 'en', 'Relationship Status'),
('resident_profile.relationship_placeholder', 'en', 'Widowed, married, etc.'),
('resident_profile.cultural_label', 'en', 'Cultural Background'),
('resident_profile.cultural_placeholder', 'en', 'Heritage, traditions'),
('resident_profile.language_label', 'en', 'Language Preferences'),
('resident_profile.language_placeholder', 'en', 'First language, other languages'),
('resident_profile.lives_at_label', 'en', 'Lives At'),
('resident_profile.about_label', 'en', 'About the Resident'),
('resident_profile.about_placeholder', 'en', 'Who they are — their story, personality, what matters to them...'),
('resident_profile.no_about_narrative', 'en', 'No "About" narrative yet.'),
('resident_profile.add_their_story', 'en', 'Add their story'),
('resident_profile.save_button', 'en', 'Save Profile'),
('resident_profile.add_more_details', 'en', 'Add more details'),
('resident_profile.add_background_details', 'en', 'Add background details'),
('resident_profile.view_memory_book', 'en', 'View Memory Book'),
('resident_profile.view_care_plan', 'en', 'View Care Plan'),
('resident_profile.full_name_required', 'en', 'Full name is required'),
('resident_profile.save_success', 'en', 'Resident profile saved'),
('resident_profile.save_error', 'en', 'Failed to save'),
('resident_profile.age_label', 'en', 'Age {age}'),
('resident_profile.fields_complete', 'en', 'of {total} fields complete')
ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
