INSERT INTO ui_translations (locale, key, value) VALUES
('ja','landing.alone_body','介護には心配、疑問、そして無数の小さな決断が伴います。CarerViewは穏やかで一貫したフレームワークを提供します — 「たぶん…」を、誰もが理解できる共有された事実に置き換えられます。'),
('ja','landing.alone_title','あなたは一人ではありません。'),
('ja','landing.careplan_after_b1','権限文書は記録され、アクセス可能で、必要になる前に確認済み'),
('ja','landing.careplan_after_b2','すべてのチームメンバーが自分の責任を把握 — 重複なし、抜け漏れなし、争いなし'),
('ja','landing.careplan_after_b3','ケアラーのストレスを監視 — ケアを行う人もサポートが必要なときにプランが警告'),
('ja','landing.careplan_after_label','CarerView使用時'),
('ja','landing.careplan_before_b1','病院の待合室で法的文書を探し回る'),
('ja','landing.careplan_before_b2','誰が何に責任を持つか合意がないために兄弟姉妹が口論になる'),
('ja','landing.careplan_before_b3','バックアップもなく、誰にも気づかれずにプライマリケアラーが燃え尽きる'),
('ja','landing.careplan_before_label','プランなしの場合'),
('ja','landing.careplan_engine_body','ほとんどのケアのギャップは危機を引き起こすまで見えません。CarerViewのデシジョンエンジンはあなたのプランをスキャンし、深刻度別にリスクをフラグ立て — チームが緊急事態の最中ではなく、前に行動できるようにします。'),
('ja','landing.careplan_engine_title','CarerViewはあなたのプランを読み取り、不足しているものを教えます'),
('ja','landing.careplan_eyebrow','ケアプラン'),
('ja','landing.careplan_gap_crit_label','重要'),
('ja','landing.careplan_gap_imp_label','重要度高'),
('ja','landing.careplan_gap_mon_label','要監視'),
('ja','landing.careplan_gap1','バックアップケアラーが特定されていない'),
('ja','landing.careplan_gap2','医療権限が文書化されていない'),
('ja','landing.careplan_gap3','プライマリケアラーのストレスレベル：高'),
('ja','landing.careplan_gap4','健康調整の担当者が割り当てられていない'),
('ja','landing.careplan_s1_desc','現在の状況は？今すぐ決断すべきことは何か？'),
('ja','landing.careplan_s1_label','状況'),
('ja','landing.careplan_s2_desc','誰が医療上の決定を下せるか？誰が財務を管理するか？法的文書は整っているか？'),
('ja','landing.careplan_s2_label','権限'),
('ja','landing.careplan_s3_desc','個人ケア、健康調整、財務、精神的サポート、レスパイトの担当者は誰か？担当者がいないことは責任がないことを意味します。'),
('ja','landing.careplan_s3_label','責任'),
('ja','landing.careplan_s4_desc','現在の居住状況は安全で持続可能か？ニーズが変化するにつれて何を変える必要があるか？'),
('ja','landing.careplan_s4_label','居住環境'),
('ja','landing.careplan_s5_desc','プライマリケアラーはこれを続けられるか？バックアップカバー、レスパイト時間、ケアを行う人へのサポートはあるか？'),
('ja','landing.careplan_s5_label','持続可能性'),
('ja','landing.careplan_s6_desc','プランの見直しはいつ必要か？誰がレビューを呼びかけ、ニーズが変化する中でチームはどのように足並みを揃えるか？'),
('ja','landing.careplan_s6_label','レビュー')
ON CONFLICT (locale, namespace, key) DO NOTHING;