-- Translation Batch 1: auth.* and create_account.* keys for all 7 non-EN locales
-- AI-generated translations. ON CONFLICT updates to allow re-runs.

INSERT INTO public.ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- SPANISH (es)
-- ============================================================
('es','common','auth.create_account_link','Crear cuenta'),
('es','common','auth.create_account_tab','Crear cuenta'),
('es','common','auth.email_first','Ingresa tu dirección de correo electrónico primero.'),
('es','common','auth.email_label','Dirección de correo electrónico'),
('es','common','auth.email_placeholder','tu.correo@ejemplo.com'),
('es','common','auth.err_email_first','Ingresa tu dirección de correo electrónico primero.'),
('es','common','auth.err_invalid_creds','Correo o contraseña incorrectos. Verifica tus datos o restablece tu contraseña.'),
('es','common','auth.err_password_short','La contraseña debe tener al menos 8 caracteres.'),
('es','common','auth.failed','Algo salió mal. Por favor intenta de nuevo.'),
('es','common','auth.forgot_password','¿Olvidaste tu contraseña?'),
('es','common','auth.free_disclaimer','Plan gratuito disponible. No se requiere tarjeta de crédito para probar.'),
('es','common','auth.free_note','Plan gratuito disponible. No se requiere tarjeta de crédito para probar.'),
('es','common','auth.get_started','Comenzar'),
('es','common','auth.invalid_credentials','Correo o contraseña incorrectos. Verifica tus datos o restablece tu contraseña.'),
('es','common','auth.password_label','Contraseña'),
('es','common','auth.password_placeholder','Tu contraseña'),
('es','common','auth.password_rule_min_length','Mín. 8 caracteres'),
('es','common','auth.password_rule_needs_number','Añade un número'),
('es','common','auth.password_rule_needs_uppercase','Añade mayúscula'),
('es','common','auth.password_strength_fair','Regular'),
('es','common','auth.password_strength_strong','Fuerte'),
('es','common','auth.password_strength_weak','Débil'),
('es','common','auth.password_too_short','La contraseña debe tener al menos 8 caracteres.'),
('es','common','auth.reset_failed','No se pudo enviar el correo de restablecimiento. Intenta de nuevo.'),
('es','common','auth.reset_sending','Enviando…'),
('es','common','auth.reset_sent','Si ese correo existe en nuestro sistema, se ha enviado un enlace de restablecimiento.'),
('es','common','auth.sending_reset','Enviando…'),
('es','common','auth.sign_in_tab','Iniciar sesión'),
('es','common','auth.signin_failed','Error al iniciar sesión. Por favor intenta de nuevo.'),
('es','common','auth.signing_in','Iniciando sesión…'),
('es','common','auth.signup_body','Elige tu plan y configura tu cuenta de cuidador — solo toma un minuto.'),
('es','common','auth.signup_prompt','Elige tu plan y configura tu cuenta de cuidador — solo toma un minuto.'),
('es','common','auth.tab_create','Crear cuenta'),
('es','common','auth.tab_signin','Iniciar sesión'),
('es','common','auth.tagline','Cuidar más claro, juntos.'),
('es','common','auth.welcome_to','Bienvenido a'),
('es','common','create_account.agree_prefix','Al crear una cuenta aceptas nuestros'),
('es','common','create_account.already_have','¿Ya tienes una cuenta?'),
('es','common','create_account.always_free','Siempre gratis'),
('es','common','create_account.cancel_note','. Cancela cuando quieras.'),
('es','common','create_account.choose_plan','Elige tu plan'),
('es','common','create_account.confirm_email_info','Revisa tu correo para confirmar tu cuenta, luego vuelve aquí para completar el pago.'),
('es','common','create_account.confirm_password_label','Confirmar contraseña'),
('es','common','create_account.confirm_password_placeholder','Vuelve a ingresar tu contraseña'),
('es','common','create_account.email_required','El correo y la contraseña son obligatorios.'),
('es','common','create_account.email_taken','Ya existe una cuenta con ese correo. Por favor inicia sesión.'),
('es','common','create_account.incomplete_setup_notice','Tu cuenta fue creada pero la configuración no se completó. Elige un plan a continuación para continuar.'),
('es','common','create_account.loading','Cargando…'),
('es','common','create_account.name_label','Nombre completo'),
('es','common','create_account.name_placeholder','Tu nombre completo'),
('es','common','create_account.obs_family','Observaciones ilimitadas, hasta 5 cuidadores'),
('es','common','create_account.obs_free','Hasta 10 observaciones por mes'),
('es','common','create_account.obs_primary','Observaciones ilimitadas, 1 cuidador'),
('es','common','create_account.password_placeholder','Crea una contraseña'),
('es','common','create_account.password_too_short','La contraseña debe tener al menos 8 caracteres.'),
('es','common','create_account.passwords_mismatch','Las contraseñas no coinciden.'),
('es','common','create_account.per_quarter','por trimestre'),
('es','common','create_account.plan_missing_price','Este plan no está disponible para comprar ahora. Contacta al soporte.'),
('es','common','create_account.promo_label','Código de promoción'),
('es','common','create_account.promo_placeholder','Ingresa el código de promoción'),
('es','common','create_account.promo_prefix','Promo:'),
('es','common','create_account.section_title','Detalles de tu cuenta'),
('es','common','create_account.selected_plan','Plan seleccionado:'),
('es','common','create_account.signup_failed','El registro falló. Por favor intenta de nuevo.'),
('es','common','create_account.submit_btn','Crear cuenta'),
('es','common','create_account.subtitle','Configura tu cuenta y empieza a hacer seguimiento hoy.'),
('es','common','create_account.title','Crea tu cuenta'),

-- ============================================================
-- FRENCH (fr)
-- ============================================================
('fr','common','auth.create_account_link','Créer un compte'),
('fr','common','auth.create_account_tab','Créer un compte'),
('fr','common','auth.email_first','Veuillez d''abord saisir votre adresse e-mail.'),
('fr','common','auth.email_label','Adresse e-mail'),
('fr','common','auth.email_placeholder','votre.email@exemple.com'),
('fr','common','auth.err_email_first','Veuillez d''abord saisir votre adresse e-mail.'),
('fr','common','auth.err_invalid_creds','E-mail ou mot de passe incorrect. Vérifiez vos identifiants ou réinitialisez votre mot de passe.'),
('fr','common','auth.err_password_short','Le mot de passe doit comporter au moins 8 caractères.'),
('fr','common','auth.failed','Une erreur s''est produite. Veuillez réessayer.'),
('fr','common','auth.forgot_password','Mot de passe oublié ?'),
('fr','common','auth.free_disclaimer','Forfait gratuit disponible. Aucune carte de crédit requise pour essayer.'),
('fr','common','auth.free_note','Forfait gratuit disponible. Aucune carte de crédit requise pour essayer.'),
('fr','common','auth.get_started','Commencer'),
('fr','common','auth.invalid_credentials','E-mail ou mot de passe incorrect. Vérifiez vos identifiants ou réinitialisez votre mot de passe.'),
('fr','common','auth.password_label','Mot de passe'),
('fr','common','auth.password_placeholder','Votre mot de passe'),
('fr','common','auth.password_rule_min_length','8 car. min.'),
('fr','common','auth.password_rule_needs_number','Ajoutez un chiffre'),
('fr','common','auth.password_rule_needs_uppercase','Ajoutez une majuscule'),
('fr','common','auth.password_strength_fair','Moyen'),
('fr','common','auth.password_strength_strong','Fort'),
('fr','common','auth.password_strength_weak','Faible'),
('fr','common','auth.password_too_short','Le mot de passe doit comporter au moins 8 caractères.'),
('fr','common','auth.reset_failed','Échec de l''envoi de l''e-mail de réinitialisation. Veuillez réessayer.'),
('fr','common','auth.reset_sending','Envoi en cours…'),
('fr','common','auth.reset_sent','Si cet e-mail existe dans notre système, un lien de réinitialisation a été envoyé.'),
('fr','common','auth.sending_reset','Envoi en cours…'),
('fr','common','auth.sign_in_tab','Se connecter'),
('fr','common','auth.signin_failed','Échec de la connexion. Veuillez réessayer.'),
('fr','common','auth.signing_in','Connexion en cours…'),
('fr','common','auth.signup_body','Choisissez votre forfait et configurez votre compte — cela ne prend qu''une minute.'),
('fr','common','auth.signup_prompt','Choisissez votre forfait et configurez votre compte — cela ne prend qu''une minute.'),
('fr','common','auth.tab_create','Créer un compte'),
('fr','common','auth.tab_signin','Se connecter'),
('fr','common','auth.tagline','Des soins plus clairs, ensemble.'),
('fr','common','auth.welcome_to','Bienvenue sur'),
('fr','common','create_account.agree_prefix','En créant un compte, vous acceptez nos'),
('fr','common','create_account.already_have','Vous avez déjà un compte ?'),
('fr','common','create_account.always_free','Toujours gratuit'),
('fr','common','create_account.cancel_note','. Annulez à tout moment.'),
('fr','common','create_account.choose_plan','Choisissez votre forfait'),
('fr','common','create_account.confirm_email_info','Vérifiez votre e-mail pour confirmer votre compte, puis revenez ici pour finaliser le paiement.'),
('fr','common','create_account.confirm_password_label','Confirmer le mot de passe'),
('fr','common','create_account.confirm_password_placeholder','Ressaisissez votre mot de passe'),
('fr','common','create_account.email_required','L''e-mail et le mot de passe sont obligatoires.'),
('fr','common','create_account.email_taken','Un compte avec cet e-mail existe déjà. Veuillez vous connecter.'),
('fr','common','create_account.incomplete_setup_notice','Votre compte a été créé mais la configuration n''est pas terminée. Choisissez un forfait ci-dessous pour continuer.'),
('fr','common','create_account.loading','Chargement…'),
('fr','common','create_account.name_label','Nom complet'),
('fr','common','create_account.name_placeholder','Votre nom complet'),
('fr','common','create_account.obs_family','Observations illimitées, jusqu''à 5 soignants'),
('fr','common','create_account.obs_free','Jusqu''à 10 observations par mois'),
('fr','common','create_account.obs_primary','Observations illimitées, 1 soignant'),
('fr','common','create_account.password_placeholder','Créez un mot de passe'),
('fr','common','create_account.password_too_short','Le mot de passe doit comporter au moins 8 caractères.'),
('fr','common','create_account.passwords_mismatch','Les mots de passe ne correspondent pas.'),
('fr','common','create_account.per_quarter','par trimestre'),
('fr','common','create_account.plan_missing_price','Ce forfait n''est pas disponible à l''achat pour le moment. Contactez le support.'),
('fr','common','create_account.promo_label','Code promo'),
('fr','common','create_account.promo_placeholder','Saisir le code promo'),
('fr','common','create_account.promo_prefix','Promo :'),
('fr','common','create_account.section_title','Informations de votre compte'),
('fr','common','create_account.selected_plan','Forfait sélectionné :'),
('fr','common','create_account.signup_failed','Échec de l''inscription. Veuillez réessayer.'),
('fr','common','create_account.submit_btn','Créer un compte'),
('fr','common','create_account.subtitle','Configurez votre compte et commencez à suivre dès aujourd''hui.'),
('fr','common','create_account.title','Créez votre compte'),

-- ============================================================
-- GERMAN (de)
-- ============================================================
('de','common','auth.create_account_link','Konto erstellen'),
('de','common','auth.create_account_tab','Konto erstellen'),
('de','common','auth.email_first','Bitte gib zuerst deine E-Mail-Adresse ein.'),
('de','common','auth.email_label','E-Mail-Adresse'),
('de','common','auth.email_placeholder','deine.email@beispiel.de'),
('de','common','auth.err_email_first','Bitte gib zuerst deine E-Mail-Adresse ein.'),
('de','common','auth.err_invalid_creds','Falsche E-Mail oder falsches Passwort. Überprüfe deine Zugangsdaten oder setze dein Passwort zurück.'),
('de','common','auth.err_password_short','Das Passwort muss mindestens 8 Zeichen lang sein.'),
('de','common','auth.failed','Etwas ist schiefgelaufen. Bitte versuche es erneut.'),
('de','common','auth.forgot_password','Passwort vergessen?'),
('de','common','auth.free_disclaimer','Kostenloser Plan verfügbar. Keine Kreditkarte erforderlich.'),
('de','common','auth.free_note','Kostenloser Plan verfügbar. Keine Kreditkarte erforderlich.'),
('de','common','auth.get_started','Loslegen'),
('de','common','auth.invalid_credentials','Falsche E-Mail oder falsches Passwort. Überprüfe deine Zugangsdaten oder setze dein Passwort zurück.'),
('de','common','auth.password_label','Passwort'),
('de','common','auth.password_placeholder','Dein Passwort'),
('de','common','auth.password_rule_min_length','Mind. 8 Zeichen'),
('de','common','auth.password_rule_needs_number','Zahl hinzufügen'),
('de','common','auth.password_rule_needs_uppercase','Großbuchstabe hinzufügen'),
('de','common','auth.password_strength_fair','Mittel'),
('de','common','auth.password_strength_strong','Stark'),
('de','common','auth.password_strength_weak','Schwach'),
('de','common','auth.password_too_short','Das Passwort muss mindestens 8 Zeichen lang sein.'),
('de','common','auth.reset_failed','Senden der Reset-E-Mail fehlgeschlagen. Bitte versuche es erneut.'),
('de','common','auth.reset_sending','Wird gesendet…'),
('de','common','auth.reset_sent','Falls diese E-Mail in unserem System existiert, wurde ein Reset-Link gesendet.'),
('de','common','auth.sending_reset','Wird gesendet…'),
('de','common','auth.sign_in_tab','Anmelden'),
('de','common','auth.signin_failed','Anmeldung fehlgeschlagen. Bitte versuche es erneut.'),
('de','common','auth.signing_in','Anmeldung läuft…'),
('de','common','auth.signup_body','Wähle deinen Plan und richte dein Pflegekonto ein — dauert nur eine Minute.'),
('de','common','auth.signup_prompt','Wähle deinen Plan und richte dein Pflegekonto ein — dauert nur eine Minute.'),
('de','common','auth.tab_create','Konto erstellen'),
('de','common','auth.tab_signin','Anmelden'),
('de','common','auth.tagline','Pflege klarer machen, gemeinsam.'),
('de','common','auth.welcome_to','Willkommen bei'),
('de','common','create_account.agree_prefix','Mit der Erstellung eines Kontos stimmst du unseren'),
('de','common','create_account.already_have','Hast du bereits ein Konto?'),
('de','common','create_account.always_free','Immer kostenlos'),
('de','common','create_account.cancel_note','. Jederzeit kündbar.'),
('de','common','create_account.choose_plan','Plan wählen'),
('de','common','create_account.confirm_email_info','Prüfe deine E-Mail zur Kontobestätigung, dann kehre hierher zurück, um den Kauf abzuschließen.'),
('de','common','create_account.confirm_password_label','Passwort bestätigen'),
('de','common','create_account.confirm_password_placeholder','Passwort erneut eingeben'),
('de','common','create_account.email_required','E-Mail und Passwort sind erforderlich.'),
('de','common','create_account.email_taken','Ein Konto mit dieser E-Mail existiert bereits. Bitte melde dich an.'),
('de','common','create_account.incomplete_setup_notice','Dein Konto wurde erstellt, die Einrichtung wurde jedoch nicht abgeschlossen. Wähle unten einen Plan, um fortzufahren.'),
('de','common','create_account.loading','Wird geladen…'),
('de','common','create_account.name_label','Vollständiger Name'),
('de','common','create_account.name_placeholder','Dein vollständiger Name'),
('de','common','create_account.obs_family','Unbegrenzte Beobachtungen, bis zu 5 Pflegepersonen'),
('de','common','create_account.obs_free','Bis zu 10 Beobachtungen pro Monat'),
('de','common','create_account.obs_primary','Unbegrenzte Beobachtungen, 1 Pflegeperson'),
('de','common','create_account.password_placeholder','Passwort erstellen'),
('de','common','create_account.password_too_short','Das Passwort muss mindestens 8 Zeichen lang sein.'),
('de','common','create_account.passwords_mismatch','Die Passwörter stimmen nicht überein.'),
('de','common','create_account.per_quarter','pro Quartal'),
('de','common','create_account.plan_missing_price','Dieser Plan ist derzeit nicht käuflich. Bitte kontaktiere den Support.'),
('de','common','create_account.promo_label','Aktionscode'),
('de','common','create_account.promo_placeholder','Aktionscode eingeben'),
('de','common','create_account.promo_prefix','Promo:'),
('de','common','create_account.section_title','Deine Kontodaten'),
('de','common','create_account.selected_plan','Ausgewählter Plan:'),
('de','common','create_account.signup_failed','Registrierung fehlgeschlagen. Bitte versuche es erneut.'),
('de','common','create_account.submit_btn','Konto erstellen'),
('de','common','create_account.subtitle','Richte dein Konto ein und fange heute mit dem Protokollieren an.'),
('de','common','create_account.title','Dein Konto erstellen'),

-- ============================================================
-- ITALIAN (it)
-- ============================================================
('it','common','auth.create_account_link','Crea account'),
('it','common','auth.create_account_tab','Crea account'),
('it','common','auth.email_first','Inserisci prima il tuo indirizzo email.'),
('it','common','auth.email_label','Indirizzo email'),
('it','common','auth.email_placeholder','tua.email@esempio.it'),
('it','common','auth.err_email_first','Inserisci prima il tuo indirizzo email.'),
('it','common','auth.err_invalid_creds','Email o password errata. Controlla le credenziali o reimposta la password.'),
('it','common','auth.err_password_short','La password deve essere di almeno 8 caratteri.'),
('it','common','auth.failed','Qualcosa è andato storto. Riprova.'),
('it','common','auth.forgot_password','Hai dimenticato la password?'),
('it','common','auth.free_disclaimer','Piano gratuito disponibile. Nessuna carta di credito richiesta per provare.'),
('it','common','auth.free_note','Piano gratuito disponibile. Nessuna carta di credito richiesta per provare.'),
('it','common','auth.get_started','Inizia'),
('it','common','auth.invalid_credentials','Email o password errata. Controlla le credenziali o reimposta la password.'),
('it','common','auth.password_label','Password'),
('it','common','auth.password_placeholder','La tua password'),
('it','common','auth.password_rule_min_length','Min. 8 caratteri'),
('it','common','auth.password_rule_needs_number','Aggiungi un numero'),
('it','common','auth.password_rule_needs_uppercase','Aggiungi maiuscola'),
('it','common','auth.password_strength_fair','Discreta'),
('it','common','auth.password_strength_strong','Forte'),
('it','common','auth.password_strength_weak','Debole'),
('it','common','auth.password_too_short','La password deve essere di almeno 8 caratteri.'),
('it','common','auth.reset_failed','Impossibile inviare l''email di reimpostazione. Riprova.'),
('it','common','auth.reset_sending','Invio in corso…'),
('it','common','auth.reset_sent','Se quell''email esiste nel nostro sistema, è stato inviato un link di reimpostazione.'),
('it','common','auth.sending_reset','Invio in corso…'),
('it','common','auth.sign_in_tab','Accedi'),
('it','common','auth.signin_failed','Accesso non riuscito. Riprova.'),
('it','common','auth.signing_in','Accesso in corso…'),
('it','common','auth.signup_body','Scegli il tuo piano e configura il tuo account — ci vuole solo un minuto.'),
('it','common','auth.signup_prompt','Scegli il tuo piano e configura il tuo account — ci vuole solo un minuto.'),
('it','common','auth.tab_create','Crea account'),
('it','common','auth.tab_signin','Accedi'),
('it','common','auth.tagline','Cura più chiara, insieme.'),
('it','common','auth.welcome_to','Benvenuto su'),
('it','common','create_account.agree_prefix','Creando un account accetti i nostri'),
('it','common','create_account.already_have','Hai già un account?'),
('it','common','create_account.always_free','Sempre gratuito'),
('it','common','create_account.cancel_note','. Annulla quando vuoi.'),
('it','common','create_account.choose_plan','Scegli il tuo piano'),
('it','common','create_account.confirm_email_info','Controlla la tua email per confermare l''account, poi torna qui per completare il pagamento.'),
('it','common','create_account.confirm_password_label','Conferma password'),
('it','common','create_account.confirm_password_placeholder','Reinserisci la password'),
('it','common','create_account.email_required','Email e password sono obbligatorie.'),
('it','common','create_account.email_taken','Esiste già un account con questa email. Accedi.'),
('it','common','create_account.incomplete_setup_notice','Il tuo account è stato creato ma la configurazione non è stata completata. Scegli un piano qui sotto per continuare.'),
('it','common','create_account.loading','Caricamento…'),
('it','common','create_account.name_label','Nome completo'),
('it','common','create_account.name_placeholder','Il tuo nome completo'),
('it','common','create_account.obs_family','Osservazioni illimitate, fino a 5 caregiver'),
('it','common','create_account.obs_free','Fino a 10 osservazioni al mese'),
('it','common','create_account.obs_primary','Osservazioni illimitate, 1 caregiver'),
('it','common','create_account.password_placeholder','Crea una password'),
('it','common','create_account.password_too_short','La password deve essere di almeno 8 caratteri.'),
('it','common','create_account.passwords_mismatch','Le password non corrispondono.'),
('it','common','create_account.per_quarter','al trimestre'),
('it','common','create_account.plan_missing_price','Questo piano non è disponibile per l''acquisto al momento. Contatta il supporto.'),
('it','common','create_account.promo_label','Codice promo'),
('it','common','create_account.promo_placeholder','Inserisci il codice promo'),
('it','common','create_account.promo_prefix','Promo:'),
('it','common','create_account.section_title','Dettagli del tuo account'),
('it','common','create_account.selected_plan','Piano selezionato:'),
('it','common','create_account.signup_failed','Registrazione non riuscita. Riprova.'),
('it','common','create_account.submit_btn','Crea account'),
('it','common','create_account.subtitle','Configura il tuo account e inizia a registrare oggi.'),
('it','common','create_account.title','Crea il tuo account'),

-- ============================================================
-- SWEDISH (sv)
-- ============================================================
('sv','common','auth.create_account_link','Skapa konto'),
('sv','common','auth.create_account_tab','Skapa konto'),
('sv','common','auth.email_first','Ange din e-postadress ovan först.'),
('sv','common','auth.email_label','E-postadress'),
('sv','common','auth.email_placeholder','din.email@exempel.se'),
('sv','common','auth.err_email_first','Ange din e-postadress ovan först.'),
('sv','common','auth.err_invalid_creds','Fel e-post eller lösenord. Kontrollera dina uppgifter eller återställ ditt lösenord.'),
('sv','common','auth.err_password_short','Lösenordet måste vara minst 8 tecken.'),
('sv','common','auth.failed','Något gick fel. Försök igen.'),
('sv','common','auth.forgot_password','Glömt lösenordet?'),
('sv','common','auth.free_disclaimer','Gratisplan tillgänglig. Inget kreditkort krävs för att prova.'),
('sv','common','auth.free_note','Gratisplan tillgänglig. Inget kreditkort krävs för att prova.'),
('sv','common','auth.get_started','Kom igång'),
('sv','common','auth.invalid_credentials','Fel e-post eller lösenord. Kontrollera dina uppgifter eller återställ ditt lösenord.'),
('sv','common','auth.password_label','Lösenord'),
('sv','common','auth.password_placeholder','Ditt lösenord'),
('sv','common','auth.password_rule_min_length','Min 8 tecken'),
('sv','common','auth.password_rule_needs_number','Lägg till en siffra'),
('sv','common','auth.password_rule_needs_uppercase','Lägg till versal'),
('sv','common','auth.password_strength_fair','Godkänd'),
('sv','common','auth.password_strength_strong','Stark'),
('sv','common','auth.password_strength_weak','Svag'),
('sv','common','auth.password_too_short','Lösenordet måste vara minst 8 tecken.'),
('sv','common','auth.reset_failed','Det gick inte att skicka återställningsmail. Försök igen.'),
('sv','common','auth.reset_sending','Skickar…'),
('sv','common','auth.reset_sent','Om den e-postadressen finns i vårt system har en återställningslänk skickats.'),
('sv','common','auth.sending_reset','Skickar…'),
('sv','common','auth.sign_in_tab','Logga in'),
('sv','common','auth.signin_failed','Inloggningen misslyckades. Försök igen.'),
('sv','common','auth.signing_in','Loggar in…'),
('sv','common','auth.signup_body','Välj ditt abonnemang och konfigurera ditt vårdkonto — det tar bara en minut.'),
('sv','common','auth.signup_prompt','Välj ditt abonnemang och konfigurera ditt vårdkonto — det tar bara en minut.'),
('sv','common','auth.tab_create','Skapa konto'),
('sv','common','auth.tab_signin','Logga in'),
('sv','common','auth.tagline','Tydligare vård, tillsammans.'),
('sv','common','auth.welcome_to','Välkommen till'),
('sv','common','create_account.agree_prefix','Genom att skapa ett konto godkänner du våra'),
('sv','common','create_account.already_have','Har du redan ett konto?'),
('sv','common','create_account.always_free','Alltid gratis'),
('sv','common','create_account.cancel_note','. Avsluta när som helst.'),
('sv','common','create_account.choose_plan','Välj ditt abonnemang'),
('sv','common','create_account.confirm_email_info','Kontrollera din e-post för att bekräfta ditt konto och återvänd sedan hit för att slutföra betalningen.'),
('sv','common','create_account.confirm_password_label','Bekräfta lösenord'),
('sv','common','create_account.confirm_password_placeholder','Ange lösenordet igen'),
('sv','common','create_account.email_required','E-post och lösenord krävs.'),
('sv','common','create_account.email_taken','Det finns redan ett konto med den e-postadressen. Logga in.'),
('sv','common','create_account.incomplete_setup_notice','Ditt konto skapades men konfigurationen slutfördes inte. Välj ett abonnemang nedan för att fortsätta.'),
('sv','common','create_account.loading','Laddar…'),
('sv','common','create_account.name_label','Fullständigt namn'),
('sv','common','create_account.name_placeholder','Ditt fullständiga namn'),
('sv','common','create_account.obs_family','Obegränsade observationer, upp till 5 vårdgivare'),
('sv','common','create_account.obs_free','Upp till 10 observationer per månad'),
('sv','common','create_account.obs_primary','Obegränsade observationer, 1 vårdgivare'),
('sv','common','create_account.password_placeholder','Skapa ett lösenord'),
('sv','common','create_account.password_too_short','Lösenordet måste vara minst 8 tecken.'),
('sv','common','create_account.passwords_mismatch','Lösenorden stämmer inte överens.'),
('sv','common','create_account.per_quarter','per kvartal'),
('sv','common','create_account.plan_missing_price','Det här abonnemanget är inte tillgängligt för köp just nu. Kontakta support.'),
('sv','common','create_account.promo_label','Kampanjkod'),
('sv','common','create_account.promo_placeholder','Ange kampanjkod'),
('sv','common','create_account.promo_prefix','Promo:'),
('sv','common','create_account.section_title','Dina kontouppgifter'),
('sv','common','create_account.selected_plan','Valt abonnemang:'),
('sv','common','create_account.signup_failed','Registreringen misslyckades. Försök igen.'),
('sv','common','create_account.submit_btn','Skapa konto'),
('sv','common','create_account.subtitle','Konfigurera ditt konto och börja spåra idag.'),
('sv','common','create_account.title','Skapa ditt konto'),

-- ============================================================
-- FINNISH (fi)
-- ============================================================
('fi','common','auth.create_account_link','Luo tili'),
('fi','common','auth.create_account_tab','Luo tili'),
('fi','common','auth.email_first','Syötä ensin sähköpostiosoitteesi.'),
('fi','common','auth.email_label','Sähköpostiosoite'),
('fi','common','auth.email_placeholder','sinun.email@esimerkki.fi'),
('fi','common','auth.err_email_first','Syötä ensin sähköpostiosoitteesi.'),
('fi','common','auth.err_invalid_creds','Väärä sähköposti tai salasana. Tarkista tietosi tai nollaa salasanasi.'),
('fi','common','auth.err_password_short','Salasanan on oltava vähintään 8 merkkiä.'),
('fi','common','auth.failed','Jotain meni pieleen. Yritä uudelleen.'),
('fi','common','auth.forgot_password','Unohditko salasanasi?'),
('fi','common','auth.free_disclaimer','Ilmainen suunnitelma saatavilla. Ei luottokorttia tarvita kokeiluun.'),
('fi','common','auth.free_note','Ilmainen suunnitelma saatavilla. Ei luottokorttia tarvita kokeiluun.'),
('fi','common','auth.get_started','Aloita'),
('fi','common','auth.invalid_credentials','Väärä sähköposti tai salasana. Tarkista tietosi tai nollaa salasanasi.'),
('fi','common','auth.password_label','Salasana'),
('fi','common','auth.password_placeholder','Salasanasi'),
('fi','common','auth.password_rule_min_length','Väh. 8 merkkiä'),
('fi','common','auth.password_rule_needs_number','Lisää numero'),
('fi','common','auth.password_rule_needs_uppercase','Lisää iso kirjain'),
('fi','common','auth.password_strength_fair','Kohtalainen'),
('fi','common','auth.password_strength_strong','Vahva'),
('fi','common','auth.password_strength_weak','Heikko'),
('fi','common','auth.password_too_short','Salasanan on oltava vähintään 8 merkkiä.'),
('fi','common','auth.reset_failed','Nollaussähköpostin lähettäminen epäonnistui. Yritä uudelleen.'),
('fi','common','auth.reset_sending','Lähetetään…'),
('fi','common','auth.reset_sent','Jos sähköpostiosoite on järjestelmässämme, nollauslinkki on lähetetty.'),
('fi','common','auth.sending_reset','Lähetetään…'),
('fi','common','auth.sign_in_tab','Kirjaudu sisään'),
('fi','common','auth.signin_failed','Kirjautuminen epäonnistui. Yritä uudelleen.'),
('fi','common','auth.signing_in','Kirjaudutaan sisään…'),
('fi','common','auth.signup_body','Valitse suunnitelmasi ja aseta hoitajatilisi — se kestää vain minuutin.'),
('fi','common','auth.signup_prompt','Valitse suunnitelmasi ja aseta hoitajatilisi — se kestää vain minuutin.'),
('fi','common','auth.tab_create','Luo tili'),
('fi','common','auth.tab_signin','Kirjaudu sisään'),
('fi','common','auth.tagline','Selkeämpää hoitoa, yhdessä.'),
('fi','common','auth.welcome_to','Tervetuloa'),
('fi','common','create_account.agree_prefix','Luomalla tilin hyväksyt'),
('fi','common','create_account.already_have','Onko sinulla jo tili?'),
('fi','common','create_account.always_free','Aina ilmainen'),
('fi','common','create_account.cancel_note','. Peruuta milloin tahansa.'),
('fi','common','create_account.choose_plan','Valitse suunnitelmasi'),
('fi','common','create_account.confirm_email_info','Tarkista sähköpostisi tilin vahvistamiseksi, palaa sitten tänne maksun viimeistelemiseksi.'),
('fi','common','create_account.confirm_password_label','Vahvista salasana'),
('fi','common','create_account.confirm_password_placeholder','Syötä salasana uudelleen'),
('fi','common','create_account.email_required','Sähköposti ja salasana ovat pakollisia.'),
('fi','common','create_account.email_taken','Tili tällä sähköpostilla on jo olemassa. Kirjaudu sisään.'),
('fi','common','create_account.incomplete_setup_notice','Tilisi on luotu, mutta asetuksia ei ole suoritettu loppuun. Valitse suunnitelma alla jatkaaksesi.'),
('fi','common','create_account.loading','Ladataan…'),
('fi','common','create_account.name_label','Koko nimi'),
('fi','common','create_account.name_placeholder','Koko nimesi'),
('fi','common','create_account.obs_family','Rajattomat havainnot, enintään 5 hoitajaa'),
('fi','common','create_account.obs_free','Enintään 10 havaintoa kuukaudessa'),
('fi','common','create_account.obs_primary','Rajattomat havainnot, 1 hoitaja'),
('fi','common','create_account.password_placeholder','Luo salasana'),
('fi','common','create_account.password_too_short','Salasanan on oltava vähintään 8 merkkiä.'),
('fi','common','create_account.passwords_mismatch','Salasanat eivät täsmää.'),
('fi','common','create_account.per_quarter','neljännesvuosittain'),
('fi','common','create_account.plan_missing_price','Tämä suunnitelma ei ole tällä hetkellä ostettavissa. Ota yhteyttä tukeen.'),
('fi','common','create_account.promo_label','Promokoodi'),
('fi','common','create_account.promo_placeholder','Syötä promokoodi'),
('fi','common','create_account.promo_prefix','Promo:'),
('fi','common','create_account.section_title','Tilisi tiedot'),
('fi','common','create_account.selected_plan','Valittu suunnitelma:'),
('fi','common','create_account.signup_failed','Rekisteröinti epäonnistui. Yritä uudelleen.'),
('fi','common','create_account.submit_btn','Luo tili'),
('fi','common','create_account.subtitle','Aseta tilisi ja aloita seuranta tänään.'),
('fi','common','create_account.title','Luo tilisi'),

-- ============================================================
-- JAPANESE (ja)
-- ============================================================
('ja','common','auth.create_account_link','アカウントを作成'),
('ja','common','auth.create_account_tab','アカウントを作成'),
('ja','common','auth.email_first','まずメールアドレスを入力してください。'),
('ja','common','auth.email_label','メールアドレス'),
('ja','common','auth.email_placeholder','your.email@example.com'),
('ja','common','auth.err_email_first','まずメールアドレスを入力してください。'),
('ja','common','auth.err_invalid_creds','メールアドレスまたはパスワードが正しくありません。認証情報を確認するか、パスワードをリセットしてください。'),
('ja','common','auth.err_password_short','パスワードは8文字以上である必要があります。'),
('ja','common','auth.failed','エラーが発生しました。もう一度お試しください。'),
('ja','common','auth.forgot_password','パスワードをお忘れですか？'),
('ja','common','auth.free_disclaimer','無料プランあり。試用にクレジットカード不要。'),
('ja','common','auth.free_note','無料プランあり。試用にクレジットカード不要。'),
('ja','common','auth.get_started','始める'),
('ja','common','auth.invalid_credentials','メールアドレスまたはパスワードが正しくありません。認証情報を確認するか、パスワードをリセットしてください。'),
('ja','common','auth.password_label','パスワード'),
('ja','common','auth.password_placeholder','パスワード'),
('ja','common','auth.password_rule_min_length','8文字以上'),
('ja','common','auth.password_rule_needs_number','数字を追加'),
('ja','common','auth.password_rule_needs_uppercase','大文字を追加'),
('ja','common','auth.password_strength_fair','普通'),
('ja','common','auth.password_strength_strong','強い'),
('ja','common','auth.password_strength_weak','弱い'),
('ja','common','auth.password_too_short','パスワードは8文字以上である必要があります。'),
('ja','common','auth.reset_failed','リセットメールの送信に失敗しました。もう一度お試しください。'),
('ja','common','auth.reset_sending','送信中…'),
('ja','common','auth.reset_sent','そのメールアドレスがシステムに存在する場合、リセットリンクが送信されました。'),
('ja','common','auth.sending_reset','送信中…'),
('ja','common','auth.sign_in_tab','ログイン'),
('ja','common','auth.signin_failed','ログインに失敗しました。もう一度お試しください。'),
('ja','common','auth.signing_in','ログイン中…'),
('ja','common','auth.signup_body','プランを選択してケアアカウントを設定してください — たった1分で完了します。'),
('ja','common','auth.signup_prompt','プランを選択してケアアカウントを設定してください — たった1分で完了します。'),
('ja','common','auth.tab_create','アカウントを作成'),
('ja','common','auth.tab_signin','ログイン'),
('ja','common','auth.tagline','より明確なケアを、一緒に。'),
('ja','common','auth.welcome_to','ようこそ'),
('ja','common','create_account.agree_prefix','アカウントを作成することで、'),
('ja','common','create_account.already_have','すでにアカウントをお持ちですか？'),
('ja','common','create_account.always_free','常に無料'),
('ja','common','create_account.cancel_note','。いつでもキャンセル可能。'),
('ja','common','create_account.choose_plan','プランを選択'),
('ja','common','create_account.confirm_email_info','メールを確認してアカウントを認証し、その後こちらに戻って支払いを完了してください。'),
('ja','common','create_account.confirm_password_label','パスワードの確認'),
('ja','common','create_account.confirm_password_placeholder','パスワードを再入力'),
('ja','common','create_account.email_required','メールアドレスとパスワードは必須です。'),
('ja','common','create_account.email_taken','そのメールアドレスのアカウントはすでに存在します。ログインしてください。'),
('ja','common','create_account.incomplete_setup_notice','アカウントは作成されましたが、設定が完了していません。続行するには以下のプランを選択してください。'),
('ja','common','create_account.loading','読み込み中…'),
('ja','common','create_account.name_label','氏名'),
('ja','common','create_account.name_placeholder','フルネーム'),
('ja','common','create_account.obs_family','無制限の観察、最大5名のケアギバー'),
('ja','common','create_account.obs_free','月最大10回の観察'),
('ja','common','create_account.obs_primary','無制限の観察、ケアギバー1名'),
('ja','common','create_account.password_placeholder','パスワードを作成'),
('ja','common','create_account.password_too_short','パスワードは8文字以上である必要があります。'),
('ja','common','create_account.passwords_mismatch','パスワードが一致しません。'),
('ja','common','create_account.per_quarter','四半期ごと'),
('ja','common','create_account.plan_missing_price','このプランは現在購入できません。サポートにお問い合わせください。'),
('ja','common','create_account.promo_label','プロモコード'),
('ja','common','create_account.promo_placeholder','プロモコードを入力'),
('ja','common','create_account.promo_prefix','プロモ：'),
('ja','common','create_account.section_title','アカウント詳細'),
('ja','common','create_account.selected_plan','選択したプラン：'),
('ja','common','create_account.signup_failed','登録に失敗しました。もう一度お試しください。'),
('ja','common','create_account.submit_btn','アカウントを作成'),
('ja','common','create_account.subtitle','アカウントを設定して今日から記録を始めましょう。'),
('ja','common','create_account.title','アカウントを作成')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
