
INSERT INTO ui_translations (locale, namespace, key, value)
VALUES
  ('es', 'common', 'obs_edit.form_adl',             'AVD'),
  ('es', 'common', 'obs_edit.form_iadl',            'AIVD'),
  ('es', 'common', 'obs_edit.form_comprehensive',   'Integral'),
  ('es', 'common', 'obs_edit.observation_label',    'Observación'),
  ('es', 'common', 'obs_edit.readonly_notice',      'Estás viendo esta observación en modo de solo lectura porque no eres el autor.'),
  ('es', 'common', 'obs_edit.frozen_notice',        'Tu cuenta ha sido suspendida. No puedes editar observaciones en este momento.'),
  ('es', 'common', 'obs_edit.render_error',         'Algo salió mal al cargar esta observación.'),
  ('es', 'common', 'obs_edit.render_error_detail',  'Por favor, actualiza la página o vuelve al panel.'),
  ('es', 'common', 'obs_form.comprehensive_label',  'Integral (AVD + AIVD)'),
  ('fr', 'common', 'obs_edit.form_adl',             'AVQ'),
  ('fr', 'common', 'obs_edit.form_iadl',            'AIVQ'),
  ('fr', 'common', 'obs_edit.form_comprehensive',   'Complet'),
  ('fr', 'common', 'obs_edit.observation_label',    'Observation'),
  ('fr', 'common', 'obs_edit.readonly_notice',      'Vous consultez cette observation en lecture seule car vous n''en êtes pas l''auteur.'),
  ('fr', 'common', 'obs_edit.frozen_notice',        'Votre compte a été suspendu. Vous ne pouvez pas modifier les observations pour le moment.'),
  ('fr', 'common', 'obs_edit.render_error',         'Un problème est survenu lors du chargement de cette observation.'),
  ('fr', 'common', 'obs_edit.render_error_detail',  'Veuillez actualiser la page ou retourner au tableau de bord.'),
  ('fr', 'common', 'obs_form.comprehensive_label',  'Complet (AVQ + AIVQ)'),
  ('de', 'common', 'obs_edit.form_adl',             'ADL'),
  ('de', 'common', 'obs_edit.form_iadl',            'IADL'),
  ('de', 'common', 'obs_edit.form_comprehensive',   'Umfassend'),
  ('de', 'common', 'obs_edit.observation_label',    'Beobachtung'),
  ('de', 'common', 'obs_edit.readonly_notice',      'Sie sehen diese Beobachtung im Nur-Lese-Modus, da Sie nicht der Autor sind.'),
  ('de', 'common', 'obs_edit.frozen_notice',        'Ihr Konto wurde gesperrt. Sie können derzeit keine Beobachtungen bearbeiten.'),
  ('de', 'common', 'obs_edit.render_error',         'Beim Laden dieser Beobachtung ist ein Fehler aufgetreten.'),
  ('de', 'common', 'obs_edit.render_error_detail',  'Bitte aktualisieren Sie die Seite oder kehren Sie zum Dashboard zurück.'),
  ('de', 'common', 'obs_form.comprehensive_label',  'Umfassend (ADL + IADL)'),
  ('it', 'common', 'obs_edit.form_adl',             'ADL'),
  ('it', 'common', 'obs_edit.form_iadl',            'IADL'),
  ('it', 'common', 'obs_edit.form_comprehensive',   'Completo'),
  ('it', 'common', 'obs_edit.observation_label',    'Osservazione'),
  ('it', 'common', 'obs_edit.readonly_notice',      'Stai visualizzando questa osservazione in modalità di sola lettura perché non sei l''autore.'),
  ('it', 'common', 'obs_edit.frozen_notice',        'Il tuo account è stato sospeso. Non puoi modificare le osservazioni al momento.'),
  ('it', 'common', 'obs_edit.render_error',         'Si è verificato un problema durante il caricamento di questa osservazione.'),
  ('it', 'common', 'obs_edit.render_error_detail',  'Aggiorna la pagina o torna alla dashboard.'),
  ('it', 'common', 'obs_form.comprehensive_label',  'Completo (ADL + IADL)'),
  ('sv', 'common', 'obs_edit.form_adl',             'ADL'),
  ('sv', 'common', 'obs_edit.form_iadl',            'IADL'),
  ('sv', 'common', 'obs_edit.form_comprehensive',   'Övergripande'),
  ('sv', 'common', 'obs_edit.observation_label',    'Observation'),
  ('sv', 'common', 'obs_edit.readonly_notice',      'Du visar denna observation i skrivskyddat läge eftersom du inte är författaren.'),
  ('sv', 'common', 'obs_edit.frozen_notice',        'Ditt konto har stängts av. Du kan inte redigera observationer just nu.'),
  ('sv', 'common', 'obs_edit.render_error',         'Något gick fel när observationen laddades.'),
  ('sv', 'common', 'obs_edit.render_error_detail',  'Uppdatera sidan eller gå tillbaka till instrumentpanelen.'),
  ('sv', 'common', 'obs_form.comprehensive_label',  'Övergripande (ADL + IADL)'),
  ('fi', 'common', 'obs_edit.form_adl',             'ADL'),
  ('fi', 'common', 'obs_edit.form_iadl',            'IADL'),
  ('fi', 'common', 'obs_edit.form_comprehensive',   'Kattava'),
  ('fi', 'common', 'obs_edit.observation_label',    'Havainto'),
  ('fi', 'common', 'obs_edit.readonly_notice',      'Katselet tätä havaintoa vain luku -tilassa, koska et ole sen tekijä.'),
  ('fi', 'common', 'obs_edit.frozen_notice',        'Tilisi on jäädytetty. Et voi muokata havaintoja tällä hetkellä.'),
  ('fi', 'common', 'obs_edit.render_error',         'Havainnon lataaminen epäonnistui.'),
  ('fi', 'common', 'obs_edit.render_error_detail',  'Päivitä sivu tai palaa kojelautaan.'),
  ('fi', 'common', 'obs_form.comprehensive_label',  'Kattava (ADL + IADL)')
ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
