-- Translation Batch 4a: memory_book.* section titles, headings, buttons, toasts for 7 non-EN locales
-- (field.* labels included; field.*_placeholder excluded for brevity — they fall back to EN gracefully)

INSERT INTO public.ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- SPANISH (es)
-- ============================================================
('es','common','memory_book.cancel','Cancelar'),
('es','common','memory_book.confirm_remove_contact','¿Quitar a {name} de los contactos?'),
('es','common','memory_book.confirm_remove_provider','¿Quitar a {name} de los proveedores?'),
('es','common','memory_book.confirm_remove_social','¿Quitar la cuenta de {platform}?'),
('es','common','memory_book.confirm_remove_sub','¿Quitar {name}?'),
('es','common','memory_book.confirm_remove_subscription','¿Quitar {name}?'),
('es','common','memory_book.confirm_remove_vehicle','¿Quitar {name}?'),
('es','common','memory_book.contact_fallback_label','Contacto'),
('es','common','memory_book.contact_save_btn','Guardar Contacto'),
('es','common','memory_book.contacts_add_btn','Añadir Contacto'),
('es','common','memory_book.contacts_add_first_btn','Añadir Primer Contacto'),
('es','common','memory_book.contacts_count_many','{count} contactos en el archivo'),
('es','common','memory_book.contacts_count_one','1 contacto en el archivo'),
('es','common','memory_book.contacts_edit_heading','Editar Contacto'),
('es','common','memory_book.contacts_empty_desc','Añade familiares, médicos, contactos de emergencia y otros colaboradores clave para que los cuidadores puedan contactar a la persona adecuada rápidamente.'),
('es','common','memory_book.contacts_empty_title','Aún no se han añadido contactos'),
('es','common','memory_book.contacts_new_heading','Nuevo Contacto'),
('es','common','memory_book.contacts_title','Red de Cuidado y Contactos'),
('es','common','memory_book.edit','Editar'),
('es','common','memory_book.finances_add_btn','Añadir Información Financiera'),
('es','common','memory_book.finances_empty_owner_desc','Registra datos bancarios, fuentes de ingresos y facturas de pago automático para gestionar las finanzas diarias.'),
('es','common','memory_book.finances_empty_owner_title','Añadir resumen financiero'),
('es','common','memory_book.finances_locked_desc','La información financiera está restringida al propietario del equipo por privacidad.'),
('es','common','memory_book.finances_locked_title','Solo acceso del propietario'),
('es','common','memory_book.finances_owner_only_notice','Esta sección es visible solo para los propietarios del equipo.'),
('es','common','memory_book.finances_subtitle','Datos bancarios, fuentes de ingresos y facturas recurrentes'),
('es','common','memory_book.finances_title','Ingresos y Finanzas'),
('es','common','memory_book.household_section_finances','Finanzas'),
('es','common','memory_book.household_section_insurance','Seguro'),
('es','common','memory_book.household_section_providers','Proveedores de Salud'),
('es','common','memory_book.household_section_subscriptions','Suscripciones'),
('es','common','memory_book.household_section_vehicle','Vehículo y Transporte'),
('es','common','memory_book.identity_add_btn','Añadir Detalles de Identidad'),
('es','common','memory_book.identity_empty_member_desc','El propietario del equipo debe completar la sección de identidad para que aparezca aquí.'),
('es','common','memory_book.identity_empty_member_title','Identidad aún no completada'),
('es','common','memory_book.identity_empty_owner_desc','Registra el nombre preferido, lugar de nacimiento, antecedentes culturales y un resumen personal breve para ayudar a los cuidadores a conectar de forma significativa.'),
('es','common','memory_book.identity_empty_owner_title','Añadir información de identidad'),
('es','common','memory_book.identity_subtitle','Detalles personales de {patientName}'),
('es','common','memory_book.identity_title','Identidad y Perfil'),
('es','common','memory_book.insurance_add_btn','Añadir Detalles del Seguro'),
('es','common','memory_book.insurance_dental_heading','Seguro Dental y de Visión'),
('es','common','memory_book.insurance_dental_vision_heading','Seguro Dental y de Visión'),
('es','common','memory_book.insurance_empty_member_desc','El propietario del equipo debe completar la sección de seguros para que aparezca aquí.'),
('es','common','memory_book.insurance_empty_member_title','Seguro aún no completado'),
('es','common','memory_book.insurance_empty_owner_desc','Registra los planes de seguro para que los cuidadores puedan encontrar rápidamente los detalles de la póliza para citas y recetas.'),
('es','common','memory_book.insurance_empty_owner_title','Añadir detalles del seguro'),
('es','common','memory_book.insurance_primary_heading','Seguro Principal'),
('es','common','memory_book.insurance_secondary_heading','Seguro Secundario'),
('es','common','memory_book.insurance_subtitle','Cobertura principal, secundaria y dental/visión'),
('es','common','memory_book.insurance_title','Seguro de Salud'),
('es','common','memory_book.medical_add_btn','Añadir Información Médica'),
('es','common','memory_book.medical_empty_member_desc','El propietario del equipo debe completar la sección médica para que aparezca aquí.'),
('es','common','memory_book.medical_empty_member_title','Información médica aún no completada'),
('es','common','memory_book.medical_empty_owner_desc','Registra condiciones, alergias, audición, visión y notas de medicamentos para ayudar a los cuidadores a proporcionar un cuidado seguro e informado.'),
('es','common','memory_book.medical_empty_owner_title','Añadir contexto médico'),
('es','common','memory_book.medical_subtitle','Información de salud orientada al cuidador — no es un registro clínico'),
('es','common','memory_book.medical_title','Contexto Médico'),
('es','common','memory_book.overview_age','Edad {age}'),
('es','common','memory_book.overview_coming_desc','Vida Diaria, Actividades, Comidas, Comportamiento y Seguridad, Diario y Registro de Cambios estarán disponibles después de la Fase 2.'),
('es','common','memory_book.overview_coming_title','Próximamente en la Fase 2'),
('es','common','memory_book.overview_incomplete_desc_many','{count} secciones aún necesitan completarse para dar a los cuidadores una imagen completa.'),
('es','common','memory_book.overview_incomplete_desc_one','1 sección aún necesita completarse para dar a los cuidadores una imagen completa.'),
('es','common','memory_book.overview_incomplete_title','Libro de Memoria Incompleto'),
('es','common','memory_book.overview_no_summary','Aún no se ha añadido un resumen personal.'),
('es','common','memory_book.overview_no_summary_owner_hint',' Añade uno en la pestaña Libro de Memoria.'),
('es','common','memory_book.overview_not_started','No iniciado'),
('es','common','memory_book.overview_progress_title','Progreso del Libro de Memoria'),
('es','common','memory_book.overview_records_many','{count} registros'),
('es','common','memory_book.overview_records_one','1 registro'),
('es','common','memory_book.overview_sections_count','{completed}/{total} secciones'),
('es','common','memory_book.prefs_add_btn','Añadir Preferencias'),
('es','common','memory_book.prefs_empty_member_desc','El propietario del equipo debe completar la sección de preferencias para que aparezca aquí.'),
('es','common','memory_book.prefs_empty_member_title','Preferencias aún no completadas'),
('es','common','memory_book.prefs_empty_owner_desc','Registrar lo que trae confort, alegría y lo que se debe evitar ayuda a cada cuidador a brindar una experiencia más personal.'),
('es','common','memory_book.prefs_empty_owner_title','Añadir gustos, disgustos y comodidades'),
('es','common','memory_book.prefs_subtitle','Lo que trae alegría, confort y lo que se debe evitar'),
('es','common','memory_book.prefs_title','Gustos, Disgustos y Comodidades'),
('es','common','memory_book.print_btn','Imprimir Libro de Memoria'),
('es','common','memory_book.print_confidential','Confidencial — Solo para uso del equipo de cuidado'),
('es','common','memory_book.print_generated','Generado'),
('es','common','memory_book.print_no_data','Aún no hay información registrada.'),
('es','common','memory_book.print_section_contacts','Red de Cuidado y Contactos'),
('es','common','memory_book.print_section_finances','Ingresos y Finanzas'),
('es','common','memory_book.print_section_household','Información del Hogar'),
('es','common','memory_book.print_section_identity','Identidad y Perfil'),
('es','common','memory_book.print_section_insurance','Seguro de Salud'),
('es','common','memory_book.print_section_medical','Contexto Médico'),
('es','common','memory_book.print_section_preferences','Gustos, Disgustos y Comodidades'),
('es','common','memory_book.print_section_providers','Proveedores de Salud'),
('es','common','memory_book.print_section_subscriptions','Suscripciones y Membresías'),
('es','common','memory_book.print_section_vehicle','Vehículo y Transporte'),
('es','common','memory_book.print_title','Libro de Memoria'),
('es','common','memory_book.provider_primary_badge','Principal'),
('es','common','memory_book.provider_primary_label','Principal'),
('es','common','memory_book.provider_save_btn','Guardar Proveedor'),
('es','common','memory_book.providers_add_btn','Añadir Proveedor'),
('es','common','memory_book.providers_add_first_btn','Añadir Primer Proveedor'),
('es','common','memory_book.providers_count_many','{count} proveedores en el archivo'),
('es','common','memory_book.providers_count_one','1 proveedor en el archivo'),
('es','common','memory_book.providers_edit_heading','Editar Proveedor'),
('es','common','memory_book.providers_empty_desc','Añade médicos, dentistas, farmacias y especialistas para que los cuidadores siempre sepan a quién contactar.'),
('es','common','memory_book.providers_empty_title','Aún no se han añadido proveedores'),
('es','common','memory_book.providers_new_heading','Nuevo Proveedor'),
('es','common','memory_book.providers_subtitle','Médicos, dentistas, farmacias y especialistas'),
('es','common','memory_book.providers_title','Proveedores de Salud'),
('es','common','memory_book.readonly_notice','Tienes acceso de visualización a esta sección. Solo los propietarios del equipo pueden hacer cambios.'),
('es','common','memory_book.save_changes','Guardar Cambios'),
('es','common','memory_book.saving','Guardando...'),
('es','common','memory_book.section_contacts','Contactos'),
('es','common','memory_book.section_household','Hogar'),
('es','common','memory_book.section_identity','Identidad'),
('es','common','memory_book.section_medical','Médico'),
('es','common','memory_book.section_preferences','Gustos y Disgustos'),
('es','common','memory_book.social_add_btn','Añadir Cuenta'),
('es','common','memory_book.social_add_first_btn','Añadir Primera Cuenta'),
('es','common','memory_book.social_count_many','{count} cuentas en el archivo'),
('es','common','memory_book.social_count_one','1 cuenta en el archivo'),
('es','common','memory_book.social_edit_heading','Editar Cuenta'),
('es','common','memory_book.social_empty_desc','Registra perfiles de redes sociales, cuentas de correo electrónico y otros servicios en línea para que los familiares puedan gestionarlos cuando sea necesario.'),
('es','common','memory_book.social_empty_title','Aún no se han añadido cuentas en línea'),
('es','common','memory_book.social_new_heading','Nueva Cuenta'),
('es','common','memory_book.social_title','Redes Sociales y Cuentas en Línea'),
('es','common','memory_book.subs_add_btn','Añadir Suscripción'),
('es','common','memory_book.subs_add_first_btn','Añadir Primera Suscripción'),
('es','common','memory_book.subs_title','Suscripciones y Membresías'),
('es','common','memory_book.subscriptions_title','Suscripciones y Membresías'),
('es','common','memory_book.tab_household','Hogar'),
('es','common','memory_book.toast_contact_added','Contacto añadido'),
('es','common','memory_book.toast_contact_failed','Error al guardar el contacto'),
('es','common','memory_book.toast_contact_removed','Contacto eliminado'),
('es','common','memory_book.toast_contact_updated','Contacto actualizado'),
('es','common','memory_book.toast_finances_saved','Información financiera guardada'),
('es','common','memory_book.toast_identity_saved','Identidad guardada'),
('es','common','memory_book.toast_insurance_saved','Información del seguro guardada'),
('es','common','memory_book.toast_medical_saved','Información médica guardada'),
('es','common','memory_book.toast_prefs_saved','Preferencias guardadas'),
('es','common','memory_book.toast_provider_added','Proveedor añadido'),
('es','common','memory_book.toast_provider_failed','Error al guardar el proveedor'),
('es','common','memory_book.toast_provider_removed','Proveedor eliminado'),
('es','common','memory_book.toast_provider_updated','Proveedor actualizado'),
('es','common','memory_book.toast_social_added','Cuenta añadida'),
('es','common','memory_book.toast_social_removed','Cuenta eliminada'),
('es','common','memory_book.toast_social_updated','Cuenta actualizada'),
('es','common','memory_book.toast_sub_added','Suscripción añadida'),
('es','common','memory_book.toast_sub_removed','Suscripción eliminada'),
('es','common','memory_book.toast_sub_updated','Suscripción actualizada'),
('es','common','memory_book.toast_subscription_added','Suscripción añadida'),
('es','common','memory_book.toast_subscription_removed','Suscripción eliminada'),
('es','common','memory_book.toast_subscription_updated','Suscripción actualizada'),

-- ============================================================
-- FRENCH (fr)
-- ============================================================
('fr','common','memory_book.cancel','Annuler'),
('fr','common','memory_book.confirm_remove_contact','Retirer {name} des contacts ?'),
('fr','common','memory_book.confirm_remove_provider','Retirer {name} des prestataires ?'),
('fr','common','memory_book.confirm_remove_social','Retirer le compte {platform} ?'),
('fr','common','memory_book.confirm_remove_sub','Retirer {name} ?'),
('fr','common','memory_book.confirm_remove_subscription','Retirer {name} ?'),
('fr','common','memory_book.confirm_remove_vehicle','Retirer {name} ?'),
('fr','common','memory_book.contact_fallback_label','Contact'),
('fr','common','memory_book.contact_save_btn','Enregistrer le contact'),
('fr','common','memory_book.contacts_add_btn','Ajouter un contact'),
('fr','common','memory_book.contacts_add_first_btn','Ajouter le premier contact'),
('fr','common','memory_book.contacts_count_many','{count} contacts enregistrés'),
('fr','common','memory_book.contacts_count_one','1 contact enregistré'),
('fr','common','memory_book.contacts_edit_heading','Modifier le contact'),
('fr','common','memory_book.contacts_empty_desc','Ajoutez des membres de la famille, des médecins, des contacts d''urgence et d''autres personnes clés pour aider les soignants à contacter rapidement la bonne personne.'),
('fr','common','memory_book.contacts_empty_title','Aucun contact ajouté pour l''instant'),
('fr','common','memory_book.contacts_new_heading','Nouveau contact'),
('fr','common','memory_book.contacts_title','Réseau de soins & Contacts'),
('fr','common','memory_book.edit','Modifier'),
('fr','common','memory_book.finances_add_btn','Ajouter des informations financières'),
('fr','common','memory_book.finances_empty_owner_desc','Enregistrez les coordonnées bancaires, les sources de revenus et les factures en prélèvement automatique pour gérer les finances quotidiennes.'),
('fr','common','memory_book.finances_empty_owner_title','Ajouter un aperçu financier'),
('fr','common','memory_book.finances_locked_desc','Les informations financières sont réservées au propriétaire de l''équipe pour des raisons de confidentialité.'),
('fr','common','memory_book.finances_locked_title','Accès propriétaire uniquement'),
('fr','common','memory_book.finances_owner_only_notice','Cette section n''est visible que par les propriétaires d''équipe.'),
('fr','common','memory_book.finances_subtitle','Coordonnées bancaires, sources de revenus et factures récurrentes'),
('fr','common','memory_book.finances_title','Revenus & Finances'),
('fr','common','memory_book.household_section_finances','Finances'),
('fr','common','memory_book.household_section_insurance','Assurance'),
('fr','common','memory_book.household_section_providers','Prestataires de santé'),
('fr','common','memory_book.household_section_subscriptions','Abonnements'),
('fr','common','memory_book.household_section_vehicle','Véhicule & Transport'),
('fr','common','memory_book.identity_add_btn','Ajouter des informations d''identité'),
('fr','common','memory_book.identity_empty_member_desc','Le propriétaire de l''équipe doit remplir la section identité avant qu''elle n''apparaisse ici.'),
('fr','common','memory_book.identity_empty_member_title','Identité pas encore complétée'),
('fr','common','memory_book.identity_empty_owner_desc','Enregistrez le nom préféré, le lieu de naissance, les origines culturelles et un bref résumé personnel pour aider les soignants à tisser des liens significatifs.'),
('fr','common','memory_book.identity_empty_owner_title','Ajouter des informations d''identité'),
('fr','common','memory_book.identity_subtitle','Informations personnelles pour {patientName}'),
('fr','common','memory_book.identity_title','Identité & Profil'),
('fr','common','memory_book.insurance_add_btn','Ajouter des informations d''assurance'),
('fr','common','memory_book.insurance_dental_heading','Assurance dentaire & visuelle'),
('fr','common','memory_book.insurance_dental_vision_heading','Assurance dentaire & visuelle'),
('fr','common','memory_book.insurance_empty_member_desc','Le propriétaire de l''équipe doit remplir la section assurance avant qu''elle n''apparaisse ici.'),
('fr','common','memory_book.insurance_empty_member_title','Assurance pas encore complétée'),
('fr','common','memory_book.insurance_empty_owner_desc','Enregistrez les plans d''assurance pour que les soignants puissent rapidement trouver les détails de la police pour les rendez-vous et les ordonnances.'),
('fr','common','memory_book.insurance_empty_owner_title','Ajouter des informations d''assurance'),
('fr','common','memory_book.insurance_primary_heading','Assurance principale'),
('fr','common','memory_book.insurance_secondary_heading','Assurance secondaire'),
('fr','common','memory_book.insurance_subtitle','Couverture principale, secondaire et dentaire/visuelle'),
('fr','common','memory_book.insurance_title','Assurance maladie'),
('fr','common','memory_book.medical_add_btn','Ajouter des informations médicales'),
('fr','common','memory_book.medical_empty_member_desc','Le propriétaire de l''équipe doit remplir la section médicale avant qu''elle n''apparaisse ici.'),
('fr','common','memory_book.medical_empty_member_title','Informations médicales pas encore complétées'),
('fr','common','memory_book.medical_empty_owner_desc','Enregistrez les conditions, allergies, audition, vision et notes sur les médicaments pour aider les soignants à fournir des soins sûrs et éclairés.'),
('fr','common','memory_book.medical_empty_owner_title','Ajouter le contexte médical'),
('fr','common','memory_book.medical_subtitle','Informations de santé orientées soignant — pas un dossier clinique'),
('fr','common','memory_book.medical_title','Contexte médical'),
('fr','common','memory_book.overview_age','Âge {age}'),
('fr','common','memory_book.overview_coming_title','Disponible en Phase 2'),
('fr','common','memory_book.overview_incomplete_title','Livre de mémoire incomplet'),
('fr','common','memory_book.overview_no_summary','Aucun résumé personnel ajouté pour l''instant.'),
('fr','common','memory_book.overview_not_started','Non commencé'),
('fr','common','memory_book.overview_progress_title','Progression du livre de mémoire'),
('fr','common','memory_book.overview_records_many','{count} enregistrements'),
('fr','common','memory_book.overview_records_one','1 enregistrement'),
('fr','common','memory_book.overview_sections_count','{completed}/{total} sections'),
('fr','common','memory_book.prefs_add_btn','Ajouter des préférences'),
('fr','common','memory_book.prefs_empty_member_title','Préférences pas encore complétées'),
('fr','common','memory_book.prefs_empty_owner_title','Ajouter les goûts, dégoûts et conforts'),
('fr','common','memory_book.prefs_subtitle','Ce qui apporte joie, réconfort et ce qui est à éviter'),
('fr','common','memory_book.prefs_title','Goûts, dégoûts & conforts'),
('fr','common','memory_book.print_btn','Imprimer le livre de mémoire'),
('fr','common','memory_book.print_confidential','Confidentiel — Réservé à l''équipe de soins'),
('fr','common','memory_book.print_generated','Généré'),
('fr','common','memory_book.print_no_data','Aucune information enregistrée pour l''instant.'),
('fr','common','memory_book.print_title','Livre de mémoire'),
('fr','common','memory_book.provider_primary_badge','Principal'),
('fr','common','memory_book.provider_save_btn','Enregistrer le prestataire'),
('fr','common','memory_book.providers_add_btn','Ajouter un prestataire'),
('fr','common','memory_book.providers_add_first_btn','Ajouter le premier prestataire'),
('fr','common','memory_book.providers_count_many','{count} prestataires enregistrés'),
('fr','common','memory_book.providers_count_one','1 prestataire enregistré'),
('fr','common','memory_book.providers_edit_heading','Modifier le prestataire'),
('fr','common','memory_book.providers_empty_desc','Ajoutez des médecins, dentistes, pharmacies et spécialistes pour que les soignants sachent toujours qui contacter.'),
('fr','common','memory_book.providers_empty_title','Aucun prestataire ajouté pour l''instant'),
('fr','common','memory_book.providers_new_heading','Nouveau prestataire'),
('fr','common','memory_book.providers_subtitle','Médecins, dentistes, pharmacies et spécialistes'),
('fr','common','memory_book.providers_title','Prestataires de santé'),
('fr','common','memory_book.readonly_notice','Vous avez un accès en lecture seule à cette section. Seuls les propriétaires d''équipe peuvent faire des modifications.'),
('fr','common','memory_book.save_changes','Enregistrer les modifications'),
('fr','common','memory_book.saving','Enregistrement...'),
('fr','common','memory_book.section_contacts','Contacts'),
('fr','common','memory_book.section_household','Ménage'),
('fr','common','memory_book.section_identity','Identité'),
('fr','common','memory_book.section_medical','Médical'),
('fr','common','memory_book.section_preferences','Goûts & Dégoûts'),
('fr','common','memory_book.social_add_btn','Ajouter un compte'),
('fr','common','memory_book.social_empty_title','Aucun compte en ligne ajouté pour l''instant'),
('fr','common','memory_book.social_title','Réseaux sociaux & Comptes en ligne'),
('fr','common','memory_book.subs_add_btn','Ajouter un abonnement'),
('fr','common','memory_book.subs_title','Abonnements & Adhésions'),
('fr','common','memory_book.subscriptions_title','Abonnements & Adhésions'),
('fr','common','memory_book.tab_household','Ménage'),
('fr','common','memory_book.toast_contact_added','Contact ajouté'),
('fr','common','memory_book.toast_contact_failed','Échec de l''enregistrement du contact'),
('fr','common','memory_book.toast_contact_removed','Contact supprimé'),
('fr','common','memory_book.toast_contact_updated','Contact mis à jour'),
('fr','common','memory_book.toast_finances_saved','Informations financières enregistrées'),
('fr','common','memory_book.toast_identity_saved','Identité enregistrée'),
('fr','common','memory_book.toast_insurance_saved','Informations d''assurance enregistrées'),
('fr','common','memory_book.toast_medical_saved','Informations médicales enregistrées'),
('fr','common','memory_book.toast_prefs_saved','Préférences enregistrées'),
('fr','common','memory_book.toast_provider_added','Prestataire ajouté'),
('fr','common','memory_book.toast_provider_failed','Échec de l''enregistrement du prestataire'),
('fr','common','memory_book.toast_provider_removed','Prestataire supprimé'),
('fr','common','memory_book.toast_provider_updated','Prestataire mis à jour'),
('fr','common','memory_book.toast_social_added','Compte ajouté'),
('fr','common','memory_book.toast_social_removed','Compte supprimé'),
('fr','common','memory_book.toast_social_updated','Compte mis à jour'),
('fr','common','memory_book.toast_sub_added','Abonnement ajouté'),
('fr','common','memory_book.toast_sub_removed','Abonnement supprimé'),
('fr','common','memory_book.toast_sub_updated','Abonnement mis à jour'),
('fr','common','memory_book.toast_subscription_added','Abonnement ajouté'),
('fr','common','memory_book.toast_subscription_removed','Abonnement supprimé'),
('fr','common','memory_book.toast_subscription_updated','Abonnement mis à jour'),

-- ============================================================
-- GERMAN (de)
-- ============================================================
('de','common','memory_book.cancel','Abbrechen'),
('de','common','memory_book.confirm_remove_contact','{name} aus den Kontakten entfernen?'),
('de','common','memory_book.confirm_remove_provider','{name} aus den Anbietern entfernen?'),
('de','common','memory_book.confirm_remove_social','{platform}-Konto entfernen?'),
('de','common','memory_book.confirm_remove_sub','{name} entfernen?'),
('de','common','memory_book.confirm_remove_subscription','{name} entfernen?'),
('de','common','memory_book.confirm_remove_vehicle','{name} entfernen?'),
('de','common','memory_book.contact_fallback_label','Kontakt'),
('de','common','memory_book.contact_save_btn','Kontakt speichern'),
('de','common','memory_book.contacts_add_btn','Kontakt hinzufügen'),
('de','common','memory_book.contacts_add_first_btn','Ersten Kontakt hinzufügen'),
('de','common','memory_book.contacts_count_many','{count} Kontakte gespeichert'),
('de','common','memory_book.contacts_count_one','1 Kontakt gespeichert'),
('de','common','memory_book.contacts_edit_heading','Kontakt bearbeiten'),
('de','common','memory_book.contacts_empty_desc','Füge Familienmitglieder, Ärzte, Notfallkontakte und andere wichtige Unterstützungspersonen hinzu, damit Pflegepersonen schnell die richtige Person erreichen können.'),
('de','common','memory_book.contacts_empty_title','Noch keine Kontakte hinzugefügt'),
('de','common','memory_book.contacts_new_heading','Neuer Kontakt'),
('de','common','memory_book.contacts_title','Pflegenetzwerk & Kontakte'),
('de','common','memory_book.edit','Bearbeiten'),
('de','common','memory_book.finances_add_btn','Finanzielle Informationen hinzufügen'),
('de','common','memory_book.finances_locked_title','Nur Eigentümerzugriff'),
('de','common','memory_book.finances_owner_only_notice','Dieser Abschnitt ist nur für Teameigentümer sichtbar.'),
('de','common','memory_book.finances_subtitle','Bankdaten, Einkommensquellen und wiederkehrende Rechnungen'),
('de','common','memory_book.finances_title','Einkommen & Finanzen'),
('de','common','memory_book.household_section_finances','Finanzen'),
('de','common','memory_book.household_section_insurance','Versicherung'),
('de','common','memory_book.household_section_providers','Gesundheitsdienstleister'),
('de','common','memory_book.household_section_subscriptions','Abonnements'),
('de','common','memory_book.household_section_vehicle','Fahrzeug & Transport'),
('de','common','memory_book.identity_add_btn','Identitätsdetails hinzufügen'),
('de','common','memory_book.identity_empty_member_title','Identität noch nicht ausgefüllt'),
('de','common','memory_book.identity_empty_owner_title','Identitätsinformationen hinzufügen'),
('de','common','memory_book.identity_subtitle','Persönliche Details für {patientName}'),
('de','common','memory_book.identity_title','Identität & Profil'),
('de','common','memory_book.insurance_add_btn','Versicherungsdetails hinzufügen'),
('de','common','memory_book.insurance_dental_heading','Zahn- & Sehhilfe-Versicherung'),
('de','common','memory_book.insurance_dental_vision_heading','Zahn- & Sehhilfe-Versicherung'),
('de','common','memory_book.insurance_empty_member_title','Versicherung noch nicht ausgefüllt'),
('de','common','memory_book.insurance_empty_owner_title','Versicherungsdetails hinzufügen'),
('de','common','memory_book.insurance_primary_heading','Hauptversicherung'),
('de','common','memory_book.insurance_secondary_heading','Nebenversicherung'),
('de','common','memory_book.insurance_subtitle','Haupt-, Neben- und Zahn-/Sehversicherung'),
('de','common','memory_book.insurance_title','Krankenversicherung'),
('de','common','memory_book.medical_add_btn','Medizinische Informationen hinzufügen'),
('de','common','memory_book.medical_empty_member_title','Medizinische Informationen noch nicht ausgefüllt'),
('de','common','memory_book.medical_empty_owner_title','Medizinischen Kontext hinzufügen'),
('de','common','memory_book.medical_subtitle','Pflegeorientierte Gesundheitsinformationen — kein klinisches Dokument'),
('de','common','memory_book.medical_title','Medizinischer Kontext'),
('de','common','memory_book.overview_age','Alter {age}'),
('de','common','memory_book.overview_incomplete_title','Erinnerungsbuch unvollständig'),
('de','common','memory_book.overview_not_started','Nicht begonnen'),
('de','common','memory_book.overview_progress_title','Fortschritt des Erinnerungsbuchs'),
('de','common','memory_book.overview_records_many','{count} Einträge'),
('de','common','memory_book.overview_records_one','1 Eintrag'),
('de','common','memory_book.overview_sections_count','{completed}/{total} Abschnitte'),
('de','common','memory_book.prefs_add_btn','Präferenzen hinzufügen'),
('de','common','memory_book.prefs_empty_member_title','Präferenzen noch nicht ausgefüllt'),
('de','common','memory_book.prefs_empty_owner_title','Vorlieben, Abneigungen & Trost hinzufügen'),
('de','common','memory_book.prefs_subtitle','Was Freude, Trost bringt und was zu vermeiden ist'),
('de','common','memory_book.prefs_title','Vorlieben, Abneigungen & Trost'),
('de','common','memory_book.print_btn','Erinnerungsbuch drucken'),
('de','common','memory_book.print_confidential','Vertraulich — nur für das Pflegeteam'),
('de','common','memory_book.print_generated','Erstellt'),
('de','common','memory_book.print_no_data','Noch keine Informationen gespeichert.'),
('de','common','memory_book.print_title','Erinnerungsbuch'),
('de','common','memory_book.provider_primary_badge','Hauptanbieter'),
('de','common','memory_book.provider_save_btn','Anbieter speichern'),
('de','common','memory_book.providers_add_btn','Anbieter hinzufügen'),
('de','common','memory_book.providers_add_first_btn','Ersten Anbieter hinzufügen'),
('de','common','memory_book.providers_count_many','{count} Anbieter gespeichert'),
('de','common','memory_book.providers_count_one','1 Anbieter gespeichert'),
('de','common','memory_book.providers_edit_heading','Anbieter bearbeiten'),
('de','common','memory_book.providers_empty_desc','Füge Ärzte, Zahnärzte, Apotheken und Spezialisten hinzu, damit Pflegepersonen immer wissen, wen sie kontaktieren sollen.'),
('de','common','memory_book.providers_empty_title','Noch keine Anbieter hinzugefügt'),
('de','common','memory_book.providers_new_heading','Neuer Anbieter'),
('de','common','memory_book.providers_subtitle','Ärzte, Zahnärzte, Apotheken und Spezialisten'),
('de','common','memory_book.providers_title','Gesundheitsdienstleister'),
('de','common','memory_book.readonly_notice','Du hast Lesezugriff auf diesen Abschnitt. Nur Teameigentümer können Änderungen vornehmen.'),
('de','common','memory_book.save_changes','Änderungen speichern'),
('de','common','memory_book.saving','Wird gespeichert...'),
('de','common','memory_book.section_contacts','Kontakte'),
('de','common','memory_book.section_household','Haushalt'),
('de','common','memory_book.section_identity','Identität'),
('de','common','memory_book.section_medical','Medizinisch'),
('de','common','memory_book.section_preferences','Vorlieben & Abneigungen'),
('de','common','memory_book.social_add_btn','Konto hinzufügen'),
('de','common','memory_book.social_empty_title','Noch keine Online-Konten hinzugefügt'),
('de','common','memory_book.social_title','Soziale Medien & Online-Konten'),
('de','common','memory_book.subs_add_btn','Abonnement hinzufügen'),
('de','common','memory_book.subs_title','Abonnements & Mitgliedschaften'),
('de','common','memory_book.subscriptions_title','Abonnements & Mitgliedschaften'),
('de','common','memory_book.tab_household','Haushalt'),
('de','common','memory_book.toast_contact_added','Kontakt hinzugefügt'),
('de','common','memory_book.toast_contact_failed','Kontakt konnte nicht gespeichert werden'),
('de','common','memory_book.toast_contact_removed','Kontakt entfernt'),
('de','common','memory_book.toast_contact_updated','Kontakt aktualisiert'),
('de','common','memory_book.toast_finances_saved','Finanzinformationen gespeichert'),
('de','common','memory_book.toast_identity_saved','Identität gespeichert'),
('de','common','memory_book.toast_insurance_saved','Versicherungsinformationen gespeichert'),
('de','common','memory_book.toast_medical_saved','Medizinische Informationen gespeichert'),
('de','common','memory_book.toast_prefs_saved','Präferenzen gespeichert'),
('de','common','memory_book.toast_provider_added','Anbieter hinzugefügt'),
('de','common','memory_book.toast_provider_failed','Anbieter konnte nicht gespeichert werden'),
('de','common','memory_book.toast_provider_removed','Anbieter entfernt'),
('de','common','memory_book.toast_provider_updated','Anbieter aktualisiert'),
('de','common','memory_book.toast_social_added','Konto hinzugefügt'),
('de','common','memory_book.toast_social_removed','Konto entfernt'),
('de','common','memory_book.toast_social_updated','Konto aktualisiert'),
('de','common','memory_book.toast_sub_added','Abonnement hinzugefügt'),
('de','common','memory_book.toast_sub_removed','Abonnement entfernt'),
('de','common','memory_book.toast_sub_updated','Abonnement aktualisiert'),
('de','common','memory_book.toast_subscription_added','Abonnement hinzugefügt'),
('de','common','memory_book.toast_subscription_removed','Abonnement entfernt'),
('de','common','memory_book.toast_subscription_updated','Abonnement aktualisiert'),

-- ============================================================
-- ITALIAN (it)
-- ============================================================
('it','common','memory_book.cancel','Annulla'),
('it','common','memory_book.confirm_remove_contact','Rimuovere {name} dai contatti?'),
('it','common','memory_book.confirm_remove_provider','Rimuovere {name} dai fornitori?'),
('it','common','memory_book.confirm_remove_social','Rimuovere l''account {platform}?'),
('it','common','memory_book.confirm_remove_sub','Rimuovere {name}?'),
('it','common','memory_book.confirm_remove_subscription','Rimuovere {name}?'),
('it','common','memory_book.confirm_remove_vehicle','Rimuovere {name}?'),
('it','common','memory_book.contact_fallback_label','Contatto'),
('it','common','memory_book.contact_save_btn','Salva Contatto'),
('it','common','memory_book.contacts_add_btn','Aggiungi Contatto'),
('it','common','memory_book.contacts_add_first_btn','Aggiungi Primo Contatto'),
('it','common','memory_book.contacts_count_many','{count} contatti nel file'),
('it','common','memory_book.contacts_count_one','1 contatto nel file'),
('it','common','memory_book.contacts_edit_heading','Modifica Contatto'),
('it','common','memory_book.contacts_empty_desc','Aggiungi familiari, medici, contatti di emergenza e altre persone chiave per aiutare i caregiver a raggiungere rapidamente la persona giusta.'),
('it','common','memory_book.contacts_empty_title','Nessun contatto aggiunto ancora'),
('it','common','memory_book.contacts_new_heading','Nuovo Contatto'),
('it','common','memory_book.contacts_title','Rete di Cura & Contatti'),
('it','common','memory_book.edit','Modifica'),
('it','common','memory_book.finances_add_btn','Aggiungi Informazioni Finanziarie'),
('it','common','memory_book.finances_locked_title','Solo accesso del proprietario'),
('it','common','memory_book.finances_owner_only_notice','Questa sezione è visibile solo ai proprietari del team.'),
('it','common','memory_book.finances_subtitle','Dati bancari, fonti di reddito e bollette ricorrenti'),
('it','common','memory_book.finances_title','Reddito & Finanze'),
('it','common','memory_book.household_section_finances','Finanze'),
('it','common','memory_book.household_section_insurance','Assicurazione'),
('it','common','memory_book.household_section_providers','Fornitori sanitari'),
('it','common','memory_book.household_section_subscriptions','Abbonamenti'),
('it','common','memory_book.household_section_vehicle','Veicolo & Trasporto'),
('it','common','memory_book.identity_add_btn','Aggiungi Dettagli Identità'),
('it','common','memory_book.identity_empty_member_title','Identità non ancora completata'),
('it','common','memory_book.identity_empty_owner_title','Aggiungi informazioni sull''identità'),
('it','common','memory_book.identity_subtitle','Dettagli personali per {patientName}'),
('it','common','memory_book.identity_title','Identità & Profilo'),
('it','common','memory_book.insurance_add_btn','Aggiungi Dettagli Assicurazione'),
('it','common','memory_book.insurance_dental_heading','Assicurazione Dentale & Visiva'),
('it','common','memory_book.insurance_dental_vision_heading','Assicurazione Dentale & Visiva'),
('it','common','memory_book.insurance_empty_member_title','Assicurazione non ancora completata'),
('it','common','memory_book.insurance_empty_owner_title','Aggiungi dettagli assicurazione'),
('it','common','memory_book.insurance_primary_heading','Assicurazione Primaria'),
('it','common','memory_book.insurance_secondary_heading','Assicurazione Secondaria'),
('it','common','memory_book.insurance_subtitle','Copertura primaria, secondaria e dentale/visiva'),
('it','common','memory_book.insurance_title','Assicurazione Sanitaria'),
('it','common','memory_book.medical_add_btn','Aggiungi Informazioni Mediche'),
('it','common','memory_book.medical_empty_member_title','Informazioni mediche non ancora completate'),
('it','common','memory_book.medical_empty_owner_title','Aggiungi contesto medico'),
('it','common','memory_book.medical_subtitle','Informazioni sanitarie orientate al caregiver — non un registro clinico'),
('it','common','memory_book.medical_title','Contesto Medico'),
('it','common','memory_book.overview_age','Età {age}'),
('it','common','memory_book.overview_incomplete_title','Libro dei Ricordi Incompleto'),
('it','common','memory_book.overview_not_started','Non iniziato'),
('it','common','memory_book.overview_progress_title','Progresso del Libro dei Ricordi'),
('it','common','memory_book.overview_records_many','{count} record'),
('it','common','memory_book.overview_records_one','1 record'),
('it','common','memory_book.overview_sections_count','{completed}/{total} sezioni'),
('it','common','memory_book.prefs_add_btn','Aggiungi Preferenze'),
('it','common','memory_book.prefs_empty_member_title','Preferenze non ancora completate'),
('it','common','memory_book.prefs_empty_owner_title','Aggiungi gusti, disgusti e comfort'),
('it','common','memory_book.prefs_subtitle','Ciò che porta gioia, conforto e ciò da evitare'),
('it','common','memory_book.prefs_title','Gusti, Disgusti & Comfort'),
('it','common','memory_book.print_btn','Stampa Libro dei Ricordi'),
('it','common','memory_book.print_confidential','Riservato — Solo per uso del team di cura'),
('it','common','memory_book.print_generated','Generato'),
('it','common','memory_book.print_no_data','Nessuna informazione registrata ancora.'),
('it','common','memory_book.print_title','Libro dei Ricordi'),
('it','common','memory_book.provider_primary_badge','Principale'),
('it','common','memory_book.provider_save_btn','Salva Fornitore'),
('it','common','memory_book.providers_add_btn','Aggiungi Fornitore'),
('it','common','memory_book.providers_add_first_btn','Aggiungi Primo Fornitore'),
('it','common','memory_book.providers_count_many','{count} fornitori nel file'),
('it','common','memory_book.providers_count_one','1 fornitore nel file'),
('it','common','memory_book.providers_edit_heading','Modifica Fornitore'),
('it','common','memory_book.providers_empty_desc','Aggiungi medici, dentisti, farmacie e specialisti così i caregiver sanno sempre chi contattare.'),
('it','common','memory_book.providers_empty_title','Nessun fornitore aggiunto ancora'),
('it','common','memory_book.providers_new_heading','Nuovo Fornitore'),
('it','common','memory_book.providers_subtitle','Medici, dentisti, farmacie e specialisti'),
('it','common','memory_book.providers_title','Fornitori Sanitari'),
('it','common','memory_book.readonly_notice','Hai accesso di sola lettura a questa sezione. Solo i proprietari del team possono apportare modifiche.'),
('it','common','memory_book.save_changes','Salva Modifiche'),
('it','common','memory_book.saving','Salvataggio...'),
('it','common','memory_book.section_contacts','Contatti'),
('it','common','memory_book.section_household','Casa'),
('it','common','memory_book.section_identity','Identità'),
('it','common','memory_book.section_medical','Medico'),
('it','common','memory_book.section_preferences','Gusti & Disgusti'),
('it','common','memory_book.social_add_btn','Aggiungi Account'),
('it','common','memory_book.social_empty_title','Nessun account online aggiunto ancora'),
('it','common','memory_book.social_title','Social Media & Account Online'),
('it','common','memory_book.subs_add_btn','Aggiungi Abbonamento'),
('it','common','memory_book.subs_title','Abbonamenti & Iscrizioni'),
('it','common','memory_book.subscriptions_title','Abbonamenti & Iscrizioni'),
('it','common','memory_book.tab_household','Casa'),
('it','common','memory_book.toast_contact_added','Contatto aggiunto'),
('it','common','memory_book.toast_contact_failed','Impossibile salvare il contatto'),
('it','common','memory_book.toast_contact_removed','Contatto rimosso'),
('it','common','memory_book.toast_contact_updated','Contatto aggiornato'),
('it','common','memory_book.toast_finances_saved','Informazioni finanziarie salvate'),
('it','common','memory_book.toast_identity_saved','Identità salvata'),
('it','common','memory_book.toast_insurance_saved','Informazioni assicurative salvate'),
('it','common','memory_book.toast_medical_saved','Informazioni mediche salvate'),
('it','common','memory_book.toast_prefs_saved','Preferenze salvate'),
('it','common','memory_book.toast_provider_added','Fornitore aggiunto'),
('it','common','memory_book.toast_provider_failed','Impossibile salvare il fornitore'),
('it','common','memory_book.toast_provider_removed','Fornitore rimosso'),
('it','common','memory_book.toast_provider_updated','Fornitore aggiornato'),
('it','common','memory_book.toast_social_added','Account aggiunto'),
('it','common','memory_book.toast_social_removed','Account rimosso'),
('it','common','memory_book.toast_social_updated','Account aggiornato'),
('it','common','memory_book.toast_sub_added','Abbonamento aggiunto'),
('it','common','memory_book.toast_sub_removed','Abbonamento rimosso'),
('it','common','memory_book.toast_sub_updated','Abbonamento aggiornato'),
('it','common','memory_book.toast_subscription_added','Abbonamento aggiunto'),
('it','common','memory_book.toast_subscription_removed','Abbonamento rimosso'),
('it','common','memory_book.toast_subscription_updated','Abbonamento aggiornato'),

-- ============================================================
-- SWEDISH (sv)
-- ============================================================
('sv','common','memory_book.cancel','Avbryt'),
('sv','common','memory_book.confirm_remove_contact','Ta bort {name} från kontakter?'),
('sv','common','memory_book.confirm_remove_provider','Ta bort {name} från leverantörer?'),
('sv','common','memory_book.confirm_remove_social','Ta bort {platform}-konto?'),
('sv','common','memory_book.confirm_remove_sub','Ta bort {name}?'),
('sv','common','memory_book.confirm_remove_subscription','Ta bort {name}?'),
('sv','common','memory_book.confirm_remove_vehicle','Ta bort {name}?'),
('sv','common','memory_book.contact_fallback_label','Kontakt'),
('sv','common','memory_book.contact_save_btn','Spara kontakt'),
('sv','common','memory_book.contacts_add_btn','Lägg till kontakt'),
('sv','common','memory_book.contacts_add_first_btn','Lägg till första kontakt'),
('sv','common','memory_book.contacts_count_many','{count} kontakter på fil'),
('sv','common','memory_book.contacts_count_one','1 kontakt på fil'),
('sv','common','memory_book.contacts_edit_heading','Redigera kontakt'),
('sv','common','memory_book.contacts_empty_desc','Lägg till familjemedlemmar, läkare, nödkontakter och andra nyckelpersoner för att hjälpa vårdgivare att snabbt nå rätt person.'),
('sv','common','memory_book.contacts_empty_title','Inga kontakter tillagda ännu'),
('sv','common','memory_book.contacts_new_heading','Ny kontakt'),
('sv','common','memory_book.contacts_title','Vårdnätverk & Kontakter'),
('sv','common','memory_book.edit','Redigera'),
('sv','common','memory_book.finances_add_btn','Lägg till finansiell information'),
('sv','common','memory_book.finances_locked_title','Endast ägaråtkomst'),
('sv','common','memory_book.finances_owner_only_notice','Det här avsnittet är synligt för teamägare.'),
('sv','common','memory_book.finances_subtitle','Bankuppgifter, inkomstkällor och återkommande räkningar'),
('sv','common','memory_book.finances_title','Inkomst & Ekonomi'),
('sv','common','memory_book.household_section_finances','Ekonomi'),
('sv','common','memory_book.household_section_insurance','Försäkring'),
('sv','common','memory_book.household_section_providers','Vårdgivare'),
('sv','common','memory_book.household_section_subscriptions','Abonnemang'),
('sv','common','memory_book.household_section_vehicle','Fordon & Transport'),
('sv','common','memory_book.identity_add_btn','Lägg till identitetsuppgifter'),
('sv','common','memory_book.identity_empty_member_title','Identitet inte ännu ifylld'),
('sv','common','memory_book.identity_empty_owner_title','Lägg till identitetsinformation'),
('sv','common','memory_book.identity_subtitle','Personliga uppgifter för {patientName}'),
('sv','common','memory_book.identity_title','Identitet & Profil'),
('sv','common','memory_book.insurance_add_btn','Lägg till försäkringsuppgifter'),
('sv','common','memory_book.insurance_dental_heading','Tand- & Synförsäkring'),
('sv','common','memory_book.insurance_dental_vision_heading','Tand- & Synförsäkring'),
('sv','common','memory_book.insurance_empty_member_title','Försäkring inte ännu ifylld'),
('sv','common','memory_book.insurance_empty_owner_title','Lägg till försäkringsuppgifter'),
('sv','common','memory_book.insurance_primary_heading','Primärförsäkring'),
('sv','common','memory_book.insurance_secondary_heading','Sekundärförsäkring'),
('sv','common','memory_book.insurance_subtitle','Primär-, sekundär- och tand-/synförsäkring'),
('sv','common','memory_book.insurance_title','Sjukförsäkring'),
('sv','common','memory_book.medical_add_btn','Lägg till medicinsk information'),
('sv','common','memory_book.medical_empty_member_title','Medicinsk information inte ännu ifylld'),
('sv','common','memory_book.medical_empty_owner_title','Lägg till medicinsk kontext'),
('sv','common','memory_book.medical_subtitle','Vårdorienterad hälsoinformation — inte ett kliniskt journalblad'),
('sv','common','memory_book.medical_title','Medicinsk kontext'),
('sv','common','memory_book.overview_age','Ålder {age}'),
('sv','common','memory_book.overview_incomplete_title','Minnesbok ofullständig'),
('sv','common','memory_book.overview_not_started','Inte påbörjad'),
('sv','common','memory_book.overview_progress_title','Minnesbokens framsteg'),
('sv','common','memory_book.overview_records_many','{count} poster'),
('sv','common','memory_book.overview_records_one','1 post'),
('sv','common','memory_book.overview_sections_count','{completed}/{total} avsnitt'),
('sv','common','memory_book.prefs_add_btn','Lägg till preferenser'),
('sv','common','memory_book.prefs_empty_member_title','Preferenser inte ännu ifyllda'),
('sv','common','memory_book.prefs_empty_owner_title','Lägg till gillanden, ogillanden och tröst'),
('sv','common','memory_book.prefs_subtitle','Vad som ger glädje, tröst och vad som bör undvikas'),
('sv','common','memory_book.prefs_title','Gillanden, ogillanden & tröst'),
('sv','common','memory_book.print_btn','Skriv ut minnesbok'),
('sv','common','memory_book.print_confidential','Konfidentiell — Endast för vårdteamets användning'),
('sv','common','memory_book.print_generated','Genererad'),
('sv','common','memory_book.print_no_data','Ingen information registrerad ännu.'),
('sv','common','memory_book.print_title','Minnesbok'),
('sv','common','memory_book.provider_primary_badge','Primär'),
('sv','common','memory_book.provider_save_btn','Spara leverantör'),
('sv','common','memory_book.providers_add_btn','Lägg till leverantör'),
('sv','common','memory_book.providers_add_first_btn','Lägg till första leverantör'),
('sv','common','memory_book.providers_count_many','{count} leverantörer på fil'),
('sv','common','memory_book.providers_count_one','1 leverantör på fil'),
('sv','common','memory_book.providers_edit_heading','Redigera leverantör'),
('sv','common','memory_book.providers_empty_desc','Lägg till läkare, tandläkare, apotek och specialister så att vårdgivare alltid vet vem de ska kontakta.'),
('sv','common','memory_book.providers_empty_title','Inga leverantörer tillagda ännu'),
('sv','common','memory_book.providers_new_heading','Ny leverantör'),
('sv','common','memory_book.providers_subtitle','Läkare, tandläkare, apotek och specialister'),
('sv','common','memory_book.providers_title','Vårdleverantörer'),
('sv','common','memory_book.readonly_notice','Du har visningsåtkomst till det här avsnittet. Bara teamägare kan göra ändringar.'),
('sv','common','memory_book.save_changes','Spara ändringar'),
('sv','common','memory_book.saving','Sparar...'),
('sv','common','memory_book.section_contacts','Kontakter'),
('sv','common','memory_book.section_household','Hushåll'),
('sv','common','memory_book.section_identity','Identitet'),
('sv','common','memory_book.section_medical','Medicinskt'),
('sv','common','memory_book.section_preferences','Gillanden & Ogillanden'),
('sv','common','memory_book.social_add_btn','Lägg till konto'),
('sv','common','memory_book.social_empty_title','Inga onlinekonton tillagda ännu'),
('sv','common','memory_book.social_title','Sociala medier & Onlinekonton'),
('sv','common','memory_book.subs_add_btn','Lägg till abonnemang'),
('sv','common','memory_book.subs_title','Abonnemang & Medlemskap'),
('sv','common','memory_book.subscriptions_title','Abonnemang & Medlemskap'),
('sv','common','memory_book.tab_household','Hushåll'),
('sv','common','memory_book.toast_contact_added','Kontakt tillagd'),
('sv','common','memory_book.toast_contact_failed','Det gick inte att spara kontakten'),
('sv','common','memory_book.toast_contact_removed','Kontakt borttagen'),
('sv','common','memory_book.toast_contact_updated','Kontakt uppdaterad'),
('sv','common','memory_book.toast_finances_saved','Finansiell information sparad'),
('sv','common','memory_book.toast_identity_saved','Identitet sparad'),
('sv','common','memory_book.toast_insurance_saved','Försäkringsinformation sparad'),
('sv','common','memory_book.toast_medical_saved','Medicinsk information sparad'),
('sv','common','memory_book.toast_prefs_saved','Preferenser sparade'),
('sv','common','memory_book.toast_provider_added','Leverantör tillagd'),
('sv','common','memory_book.toast_provider_failed','Det gick inte att spara leverantören'),
('sv','common','memory_book.toast_provider_removed','Leverantör borttagen'),
('sv','common','memory_book.toast_provider_updated','Leverantör uppdaterad'),
('sv','common','memory_book.toast_social_added','Konto tillagt'),
('sv','common','memory_book.toast_social_removed','Konto borttaget'),
('sv','common','memory_book.toast_social_updated','Konto uppdaterat'),
('sv','common','memory_book.toast_sub_added','Abonnemang tillagt'),
('sv','common','memory_book.toast_sub_removed','Abonnemang borttaget'),
('sv','common','memory_book.toast_sub_updated','Abonnemang uppdaterat'),
('sv','common','memory_book.toast_subscription_added','Abonnemang tillagt'),
('sv','common','memory_book.toast_subscription_removed','Abonnemang borttaget'),
('sv','common','memory_book.toast_subscription_updated','Abonnemang uppdaterat'),

-- ============================================================
-- FINNISH (fi)
-- ============================================================
('fi','common','memory_book.cancel','Peruuta'),
('fi','common','memory_book.confirm_remove_contact','Poistetaanko {name} yhteystiedoista?'),
('fi','common','memory_book.confirm_remove_provider','Poistetaanko {name} palveluntarjoajista?'),
('fi','common','memory_book.confirm_remove_social','Poistetaanko {platform}-tili?'),
('fi','common','memory_book.confirm_remove_sub','Poistetaanko {name}?'),
('fi','common','memory_book.confirm_remove_subscription','Poistetaanko {name}?'),
('fi','common','memory_book.confirm_remove_vehicle','Poistetaanko {name}?'),
('fi','common','memory_book.contact_fallback_label','Yhteystieto'),
('fi','common','memory_book.contact_save_btn','Tallenna yhteystieto'),
('fi','common','memory_book.contacts_add_btn','Lisää yhteystieto'),
('fi','common','memory_book.contacts_add_first_btn','Lisää ensimmäinen yhteystieto'),
('fi','common','memory_book.contacts_count_many','{count} yhteystietoa tallennettu'),
('fi','common','memory_book.contacts_count_one','1 yhteystieto tallennettu'),
('fi','common','memory_book.contacts_edit_heading','Muokkaa yhteystietoa'),
('fi','common','memory_book.contacts_empty_desc','Lisää perheenjäseniä, lääkäreitä, hätäyhteystietoja ja muita avainhenkilöitä, jotta hoitajat voivat tavoittaa oikean henkilön nopeasti.'),
('fi','common','memory_book.contacts_empty_title','Yhteystietoja ei ole vielä lisätty'),
('fi','common','memory_book.contacts_new_heading','Uusi yhteystieto'),
('fi','common','memory_book.contacts_title','Hoitoverkosto & Yhteystiedot'),
('fi','common','memory_book.edit','Muokkaa'),
('fi','common','memory_book.finances_add_btn','Lisää taloudellisia tietoja'),
('fi','common','memory_book.finances_locked_title','Vain omistajan käyttöoikeus'),
('fi','common','memory_book.finances_owner_only_notice','Tämä osio näkyy vain tiimin omistajille.'),
('fi','common','memory_book.finances_subtitle','Pankkitiedot, tulonlähteet ja toistuvat laskut'),
('fi','common','memory_book.finances_title','Tulot & Talous'),
('fi','common','memory_book.household_section_finances','Talous'),
('fi','common','memory_book.household_section_insurance','Vakuutus'),
('fi','common','memory_book.household_section_providers','Terveydenhuollon palveluntarjoajat'),
('fi','common','memory_book.household_section_subscriptions','Tilaukset'),
('fi','common','memory_book.household_section_vehicle','Ajoneuvo & Liikenne'),
('fi','common','memory_book.identity_add_btn','Lisää henkilöllisyystiedot'),
('fi','common','memory_book.identity_empty_member_title','Henkilöllisyyttä ei ole vielä täytetty'),
('fi','common','memory_book.identity_empty_owner_title','Lisää henkilöllisyystiedot'),
('fi','common','memory_book.identity_subtitle','Henkilötiedot kohteelle {patientName}'),
('fi','common','memory_book.identity_title','Henkilöllisyys & Profiili'),
('fi','common','memory_book.insurance_add_btn','Lisää vakuutustiedot'),
('fi','common','memory_book.insurance_dental_heading','Hammas- & Näkövakuutus'),
('fi','common','memory_book.insurance_dental_vision_heading','Hammas- & Näkövakuutus'),
('fi','common','memory_book.insurance_empty_member_title','Vakuutusta ei ole vielä täytetty'),
('fi','common','memory_book.insurance_empty_owner_title','Lisää vakuutustiedot'),
('fi','common','memory_book.insurance_primary_heading','Pääasiallinen Vakuutus'),
('fi','common','memory_book.insurance_secondary_heading','Toissijainen Vakuutus'),
('fi','common','memory_book.insurance_subtitle','Ensisijainen, toissijainen ja hammas-/näkövakuutus'),
('fi','common','memory_book.insurance_title','Sairausvakuutus'),
('fi','common','memory_book.medical_add_btn','Lisää lääketieteellistä tietoa'),
('fi','common','memory_book.medical_empty_member_title','Lääketieteellisiä tietoja ei ole vielä täytetty'),
('fi','common','memory_book.medical_empty_owner_title','Lisää lääketieteellinen konteksti'),
('fi','common','memory_book.medical_subtitle','Hoitajasuuntautunut terveysinformaatio — ei kliininen potilasasiakirja'),
('fi','common','memory_book.medical_title','Lääketieteellinen Konteksti'),
('fi','common','memory_book.overview_age','Ikä {age}'),
('fi','common','memory_book.overview_incomplete_title','Muistokirja Puutteellinen'),
('fi','common','memory_book.overview_not_started','Ei aloitettu'),
('fi','common','memory_book.overview_progress_title','Muistokirjan Edistyminen'),
('fi','common','memory_book.overview_records_many','{count} tietuetta'),
('fi','common','memory_book.overview_records_one','1 tietue'),
('fi','common','memory_book.overview_sections_count','{completed}/{total} osiota'),
('fi','common','memory_book.prefs_add_btn','Lisää mieltymykset'),
('fi','common','memory_book.prefs_empty_member_title','Mieltymyksiä ei ole vielä täytetty'),
('fi','common','memory_book.prefs_empty_owner_title','Lisää tykkäykset, inhokit ja lohdutukset'),
('fi','common','memory_book.prefs_subtitle','Mikä tuo iloa, lohdutusta ja mitä tulee välttää'),
('fi','common','memory_book.prefs_title','Tykkäykset, Inhokit & Lohdutukset'),
('fi','common','memory_book.print_btn','Tulosta Muistokirja'),
('fi','common','memory_book.print_confidential','Luottamuksellinen — Vain hoitotiimin käyttöön'),
('fi','common','memory_book.print_generated','Luotu'),
('fi','common','memory_book.print_no_data','Tietoja ei ole vielä tallennettu.'),
('fi','common','memory_book.print_title','Muistokirja'),
('fi','common','memory_book.provider_primary_badge','Ensisijainen'),
('fi','common','memory_book.provider_save_btn','Tallenna palveluntarjoaja'),
('fi','common','memory_book.providers_add_btn','Lisää palveluntarjoaja'),
('fi','common','memory_book.providers_add_first_btn','Lisää ensimmäinen palveluntarjoaja'),
('fi','common','memory_book.providers_count_many','{count} palveluntarjoajaa tallennettu'),
('fi','common','memory_book.providers_count_one','1 palveluntarjoaja tallennettu'),
('fi','common','memory_book.providers_edit_heading','Muokkaa palveluntarjoajaa'),
('fi','common','memory_book.providers_empty_desc','Lisää lääkäreitä, hammaslääkäreitä, apteekkeja ja erikoislääkäreitä, jotta hoitajat tietävät aina ketä ottaa yhteyttä.'),
('fi','common','memory_book.providers_empty_title','Palveluntarjoajia ei ole vielä lisätty'),
('fi','common','memory_book.providers_new_heading','Uusi palveluntarjoaja'),
('fi','common','memory_book.providers_subtitle','Lääkärit, hammaslääkärit, apteekit ja erikoislääkärit'),
('fi','common','memory_book.providers_title','Terveydenhuollon Palveluntarjoajat'),
('fi','common','memory_book.readonly_notice','Sinulla on katseluoikeus tähän osioon. Vain tiimin omistajat voivat tehdä muutoksia.'),
('fi','common','memory_book.save_changes','Tallenna Muutokset'),
('fi','common','memory_book.saving','Tallennetaan...'),
('fi','common','memory_book.section_contacts','Yhteystiedot'),
('fi','common','memory_book.section_household','Kotitalous'),
('fi','common','memory_book.section_identity','Henkilöllisyys'),
('fi','common','memory_book.section_medical','Lääketieteellinen'),
('fi','common','memory_book.section_preferences','Tykkäykset & Inhokit'),
('fi','common','memory_book.social_add_btn','Lisää tili'),
('fi','common','memory_book.social_empty_title','Verkkotilejä ei ole vielä lisätty'),
('fi','common','memory_book.social_title','Sosiaalinen Media & Verkkotilit'),
('fi','common','memory_book.subs_add_btn','Lisää tilaus'),
('fi','common','memory_book.subs_title','Tilaukset & Jäsenyydet'),
('fi','common','memory_book.subscriptions_title','Tilaukset & Jäsenyydet'),
('fi','common','memory_book.tab_household','Kotitalous'),
('fi','common','memory_book.toast_contact_added','Yhteystieto lisätty'),
('fi','common','memory_book.toast_contact_failed','Yhteystiedon tallentaminen epäonnistui'),
('fi','common','memory_book.toast_contact_removed','Yhteystieto poistettu'),
('fi','common','memory_book.toast_contact_updated','Yhteystieto päivitetty'),
('fi','common','memory_book.toast_finances_saved','Taloudelliset tiedot tallennettu'),
('fi','common','memory_book.toast_identity_saved','Henkilöllisyys tallennettu'),
('fi','common','memory_book.toast_insurance_saved','Vakuutustiedot tallennettu'),
('fi','common','memory_book.toast_medical_saved','Lääketieteelliset tiedot tallennettu'),
('fi','common','memory_book.toast_prefs_saved','Mieltymykset tallennettu'),
('fi','common','memory_book.toast_provider_added','Palveluntarjoaja lisätty'),
('fi','common','memory_book.toast_provider_failed','Palveluntarjoajan tallentaminen epäonnistui'),
('fi','common','memory_book.toast_provider_removed','Palveluntarjoaja poistettu'),
('fi','common','memory_book.toast_provider_updated','Palveluntarjoaja päivitetty'),
('fi','common','memory_book.toast_social_added','Tili lisätty'),
('fi','common','memory_book.toast_social_removed','Tili poistettu'),
('fi','common','memory_book.toast_social_updated','Tili päivitetty'),
('fi','common','memory_book.toast_sub_added','Tilaus lisätty'),
('fi','common','memory_book.toast_sub_removed','Tilaus poistettu'),
('fi','common','memory_book.toast_sub_updated','Tilaus päivitetty'),
('fi','common','memory_book.toast_subscription_added','Tilaus lisätty'),
('fi','common','memory_book.toast_subscription_removed','Tilaus poistettu'),
('fi','common','memory_book.toast_subscription_updated','Tilaus päivitetty'),

-- ============================================================
-- JAPANESE (ja)
-- ============================================================
('ja','common','memory_book.cancel','キャンセル'),
('ja','common','memory_book.confirm_remove_contact','{name}を連絡先から削除しますか？'),
('ja','common','memory_book.confirm_remove_provider','{name}をプロバイダーから削除しますか？'),
('ja','common','memory_book.confirm_remove_social','{platform}アカウントを削除しますか？'),
('ja','common','memory_book.confirm_remove_sub','{name}を削除しますか？'),
('ja','common','memory_book.confirm_remove_subscription','{name}を削除しますか？'),
('ja','common','memory_book.confirm_remove_vehicle','{name}を削除しますか？'),
('ja','common','memory_book.contact_fallback_label','連絡先'),
('ja','common','memory_book.contact_save_btn','連絡先を保存'),
('ja','common','memory_book.contacts_add_btn','連絡先を追加'),
('ja','common','memory_book.contacts_add_first_btn','最初の連絡先を追加'),
('ja','common','memory_book.contacts_count_many','{count}件の連絡先'),
('ja','common','memory_book.contacts_count_one','1件の連絡先'),
('ja','common','memory_book.contacts_edit_heading','連絡先を編集'),
('ja','common','memory_book.contacts_empty_desc','家族、医師、緊急連絡先、その他の重要な支援者を追加して、ケアギバーが適切な人に素早く連絡できるようにしましょう。'),
('ja','common','memory_book.contacts_empty_title','まだ連絡先が追加されていません'),
('ja','common','memory_book.contacts_new_heading','新しい連絡先'),
('ja','common','memory_book.contacts_title','ケアネットワーク & 連絡先'),
('ja','common','memory_book.edit','編集'),
('ja','common','memory_book.finances_add_btn','財務情報を追加'),
('ja','common','memory_book.finances_locked_title','オーナーのみアクセス可能'),
('ja','common','memory_book.finances_owner_only_notice','このセクションはチームオーナーのみ閲覧できます。'),
('ja','common','memory_book.finances_subtitle','銀行情報、収入源、自動引き落とし請求'),
('ja','common','memory_book.finances_title','収入 & 財務'),
('ja','common','memory_book.household_section_finances','財務'),
('ja','common','memory_book.household_section_insurance','保険'),
('ja','common','memory_book.household_section_providers','医療機関'),
('ja','common','memory_book.household_section_subscriptions','サブスクリプション'),
('ja','common','memory_book.household_section_vehicle','車両 & 交通'),
('ja','common','memory_book.identity_add_btn','身元情報を追加'),
('ja','common','memory_book.identity_empty_member_title','身元情報がまだ入力されていません'),
('ja','common','memory_book.identity_empty_owner_title','身元情報を追加'),
('ja','common','memory_book.identity_subtitle','{patientName}の個人情報'),
('ja','common','memory_book.identity_title','身元 & プロフィール'),
('ja','common','memory_book.insurance_add_btn','保険情報を追加'),
('ja','common','memory_book.insurance_dental_heading','歯科 & 視力保険'),
('ja','common','memory_book.insurance_dental_vision_heading','歯科 & 視力保険'),
('ja','common','memory_book.insurance_empty_member_title','保険情報がまだ入力されていません'),
('ja','common','memory_book.insurance_empty_owner_title','保険情報を追加'),
('ja','common','memory_book.insurance_primary_heading','主保険'),
('ja','common','memory_book.insurance_secondary_heading','副保険'),
('ja','common','memory_book.insurance_subtitle','主保険、副保険、歯科・視力保険'),
('ja','common','memory_book.insurance_title','健康保険'),
('ja','common','memory_book.medical_add_btn','医療情報を追加'),
('ja','common','memory_book.medical_empty_member_title','医療情報がまだ入力されていません'),
('ja','common','memory_book.medical_empty_owner_title','医療コンテキストを追加'),
('ja','common','memory_book.medical_subtitle','ケアギバー向け健康情報 — 臨床記録ではありません'),
('ja','common','memory_book.medical_title','医療コンテキスト'),
('ja','common','memory_book.overview_age','年齢 {age}'),
('ja','common','memory_book.overview_incomplete_title','思い出の本が未完成'),
('ja','common','memory_book.overview_not_started','未開始'),
('ja','common','memory_book.overview_progress_title','思い出の本の進捗'),
('ja','common','memory_book.overview_records_many','{count}件の記録'),
('ja','common','memory_book.overview_records_one','1件の記録'),
('ja','common','memory_book.overview_sections_count','{completed}/{total}セクション'),
('ja','common','memory_book.prefs_add_btn','好みを追加'),
('ja','common','memory_book.prefs_empty_member_title','好みがまだ入力されていません'),
('ja','common','memory_book.prefs_empty_owner_title','好き・嫌い・慰めを追加'),
('ja','common','memory_book.prefs_subtitle','喜び、慰め、避けるべきことをまとめます'),
('ja','common','memory_book.prefs_title','好み・嫌い・慰め'),
('ja','common','memory_book.print_btn','思い出の本を印刷'),
('ja','common','memory_book.print_confidential','機密 — ケアチーム専用'),
('ja','common','memory_book.print_generated','作成日'),
('ja','common','memory_book.print_no_data','まだ情報が記録されていません。'),
('ja','common','memory_book.print_title','思い出の本'),
('ja','common','memory_book.provider_primary_badge','主要'),
('ja','common','memory_book.provider_save_btn','プロバイダーを保存'),
('ja','common','memory_book.providers_add_btn','プロバイダーを追加'),
('ja','common','memory_book.providers_add_first_btn','最初のプロバイダーを追加'),
('ja','common','memory_book.providers_count_many','{count}件のプロバイダー'),
('ja','common','memory_book.providers_count_one','1件のプロバイダー'),
('ja','common','memory_book.providers_edit_heading','プロバイダーを編集'),
('ja','common','memory_book.providers_empty_desc','医師、歯科医、薬局、専門医を追加して、ケアギバーが常に誰に連絡すべきかを把握できるようにしましょう。'),
('ja','common','memory_book.providers_empty_title','まだプロバイダーが追加されていません'),
('ja','common','memory_book.providers_new_heading','新しいプロバイダー'),
('ja','common','memory_book.providers_subtitle','医師、歯科医、薬局、専門医'),
('ja','common','memory_book.providers_title','医療プロバイダー'),
('ja','common','memory_book.readonly_notice','このセクションへの閲覧アクセスがあります。変更はチームオーナーのみが行えます。'),
('ja','common','memory_book.save_changes','変更を保存'),
('ja','common','memory_book.saving','保存中...'),
('ja','common','memory_book.section_contacts','連絡先'),
('ja','common','memory_book.section_household','家庭'),
('ja','common','memory_book.section_identity','身元'),
('ja','common','memory_book.section_medical','医療'),
('ja','common','memory_book.section_preferences','好き・嫌い'),
('ja','common','memory_book.social_add_btn','アカウントを追加'),
('ja','common','memory_book.social_empty_title','まだオンラインアカウントが追加されていません'),
('ja','common','memory_book.social_title','ソーシャルメディア & オンラインアカウント'),
('ja','common','memory_book.subs_add_btn','サブスクリプションを追加'),
('ja','common','memory_book.subs_title','サブスクリプション & 会員'),
('ja','common','memory_book.subscriptions_title','サブスクリプション & 会員'),
('ja','common','memory_book.tab_household','家庭'),
('ja','common','memory_book.toast_contact_added','連絡先を追加しました'),
('ja','common','memory_book.toast_contact_failed','連絡先の保存に失敗しました'),
('ja','common','memory_book.toast_contact_removed','連絡先を削除しました'),
('ja','common','memory_book.toast_contact_updated','連絡先を更新しました'),
('ja','common','memory_book.toast_finances_saved','財務情報を保存しました'),
('ja','common','memory_book.toast_identity_saved','身元情報を保存しました'),
('ja','common','memory_book.toast_insurance_saved','保険情報を保存しました'),
('ja','common','memory_book.toast_medical_saved','医療情報を保存しました'),
('ja','common','memory_book.toast_prefs_saved','好みを保存しました'),
('ja','common','memory_book.toast_provider_added','プロバイダーを追加しました'),
('ja','common','memory_book.toast_provider_failed','プロバイダーの保存に失敗しました'),
('ja','common','memory_book.toast_provider_removed','プロバイダーを削除しました'),
('ja','common','memory_book.toast_provider_updated','プロバイダーを更新しました'),
('ja','common','memory_book.toast_social_added','アカウントを追加しました'),
('ja','common','memory_book.toast_social_removed','アカウントを削除しました'),
('ja','common','memory_book.toast_social_updated','アカウントを更新しました'),
('ja','common','memory_book.toast_sub_added','サブスクリプションを追加しました'),
('ja','common','memory_book.toast_sub_removed','サブスクリプションを削除しました'),
('ja','common','memory_book.toast_sub_updated','サブスクリプションを更新しました'),
('ja','common','memory_book.toast_subscription_added','サブスクリプションを追加しました'),
('ja','common','memory_book.toast_subscription_removed','サブスクリプションを削除しました'),
('ja','common','memory_book.toast_subscription_updated','サブスクリプションを更新しました')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
