-- Phase 2: Japanese translations for memory_book_page namespace
INSERT INTO ui_translations (locale, key, value) VALUES
('ja', 'memory_book_page.abt_label', 'About'),
('ja', 'memory_book_page.add_page_cta', 'Add custom page'),
('ja', 'memory_book_page.add_page_heading', 'Custom Pages'),
('ja', 'memory_book_page.age_with_value', 'Age {age}'),
('ja', 'memory_book_page.all_pages', 'All Pages'),
('ja', 'memory_book_page.back_to_mb', 'Back to Memory Book'),
('ja', 'memory_book_page.back_to_pages', 'Back to pages'),
('ja', 'memory_book_page.beta_label', 'Beta'),
('ja', 'memory_book_page.breadcrumb_mb', 'Memory Book'),
('ja', 'memory_book_page.breadcrumb_page', 'Pages'),
('ja', 'memory_book_page.color_picker_label', 'Page color'),
('ja', 'memory_book_page.completed_sections', '{n} sections completed'),
('ja', 'memory_book_page.content_field_label', 'Content'),
('ja', 'memory_book_page.content_placeholder', 'Add content here'),
('ja', 'memory_book_page.create_page_cta', 'Create page'),
('ja', 'memory_book_page.custom_pages_heading', 'Custom pages'),
('ja', 'memory_book_page.custom_page_color_hint', 'Choose a color for this custom page'),
('ja', 'memory_book_page.custom_page_title_hint', 'Enter a title for this custom page'),
('ja', 'memory_book_page.delete_page_button', 'Delete page'),
('ja', 'memory_book_page.delete_page_confirm', 'Delete this page'),
('ja', 'memory_book_page.delete_page_confirm_subtitle', 'This action cannot be undone.'),
('ja', 'memory_book_page.description', 'Add custom pages or reference built-in sections'),
('ja', 'memory_book_page.editing_disabled_archived', 'Memory Books that have been archived cannot be edited.'),
('ja', 'memory_book_page.editing_disabled_template', 'Template Memory Books cannot be edited.'),
('ja', 'memory_book_page.error_missing_title', 'Page title is required'),
('ja', 'memory_book_page.heading', 'Pages'),
('ja', 'memory_book_page.last_updated', 'Last updated'),
('ja', 'memory_book_page.mb_archive_label', 'Archived'),
('ja', 'memory_book_page.mb_created_label', 'Created'),
('ja', 'memory_book_page.mb_draft_label', 'Draft'),
('ja', 'memory_book_page.mb_owners_label', 'Managed by'),
('ja', 'memory_book_page.mb_resident_label', 'For'),
('ja', 'memory_book_page.mb_status_active', 'Active'),
('ja', 'memory_book_page.mb_status_archived', 'Archived'),
('ja', 'memory_book_page.mb_status_draft', 'Draft'),
('ja', 'memory_book_page.nav_label', 'Pages'),
('ja', 'memory_book_page.nav_label_all_pages', 'All pages'),
('ja', 'memory_book_page.nav_label_profile', 'Profile'),
('ja', 'memory_book_page.no_custom_pages', 'No custom pages yet'),
('ja', 'memory_book_page.no_custom_pages_subtitle', 'Create a custom page to get started'),
('ja', 'memory_book_page.no_memory_books', 'No Memory Books'),
('ja', 'memory_book_page.page_title', 'Memory Book Pages'),
('ja', 'memory_book_page.pages_help_content', 'Add links to custom pages or one of the built-in sections'),
('ja', 'memory_book_page.pages_help_heading', 'Custom and standard pages'),
('ja', 'memory_book_page.read_only_archived', 'Archived'),
('ja', 'memory_book_page.read_only_template', 'Template'),
('ja', 'memory_book_page.save_changes_cta', 'Save changes'),
('ja', 'memory_book_page.save_page_cta', 'Save page'),
('ja', 'memory_book_page.section_pages', 'Pages'),
('ja', 'memory_book_page.title_field_label', 'Page title'),
('ja', 'memory_book_page.title_placeholder', 'Enter page title'),
('ja', 'memory_book_page.view_memory_book', 'View Memory Book')
ON CONFLICT (locale, namespace, key) DO NOTHING;