
INSERT INTO ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- English
-- ============================================================
('en','common','memory_book.social_title','Social Media & Online Accounts'),
('en','common','memory_book.social_count_one','1 account on file'),
('en','common','memory_book.social_count_many','{count} accounts on file'),
('en','common','memory_book.social_add_btn','Add Account'),
('en','common','memory_book.social_add_first_btn','Add First Account'),
('en','common','memory_book.social_empty_title','No online accounts added yet'),
('en','common','memory_book.social_empty_desc','Record social media profiles, email accounts, and other online services so family members can manage them when needed.'),
('en','common','memory_book.social_edit_heading','Edit Account'),
('en','common','memory_book.social_new_heading','New Account'),
('en','common','memory_book.field_social_platform','Platform *'),
('en','common','memory_book.field_social_platform_select','Select a platform'),
('en','common','memory_book.field_social_custom_platform','Platform Name *'),
('en','common','memory_book.field_social_custom_platform_placeholder','e.g. MySpace, Clubhouse, Flickr'),
('en','common','memory_book.field_social_username','Username / Handle / Email'),
('en','common','memory_book.field_social_username_placeholder','e.g. @johndoe or john@example.com'),
('en','common','memory_book.field_social_url','Profile URL'),
('en','common','memory_book.field_social_url_placeholder','e.g. https://facebook.com/johndoe'),
('en','common','memory_book.field_social_notes_placeholder','e.g. Managed by daughter Jane, password hint in safe'),
('en','common','memory_book.toast_social_added','Account added'),
('en','common','memory_book.toast_social_updated','Account updated'),
('en','common','memory_book.toast_social_removed','Account removed'),
('en','common','memory_book.toast_social_platform_required','Platform is required'),
('en','common','memory_book.confirm_remove_social','Remove {platform} account?'),

-- ============================================================
-- Spanish
-- ============================================================
('es','common','memory_book.social_title','Redes Sociales y Cuentas en Línea'),
('es','common','memory_book.social_count_one','1 cuenta registrada'),
('es','common','memory_book.social_count_many','{count} cuentas registradas'),
('es','common','memory_book.social_add_btn','Añadir Cuenta'),
('es','common','memory_book.social_add_first_btn','Añadir Primera Cuenta'),
('es','common','memory_book.social_empty_title','Sin cuentas en línea registradas'),
('es','common','memory_book.social_empty_desc','Registre perfiles de redes sociales, cuentas de correo y otros servicios en línea para que los familiares puedan gestionarlos cuando sea necesario.'),
('es','common','memory_book.social_edit_heading','Editar Cuenta'),
('es','common','memory_book.social_new_heading','Nueva Cuenta'),
('es','common','memory_book.field_social_platform','Plataforma *'),
('es','common','memory_book.field_social_platform_select','Seleccionar plataforma'),
('es','common','memory_book.field_social_custom_platform','Nombre de la Plataforma *'),
('es','common','memory_book.field_social_custom_platform_placeholder','p.ej. MySpace, Clubhouse, Flickr'),
('es','common','memory_book.field_social_username','Usuario / Alias / Correo'),
('es','common','memory_book.field_social_username_placeholder','p.ej. @juanperez o juan@ejemplo.com'),
('es','common','memory_book.field_social_url','URL del Perfil'),
('es','common','memory_book.field_social_url_placeholder','p.ej. https://facebook.com/juanperez'),
('es','common','memory_book.field_social_notes_placeholder','p.ej. Gestionado por la hija Ana, pista de contraseña en la caja fuerte'),
('es','common','memory_book.toast_social_added','Cuenta añadida'),
('es','common','memory_book.toast_social_updated','Cuenta actualizada'),
('es','common','memory_book.toast_social_removed','Cuenta eliminada'),
('es','common','memory_book.toast_social_platform_required','La plataforma es obligatoria'),
('es','common','memory_book.confirm_remove_social','¿Eliminar cuenta de {platform}?'),

-- ============================================================
-- Italian
-- ============================================================
('it','common','memory_book.social_title','Social Media e Account Online'),
('it','common','memory_book.social_count_one','1 account registrato'),
('it','common','memory_book.social_count_many','{count} account registrati'),
('it','common','memory_book.social_add_btn','Aggiungi Account'),
('it','common','memory_book.social_add_first_btn','Aggiungi Primo Account'),
('it','common','memory_book.social_empty_title','Nessun account online aggiunto'),
('it','common','memory_book.social_empty_desc','Registra profili social, account email e altri servizi online in modo che i familiari possano gestirli quando necessario.'),
('it','common','memory_book.social_edit_heading','Modifica Account'),
('it','common','memory_book.social_new_heading','Nuovo Account'),
('it','common','memory_book.field_social_platform','Piattaforma *'),
('it','common','memory_book.field_social_platform_select','Seleziona una piattaforma'),
('it','common','memory_book.field_social_custom_platform','Nome della Piattaforma *'),
('it','common','memory_book.field_social_custom_platform_placeholder','es. MySpace, Clubhouse, Flickr'),
('it','common','memory_book.field_social_username','Nome utente / Handle / Email'),
('it','common','memory_book.field_social_username_placeholder','es. @mariorossi o mario@esempio.com'),
('it','common','memory_book.field_social_url','URL del Profilo'),
('it','common','memory_book.field_social_url_placeholder','es. https://facebook.com/mariorossi'),
('it','common','memory_book.field_social_notes_placeholder','es. Gestito dalla figlia Maria, suggerimento password nella cassaforte'),
('it','common','memory_book.toast_social_added','Account aggiunto'),
('it','common','memory_book.toast_social_updated','Account aggiornato'),
('it','common','memory_book.toast_social_removed','Account rimosso'),
('it','common','memory_book.toast_social_platform_required','La piattaforma è obbligatoria'),
('it','common','memory_book.confirm_remove_social','Rimuovere account {platform}?'),

-- ============================================================
-- French
-- ============================================================
('fr','common','memory_book.social_title','Réseaux Sociaux et Comptes en Ligne'),
('fr','common','memory_book.social_count_one','1 compte enregistré'),
('fr','common','memory_book.social_count_many','{count} comptes enregistrés'),
('fr','common','memory_book.social_add_btn','Ajouter un Compte'),
('fr','common','memory_book.social_add_first_btn','Ajouter le Premier Compte'),
('fr','common','memory_book.social_empty_title','Aucun compte en ligne enregistré'),
('fr','common','memory_book.social_empty_desc','Enregistrez les profils de réseaux sociaux, comptes e-mail et autres services en ligne afin que les proches puissent les gérer si nécessaire.'),
('fr','common','memory_book.social_edit_heading','Modifier le Compte'),
('fr','common','memory_book.social_new_heading','Nouveau Compte'),
('fr','common','memory_book.field_social_platform','Plateforme *'),
('fr','common','memory_book.field_social_platform_select','Sélectionner une plateforme'),
('fr','common','memory_book.field_social_custom_platform','Nom de la Plateforme *'),
('fr','common','memory_book.field_social_custom_platform_placeholder','ex. MySpace, Clubhouse, Flickr'),
('fr','common','memory_book.field_social_username','Nom d''utilisateur / Pseudo / E-mail'),
('fr','common','memory_book.field_social_username_placeholder','ex. @jeandupon ou jean@exemple.com'),
('fr','common','memory_book.field_social_url','URL du Profil'),
('fr','common','memory_book.field_social_url_placeholder','ex. https://facebook.com/jeandupon'),
('fr','common','memory_book.field_social_notes_placeholder','ex. Géré par la fille Marie, indice de mot de passe dans le coffre'),
('fr','common','memory_book.toast_social_added','Compte ajouté'),
('fr','common','memory_book.toast_social_updated','Compte mis à jour'),
('fr','common','memory_book.toast_social_removed','Compte supprimé'),
('fr','common','memory_book.toast_social_platform_required','La plateforme est obligatoire'),
('fr','common','memory_book.confirm_remove_social','Supprimer le compte {platform} ?'),

-- ============================================================
-- German
-- ============================================================
('de','common','memory_book.social_title','Soziale Medien & Online-Konten'),
('de','common','memory_book.social_count_one','1 Konto eingetragen'),
('de','common','memory_book.social_count_many','{count} Konten eingetragen'),
('de','common','memory_book.social_add_btn','Konto hinzufügen'),
('de','common','memory_book.social_add_first_btn','Erstes Konto hinzufügen'),
('de','common','memory_book.social_empty_title','Noch keine Online-Konten eingetragen'),
('de','common','memory_book.social_empty_desc','Erfassen Sie Social-Media-Profile, E-Mail-Konten und andere Online-Dienste, damit Familienmitglieder diese bei Bedarf verwalten können.'),
('de','common','memory_book.social_edit_heading','Konto bearbeiten'),
('de','common','memory_book.social_new_heading','Neues Konto'),
('de','common','memory_book.field_social_platform','Plattform *'),
('de','common','memory_book.field_social_platform_select','Plattform auswählen'),
('de','common','memory_book.field_social_custom_platform','Plattformname *'),
('de','common','memory_book.field_social_custom_platform_placeholder','z.B. MySpace, Clubhouse, Flickr'),
('de','common','memory_book.field_social_username','Benutzername / Handle / E-Mail'),
('de','common','memory_book.field_social_username_placeholder','z.B. @hansmüller oder hans@beispiel.de'),
('de','common','memory_book.field_social_url','Profil-URL'),
('de','common','memory_book.field_social_url_placeholder','z.B. https://facebook.com/hansmueller'),
('de','common','memory_book.field_social_notes_placeholder','z.B. Verwaltet von Tochter Maria, Passworthinweis im Safe'),
('de','common','memory_book.toast_social_added','Konto hinzugefügt'),
('de','common','memory_book.toast_social_updated','Konto aktualisiert'),
('de','common','memory_book.toast_social_removed','Konto entfernt'),
('de','common','memory_book.toast_social_platform_required','Plattform ist erforderlich'),
('de','common','memory_book.confirm_remove_social','{platform}-Konto entfernen?'),

-- ============================================================
-- Swedish
-- ============================================================
('sv','common','memory_book.social_title','Sociala Medier & Onlinekonton'),
('sv','common','memory_book.social_count_one','1 konto registrerat'),
('sv','common','memory_book.social_count_many','{count} konton registrerade'),
('sv','common','memory_book.social_add_btn','Lägg till Konto'),
('sv','common','memory_book.social_add_first_btn','Lägg till Första Konto'),
('sv','common','memory_book.social_empty_title','Inga onlinekonton tillagda ännu'),
('sv','common','memory_book.social_empty_desc','Registrera profiler på sociala medier, e-postkonton och andra onlinetjänster så att familjemedlemmar kan hantera dem vid behov.'),
('sv','common','memory_book.social_edit_heading','Redigera Konto'),
('sv','common','memory_book.social_new_heading','Nytt Konto'),
('sv','common','memory_book.field_social_platform','Plattform *'),
('sv','common','memory_book.field_social_platform_select','Välj en plattform'),
('sv','common','memory_book.field_social_custom_platform','Plattformnamn *'),
('sv','common','memory_book.field_social_custom_platform_placeholder','t.ex. MySpace, Clubhouse, Flickr'),
('sv','common','memory_book.field_social_username','Användarnamn / Handle / E-post'),
('sv','common','memory_book.field_social_username_placeholder','t.ex. @eriksson eller erik@exempel.se'),
('sv','common','memory_book.field_social_url','Profil-URL'),
('sv','common','memory_book.field_social_url_placeholder','t.ex. https://facebook.com/eriksson'),
('sv','common','memory_book.field_social_notes_placeholder','t.ex. Hanteras av dotter Anna, lösenordstips i kassaskåpet'),
('sv','common','memory_book.toast_social_added','Konto tillagt'),
('sv','common','memory_book.toast_social_updated','Konto uppdaterat'),
('sv','common','memory_book.toast_social_removed','Konto borttaget'),
('sv','common','memory_book.toast_social_platform_required','Plattform krävs'),
('sv','common','memory_book.confirm_remove_social','Ta bort {platform}-konto?'),

-- ============================================================
-- Finnish
-- ============================================================
('fi','common','memory_book.social_title','Sosiaalinen Media & Verkkotilit'),
('fi','common','memory_book.social_count_one','1 tili rekisteröity'),
('fi','common','memory_book.social_count_many','{count} tiliä rekisteröity'),
('fi','common','memory_book.social_add_btn','Lisää Tili'),
('fi','common','memory_book.social_add_first_btn','Lisää Ensimmäinen Tili'),
('fi','common','memory_book.social_empty_title','Ei verkkotilejä vielä'),
('fi','common','memory_book.social_empty_desc','Kirjaa sosiaalisen median profiilit, sähköpostitilit ja muut verkkopalvelut, jotta perheenjäsenet voivat hallita niitä tarvittaessa.'),
('fi','common','memory_book.social_edit_heading','Muokkaa Tiliä'),
('fi','common','memory_book.social_new_heading','Uusi Tili'),
('fi','common','memory_book.field_social_platform','Alusta *'),
('fi','common','memory_book.field_social_platform_select','Valitse alusta'),
('fi','common','memory_book.field_social_custom_platform','Alustan nimi *'),
('fi','common','memory_book.field_social_custom_platform_placeholder','esim. MySpace, Clubhouse, Flickr'),
('fi','common','memory_book.field_social_username','Käyttäjänimi / Handle / Sähköposti'),
('fi','common','memory_book.field_social_username_placeholder','esim. @makkonen tai matti@esimerkki.fi'),
('fi','common','memory_book.field_social_url','Profiilin URL'),
('fi','common','memory_book.field_social_url_placeholder','esim. https://facebook.com/makkonen'),
('fi','common','memory_book.field_social_notes_placeholder','esim. Tytär Anna hoitaa, salasanavinkki kassakaapissa'),
('fi','common','memory_book.toast_social_added','Tili lisätty'),
('fi','common','memory_book.toast_social_updated','Tili päivitetty'),
('fi','common','memory_book.toast_social_removed','Tili poistettu'),
('fi','common','memory_book.toast_social_platform_required','Alusta vaaditaan'),
('fi','common','memory_book.confirm_remove_social','Poista {platform}-tili?')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
