-- Translation Batch 5: care_plan.* and care_hub.* keys for all 7 non-EN locales

INSERT INTO public.ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- SPANISH (es)
-- ============================================================
('es','common','care_hub.title','Centro de Cuidado'),
('es','common','care_plan.all_complete_no_gaps','Todas las secciones completas — no se identificaron brechas.'),
('es','common','care_plan.all_sections_complete','Todas las secciones completas'),
('es','common','care_plan.auth_emergency','Preparación para emergencias'),
('es','common','care_plan.auth_financial','Autoridad financiera'),
('es','common','care_plan.auth_health','Autoridad en decisiones de salud'),
('es','common','care_plan.auth_legal','Documentos legales'),
('es','common','care_plan.auth_preferences','Preferencias de cuidado documentadas'),
('es','common','care_plan.auth_records','Registros organizados'),
('es','common','care_plan.authority_preamble','La autoridad debe establecerse, no asumirse. Ser el familiar más cercano no significa automáticamente tener autoridad legal sobre las decisiones de salud, finanzas o registros.'),
('es','common','care_plan.authority_status_confirmed','Confirmado'),
('es','common','care_plan.authority_status_missing','Faltante'),
('es','common','care_plan.authority_status_not_applicable','No aplica'),
('es','common','care_plan.authority_status_unclear','No claro'),
('es','common','care_plan.backup_label','Suplente'),
('es','common','care_plan.care_plan_for','Plan de cuidado para'),
('es','common','care_plan.continue_building','Continuar construyendo'),
('es','common','care_plan.create_button','Crear Plan de Cuidado'),
('es','common','care_plan.creating','Creando...'),
('es','common','care_plan.critical_alert','{count} brecha{plural} crítica{plural} necesitan atención'),
('es','common','care_plan.cta_continue','Continuar'),
('es','common','care_plan.cta_open','Abrir'),
('es','common','care_plan.cta_review','Revisar'),
('es','common','care_plan.cta_start','Comenzar'),
('es','common','care_plan.description','El Plan de Cuidado es el plan operativo general del equipo de cuidado. Cubre quién es responsable de qué, qué autoridad existe, cómo se organizará el cuidado y cuándo debe revisarse el plan.'),
('es','common','care_plan.edit_care_plan','Editar Plan de Cuidado'),
('es','common','care_plan.gap_count','{count} brecha{plural}'),
('es','common','care_plan.gap_critical','{count} brecha{plural} crítica{plural}'),
('es','common','care_plan.gap_important','{count} importante{plural}'),
('es','common','care_plan.gap_monitor','{count} para monitorear'),
('es','common','care_plan.gaps_identified','{count} brecha{plural} identificada{plural}'),
('es','common','care_plan.generated_on','Generado {date}'),
('es','common','care_plan.go_to_dashboard','Ir al Panel de Control'),
('es','common','care_plan.living_alternatives','Alternativas siendo consideradas'),
('es','common','care_plan.living_arrangement_label','Arreglo'),
('es','common','care_plan.living_assisted','Vida asistida o cuidado residencial'),
('es','common','care_plan.living_constraints','Restricciones financieras / familiares'),
('es','common','care_plan.living_family_home','El residente se muda a la casa familiar'),
('es','common','care_plan.living_paid_in_home','Apoyo en casa pagado'),
('es','common','care_plan.living_resident_home','El residente permanece en su propia casa'),
('es','common','care_plan.living_safety','Problemas de seguridad'),
('es','common','care_plan.living_triggers','Factores desencadenantes del cambio'),
('es','common','care_plan.living_undecided','Sin decidir / aún evaluando'),
('es','common','care_plan.living_working_label','Funcionando'),
('es','common','care_plan.load_error','No se puede cargar el Plan de Cuidado. Por favor actualiza la página.'),
('es','common','care_plan.memory_book_desc','Conocer a la persona — identidad, salud, preferencias'),
('es','common','care_plan.memory_book_label','Libro de Memoria'),
('es','common','care_plan.modal_back','Atrás'),
('es','common','care_plan.modal_close','Cerrar'),
('es','common','care_plan.modal_mark_complete','Marcar como completo'),
('es','common','care_plan.modal_read_only_notice','Puedes ver esta sección pero solo el propietario del equipo puede hacer cambios.'),
('es','common','care_plan.modal_save','Guardar'),
('es','common','care_plan.modal_save_error','El guardado falló. Verifica tu conexión e inténtalo de nuevo.'),
('es','common','care_plan.modal_saved','Guardado'),
('es','common','care_plan.modal_saving','Guardando...'),
('es','common','care_plan.modal_section_of','Sección {current} de {total}'),
('es','common','care_plan.modal_unsaved_changes','Tienes cambios sin guardar. ¿Salir sin guardar?'),
('es','common','care_plan.more_gaps','más'),
('es','common','care_plan.no_gaps_incomplete','No hay brechas en las secciones completadas. {remaining} sección{plural} todavía por completar.'),
('es','common','care_plan.no_plan_body','El propietario del equipo de cuidado aún no ha creado un Plan de Cuidado. Vuelve más tarde.'),
('es','common','care_plan.no_plan_title','Aún no hay Plan de Cuidado'),
('es','common','care_plan.no_team_body','El Plan de Cuidado está vinculado a tu equipo de cuidado. Configura primero tu equipo de cuidado para comenzar.'),
('es','common','care_plan.no_team_title','No se encontró equipo de cuidado'),
('es','common','care_plan.not_filled_in','no completado'),
('es','common','care_plan.observations_desc','Seguimiento del cambio — notas funcionales del día a día'),
('es','common','care_plan.observations_label','Observaciones'),
('es','common','care_plan.of_total_sections','de {total} secciones completas'),
('es','common','care_plan.of_total_sections_count','{completed} de {total} secciones completas'),
('es','common','care_plan.open_memory_book','Abrir Libro de Memoria'),
('es','common','care_plan.owner_label','Propietario'),
('es','common','care_plan.print','Imprimir'),
('es','common','care_plan.print_summary','Imprimir resumen'),
('es','common','care_plan.progress_label','{completed} de {total} secciones completas'),
('es','common','care_plan.resident_fallback','residente'),
('es','common','care_plan.resp_admin','Administración'),
('es','common','care_plan.resp_emotional','Apoyo emocional'),
('es','common','care_plan.resp_health','Coordinación de salud'),
('es','common','care_plan.resp_household','Apoyo doméstico'),
('es','common','care_plan.resp_personal_care','Cuidado personal'),
('es','common','care_plan.resp_respite','Suplente / descanso'),
('es','common','care_plan.resp_scheduling','Citas'),
('es','common','care_plan.section_authority','Autoridad'),
('es','common','care_plan.section_living_arrangement','Arreglo de Vida'),
('es','common','care_plan.section_responsibilities','Responsabilidades'),
('es','common','care_plan.section_review','Revisión'),
('es','common','care_plan.section_situation','Situación'),
('es','common','care_plan.section_sustainability','Sostenibilidad'),
('es','common','care_plan.situation_concerns','Principales preocupaciones'),
('es','common','care_plan.situation_current','Situación actual'),
('es','common','care_plan.start_body','Tu equipo aún no tiene un Plan de Cuidado. Crea uno para coordinar responsabilidades, autoridad y arreglos de vida.'),
('es','common','care_plan.start_building','Comenzar a construir'),
('es','common','care_plan.start_title','Inicia tu Plan de Cuidado'),
('es','common','care_plan.status_complete','Completo'),
('es','common','care_plan.status_in_progress','En progreso'),
('es','common','care_plan.status_not_started','No iniciado'),
('es','common','care_plan.subtitle','Coordinar al equipo'),
('es','common','care_plan.summary_breadcrumb','Resumen'),
('es','common','care_plan.summary_title','Resumen del Plan de Cuidado'),
('es','common','care_plan.title','Plan de Cuidado'),
('es','common','care_plan.view_summary','Ver resumen'),
('es','common','care_plan.view_summary_full','Ver Resumen del Plan de Cuidado'),
('es','common','care_plan.view_summary_partial','Ver resumen parcial'),

-- ============================================================
-- FRENCH (fr)
-- ============================================================
('fr','common','care_hub.title','Centre de soins'),
('fr','common','care_plan.all_complete_no_gaps','Toutes les sections complètes — aucune lacune identifiée.'),
('fr','common','care_plan.all_sections_complete','Toutes les sections complètes'),
('fr','common','care_plan.authority_status_confirmed','Confirmé'),
('fr','common','care_plan.authority_status_missing','Manquant'),
('fr','common','care_plan.authority_status_not_applicable','Non applicable'),
('fr','common','care_plan.authority_status_unclear','Peu clair'),
('fr','common','care_plan.backup_label','Suppléant'),
('fr','common','care_plan.care_plan_for','Plan de soins pour'),
('fr','common','care_plan.continue_building','Continuer à construire'),
('fr','common','care_plan.create_button','Créer un plan de soins'),
('fr','common','care_plan.creating','Création en cours...'),
('fr','common','care_plan.cta_continue','Continuer'),
('fr','common','care_plan.cta_open','Ouvrir'),
('fr','common','care_plan.cta_review','Réviser'),
('fr','common','care_plan.cta_start','Commencer'),
('fr','common','care_plan.description','Le Plan de soins est le plan opérationnel global de l''équipe soignante. Il couvre qui est responsable de quoi, quelle autorité existe, comment les soins seront organisés et quand le plan devrait être révisé.'),
('fr','common','care_plan.edit_care_plan','Modifier le plan de soins'),
('fr','common','care_plan.generated_on','Généré le {date}'),
('fr','common','care_plan.go_to_dashboard','Aller au tableau de bord'),
('fr','common','care_plan.living_alternatives','Alternatives envisagées'),
('fr','common','care_plan.living_assisted','Vie assistée ou soins en résidence'),
('fr','common','care_plan.living_family_home','Le résident s''installe dans une maison familiale'),
('fr','common','care_plan.living_paid_in_home','Soutien à domicile rémunéré'),
('fr','common','care_plan.living_resident_home','Le résident reste dans son propre domicile'),
('fr','common','care_plan.living_undecided','Non décidé / encore en évaluation'),
('fr','common','care_plan.load_error','Impossible de charger le Plan de soins. Veuillez actualiser la page.'),
('fr','common','care_plan.memory_book_label','Livre de mémoire'),
('fr','common','care_plan.modal_back','Retour'),
('fr','common','care_plan.modal_close','Fermer'),
('fr','common','care_plan.modal_mark_complete','Marquer comme complet'),
('fr','common','care_plan.modal_read_only_notice','Vous pouvez voir cette section mais seul le propriétaire de l''équipe peut effectuer des modifications.'),
('fr','common','care_plan.modal_save','Enregistrer'),
('fr','common','care_plan.modal_save_error','Échec de l''enregistrement. Vérifiez votre connexion et réessayez.'),
('fr','common','care_plan.modal_saved','Enregistré'),
('fr','common','care_plan.modal_saving','Enregistrement...'),
('fr','common','care_plan.modal_section_of','Section {current} de {total}'),
('fr','common','care_plan.modal_unsaved_changes','Vous avez des modifications non enregistrées. Quitter sans enregistrer ?'),
('fr','common','care_plan.more_gaps','de plus'),
('fr','common','care_plan.no_plan_body','Le propriétaire de l''équipe soignante n''a pas encore créé de Plan de soins. Revenez plus tard.'),
('fr','common','care_plan.no_plan_title','Pas encore de Plan de soins'),
('fr','common','care_plan.no_team_body','Le Plan de soins est lié à votre équipe soignante. Configurez d''abord votre équipe soignante pour commencer.'),
('fr','common','care_plan.no_team_title','Aucune équipe soignante trouvée'),
('fr','common','care_plan.not_filled_in','non rempli'),
('fr','common','care_plan.observations_label','Observations'),
('fr','common','care_plan.open_memory_book','Ouvrir le livre de mémoire'),
('fr','common','care_plan.owner_label','Propriétaire'),
('fr','common','care_plan.print','Imprimer'),
('fr','common','care_plan.print_summary','Imprimer le résumé'),
('fr','common','care_plan.progress_label','{completed} de {total} sections complètes'),
('fr','common','care_plan.resident_fallback','résident'),
('fr','common','care_plan.resp_admin','Administration'),
('fr','common','care_plan.resp_emotional','Soutien émotionnel'),
('fr','common','care_plan.resp_health','Coordination des soins'),
('fr','common','care_plan.resp_household','Soutien domestique'),
('fr','common','care_plan.resp_personal_care','Soins personnels'),
('fr','common','care_plan.resp_respite','Suppléant / répit'),
('fr','common','care_plan.resp_scheduling','Rendez-vous'),
('fr','common','care_plan.section_authority','Autorité'),
('fr','common','care_plan.section_living_arrangement','Arrangement de vie'),
('fr','common','care_plan.section_responsibilities','Responsabilités'),
('fr','common','care_plan.section_review','Révision'),
('fr','common','care_plan.section_situation','Situation'),
('fr','common','care_plan.section_sustainability','Durabilité'),
('fr','common','care_plan.situation_concerns','Principales préoccupations'),
('fr','common','care_plan.situation_current','Situation actuelle'),
('fr','common','care_plan.start_body','Votre équipe n''a pas encore de Plan de soins. Créez-en un pour coordonner les responsabilités, l''autorité et les arrangements de vie.'),
('fr','common','care_plan.start_building','Commencer à construire'),
('fr','common','care_plan.start_title','Commencez votre Plan de soins'),
('fr','common','care_plan.status_complete','Complet'),
('fr','common','care_plan.status_in_progress','En cours'),
('fr','common','care_plan.status_not_started','Non commencé'),
('fr','common','care_plan.subtitle','Coordonner l''équipe'),
('fr','common','care_plan.summary_breadcrumb','Résumé'),
('fr','common','care_plan.summary_title','Résumé du Plan de soins'),
('fr','common','care_plan.title','Plan de soins'),
('fr','common','care_plan.view_summary','Voir le résumé'),
('fr','common','care_plan.view_summary_full','Voir le résumé complet du Plan de soins'),
('fr','common','care_plan.view_summary_partial','Voir le résumé partiel'),

-- ============================================================
-- GERMAN (de)
-- ============================================================
('de','common','care_hub.title','Pflege-Hub'),
('de','common','care_plan.all_complete_no_gaps','Alle Abschnitte vollständig — keine Lücken identifiziert.'),
('de','common','care_plan.all_sections_complete','Alle Abschnitte vollständig'),
('de','common','care_plan.authority_status_confirmed','Bestätigt'),
('de','common','care_plan.authority_status_missing','Fehlend'),
('de','common','care_plan.authority_status_not_applicable','Nicht zutreffend'),
('de','common','care_plan.authority_status_unclear','Unklar'),
('de','common','care_plan.backup_label','Stellvertreter'),
('de','common','care_plan.care_plan_for','Pflegeplan für'),
('de','common','care_plan.continue_building','Weiter aufbauen'),
('de','common','care_plan.create_button','Pflegeplan erstellen'),
('de','common','care_plan.creating','Wird erstellt...'),
('de','common','care_plan.cta_continue','Weiter'),
('de','common','care_plan.cta_open','Öffnen'),
('de','common','care_plan.cta_review','Überprüfen'),
('de','common','care_plan.cta_start','Starten'),
('de','common','care_plan.description','Der Pflegeplan ist der übergeordnete Betriebsplan des Pflegeteams. Er legt fest, wer für was verantwortlich ist, welche Befugnisse bestehen, wie die Pflege organisiert wird und wann der Plan überprüft werden sollte.'),
('de','common','care_plan.edit_care_plan','Pflegeplan bearbeiten'),
('de','common','care_plan.generated_on','Erstellt am {date}'),
('de','common','care_plan.go_to_dashboard','Zum Dashboard'),
('de','common','care_plan.living_alternatives','In Betracht gezogene Alternativen'),
('de','common','care_plan.living_assisted','Betreutes Wohnen oder stationäre Pflege'),
('de','common','care_plan.living_family_home','Bewohner zieht in ein Familienhaus'),
('de','common','care_plan.living_paid_in_home','Bezahlte Unterstützung zu Hause'),
('de','common','care_plan.living_resident_home','Bewohner bleibt im eigenen Zuhause'),
('de','common','care_plan.living_undecided','Unentschieden / noch in Bewertung'),
('de','common','care_plan.load_error','Pflegeplan konnte nicht geladen werden. Bitte lade die Seite neu.'),
('de','common','care_plan.memory_book_label','Erinnerungsbuch'),
('de','common','care_plan.modal_back','Zurück'),
('de','common','care_plan.modal_close','Schließen'),
('de','common','care_plan.modal_mark_complete','Als vollständig markieren'),
('de','common','care_plan.modal_read_only_notice','Du kannst diesen Abschnitt ansehen, aber nur der Teameigentümer kann Änderungen vornehmen.'),
('de','common','care_plan.modal_save','Speichern'),
('de','common','care_plan.modal_save_error','Speichern fehlgeschlagen. Überprüfe deine Verbindung und versuche es erneut.'),
('de','common','care_plan.modal_saved','Gespeichert'),
('de','common','care_plan.modal_saving','Wird gespeichert...'),
('de','common','care_plan.modal_section_of','Abschnitt {current} von {total}'),
('de','common','care_plan.modal_unsaved_changes','Du hast ungespeicherte Änderungen. Ohne Speichern verlassen?'),
('de','common','care_plan.more_gaps','weitere'),
('de','common','care_plan.no_plan_body','Der Pflegeteameigentümer hat noch keinen Pflegeplan erstellt. Schaue später wieder vorbei.'),
('de','common','care_plan.no_plan_title','Noch kein Pflegeplan'),
('de','common','care_plan.no_team_body','Der Pflegeplan ist mit deinem Pflegeteam verknüpft. Richte zuerst dein Pflegeteam ein, um zu beginnen.'),
('de','common','care_plan.no_team_title','Kein Pflegeteam gefunden'),
('de','common','care_plan.not_filled_in','nicht ausgefüllt'),
('de','common','care_plan.observations_label','Beobachtungen'),
('de','common','care_plan.open_memory_book','Erinnerungsbuch öffnen'),
('de','common','care_plan.owner_label','Eigentümer'),
('de','common','care_plan.print','Drucken'),
('de','common','care_plan.print_summary','Zusammenfassung drucken'),
('de','common','care_plan.progress_label','{completed} von {total} Abschnitten vollständig'),
('de','common','care_plan.resident_fallback','Bewohner'),
('de','common','care_plan.resp_admin','Verwaltung'),
('de','common','care_plan.resp_emotional','Emotionale Unterstützung'),
('de','common','care_plan.resp_health','Gesundheitskoordination'),
('de','common','care_plan.resp_household','Haushaltshilfe'),
('de','common','care_plan.resp_personal_care','Körperpflege'),
('de','common','care_plan.resp_respite','Stellvertreter / Auszeit'),
('de','common','care_plan.resp_scheduling','Termine'),
('de','common','care_plan.section_authority','Befugnis'),
('de','common','care_plan.section_living_arrangement','Wohnsituation'),
('de','common','care_plan.section_responsibilities','Verantwortlichkeiten'),
('de','common','care_plan.section_review','Überprüfung'),
('de','common','care_plan.section_situation','Situation'),
('de','common','care_plan.section_sustainability','Nachhaltigkeit'),
('de','common','care_plan.situation_concerns','Hauptanliegen'),
('de','common','care_plan.situation_current','Aktuelle Situation'),
('de','common','care_plan.start_body','Dein Team hat noch keinen Pflegeplan. Erstelle einen, um Verantwortlichkeiten, Befugnisse und Wohnarrangements zu koordinieren.'),
('de','common','care_plan.start_building','Aufbau beginnen'),
('de','common','care_plan.start_title','Starte deinen Pflegeplan'),
('de','common','care_plan.status_complete','Vollständig'),
('de','common','care_plan.status_in_progress','In Bearbeitung'),
('de','common','care_plan.status_not_started','Nicht begonnen'),
('de','common','care_plan.subtitle','Team koordinieren'),
('de','common','care_plan.summary_breadcrumb','Zusammenfassung'),
('de','common','care_plan.summary_title','Pflegeplan-Zusammenfassung'),
('de','common','care_plan.title','Pflegeplan'),
('de','common','care_plan.view_summary','Zusammenfassung anzeigen'),
('de','common','care_plan.view_summary_full','Vollständige Pflegeplan-Zusammenfassung anzeigen'),
('de','common','care_plan.view_summary_partial','Teilzusammenfassung anzeigen'),

-- ============================================================
-- ITALIAN (it)
-- ============================================================
('it','common','care_hub.title','Centro di Cura'),
('it','common','care_plan.all_complete_no_gaps','Tutte le sezioni complete — nessuna lacuna identificata.'),
('it','common','care_plan.all_sections_complete','Tutte le sezioni complete'),
('it','common','care_plan.authority_status_confirmed','Confermato'),
('it','common','care_plan.authority_status_missing','Mancante'),
('it','common','care_plan.authority_status_not_applicable','Non applicabile'),
('it','common','care_plan.authority_status_unclear','Non chiaro'),
('it','common','care_plan.backup_label','Supplente'),
('it','common','care_plan.care_plan_for','Piano di cura per'),
('it','common','care_plan.continue_building','Continua a costruire'),
('it','common','care_plan.create_button','Crea Piano di Cura'),
('it','common','care_plan.creating','Creazione in corso...'),
('it','common','care_plan.cta_continue','Continua'),
('it','common','care_plan.cta_open','Apri'),
('it','common','care_plan.cta_review','Rivedi'),
('it','common','care_plan.cta_start','Inizia'),
('it','common','care_plan.description','Il Piano di Cura è il piano operativo generale del team di cura. Copre chi è responsabile di cosa, quale autorità esiste, come verrà organizzata la cura e quando il piano dovrebbe essere rivisto.'),
('it','common','care_plan.edit_care_plan','Modifica Piano di Cura'),
('it','common','care_plan.generated_on','Generato il {date}'),
('it','common','care_plan.go_to_dashboard','Vai alla Dashboard'),
('it','common','care_plan.living_alternatives','Alternative considerate'),
('it','common','care_plan.living_assisted','Vita assistita o cure residenziali'),
('it','common','care_plan.living_family_home','Il residente si trasferisce in una casa familiare'),
('it','common','care_plan.living_paid_in_home','Supporto domiciliare a pagamento'),
('it','common','care_plan.living_resident_home','Il residente rimane nella propria casa'),
('it','common','care_plan.living_undecided','Non deciso / ancora in valutazione'),
('it','common','care_plan.load_error','Impossibile caricare il Piano di Cura. Aggiorna la pagina.'),
('it','common','care_plan.memory_book_label','Libro dei Ricordi'),
('it','common','care_plan.modal_back','Indietro'),
('it','common','care_plan.modal_close','Chiudi'),
('it','common','care_plan.modal_mark_complete','Segna come completo'),
('it','common','care_plan.modal_read_only_notice','Puoi visualizzare questa sezione ma solo il proprietario del team può apportare modifiche.'),
('it','common','care_plan.modal_save','Salva'),
('it','common','care_plan.modal_save_error','Salvataggio non riuscito. Controlla la connessione e riprova.'),
('it','common','care_plan.modal_saved','Salvato'),
('it','common','care_plan.modal_saving','Salvataggio...'),
('it','common','care_plan.modal_section_of','Sezione {current} di {total}'),
('it','common','care_plan.modal_unsaved_changes','Hai modifiche non salvate. Uscire senza salvare?'),
('it','common','care_plan.more_gaps','altri'),
('it','common','care_plan.no_plan_body','Il proprietario del team di cura non ha ancora creato un Piano di Cura. Ricontrolla più tardi.'),
('it','common','care_plan.no_plan_title','Nessun Piano di Cura ancora'),
('it','common','care_plan.no_team_body','Il Piano di Cura è collegato al tuo team di cura. Configura prima il tuo team per iniziare.'),
('it','common','care_plan.no_team_title','Nessun team di cura trovato'),
('it','common','care_plan.not_filled_in','non compilato'),
('it','common','care_plan.observations_label','Osservazioni'),
('it','common','care_plan.open_memory_book','Apri Libro dei Ricordi'),
('it','common','care_plan.owner_label','Proprietario'),
('it','common','care_plan.print','Stampa'),
('it','common','care_plan.print_summary','Stampa riepilogo'),
('it','common','care_plan.progress_label','{completed} di {total} sezioni complete'),
('it','common','care_plan.resident_fallback','residente'),
('it','common','care_plan.resp_admin','Amministrazione'),
('it','common','care_plan.resp_emotional','Supporto emotivo'),
('it','common','care_plan.resp_health','Coordinamento sanitario'),
('it','common','care_plan.resp_household','Supporto domestico'),
('it','common','care_plan.resp_personal_care','Cura personale'),
('it','common','care_plan.resp_respite','Supplente / sollievo'),
('it','common','care_plan.resp_scheduling','Appuntamenti'),
('it','common','care_plan.section_authority','Autorità'),
('it','common','care_plan.section_living_arrangement','Sistemazione di Vita'),
('it','common','care_plan.section_responsibilities','Responsabilità'),
('it','common','care_plan.section_review','Revisione'),
('it','common','care_plan.section_situation','Situazione'),
('it','common','care_plan.section_sustainability','Sostenibilità'),
('it','common','care_plan.situation_concerns','Preoccupazioni principali'),
('it','common','care_plan.situation_current','Situazione attuale'),
('it','common','care_plan.start_body','Il tuo team non ha ancora un Piano di Cura. Creane uno per coordinare responsabilità, autorità e sistemazioni di vita.'),
('it','common','care_plan.start_building','Inizia a costruire'),
('it','common','care_plan.start_title','Inizia il tuo Piano di Cura'),
('it','common','care_plan.status_complete','Completo'),
('it','common','care_plan.status_in_progress','In corso'),
('it','common','care_plan.status_not_started','Non iniziato'),
('it','common','care_plan.subtitle','Coordinare il team'),
('it','common','care_plan.summary_breadcrumb','Riepilogo'),
('it','common','care_plan.summary_title','Riepilogo del Piano di Cura'),
('it','common','care_plan.title','Piano di Cura'),
('it','common','care_plan.view_summary','Vedi riepilogo'),
('it','common','care_plan.view_summary_full','Vedi Riepilogo Completo del Piano di Cura'),
('it','common','care_plan.view_summary_partial','Vedi riepilogo parziale'),

-- ============================================================
-- SWEDISH (sv)
-- ============================================================
('sv','common','care_hub.title','Vård-Hub'),
('sv','common','care_plan.all_complete_no_gaps','Alla avsnitt klara — inga luckor identifierade.'),
('sv','common','care_plan.all_sections_complete','Alla avsnitt klara'),
('sv','common','care_plan.authority_status_confirmed','Bekräftad'),
('sv','common','care_plan.authority_status_missing','Saknas'),
('sv','common','care_plan.authority_status_not_applicable','Ej tillämpligt'),
('sv','common','care_plan.authority_status_unclear','Oklart'),
('sv','common','care_plan.backup_label','Ersättare'),
('sv','common','care_plan.care_plan_for','Vårdplan för'),
('sv','common','care_plan.continue_building','Fortsätt bygga'),
('sv','common','care_plan.create_button','Skapa vårdplan'),
('sv','common','care_plan.creating','Skapar...'),
('sv','common','care_plan.cta_continue','Fortsätt'),
('sv','common','care_plan.cta_open','Öppna'),
('sv','common','care_plan.cta_review','Granska'),
('sv','common','care_plan.cta_start','Starta'),
('sv','common','care_plan.description','Vårdplanen är vårdteamets övergripande driftsplan. Den täcker vem som ansvarar för vad, vilken befogenhet som finns, hur vården ska organiseras och när planen ska granskas.'),
('sv','common','care_plan.edit_care_plan','Redigera vårdplan'),
('sv','common','care_plan.generated_on','Genererad {date}'),
('sv','common','care_plan.go_to_dashboard','Gå till instrumentpanelen'),
('sv','common','care_plan.living_alternatives','Alternativ som övervägs'),
('sv','common','care_plan.living_assisted','Assisterat boende eller hemvård'),
('sv','common','care_plan.living_family_home','Boende flyttar in i ett familjehus'),
('sv','common','care_plan.living_paid_in_home','Betalt hemstöd'),
('sv','common','care_plan.living_resident_home','Boende stannar i sitt eget hem'),
('sv','common','care_plan.living_undecided','Obeslutat / utvärderas fortfarande'),
('sv','common','care_plan.load_error','Det gick inte att ladda vårdplanen. Uppdatera sidan.'),
('sv','common','care_plan.memory_book_label','Minnesbok'),
('sv','common','care_plan.modal_back','Tillbaka'),
('sv','common','care_plan.modal_close','Stäng'),
('sv','common','care_plan.modal_mark_complete','Markera som klar'),
('sv','common','care_plan.modal_read_only_notice','Du kan se det här avsnittet men bara teamägaren kan göra ändringar.'),
('sv','common','care_plan.modal_save','Spara'),
('sv','common','care_plan.modal_save_error','Sparning misslyckades. Kontrollera din anslutning och försök igen.'),
('sv','common','care_plan.modal_saved','Sparad'),
('sv','common','care_plan.modal_saving','Sparar...'),
('sv','common','care_plan.modal_section_of','Avsnitt {current} av {total}'),
('sv','common','care_plan.modal_unsaved_changes','Du har osparade ändringar. Lämna utan att spara?'),
('sv','common','care_plan.more_gaps','fler'),
('sv','common','care_plan.no_plan_body','Vårdteamets ägare har inte skapat en vårdplan ännu. Kom tillbaka senare.'),
('sv','common','care_plan.no_plan_title','Ingen vårdplan ännu'),
('sv','common','care_plan.no_team_body','Vårdplanen är kopplad till ditt vårdteam. Konfigurera ditt vårdteam först för att komma igång.'),
('sv','common','care_plan.no_team_title','Inget vårdteam hittat'),
('sv','common','care_plan.not_filled_in','inte ifyllt'),
('sv','common','care_plan.observations_label','Observationer'),
('sv','common','care_plan.open_memory_book','Öppna minnesbok'),
('sv','common','care_plan.owner_label','Ägare'),
('sv','common','care_plan.print','Skriv ut'),
('sv','common','care_plan.print_summary','Skriv ut sammanfattning'),
('sv','common','care_plan.progress_label','{completed} av {total} avsnitt klara'),
('sv','common','care_plan.resident_fallback','boende'),
('sv','common','care_plan.resp_admin','Administration'),
('sv','common','care_plan.resp_emotional','Emotionellt stöd'),
('sv','common','care_plan.resp_health','Hälsokoordinering'),
('sv','common','care_plan.resp_household','Hushållsstöd'),
('sv','common','care_plan.resp_personal_care','Personlig vård'),
('sv','common','care_plan.resp_respite','Ersättare / avlastning'),
('sv','common','care_plan.resp_scheduling','Tidsbokning'),
('sv','common','care_plan.section_authority','Befogenhet'),
('sv','common','care_plan.section_living_arrangement','Boendesituation'),
('sv','common','care_plan.section_responsibilities','Ansvar'),
('sv','common','care_plan.section_review','Granskning'),
('sv','common','care_plan.section_situation','Situation'),
('sv','common','care_plan.section_sustainability','Hållbarhet'),
('sv','common','care_plan.situation_concerns','Huvudsakliga bekymmer'),
('sv','common','care_plan.situation_current','Nuvarande situation'),
('sv','common','care_plan.start_body','Ditt team har ingen vårdplan ännu. Skapa en för att koordinera ansvar, befogenheter och boendesituationer.'),
('sv','common','care_plan.start_building','Börja bygga'),
('sv','common','care_plan.start_title','Starta din vårdplan'),
('sv','common','care_plan.status_complete','Klar'),
('sv','common','care_plan.status_in_progress','Pågår'),
('sv','common','care_plan.status_not_started','Inte påbörjad'),
('sv','common','care_plan.subtitle','Koordinera teamet'),
('sv','common','care_plan.summary_breadcrumb','Sammanfattning'),
('sv','common','care_plan.summary_title','Sammanfattning av vårdplan'),
('sv','common','care_plan.title','Vårdplan'),
('sv','common','care_plan.view_summary','Visa sammanfattning'),
('sv','common','care_plan.view_summary_full','Visa fullständig sammanfattning av vårdplan'),
('sv','common','care_plan.view_summary_partial','Visa partiell sammanfattning'),

-- ============================================================
-- FINNISH (fi)
-- ============================================================
('fi','common','care_hub.title','Hoitokeskus'),
('fi','common','care_plan.all_complete_no_gaps','Kaikki osiot valmiita — ei tunnistettu aukkoja.'),
('fi','common','care_plan.all_sections_complete','Kaikki osiot valmiita'),
('fi','common','care_plan.authority_status_confirmed','Vahvistettu'),
('fi','common','care_plan.authority_status_missing','Puuttuu'),
('fi','common','care_plan.authority_status_not_applicable','Ei sovelleta'),
('fi','common','care_plan.authority_status_unclear','Epäselvä'),
('fi','common','care_plan.backup_label','Varahenkilö'),
('fi','common','care_plan.care_plan_for','Hoitosuunnitelma kohteelle'),
('fi','common','care_plan.continue_building','Jatka rakentamista'),
('fi','common','care_plan.create_button','Luo hoitosuunnitelma'),
('fi','common','care_plan.creating','Luodaan...'),
('fi','common','care_plan.cta_continue','Jatka'),
('fi','common','care_plan.cta_open','Avaa'),
('fi','common','care_plan.cta_review','Tarkista'),
('fi','common','care_plan.cta_start','Aloita'),
('fi','common','care_plan.description','Hoitosuunnitelma on hoitotiimin suuri toimintasuunnitelma. Se kattaa kuka vastaa mistäkin, mitä valtuuksia on, miten hoito järjestetään ja milloin suunnitelma pitäisi tarkistaa.'),
('fi','common','care_plan.edit_care_plan','Muokkaa hoitosuunnitelmaa'),
('fi','common','care_plan.generated_on','Luotu {date}'),
('fi','common','care_plan.go_to_dashboard','Siirry kojelautaan'),
('fi','common','care_plan.living_alternatives','Harkitut vaihtoehdot'),
('fi','common','care_plan.living_assisted','Tuettu asuminen tai hoitokoti'),
('fi','common','care_plan.living_family_home','Asukas muuttaa perheen kotiin'),
('fi','common','care_plan.living_paid_in_home','Maksullinen kotihoito'),
('fi','common','care_plan.living_resident_home','Asukas jää omaan kotiinsa'),
('fi','common','care_plan.living_undecided','Ei päätetty / vielä arvioidaan'),
('fi','common','care_plan.load_error','Hoitosuunnitelman lataaminen epäonnistui. Päivitä sivu.'),
('fi','common','care_plan.memory_book_label','Muistokirja'),
('fi','common','care_plan.modal_back','Takaisin'),
('fi','common','care_plan.modal_close','Sulje'),
('fi','common','care_plan.modal_mark_complete','Merkitse valmiiksi'),
('fi','common','care_plan.modal_read_only_notice','Voit katsella tätä osiota, mutta vain tiimin omistaja voi tehdä muutoksia.'),
('fi','common','care_plan.modal_save','Tallenna'),
('fi','common','care_plan.modal_save_error','Tallennus epäonnistui. Tarkista yhteytesi ja yritä uudelleen.'),
('fi','common','care_plan.modal_saved','Tallennettu'),
('fi','common','care_plan.modal_saving','Tallennetaan...'),
('fi','common','care_plan.modal_section_of','Osio {current} / {total}'),
('fi','common','care_plan.modal_unsaved_changes','Sinulla on tallentamattomia muutoksia. Poistu tallentamatta?'),
('fi','common','care_plan.more_gaps','lisää'),
('fi','common','care_plan.no_plan_body','Hoitotiimin omistaja ei ole vielä luonut hoitosuunnitelmaa. Tarkista myöhemmin.'),
('fi','common','care_plan.no_plan_title','Ei vielä hoitosuunnitelmaa'),
('fi','common','care_plan.no_team_body','Hoitosuunnitelma on yhdistetty hoitotiimiisi. Aseta hoitotiimisi ensin aloittaaksesi.'),
('fi','common','care_plan.no_team_title','Hoitotiimiä ei löydy'),
('fi','common','care_plan.not_filled_in','ei täytetty'),
('fi','common','care_plan.observations_label','Havainnot'),
('fi','common','care_plan.open_memory_book','Avaa muistokirja'),
('fi','common','care_plan.owner_label','Omistaja'),
('fi','common','care_plan.print','Tulosta'),
('fi','common','care_plan.print_summary','Tulosta yhteenveto'),
('fi','common','care_plan.progress_label','{completed} / {total} osiota valmis'),
('fi','common','care_plan.resident_fallback','asukas'),
('fi','common','care_plan.resp_admin','Hallinto'),
('fi','common','care_plan.resp_emotional','Henkinen tuki'),
('fi','common','care_plan.resp_health','Terveydenhuollon koordinointi'),
('fi','common','care_plan.resp_household','Kotitalouden tuki'),
('fi','common','care_plan.resp_personal_care','Henkilökohtainen hoito'),
('fi','common','care_plan.resp_respite','Varahenkilö / lepoaika'),
('fi','common','care_plan.resp_scheduling','Ajanvaraukset'),
('fi','common','care_plan.section_authority','Valtuudet'),
('fi','common','care_plan.section_living_arrangement','Asumistilanne'),
('fi','common','care_plan.section_responsibilities','Vastuut'),
('fi','common','care_plan.section_review','Tarkistus'),
('fi','common','care_plan.section_situation','Tilanne'),
('fi','common','care_plan.section_sustainability','Kestävyys'),
('fi','common','care_plan.situation_concerns','Päähuolenaiheet'),
('fi','common','care_plan.situation_current','Nykyinen tilanne'),
('fi','common','care_plan.start_body','Tiimilläsi ei ole vielä hoitosuunnitelmaa. Luo yksi koordinoidaksesi vastuut, valtuudet ja asumistilanteet.'),
('fi','common','care_plan.start_building','Aloita rakentaminen'),
('fi','common','care_plan.start_title','Aloita hoitosuunnitelmasi'),
('fi','common','care_plan.status_complete','Valmis'),
('fi','common','care_plan.status_in_progress','Käynnissä'),
('fi','common','care_plan.status_not_started','Ei aloitettu'),
('fi','common','care_plan.subtitle','Koordinoi tiimi'),
('fi','common','care_plan.summary_breadcrumb','Yhteenveto'),
('fi','common','care_plan.summary_title','Hoitosuunnitelman yhteenveto'),
('fi','common','care_plan.title','Hoitosuunnitelma'),
('fi','common','care_plan.view_summary','Näytä yhteenveto'),
('fi','common','care_plan.view_summary_full','Näytä hoitosuunnitelman täydellinen yhteenveto'),
('fi','common','care_plan.view_summary_partial','Näytä osittainen yhteenveto'),

-- ============================================================
-- JAPANESE (ja)
-- ============================================================
('ja','common','care_hub.title','ケアハブ'),
('ja','common','care_plan.all_complete_no_gaps','すべてのセクションが完了 — ギャップは確認されませんでした。'),
('ja','common','care_plan.all_sections_complete','すべてのセクションが完了'),
('ja','common','care_plan.authority_status_confirmed','確認済み'),
('ja','common','care_plan.authority_status_missing','欠如'),
('ja','common','care_plan.authority_status_not_applicable','該当なし'),
('ja','common','care_plan.authority_status_unclear','不明確'),
('ja','common','care_plan.backup_label','バックアップ'),
('ja','common','care_plan.care_plan_for','ケアプラン（対象者：'),
('ja','common','care_plan.continue_building','引き続き作成'),
('ja','common','care_plan.create_button','ケアプランを作成'),
('ja','common','care_plan.creating','作成中...'),
('ja','common','care_plan.cta_continue','続ける'),
('ja','common','care_plan.cta_open','開く'),
('ja','common','care_plan.cta_review','見直す'),
('ja','common','care_plan.cta_start','開始'),
('ja','common','care_plan.description','ケアプランは、ケアチームの大局的な運営計画です。誰が何を担当するか、どのような権限があるか、ケアをどのように手配するか、いつ計画を見直すかを定めます。'),
('ja','common','care_plan.edit_care_plan','ケアプランを編集'),
('ja','common','care_plan.generated_on','{date}に生成'),
('ja','common','care_plan.go_to_dashboard','ダッシュボードへ'),
('ja','common','care_plan.living_alternatives','検討中の代替案'),
('ja','common','care_plan.living_assisted','介護付き住宅または施設ケア'),
('ja','common','care_plan.living_family_home','居住者が家族の家に引っ越す'),
('ja','common','care_plan.living_paid_in_home','有料の在宅サポート'),
('ja','common','care_plan.living_resident_home','居住者が自宅に留まる'),
('ja','common','care_plan.living_undecided','未決定 / まだ評価中'),
('ja','common','care_plan.load_error','ケアプランを読み込めません。ページを更新してください。'),
('ja','common','care_plan.memory_book_label','思い出の本'),
('ja','common','care_plan.modal_back','戻る'),
('ja','common','care_plan.modal_close','閉じる'),
('ja','common','care_plan.modal_mark_complete','完了としてマーク'),
('ja','common','care_plan.modal_read_only_notice','このセクションを表示できますが、変更はチームオーナーのみが行えます。'),
('ja','common','care_plan.modal_save','保存'),
('ja','common','care_plan.modal_save_error','保存に失敗しました。接続を確認してもう一度お試しください。'),
('ja','common','care_plan.modal_saved','保存済み'),
('ja','common','care_plan.modal_saving','保存中...'),
('ja','common','care_plan.modal_section_of','セクション {current} / {total}'),
('ja','common','care_plan.modal_unsaved_changes','未保存の変更があります。保存せずに退出しますか？'),
('ja','common','care_plan.more_gaps','もっと'),
('ja','common','care_plan.no_plan_body','ケアチームのオーナーはまだケアプランを作成していません。後でもう一度確認してください。'),
('ja','common','care_plan.no_plan_title','まだケアプランがありません'),
('ja','common','care_plan.no_team_body','ケアプランはあなたのケアチームに関連しています。まずケアチームを設定してください。'),
('ja','common','care_plan.no_team_title','ケアチームが見つかりません'),
('ja','common','care_plan.not_filled_in','未入力'),
('ja','common','care_plan.observations_label','観察'),
('ja','common','care_plan.open_memory_book','思い出の本を開く'),
('ja','common','care_plan.owner_label','オーナー'),
('ja','common','care_plan.print','印刷'),
('ja','common','care_plan.print_summary','概要を印刷'),
('ja','common','care_plan.progress_label','{total}セクション中{completed}完了'),
('ja','common','care_plan.resident_fallback','居住者'),
('ja','common','care_plan.resp_admin','管理'),
('ja','common','care_plan.resp_emotional','精神的サポート'),
('ja','common','care_plan.resp_health','健康調整'),
('ja','common','care_plan.resp_household','家事サポート'),
('ja','common','care_plan.resp_personal_care','身の回りの世話'),
('ja','common','care_plan.resp_respite','バックアップ / レスパイト'),
('ja','common','care_plan.resp_scheduling','予約管理'),
('ja','common','care_plan.section_authority','権限'),
('ja','common','care_plan.section_living_arrangement','生活環境'),
('ja','common','care_plan.section_responsibilities','責任'),
('ja','common','care_plan.section_review','見直し'),
('ja','common','care_plan.section_situation','状況'),
('ja','common','care_plan.section_sustainability','持続可能性'),
('ja','common','care_plan.situation_concerns','主な懸念事項'),
('ja','common','care_plan.situation_current','現在の状況'),
('ja','common','care_plan.start_body','チームにはまだケアプランがありません。責任、権限、生活環境を調整するために作成してください。'),
('ja','common','care_plan.start_building','作成を開始'),
('ja','common','care_plan.start_title','ケアプランを始める'),
('ja','common','care_plan.status_complete','完了'),
('ja','common','care_plan.status_in_progress','進行中'),
('ja','common','care_plan.status_not_started','未着手'),
('ja','common','care_plan.subtitle','チームを調整する'),
('ja','common','care_plan.summary_breadcrumb','概要'),
('ja','common','care_plan.summary_title','ケアプラン概要'),
('ja','common','care_plan.title','ケアプラン'),
('ja','common','care_plan.view_summary','概要を表示'),
('ja','common','care_plan.view_summary_full','ケアプランの完全な概要を表示'),
('ja','common','care_plan.view_summary_partial','部分的な概要を表示')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
