-- Translation Batch 3: new_obs.*, obs_edit.*, obs_form.* keys for all 7 non-EN locales

INSERT INTO public.ui_translations (locale, namespace, key, value) VALUES

-- ============================================================
-- SPANISH (es)
-- ============================================================
('es','common','new_obs.adl_desc','Evalúa tareas básicas de autocuidado como bañarse, vestirse, comer y moverse.'),
('es','common','new_obs.adl_title','Actividades de la Vida Diaria'),
('es','common','new_obs.choose_type','Elige el tipo de observación que deseas registrar.'),
('es','common','new_obs.comprehensive_desc','Una evaluación completa de AVD y AIVD en una sola. Usa 1 de tus 100 observaciones anuales.'),
('es','common','new_obs.comprehensive_title','Evaluación Integral'),
('es','common','new_obs.create_title','Crear una Nueva Observación'),
('es','common','new_obs.iadl_desc','Evalúa habilidades diarias complejas como gestión de medicamentos, finanzas y transporte.'),
('es','common','new_obs.iadl_title','Actividades Instrumentales de la Vida Diaria'),
('es','common','new_obs.loading','Preparando tu nueva observación…'),
('es','common','new_obs.no_team','Crea primero tu Círculo Familiar.'),
('es','common','new_obs.page_title','Nueva Observación'),
('es','common','new_obs.quota_reached','Cuota del equipo alcanzada (100/año).'),
('es','common','new_obs.remaining_prefix','Observaciones restantes este año:'),
('es','common','new_obs.seat_frozen','Asiento congelado. Pide al propietario que gestione la facturación.'),
('es','common','new_obs.solo_quota_reached_body','Actualiza a un plan de pago para registrar observaciones sin límites.'),
('es','common','new_obs.solo_quota_reached_cta','Ver planes'),
('es','common','new_obs.solo_quota_reached_title','Has usado tus 3 observaciones gratuitas'),
('es','common','new_obs.solo_remaining_one','1 observación gratuita restante'),
('es','common','new_obs.solo_remaining_other','{{count}} observaciones gratuitas restantes'),
('es','common','obs_edit.adl_label','Vida Diaria (AVD)'),
('es','common','obs_edit.comp_label','Integral'),
('es','common','obs_edit.fetching','Obteniendo observación…'),
('es','common','obs_edit.form_adl','AVD'),
('es','common','obs_edit.form_comprehensive','Integral'),
('es','common','obs_edit.form_iadl','AIVD'),
('es','common','obs_edit.frozen_notice','Tu cuenta ha sido suspendida. No puedes editar observaciones en este momento.'),
('es','common','obs_edit.iadl_label','Habilidades de Vida (AIVD)'),
('es','common','obs_edit.invalid_type','La observación tiene un tipo de formulario no válido:'),
('es','common','obs_edit.loading','Cargando observación…'),
('es','common','obs_edit.missing_id','Falta el ID de observación en la URL.'),
('es','common','obs_edit.not_found','Observación no encontrada.'),
('es','common','obs_edit.observation_label','Observación'),
('es','common','obs_edit.readonly_notice','Estás viendo esta observación en modo de solo lectura porque no eres el autor.'),
('es','common','obs_edit.render_error','Algo salió mal al cargar esta observación.'),
('es','common','obs_edit.render_error_detail','Actualiza la página o vuelve al panel de control.'),
('es','common','obs_form.adl_label','Actividades de la Vida Diaria'),
('es','common','obs_form.autosave_hint','Se guarda automáticamente una vez que hayas puntuado al menos un elemento'),
('es','common','obs_form.cat_notes_label','Notas para {category} (opcional)'),
('es','common','obs_form.cat_notes_ph','Cualquier nota específica de {category}…'),
('es','common','obs_form.comprehensive_label','Integral (AVD + AIVD)'),
('es','common','obs_form.date_invalid','Por favor ingresa una fecha válida en formato MM/DD/AAAA'),
('es','common','obs_form.date_label','Fecha de observación'),
('es','common','obs_form.date_placeholder','MM/DD/AAAA'),
('es','common','obs_form.date_required','La fecha de observación es obligatoria'),
('es','common','obs_form.err_email','Tu correo de cuenta falta o es inválido. Cierra sesión e inicia sesión de nuevo.'),
('es','common','obs_form.err_no_score','Por favor selecciona al menos una puntuación antes de guardar.'),
('es','common','obs_form.form_type_comp','Integral (AVD + AIVD)'),
('es','common','obs_form.guidance','Completa tanto o tan poco como quieras. No necesitas responder todas las preguntas — incluso unos pocos puntajes son útiles. Tu trabajo se guarda automáticamente cada 45 segundos una vez que hayas ingresado al menos una puntuación.'),
('es','common','obs_form.iadl_label','Habilidades de Vida'),
('es','common','obs_form.last_saved','Guardado por última vez {time}'),
('es','common','obs_form.loading','Cargando tu formulario de observación…'),
('es','common','obs_form.mode_in_person','En Persona'),
('es','common','obs_form.mode_label','¿Cómo observaste?'),
('es','common','obs_form.mode_video','Videollamada'),
('es','common','obs_form.mode_voice','Llamada de Voz'),
('es','common','obs_form.more_help','Más ayuda necesaria'),
('es','common','obs_form.more_indep','Más independiente'),
('es','common','obs_form.no_questions','No hay preguntas disponibles'),
('es','common','obs_form.notes_label','Notas generales (opcional)'),
('es','common','obs_form.notes_ph','Cualquier observación general sobre la visita de hoy…'),
('es','common','obs_form.notes_placeholder','Cualquier observación general sobre la visita de hoy…'),
('es','common','obs_form.patient_label','Persona siendo observada'),
('es','common','obs_form.patient_ph','Su nombre'),
('es','common','obs_form.resident_edit_link','Editar'),
('es','common','obs_form.resident_no_profile_hint','Aún no se ha configurado el perfil del residente.'),
('es','common','obs_form.resident_no_profile_link','Configurar perfil del residente'),
('es','common','obs_form.save_changes','Guardar Cambios'),
('es','common','obs_form.save_continue','Guardar y Continuar'),
('es','common','obs_form.save_obs','Guardar Observación'),
('es','common','obs_form.score_ref_header','Referencia de puntuación — toca un número en cada pregunta para registrar tu observación'),
('es','common','obs_form.scored_count','{scored} de {total} puntuados'),
('es','common','obs_form.title_edit','Editar Observación'),
('es','common','obs_form.title_new','Nueva Observación'),

-- ============================================================
-- FRENCH (fr)
-- ============================================================
('fr','common','new_obs.adl_desc','Évaluer les tâches de soins personnels de base telles que le bain, l''habillage, l''alimentation et la mobilité.'),
('fr','common','new_obs.adl_title','Activités de la vie quotidienne'),
('fr','common','new_obs.choose_type','Choisissez le type d''observation que vous souhaitez enregistrer.'),
('fr','common','new_obs.comprehensive_desc','Une évaluation complète AVQ et AIVQ en une seule. Utilise 1 de vos 100 observations annuelles.'),
('fr','common','new_obs.comprehensive_title','Évaluation complète'),
('fr','common','new_obs.create_title','Créer une nouvelle observation'),
('fr','common','new_obs.iadl_desc','Évaluer les compétences quotidiennes complexes telles que la gestion des médicaments, des finances et du transport.'),
('fr','common','new_obs.iadl_title','Activités instrumentales de la vie quotidienne'),
('fr','common','new_obs.loading','Préparation de votre nouvelle observation…'),
('fr','common','new_obs.no_team','Créez d''abord votre Cercle familial.'),
('fr','common','new_obs.page_title','Nouvelle observation'),
('fr','common','new_obs.quota_reached','Quota d''équipe atteint (100/an).'),
('fr','common','new_obs.remaining_prefix','Observations restantes cette année :'),
('fr','common','new_obs.seat_frozen','Siège bloqué. Demandez au propriétaire de gérer la facturation.'),
('fr','common','new_obs.solo_quota_reached_body','Passez à un forfait payant pour suivre les observations sans limites.'),
('fr','common','new_obs.solo_quota_reached_cta','Voir les forfaits'),
('fr','common','new_obs.solo_quota_reached_title','Vous avez utilisé vos 3 observations gratuites'),
('fr','common','new_obs.solo_remaining_one','1 observation gratuite restante'),
('fr','common','new_obs.solo_remaining_other','{{count}} observations gratuites restantes'),
('fr','common','obs_edit.adl_label','Vie quotidienne (AVQ)'),
('fr','common','obs_edit.comp_label','Complet'),
('fr','common','obs_edit.fetching','Récupération de l''observation…'),
('fr','common','obs_edit.form_adl','AVQ'),
('fr','common','obs_edit.form_comprehensive','Complet'),
('fr','common','obs_edit.form_iadl','AIVQ'),
('fr','common','obs_edit.frozen_notice','Votre compte a été suspendu. Vous ne pouvez pas modifier les observations pour le moment.'),
('fr','common','obs_edit.iadl_label','Compétences de vie (AIVQ)'),
('fr','common','obs_edit.invalid_type','L''observation a un type de formulaire invalide :'),
('fr','common','obs_edit.loading','Chargement de l''observation…'),
('fr','common','obs_edit.missing_id','ID d''observation manquant dans l''URL.'),
('fr','common','obs_edit.not_found','Observation introuvable.'),
('fr','common','obs_edit.observation_label','Observation'),
('fr','common','obs_edit.readonly_notice','Vous consultez cette observation en mode lecture seule car vous n''en êtes pas l''auteur.'),
('fr','common','obs_edit.render_error','Un problème s''est produit lors du chargement de cette observation.'),
('fr','common','obs_edit.render_error_detail','Veuillez actualiser la page ou retourner au tableau de bord.'),
('fr','common','obs_form.adl_label','Activités de la vie quotidienne'),
('fr','common','obs_form.autosave_hint','Sauvegarde automatique une fois que vous avez coté au moins un élément'),
('fr','common','obs_form.cat_notes_label','Notes pour {category} (facultatif)'),
('fr','common','obs_form.cat_notes_ph','Notes spécifiques à {category}…'),
('fr','common','obs_form.comprehensive_label','Complet (AVQ + AIVQ)'),
('fr','common','obs_form.date_invalid','Veuillez saisir une date valide au format JJ/MM/AAAA'),
('fr','common','obs_form.date_label','Date de l''observation'),
('fr','common','obs_form.date_placeholder','JJ/MM/AAAA'),
('fr','common','obs_form.date_required','La date de l''observation est obligatoire'),
('fr','common','obs_form.err_email','L''e-mail de votre compte est manquant ou invalide. Déconnectez-vous et reconnectez-vous.'),
('fr','common','obs_form.err_no_score','Veuillez sélectionner au moins un score avant de sauvegarder.'),
('fr','common','obs_form.form_type_comp','Complet (AVQ + AIVQ)'),
('fr','common','obs_form.guidance','Remplissez autant ou aussi peu que vous le souhaitez. Vous n''avez pas besoin de répondre à toutes les questions — même quelques scores sont utiles. Votre travail est sauvegardé automatiquement toutes les 45 secondes une fois que vous avez saisi au moins un score.'),
('fr','common','obs_form.iadl_label','Compétences de vie'),
('fr','common','obs_form.last_saved','Dernière sauvegarde {time}'),
('fr','common','obs_form.loading','Chargement de votre formulaire d''observation…'),
('fr','common','obs_form.mode_in_person','En personne'),
('fr','common','obs_form.mode_label','Comment avez-vous observé ?'),
('fr','common','obs_form.mode_video','Appel vidéo'),
('fr','common','obs_form.mode_voice','Appel vocal'),
('fr','common','obs_form.more_help','Plus d''aide nécessaire'),
('fr','common','obs_form.more_indep','Plus indépendant'),
('fr','common','obs_form.no_questions','Aucune question disponible'),
('fr','common','obs_form.notes_label','Notes générales (facultatif)'),
('fr','common','obs_form.notes_ph','Observations générales sur la visite d''aujourd''hui…'),
('fr','common','obs_form.notes_placeholder','Observations générales sur la visite d''aujourd''hui…'),
('fr','common','obs_form.patient_label','Personne observée'),
('fr','common','obs_form.patient_ph','Son nom'),
('fr','common','obs_form.resident_edit_link','Modifier'),
('fr','common','obs_form.resident_no_profile_hint','Aucun profil résident configuré pour le moment.'),
('fr','common','obs_form.resident_no_profile_link','Configurer le profil résident'),
('fr','common','obs_form.save_changes','Enregistrer les modifications'),
('fr','common','obs_form.save_continue','Enregistrer et continuer'),
('fr','common','obs_form.save_obs','Enregistrer l''observation'),
('fr','common','obs_form.score_ref_header','Référence des scores — appuyez sur un numéro à chaque question pour enregistrer votre observation'),
('fr','common','obs_form.scored_count','{scored} sur {total} cotés'),
('fr','common','obs_form.title_edit','Modifier l''observation'),
('fr','common','obs_form.title_new','Nouvelle observation'),

-- ============================================================
-- GERMAN (de)
-- ============================================================
('de','common','new_obs.adl_desc','Bewertung grundlegender Selbstfürsorgeaufgaben wie Baden, Ankleiden, Essen und Mobilität.'),
('de','common','new_obs.adl_title','Aktivitäten des täglichen Lebens'),
('de','common','new_obs.choose_type','Wähle die Art der Beobachtung, die du aufzeichnen möchtest.'),
('de','common','new_obs.comprehensive_desc','Eine vollständige ADL- und IADL-Bewertung in einer. Verwendet 1 deiner 100 jährlichen Beobachtungen.'),
('de','common','new_obs.comprehensive_title','Umfassende Beurteilung'),
('de','common','new_obs.create_title','Neue Beobachtung erstellen'),
('de','common','new_obs.iadl_desc','Bewertung komplexer alltäglicher Fähigkeiten wie Medikamentenverwaltung, Finanzen und Transport.'),
('de','common','new_obs.iadl_title','Instrumentelle Aktivitäten des täglichen Lebens'),
('de','common','new_obs.loading','Neue Beobachtung wird vorbereitet…'),
('de','common','new_obs.no_team','Erstelle zuerst deinen Familienkreis.'),
('de','common','new_obs.page_title','Neue Beobachtung'),
('de','common','new_obs.quota_reached','Teamkontingent erreicht (100/Jahr).'),
('de','common','new_obs.remaining_prefix','Verbleibende Beobachtungen dieses Jahr:'),
('de','common','new_obs.seat_frozen','Platz eingefroren. Bitte den Eigentümer, die Abrechnung zu verwalten.'),
('de','common','new_obs.solo_quota_reached_body','Wechsle zu einem kostenpflichtigen Plan, um Beobachtungen ohne Limits zu erfassen.'),
('de','common','new_obs.solo_quota_reached_cta','Pläne ansehen'),
('de','common','new_obs.solo_quota_reached_title','Du hast deine 3 kostenlosen Beobachtungen aufgebraucht'),
('de','common','new_obs.solo_remaining_one','1 kostenlose Beobachtung verbleibend'),
('de','common','new_obs.solo_remaining_other','{{count}} kostenlose Beobachtungen verbleibend'),
('de','common','obs_edit.adl_label','Tägliches Leben (ADL)'),
('de','common','obs_edit.comp_label','Umfassend'),
('de','common','obs_edit.fetching','Beobachtung wird abgerufen…'),
('de','common','obs_edit.form_adl','ADL'),
('de','common','obs_edit.form_comprehensive','Umfassend'),
('de','common','obs_edit.form_iadl','IADL'),
('de','common','obs_edit.frozen_notice','Dein Konto wurde gesperrt. Du kannst Beobachtungen derzeit nicht bearbeiten.'),
('de','common','obs_edit.iadl_label','Lebensfertigkeiten (IADL)'),
('de','common','obs_edit.invalid_type','Beobachtung hat einen ungültigen Formulartyp:'),
('de','common','obs_edit.loading','Beobachtung wird geladen…'),
('de','common','obs_edit.missing_id','Beobachtungs-ID in der URL fehlt.'),
('de','common','obs_edit.not_found','Beobachtung nicht gefunden.'),
('de','common','obs_edit.observation_label','Beobachtung'),
('de','common','obs_edit.readonly_notice','Du siehst diese Beobachtung im Nur-Lesen-Modus, da du nicht der Autor bist.'),
('de','common','obs_edit.render_error','Beim Laden dieser Beobachtung ist ein Fehler aufgetreten.'),
('de','common','obs_edit.render_error_detail','Bitte lade die Seite neu oder kehre zum Dashboard zurück.'),
('de','common','obs_form.adl_label','Aktivitäten des täglichen Lebens'),
('de','common','obs_form.autosave_hint','Wird automatisch gespeichert, sobald du mindestens ein Element bewertet hast'),
('de','common','obs_form.cat_notes_label','Notizen für {category} (optional)'),
('de','common','obs_form.cat_notes_ph','Spezifische Notizen zu {category}…'),
('de','common','obs_form.comprehensive_label','Umfassend (ADL + IADL)'),
('de','common','obs_form.date_invalid','Bitte gib ein gültiges Datum im Format TT.MM.JJJJ ein'),
('de','common','obs_form.date_label','Datum der Beobachtung'),
('de','common','obs_form.date_placeholder','TT.MM.JJJJ'),
('de','common','obs_form.date_required','Datum der Beobachtung ist erforderlich'),
('de','common','obs_form.err_email','Deine Konto-E-Mail fehlt oder ist ungültig. Bitte melde dich ab und wieder an.'),
('de','common','obs_form.err_no_score','Bitte wähle mindestens einen Score aus, bevor du speicherst.'),
('de','common','obs_form.form_type_comp','Umfassend (ADL + IADL)'),
('de','common','obs_form.guidance','Fülle so viel oder so wenig aus, wie du möchtest. Du musst nicht jede Frage beantworten — selbst ein paar Bewertungen sind hilfreich. Deine Arbeit wird alle 45 Sekunden automatisch gespeichert, sobald du mindestens einen Score eingegeben hast.'),
('de','common','obs_form.iadl_label','Lebensfertigkeiten'),
('de','common','obs_form.last_saved','Zuletzt gespeichert {time}'),
('de','common','obs_form.loading','Beobachtungsformular wird geladen…'),
('de','common','obs_form.mode_in_person','Persönlich'),
('de','common','obs_form.mode_label','Wie hast du beobachtet?'),
('de','common','obs_form.mode_video','Videoanruf'),
('de','common','obs_form.mode_voice','Sprachanruf'),
('de','common','obs_form.more_help','Mehr Hilfe benötigt'),
('de','common','obs_form.more_indep','Selbstständiger'),
('de','common','obs_form.no_questions','Keine Fragen verfügbar'),
('de','common','obs_form.notes_label','Allgemeine Notizen (optional)'),
('de','common','obs_form.notes_ph','Allgemeine Beobachtungen zum heutigen Besuch…'),
('de','common','obs_form.notes_placeholder','Allgemeine Beobachtungen zum heutigen Besuch…'),
('de','common','obs_form.patient_label','Beobachtete Person'),
('de','common','obs_form.patient_ph','Ihr Name'),
('de','common','obs_form.resident_edit_link','Bearbeiten'),
('de','common','obs_form.resident_no_profile_hint','Noch kein Bewohnerprofil eingerichtet.'),
('de','common','obs_form.resident_no_profile_link','Bewohnerprofil einrichten'),
('de','common','obs_form.save_changes','Änderungen speichern'),
('de','common','obs_form.save_continue','Speichern und weiter'),
('de','common','obs_form.save_obs','Beobachtung speichern'),
('de','common','obs_form.score_ref_header','Bewertungsreferenz — tippe bei jeder Frage eine Zahl an, um deine Beobachtung zu erfassen'),
('de','common','obs_form.scored_count','{scored} von {total} bewertet'),
('de','common','obs_form.title_edit','Beobachtung bearbeiten'),
('de','common','obs_form.title_new','Neue Beobachtung'),

-- ============================================================
-- ITALIAN (it)
-- ============================================================
('it','common','new_obs.adl_desc','Valuta le attività di cura personale di base come fare il bagno, vestirsi, mangiare e muoversi.'),
('it','common','new_obs.adl_title','Attività della Vita Quotidiana'),
('it','common','new_obs.choose_type','Scegli il tipo di osservazione che vuoi registrare.'),
('it','common','new_obs.comprehensive_desc','Una valutazione completa AVQ e AIVQ in una sola. Usa 1 delle tue 100 osservazioni annuali.'),
('it','common','new_obs.comprehensive_title','Valutazione Completa'),
('it','common','new_obs.create_title','Crea una Nuova Osservazione'),
('it','common','new_obs.iadl_desc','Valuta abilità quotidiane complesse come la gestione dei farmaci, delle finanze e dei trasporti.'),
('it','common','new_obs.iadl_title','Attività Strumentali della Vita Quotidiana'),
('it','common','new_obs.loading','Preparazione della nuova osservazione…'),
('it','common','new_obs.no_team','Crea prima il tuo Circolo Familiare.'),
('it','common','new_obs.page_title','Nuova Osservazione'),
('it','common','new_obs.quota_reached','Quota del team raggiunta (100/anno).'),
('it','common','new_obs.remaining_prefix','Osservazioni rimanenti quest''anno:'),
('it','common','new_obs.seat_frozen','Posto bloccato. Chiedi al proprietario di gestire la fatturazione.'),
('it','common','new_obs.solo_quota_reached_body','Passa a un piano a pagamento per registrare osservazioni senza limiti.'),
('it','common','new_obs.solo_quota_reached_cta','Vedi piani'),
('it','common','new_obs.solo_quota_reached_title','Hai usato le tue 3 osservazioni gratuite'),
('it','common','new_obs.solo_remaining_one','1 osservazione gratuita rimanente'),
('it','common','new_obs.solo_remaining_other','{{count}} osservazioni gratuite rimanenti'),
('it','common','obs_edit.adl_label','Vita Quotidiana (AVQ)'),
('it','common','obs_edit.comp_label','Completo'),
('it','common','obs_edit.fetching','Recupero osservazione…'),
('it','common','obs_edit.form_adl','AVQ'),
('it','common','obs_edit.form_comprehensive','Completo'),
('it','common','obs_edit.form_iadl','AIVQ'),
('it','common','obs_edit.frozen_notice','Il tuo account è stato sospeso. Non puoi modificare le osservazioni al momento.'),
('it','common','obs_edit.iadl_label','Abilità di Vita (AIVQ)'),
('it','common','obs_edit.invalid_type','L''osservazione ha un tipo di modulo non valido:'),
('it','common','obs_edit.loading','Caricamento osservazione…'),
('it','common','obs_edit.missing_id','ID osservazione mancante nell''URL.'),
('it','common','obs_edit.not_found','Osservazione non trovata.'),
('it','common','obs_edit.observation_label','Osservazione'),
('it','common','obs_edit.readonly_notice','Stai visualizzando questa osservazione in modalità sola lettura perché non sei l''autore.'),
('it','common','obs_edit.render_error','Qualcosa è andato storto durante il caricamento di questa osservazione.'),
('it','common','obs_edit.render_error_detail','Aggiorna la pagina o torna alla dashboard.'),
('it','common','obs_form.adl_label','Attività della Vita Quotidiana'),
('it','common','obs_form.autosave_hint','Salva automaticamente dopo aver valutato almeno un elemento'),
('it','common','obs_form.cat_notes_label','Note per {category} (opzionale)'),
('it','common','obs_form.cat_notes_ph','Note specifiche per {category}…'),
('it','common','obs_form.comprehensive_label','Completo (AVQ + AIVQ)'),
('it','common','obs_form.date_invalid','Inserisci una data valida nel formato GG/MM/AAAA'),
('it','common','obs_form.date_label','Data dell''osservazione'),
('it','common','obs_form.date_placeholder','GG/MM/AAAA'),
('it','common','obs_form.date_required','La data dell''osservazione è obbligatoria'),
('it','common','obs_form.err_email','L''email del tuo account è mancante o non valida. Esci e accedi di nuovo.'),
('it','common','obs_form.err_no_score','Seleziona almeno un punteggio prima di salvare.'),
('it','common','obs_form.form_type_comp','Completo (AVQ + AIVQ)'),
('it','common','obs_form.guidance','Compila quanto vuoi. Non è necessario rispondere a tutte le domande — anche pochi punteggi sono utili. Il lavoro si salva automaticamente ogni 45 secondi dopo aver inserito almeno un punteggio.'),
('it','common','obs_form.iadl_label','Abilità di Vita'),
('it','common','obs_form.last_saved','Ultimo salvataggio {time}'),
('it','common','obs_form.loading','Caricamento del modulo osservazione…'),
('it','common','obs_form.mode_in_person','Di Persona'),
('it','common','obs_form.mode_label','Come hai osservato?'),
('it','common','obs_form.mode_video','Videochiamata'),
('it','common','obs_form.mode_voice','Chiamata Vocale'),
('it','common','obs_form.more_help','Più aiuto necessario'),
('it','common','obs_form.more_indep','Più indipendente'),
('it','common','obs_form.no_questions','Nessuna domanda disponibile'),
('it','common','obs_form.notes_label','Note generali (opzionale)'),
('it','common','obs_form.notes_ph','Osservazioni generali sulla visita di oggi…'),
('it','common','obs_form.notes_placeholder','Osservazioni generali sulla visita di oggi…'),
('it','common','obs_form.patient_label','Persona osservata'),
('it','common','obs_form.patient_ph','Il loro nome'),
('it','common','obs_form.resident_edit_link','Modifica'),
('it','common','obs_form.resident_no_profile_hint','Nessun profilo residente configurato ancora.'),
('it','common','obs_form.resident_no_profile_link','Configura profilo residente'),
('it','common','obs_form.save_changes','Salva Modifiche'),
('it','common','obs_form.save_continue','Salva e Continua'),
('it','common','obs_form.save_obs','Salva Osservazione'),
('it','common','obs_form.score_ref_header','Riferimento punteggio — tocca un numero su ogni domanda per registrare la tua osservazione'),
('it','common','obs_form.scored_count','{scored} di {total} valutati'),
('it','common','obs_form.title_edit','Modifica Osservazione'),
('it','common','obs_form.title_new','Nuova Osservazione'),

-- ============================================================
-- SWEDISH (sv)
-- ============================================================
('sv','common','new_obs.adl_desc','Bedöm grundläggande egenvårdsuppgifter som badning, påklädning, ätande och rörlighet.'),
('sv','common','new_obs.adl_title','Aktiviteter i Dagligt Liv'),
('sv','common','new_obs.choose_type','Välj vilken typ av observation du vill registrera.'),
('sv','common','new_obs.comprehensive_desc','En fullständig ADL- och IADL-bedömning i en. Använder 1 av dina 100 årliga observationer.'),
('sv','common','new_obs.comprehensive_title','Heltäckande bedömning'),
('sv','common','new_obs.create_title','Skapa en ny observation'),
('sv','common','new_obs.iadl_desc','Bedöm komplexa dagliga färdigheter som hantering av mediciner, ekonomi och transport.'),
('sv','common','new_obs.iadl_title','Instrumentella Aktiviteter i Dagligt Liv'),
('sv','common','new_obs.loading','Förbereder din nya observation…'),
('sv','common','new_obs.no_team','Skapa din Familjecirkel först.'),
('sv','common','new_obs.page_title','Ny observation'),
('sv','common','new_obs.quota_reached','Teamkvot nådd (100/år).'),
('sv','common','new_obs.remaining_prefix','Återstående observationer detta år:'),
('sv','common','new_obs.seat_frozen','Plats fryst. Be ägaren hantera faktureringen.'),
('sv','common','new_obs.solo_quota_reached_body','Uppgradera till ett betalt abonnemang för att spåra observationer utan begränsningar.'),
('sv','common','new_obs.solo_quota_reached_cta','Visa abonnemang'),
('sv','common','new_obs.solo_quota_reached_title','Du har använt dina 3 gratis observationer'),
('sv','common','new_obs.solo_remaining_one','1 gratis observation kvar'),
('sv','common','new_obs.solo_remaining_other','{{count}} gratis observationer kvar'),
('sv','common','obs_edit.adl_label','Dagligt Liv (ADL)'),
('sv','common','obs_edit.comp_label','Heltäckande'),
('sv','common','obs_edit.fetching','Hämtar observation…'),
('sv','common','obs_edit.form_adl','ADL'),
('sv','common','obs_edit.form_comprehensive','Heltäckande'),
('sv','common','obs_edit.form_iadl','IADL'),
('sv','common','obs_edit.frozen_notice','Ditt konto har stängts av. Du kan inte redigera observationer just nu.'),
('sv','common','obs_edit.iadl_label','Livsfärdigheter (IADL)'),
('sv','common','obs_edit.invalid_type','Observationen har en ogiltig formulärtyp:'),
('sv','common','obs_edit.loading','Laddar observation…'),
('sv','common','obs_edit.missing_id','Observations-ID saknas i URL:en.'),
('sv','common','obs_edit.not_found','Observation hittades inte.'),
('sv','common','obs_edit.observation_label','Observation'),
('sv','common','obs_edit.readonly_notice','Du visar denna observation i skrivskyddat läge eftersom du inte är författaren.'),
('sv','common','obs_edit.render_error','Något gick fel vid laddning av denna observation.'),
('sv','common','obs_edit.render_error_detail','Uppdatera sidan eller gå tillbaka till instrumentpanelen.'),
('sv','common','obs_form.adl_label','Aktiviteter i Dagligt Liv'),
('sv','common','obs_form.autosave_hint','Sparas automatiskt när du har poängsatt minst ett objekt'),
('sv','common','obs_form.cat_notes_label','Anteckningar för {category} (valfritt)'),
('sv','common','obs_form.cat_notes_ph','Specifika anteckningar för {category}…'),
('sv','common','obs_form.comprehensive_label','Heltäckande (ADL + IADL)'),
('sv','common','obs_form.date_invalid','Ange ett giltigt datum i formatet ÅÅÅÅ-MM-DD'),
('sv','common','obs_form.date_label','Datum för observation'),
('sv','common','obs_form.date_placeholder','ÅÅÅÅ-MM-DD'),
('sv','common','obs_form.date_required','Datum för observation krävs'),
('sv','common','obs_form.err_email','Din kontoe-post saknas eller är ogiltig. Logga ut och logga in igen.'),
('sv','common','obs_form.err_no_score','Välj minst ett betyg innan du sparar.'),
('sv','common','obs_form.form_type_comp','Heltäckande (ADL + IADL)'),
('sv','common','obs_form.guidance','Fyll i så mycket eller lite du vill. Du behöver inte svara på varje fråga — även några betyg är till hjälp. Ditt arbete sparas automatiskt var 45:e sekund när du har angett minst ett betyg.'),
('sv','common','obs_form.iadl_label','Livsfärdigheter'),
('sv','common','obs_form.last_saved','Senast sparad {time}'),
('sv','common','obs_form.loading','Laddar ditt observationsformulär…'),
('sv','common','obs_form.mode_in_person','Personligen'),
('sv','common','obs_form.mode_label','Hur observerade du?'),
('sv','common','obs_form.mode_video','Videosamtal'),
('sv','common','obs_form.mode_voice','Röstsamtal'),
('sv','common','obs_form.more_help','Mer hjälp behövs'),
('sv','common','obs_form.more_indep','Mer självständig'),
('sv','common','obs_form.no_questions','Inga frågor tillgängliga'),
('sv','common','obs_form.notes_label','Allmänna anteckningar (valfritt)'),
('sv','common','obs_form.notes_ph','Allmänna observationer om dagens besök…'),
('sv','common','obs_form.notes_placeholder','Allmänna observationer om dagens besök…'),
('sv','common','obs_form.patient_label','Person som observeras'),
('sv','common','obs_form.patient_ph','Deras namn'),
('sv','common','obs_form.resident_edit_link','Redigera'),
('sv','common','obs_form.resident_no_profile_hint','Inget boendeprofil konfigurerat ännu.'),
('sv','common','obs_form.resident_no_profile_link','Konfigurera boendeprofil'),
('sv','common','obs_form.save_changes','Spara ändringar'),
('sv','common','obs_form.save_continue','Spara och fortsätt'),
('sv','common','obs_form.save_obs','Spara observation'),
('sv','common','obs_form.score_ref_header','Poängreferens — tryck på ett nummer för varje fråga för att registrera din observation'),
('sv','common','obs_form.scored_count','{scored} av {total} poängsatta'),
('sv','common','obs_form.title_edit','Redigera observation'),
('sv','common','obs_form.title_new','Ny observation'),

-- ============================================================
-- FINNISH (fi)
-- ============================================================
('fi','common','new_obs.adl_desc','Arvioi perusomahoitotehtäviä kuten kylpeminen, pukeutuminen, syöminen ja liikkuminen.'),
('fi','common','new_obs.adl_title','Päivittäisen Elämän Toiminnot'),
('fi','common','new_obs.choose_type','Valitse havaintotyyppi, jonka haluat tallentaa.'),
('fi','common','new_obs.comprehensive_desc','Täydellinen ADL- ja IADL-arviointi yhdessä. Käyttää 1 sadasta vuosittaisesta havainnosta.'),
('fi','common','new_obs.comprehensive_title','Kattava arviointi'),
('fi','common','new_obs.create_title','Luo uusi havainto'),
('fi','common','new_obs.iadl_desc','Arvioi monimutkaisia päivittäisiä taitoja kuten lääkityksen hallinta, talous ja liikenne.'),
('fi','common','new_obs.iadl_title','Välineelliset Päivittäisen Elämän Toiminnot'),
('fi','common','new_obs.loading','Valmistellaan uutta havaintoa…'),
('fi','common','new_obs.no_team','Luo ensin perhepiirisi.'),
('fi','common','new_obs.page_title','Uusi havainto'),
('fi','common','new_obs.quota_reached','Tiimin kiintiö saavutettu (100/vuosi).'),
('fi','common','new_obs.remaining_prefix','Havaintoja jäljellä tänä vuonna:'),
('fi','common','new_obs.seat_frozen','Paikka jäädytetty. Pyydä omistajaa hallitsemaan laskutusta.'),
('fi','common','new_obs.solo_quota_reached_body','Päivitä maksulliseen suunnitelmaan seurataksesi havaintoja ilman rajoituksia.'),
('fi','common','new_obs.solo_quota_reached_cta','Katso suunnitelmat'),
('fi','common','new_obs.solo_quota_reached_title','Olet käyttänyt 3 ilmaista havaintoasi'),
('fi','common','new_obs.solo_remaining_one','1 ilmainen havainto jäljellä'),
('fi','common','new_obs.solo_remaining_other','{{count}} ilmaista havaintoa jäljellä'),
('fi','common','obs_edit.adl_label','Päivittäinen Elämä (ADL)'),
('fi','common','obs_edit.comp_label','Kattava'),
('fi','common','obs_edit.fetching','Haetaan havaintoa…'),
('fi','common','obs_edit.form_adl','ADL'),
('fi','common','obs_edit.form_comprehensive','Kattava'),
('fi','common','obs_edit.form_iadl','IADL'),
('fi','common','obs_edit.frozen_notice','Tilisi on jäädytetty. Et voi muokata havaintoja tällä hetkellä.'),
('fi','common','obs_edit.iadl_label','Elämäntaidot (IADL)'),
('fi','common','obs_edit.invalid_type','Havainnolla on virheellinen lomaketyyppi:'),
('fi','common','obs_edit.loading','Ladataan havaintoa…'),
('fi','common','obs_edit.missing_id','URL:stä puuttuu havainnon tunniste.'),
('fi','common','obs_edit.not_found','Havaintoa ei löydy.'),
('fi','common','obs_edit.observation_label','Havainto'),
('fi','common','obs_edit.readonly_notice','Katselet tätä havaintoa vain luku -tilassa, koska et ole sen tekijä.'),
('fi','common','obs_edit.render_error','Havainnon lataaminen epäonnistui.'),
('fi','common','obs_edit.render_error_detail','Päivitä sivu tai palaa kojelautaan.'),
('fi','common','obs_form.adl_label','Päivittäisen Elämän Toiminnot'),
('fi','common','obs_form.autosave_hint','Tallentuu automaattisesti, kun olet pisteytetty vähintään yhden kohteen'),
('fi','common','obs_form.cat_notes_label','Muistiinpanot {category}lle (valinnainen)'),
('fi','common','obs_form.cat_notes_ph','Spesifiset muistiinpanot {category}lle…'),
('fi','common','obs_form.comprehensive_label','Kattava (ADL + IADL)'),
('fi','common','obs_form.date_invalid','Syötä kelvollinen päivämäärä muodossa PP.KK.VVVV'),
('fi','common','obs_form.date_label','Havainnon päivämäärä'),
('fi','common','obs_form.date_placeholder','PP.KK.VVVV'),
('fi','common','obs_form.date_required','Havainnon päivämäärä on pakollinen'),
('fi','common','obs_form.err_email','Tilisi sähköposti puuttuu tai on virheellinen. Kirjaudu ulos ja uudelleen sisään.'),
('fi','common','obs_form.err_no_score','Valitse vähintään yksi pistemäärä ennen tallentamista.'),
('fi','common','obs_form.form_type_comp','Kattava (ADL + IADL)'),
('fi','common','obs_form.guidance','Täytä niin paljon tai vähän kuin haluat. Sinun ei tarvitse vastata jokaiseen kysymykseen — jopa muutama pistemäärä on hyödyllinen. Työsi tallentuu automaattisesti 45 sekunnin välein, kun olet syöttänyt vähintään yhden pistemäärän.'),
('fi','common','obs_form.iadl_label','Elämäntaidot'),
('fi','common','obs_form.last_saved','Viimeksi tallennettu {time}'),
('fi','common','obs_form.loading','Ladataan havaintolomaketta…'),
('fi','common','obs_form.mode_in_person','Henkilökohtaisesti'),
('fi','common','obs_form.mode_label','Miten havaitsit?'),
('fi','common','obs_form.mode_video','Videopuhelu'),
('fi','common','obs_form.mode_voice','Äänipuhelu'),
('fi','common','obs_form.more_help','Enemmän apua tarvitaan'),
('fi','common','obs_form.more_indep','Itsenäisempi'),
('fi','common','obs_form.no_questions','Kysymyksiä ei saatavilla'),
('fi','common','obs_form.notes_label','Yleiset muistiinpanot (valinnainen)'),
('fi','common','obs_form.notes_ph','Yleisiä havaintoja tämän päivän vierailusta…'),
('fi','common','obs_form.notes_placeholder','Yleisiä havaintoja tämän päivän vierailusta…'),
('fi','common','obs_form.patient_label','Havainnoitava henkilö'),
('fi','common','obs_form.patient_ph','Heidän nimensä'),
('fi','common','obs_form.resident_edit_link','Muokkaa'),
('fi','common','obs_form.resident_no_profile_hint','Asukkaan profiilia ei ole vielä asetettu.'),
('fi','common','obs_form.resident_no_profile_link','Aseta asukkaan profiili'),
('fi','common','obs_form.save_changes','Tallenna Muutokset'),
('fi','common','obs_form.save_continue','Tallenna ja Jatka'),
('fi','common','obs_form.save_obs','Tallenna Havainto'),
('fi','common','obs_form.score_ref_header','Pistemäärän viite — napauta numeroa kussakin kysymyksessä tallentaaksesi havaintosi'),
('fi','common','obs_form.scored_count','{scored} / {total} pisteytetty'),
('fi','common','obs_form.title_edit','Muokkaa Havaintoa'),
('fi','common','obs_form.title_new','Uusi Havainto'),

-- ============================================================
-- JAPANESE (ja)
-- ============================================================
('ja','common','new_obs.adl_desc','入浴、着替え、食事、移動などの基本的なセルフケアタスクを評価します。'),
('ja','common','new_obs.adl_title','日常生活動作'),
('ja','common','new_obs.choose_type','記録する観察の種類を選択してください。'),
('ja','common','new_obs.comprehensive_desc','ADLとIADLの両方を一度に評価します。年間100回の観察のうち1回を使用します。'),
('ja','common','new_obs.comprehensive_title','包括的評価'),
('ja','common','new_obs.create_title','新しい観察を作成'),
('ja','common','new_obs.iadl_desc','服薬管理、財務、交通機関などの複雑な日常スキルを評価します。'),
('ja','common','new_obs.iadl_title','手段的日常生活動作'),
('ja','common','new_obs.loading','新しい観察を準備中…'),
('ja','common','new_obs.no_team','まずファミリーサークルを作成してください。'),
('ja','common','new_obs.page_title','新しい観察'),
('ja','common','new_obs.quota_reached','チームのクォータに達しました（100/年）。'),
('ja','common','new_obs.remaining_prefix','今年の残り観察数：'),
('ja','common','new_obs.seat_frozen','シートが凍結されています。オーナーに請求管理を依頼してください。'),
('ja','common','new_obs.solo_quota_reached_body','有料プランにアップグレードして、制限なく観察を記録しましょう。'),
('ja','common','new_obs.solo_quota_reached_cta','プランを見る'),
('ja','common','new_obs.solo_quota_reached_title','3回の無料観察を使い切りました'),
('ja','common','new_obs.solo_remaining_one','残り1回の無料観察'),
('ja','common','new_obs.solo_remaining_other','残り{{count}}回の無料観察'),
('ja','common','obs_edit.adl_label','日常生活（ADL）'),
('ja','common','obs_edit.comp_label','包括的'),
('ja','common','obs_edit.fetching','観察を取得中…'),
('ja','common','obs_edit.form_adl','ADL'),
('ja','common','obs_edit.form_comprehensive','包括的'),
('ja','common','obs_edit.form_iadl','IADL'),
('ja','common','obs_edit.frozen_notice','アカウントが停止されました。現在、観察を編集できません。'),
('ja','common','obs_edit.iadl_label','生活スキル（IADL）'),
('ja','common','obs_edit.invalid_type','観察に無効なフォームタイプがあります：'),
('ja','common','obs_edit.loading','観察を読み込み中…'),
('ja','common','obs_edit.missing_id','URLに観察IDがありません。'),
('ja','common','obs_edit.not_found','観察が見つかりません。'),
('ja','common','obs_edit.observation_label','観察'),
('ja','common','obs_edit.readonly_notice','あなたは著者ではないため、この観察を読み取り専用モードで表示しています。'),
('ja','common','obs_edit.render_error','この観察の読み込み中に問題が発生しました。'),
('ja','common','obs_edit.render_error_detail','ページを更新するか、ダッシュボードに戻ってください。'),
('ja','common','obs_form.adl_label','日常生活動作'),
('ja','common','obs_form.autosave_hint','少なくとも1つの項目を採点すると自動保存されます'),
('ja','common','obs_form.cat_notes_label','{category}のメモ（任意）'),
('ja','common','obs_form.cat_notes_ph','{category}に特定のメモ…'),
('ja','common','obs_form.comprehensive_label','包括的（ADL + IADL）'),
('ja','common','obs_form.date_invalid','MM/DD/YYYY形式で有効な日付を入力してください'),
('ja','common','obs_form.date_label','観察日'),
('ja','common','obs_form.date_placeholder','MM/DD/YYYY'),
('ja','common','obs_form.date_required','観察日は必須です'),
('ja','common','obs_form.err_email','アカウントのメールが見つからないか無効です。サインアウトして再度サインインしてください。'),
('ja','common','obs_form.err_no_score','保存前に少なくとも1つのスコアを選択してください。'),
('ja','common','obs_form.form_type_comp','包括的（ADL + IADL）'),
('ja','common','obs_form.guidance','好きなだけ記入してください。すべての質問に答える必要はありません。スコアがいくつかあるだけでも役立ちます。少なくとも1つのスコアを入力すると、45秒ごとに自動保存されます。'),
('ja','common','obs_form.iadl_label','生活スキル'),
('ja','common','obs_form.last_saved','最終保存 {time}'),
('ja','common','obs_form.loading','観察フォームを読み込み中…'),
('ja','common','obs_form.mode_in_person','対面'),
('ja','common','obs_form.mode_label','どのように観察しましたか？'),
('ja','common','obs_form.mode_video','ビデオ通話'),
('ja','common','obs_form.mode_voice','音声通話'),
('ja','common','obs_form.more_help','より多くの支援が必要'),
('ja','common','obs_form.more_indep','より自立している'),
('ja','common','obs_form.no_questions','質問はありません'),
('ja','common','obs_form.notes_label','全体的なメモ（任意）'),
('ja','common','obs_form.notes_ph','今日の訪問についての一般的な観察…'),
('ja','common','obs_form.notes_placeholder','今日の訪問についての一般的な観察…'),
('ja','common','obs_form.patient_label','観察対象者'),
('ja','common','obs_form.patient_ph','名前'),
('ja','common','obs_form.resident_edit_link','編集'),
('ja','common','obs_form.resident_no_profile_hint','居住者プロファイルはまだ設定されていません。'),
('ja','common','obs_form.resident_no_profile_link','居住者プロファイルを設定'),
('ja','common','obs_form.save_changes','変更を保存'),
('ja','common','obs_form.save_continue','保存して続ける'),
('ja','common','obs_form.save_obs','観察を保存'),
('ja','common','obs_form.score_ref_header','スコア参照 — 各質問の数字をタップして観察を記録してください'),
('ja','common','obs_form.scored_count','{total}のうち{scored}採点済み'),
('ja','common','obs_form.title_edit','観察を編集'),
('ja','common','obs_form.title_new','新しい観察')

ON CONFLICT (locale, namespace, key) DO UPDATE SET value = EXCLUDED.value;
