INSERT INTO ui_translations (locale, key, value) VALUES
('ja', 'memory_book.cancel', 'キャンセル'),
('ja', 'memory_book.confirm_remove_contact', '{name}を連絡先から削除しますか？'),
('ja', 'memory_book.confirm_remove_provider', '{name}をプロバイダーから削除しますか？'),
('ja', 'memory_book.confirm_remove_social', '{platform}アカウントを削除しますか？'),
('ja', 'memory_book.confirm_remove_sub', '{name}を削除しますか？'),
('ja', 'memory_book.confirm_remove_subscription', '{name}を削除しますか？'),
('ja', 'memory_book.confirm_remove_vehicle', '{name}を削除しますか？'),
('ja', 'memory_book.contact_fallback_label', '連絡先'),
('ja', 'memory_book.contact_save_btn', '連絡先を保存'),
('ja', 'memory_book.contacts_count_many', 'ファイルに{count}件の連絡先'),
('ja', 'memory_book.contacts_count_one', 'ファイルに1件の連絡先'),
('ja', 'memory_book.contacts_edit_heading', '連絡先を編集'),
('ja', 'memory_book.contacts_new_heading', '新しい連絡先'),
('ja', 'memory_book.edit', '編集'),
('ja', 'memory_book.field_about_me_placeholder', 'この人について他の人に知ってほしいことは何ですか？その人の個性、情熱、その人らしさを説明してください...'),
('ja', 'memory_book.field_address', '住所'),
('ja', 'memory_book.field_address_placeholder', 'クリニックの住所'),
('ja', 'memory_book.field_address_pref', '呼ばれ方の好み'),
('ja', 'memory_book.field_address_pref_placeholder', '例：田中さん、おばあちゃん、下の名前のみ'),
('ja', 'memory_book.field_allergies_placeholder', '食物アレルギー、薬アレルギー、環境アレルギー...'),
('ja', 'memory_book.field_auto_pay_bills', '自動支払いの請求'),
('ja', 'memory_book.field_auto_pay_bills_placeholder', '定期的な請求をリストアップ...'),
('ja', 'memory_book.field_avoid', '避けるべきこと'),
('ja', 'memory_book.field_avoid_placeholder', '避けるべきトピック、状況、人、または環境...'),
('ja', 'memory_book.field_bank_name', '銀行 / 口座名'),
('ja', 'memory_book.field_bank_name_placeholder', '例：アカデミー銀行——普通預金'),
('ja', 'memory_book.field_birthplace_placeholder', '町、都市、または地域'),
('ja', 'memory_book.field_comforts', '動揺したときに慰めになること'),
('ja', 'memory_book.field_comforts_placeholder', '音楽、特定の人、ルーティン、タッチ、言葉...'),
('ja', 'memory_book.field_conditions_placeholder', '日々のケアに関連する主要な症状をリストアップ...'),
('ja', 'memory_book.field_conversation_placeholder', '話すのが好きなトピック——家族、歴史、スポーツ、趣味...'),
('ja', 'memory_book.field_coverage_type_placeholder', '例：パートA——入院、パートB——医療'),
('ja', 'memory_book.field_cultural_bg', '文化的背景'),
('ja', 'memory_book.field_cultural_bg_placeholder', '文化的アイデンティティ、伝統、慣行'),
('ja', 'memory_book.field_cultural_prefs', '文化的な好み'),
('ja', 'memory_book.field_dislikes_placeholder', '不快感や不満を引き起こすもの...'),
('ja', 'memory_book.field_email', 'メール'),
('ja', 'memory_book.field_fears', '恐れ / 苦痛のトリガー'),
('ja', 'memory_book.field_fears_placeholder', '恐れ、興奮、または苦痛を引き起こすもの...'),
('ja', 'memory_book.field_foods_disliked', '嫌いな食べ物または避けている食べ物'),
('ja', 'memory_book.field_foods_disliked_placeholder', '食べ物の嫌い、食感の嫌悪...'),
('ja', 'memory_book.field_foods_liked', '好きな食べ物'),
('ja', 'memory_book.field_foods_liked_placeholder', 'お気に入りの食べ物、料理、おやつ...'),
('ja', 'memory_book.field_full_name', '氏名 *'),
('ja', 'memory_book.field_full_name_placeholder', '連絡先の氏名'),
('ja', 'memory_book.field_hearing', '聴覚に関するメモ'),
('ja', 'memory_book.field_hearing_placeholder', '補聴器、好み、ヒント...'),
('ja', 'memory_book.field_income_sources', '月収の源泉'),
('ja', 'memory_book.field_income_sources_placeholder', '収入源をリストアップ...'),
('ja', 'memory_book.field_insurance_notes', '追加メモ'),
('ja', 'memory_book.field_insurance_notes_placeholder', 'その他の保険の詳細や指示...'),
('ja', 'memory_book.field_insurer', '保険会社'),
('ja', 'memory_book.field_insurer_placeholder', '例：国民健康保険、ブルークロス'),
('ja', 'memory_book.field_investment_notes', '投資口座'),
('ja', 'memory_book.field_investment_notes_placeholder', '投資または退職口座に関するメモ...'),
('ja', 'memory_book.field_language_prefs_placeholder', '主要言語、コミュニケーションスタイル'),
('ja', 'memory_book.field_license_plate', 'ナンバープレート'),
('ja', 'memory_book.field_license_plate_placeholder', 'ナンバープレート番号'),
('ja', 'memory_book.field_likes', '楽しんでいること / 幸せにするもの'),
('ja', 'memory_book.field_likes_placeholder', '好きな活動、トピック、経験...'),
('ja', 'memory_book.field_make_model_year', 'メーカー / モデル / 年 *'),
('ja', 'memory_book.field_make_model_year_placeholder', '例：2019年 スバル フォレスター'),
('ja', 'memory_book.field_medications_placeholder', '現在の薬、用量、タイミング、投与に関するメモ...'),
('ja', 'memory_book.field_member_id', '会員ID'),
('ja', 'memory_book.field_member_id_placeholder', '会員または証券ID番号'),
('ja', 'memory_book.field_music', '音楽の好み'),
('ja', 'memory_book.field_music_placeholder', '好きなジャンル、アーティスト、曲、または楽器...'),
('ja', 'memory_book.field_notes', 'メモ'),
('ja', 'memory_book.field_notes_placeholder', 'この連絡先に関する追加メモ...'),
('ja', 'memory_book.field_other_medical', 'その他の医療上の考慮事項'),
('ja', 'memory_book.field_other_medical_placeholder', '介護者が知っておくべきその他の健康情報...'),
('ja', 'memory_book.field_parking_location', '駐車場所'),
('ja', 'memory_book.field_parking_location_placeholder', '例：スペース#9、レベル2、建物A'),
('ja', 'memory_book.field_phone', '電話'),
('ja', 'memory_book.field_plan', 'プラン名'),
('ja', 'memory_book.field_plan_placeholder', 'プラン名または番号'),
('ja', 'memory_book.field_practice_name', '診療所 / クリニック名'),
('ja', 'memory_book.field_practice_name_placeholder', '診療所またはクリニックの名前'),
('ja', 'memory_book.field_preferred_name_placeholder', '彼らが好む名前は何ですか？'),
('ja', 'memory_book.field_provider_address_placeholder', 'クリニックの住所'),
('ja', 'memory_book.field_provider_is_primary', 'プライマリプロバイダーとしてマーク'),
('ja', 'memory_book.field_provider_notes_placeholder', 'このプロバイダーに関する重要なメモ...'),
('ja', 'memory_book.field_provider_primary', 'プライマリプロバイダーとしてマーク'),
('ja', 'memory_book.field_registration_due', '登録期限'),
('ja', 'memory_book.field_relationship', '関係'),
('ja', 'memory_book.field_relationship_placeholder', '例：娘、かかりつけ医'),
('ja', 'memory_book.field_relationship_status_placeholder', '例：配偶者に先立たれた、既婚'),
('ja', 'memory_book.field_role', '役割'),
('ja', 'memory_book.field_role_select', '役割を選択...'),
('ja', 'memory_book.field_sensory', '感覚の好み'),
('ja', 'memory_book.field_sensory_placeholder', '照明、騒音レベル、温度、タッチの好み...'),
('ja', 'memory_book.field_service_provider', 'サービスプロバイダー'),
('ja', 'memory_book.field_service_provider_placeholder', '例：マイク・ショー・スバル、デンバー'),
('ja', 'memory_book.field_social_custom_platform', 'プラットフォーム名 *'),
('ja', 'memory_book.field_social_custom_platform_placeholder', '例：マイスペース、クラブハウス、フリッカー'),
('ja', 'memory_book.field_social_notes_placeholder', '例：娘のジェーンが管理、金庫にパスワードヒント'),
('ja', 'memory_book.field_social_platform', 'プラットフォーム *'),
('ja', 'memory_book.field_social_platform_select', 'プラットフォームを選択'),
('ja', 'memory_book.field_social_url', 'プロフィールURL'),
('ja', 'memory_book.field_social_url_placeholder', '例：https://facebook.com/johndoe'),
('ja', 'memory_book.field_social_username', 'ユーザー名 / ハンドル / メール'),
('ja', 'memory_book.field_social_username_placeholder', '例：@johndoe または john@example.com'),
('ja', 'memory_book.field_specialty', '専門 / 役割'),
('ja', 'memory_book.field_specialty_placeholder', '例：一般医、循環器内科医、歯科医、薬局'),
('ja', 'memory_book.field_sub_category', 'カテゴリ'),
('ja', 'memory_book.field_sub_category_select', 'カテゴリを選択'),
('ja', 'memory_book.field_sub_name', 'サービス名 *'),
('ja', 'memory_book.field_sub_name_placeholder', '例：アマゾンプライム、ネットフリックス、AAA'),
('ja', 'memory_book.field_subscription_category', 'カテゴリ'),
('ja', 'memory_book.field_subscription_name', 'サービス名 *'),
('ja', 'memory_book.field_subscription_name_placeholder', '例：アマゾンプライム、タイムマガジン、AAA'),
('ja', 'memory_book.field_subscription_notes', 'メモ'),
('ja', 'memory_book.field_subscription_notes_placeholder', '口座番号、更新日、またはその他の詳細...'),
('ja', 'memory_book.field_vehicle_make_model', 'メーカー / モデル / 年 *'),
('ja', 'memory_book.field_vehicle_make_model_placeholder', '例：2019年 スバル フォレスター'),
('ja', 'memory_book.field_vehicle_notes', 'メモ'),
('ja', 'memory_book.field_vehicle_notes_placeholder', 'その他の車両に関するメモ...'),
('ja', 'memory_book.field_vehicle_parking', '駐車場所'),
('ja', 'memory_book.field_vehicle_parking_placeholder', '例：スペース#9、レベル2、建物A'),
('ja', 'memory_book.field_vehicle_plate_placeholder', 'ナンバープレート番号'),
('ja', 'memory_book.field_vehicle_reg_due', '登録期限'),
('ja', 'memory_book.field_vehicle_reg_due_placeholder', '年月、例：2026年3月'),
('ja', 'memory_book.field_vehicle_service', 'サービスプロバイダー'),
('ja', 'memory_book.field_vehicle_service_placeholder', '例：マイク・ショー・スバル、デンバー'),
('ja', 'memory_book.field_vision', '視覚に関するメモ'),
('ja', 'memory_book.field_vision_placeholder', 'メガネ、障害、好み...'),
('ja', 'memory_book.finances_empty_owner_desc', '日々の財務管理に役立てるために、銀行の詳細、収入源、自動支払いの請求を記録してください。'),
('ja', 'memory_book.finances_empty_owner_title', '財務概要を追加'),
('ja', 'memory_book.finances_locked_desc', '財務情報はプライバシーのためチームオーナーのみに制限されています。'),
('ja', 'memory_book.finances_locked_title', 'オーナーアクセスのみ'),
('ja', 'memory_book.finances_owner_only_notice', 'このセクションはチームオーナーのみに表示されます。'),
('ja', 'memory_book.finances_subtitle', '銀行、収入源、定期的な請求'),
('ja', 'memory_book.identity_add_btn', 'アイデンティティの詳細を追加'),
('ja', 'memory_book.identity_empty_member_desc', 'チームオーナーがアイデンティティセクションを入力する必要があります。'),
('ja', 'memory_book.identity_empty_member_title', 'アイデンティティはまだ完了していません'),
('ja', 'memory_book.identity_empty_owner_desc', '介護者が意義深くつながれるように、好みの名前、出生地、文化的背景、および簡単な個人的なサマリーを記録してください。'),
('ja', 'memory_book.identity_empty_owner_title', 'アイデンティティ情報を追加'),
('ja', 'memory_book.identity_subtitle', '{residentName}の個人詳細'),
('ja', 'memory_book.identity_title', 'アイデンティティ & プロフィール'),
('ja', 'memory_book.insurance_dental_heading', '歯科 & 視覚保険'),
('ja', 'memory_book.insurance_dental_vision_heading', '歯科 & 視覚保険'),
('ja', 'memory_book.insurance_empty_member_desc', 'チームオーナーが保険セクションを入力する必要があります。'),
('ja', 'memory_book.insurance_empty_member_title', '保険はまだ完了していません'),
('ja', 'memory_book.insurance_empty_owner_desc', '介護者が予約や処方箋のために保険の詳細をすぐに見つけられるように、保険プランを記録してください。'),
('ja', 'memory_book.insurance_empty_owner_title', '保険の詳細を追加'),
('ja', 'memory_book.insurance_primary_heading', 'プライマリ保険'),
('ja', 'memory_book.insurance_secondary_heading', 'セカンダリ保険'),
('ja', 'memory_book.insurance_subtitle', 'プライマリ、セカンダリ、歯科/視覚の補償'),
('ja', 'memory_book.label_about_me', '私について'),
('ja', 'memory_book.label_address', '呼ばれ方'),
('ja', 'memory_book.label_avoid', '避けるべきこと'),
('ja', 'memory_book.label_birthplace', '出生地'),
('ja', 'memory_book.label_comforts', '動揺したときの慰め'),
('ja', 'memory_book.label_conversation', '良い会話トピック'),
('ja', 'memory_book.label_cultural_bg', '文化的背景'),
('ja', 'memory_book.label_dislikes', '嫌いなこと'),
('ja', 'memory_book.label_enjoys', '楽しんでいること / 幸せにするもの'),
('ja', 'memory_book.label_fears', '恐れ / 苦痛のトリガー'),
('ja', 'memory_book.label_foods_disliked', '避けるべき食べ物'),
('ja', 'memory_book.label_foods_liked', '好きな食べ物'),
('ja', 'memory_book.label_language_prefs', '言語の好み'),
('ja', 'memory_book.label_music', '音楽の好み'),
('ja', 'memory_book.label_preferred_name', '好みの名前'),
('ja', 'memory_book.label_relationship_status', '婚姻状況'),
('ja', 'memory_book.label_sensory', '感覚の好み'),
('ja', 'memory_book.medical_add_btn', '医療情報を追加'),
('ja', 'memory_book.medical_empty_member_desc', 'チームオーナーが医療セクションを入力する必要があります。'),
('ja', 'memory_book.medical_empty_member_title', '医療情報はまだ完了していません'),
('ja', 'memory_book.medical_empty_owner_desc', '介護者が安全で十分な情報に基づいたケアを提供できるよう、症状、アレルギー、聴覚、視覚、および薬に関するメモを記録してください。'),
('ja', 'memory_book.medical_empty_owner_title', '医療コンテキストを追加'),
('ja', 'memory_book.medical_subtitle', '介護者向けの健康情報——臨床記録ではない'),
('ja', 'memory_book.overview_age', '{age}歳'),
('ja', 'memory_book.overview_coming_desc', '日常生活、活動、食事、行動と安全、日記、変更ログはフェーズ2後に利用可能になります。'),
('ja', 'memory_book.overview_coming_title', 'フェーズ2で登場'),
('ja', 'memory_book.overview_incomplete_desc_many', '介護者に完全な情報を提供するために、{count}のセクションをまだ入力する必要があります。'),
('ja', 'memory_book.overview_incomplete_desc_one', '介護者に完全な情報を提供するために、1つのセクションをまだ入力する必要があります。'),
('ja', 'memory_book.overview_incomplete_title', 'メモリーブックが未完成'),
('ja', 'memory_book.overview_no_summary', 'まだ個人的なサマリーが追加されていません。'),
('ja', 'memory_book.overview_no_summary_owner_hint', 'メモリーブックタブで追加してください。'),
('ja', 'memory_book.overview_not_started', '未開始'),
('ja', 'memory_book.overview_progress_title', 'メモリーブックの進捗'),
('ja', 'memory_book.overview_records_many', '{count}件の記録'),
('ja', 'memory_book.overview_records_one', '1件の記録'),
('ja', 'memory_book.overview_sections_count', '{completed}/{total}セクション'),
('ja', 'memory_book.prefs_add_btn', '好みを追加'),
('ja', 'memory_book.prefs_empty_member_desc', 'チームオーナーが好みセクションを入力する必要があります。'),
('ja', 'memory_book.prefs_empty_member_title', '好みはまだ完了していません'),
('ja', 'memory_book.prefs_empty_owner_desc', '何が慰め、喜び、避けるべきかを記録することで、すべての介護者がより個人的な体験を提供できます。'),
('ja', 'memory_book.prefs_empty_owner_title', '好き、嫌い & 慰めを追加'),
('ja', 'memory_book.prefs_subtitle', '喜びと慰めをもたらすもの、避けるべきもの'),
('ja', 'memory_book.print_btn', 'メモリーブックを印刷'),
('ja', 'memory_book.print_confidential', '機密——ケアチーム専用'),
('ja', 'memory_book.print_generated', '生成日'),
('ja', 'memory_book.print_no_data', 'まだ情報が記録されていません。'),
('ja', 'memory_book.print_section_contacts', 'ケアネットワーク & 連絡先'),
('ja', 'memory_book.print_section_finances', '収入 & 財務'),
('ja', 'memory_book.print_section_household', '家庭情報'),
('ja', 'memory_book.print_section_identity', 'アイデンティティ & プロフィール'),
('ja', 'memory_book.print_section_insurance', '健康保険'),
('ja', 'memory_book.print_section_medical', '医療コンテキスト'),
('ja', 'memory_book.print_section_preferences', '好き、嫌い & 慰め'),
('ja', 'memory_book.print_section_providers', '医療提供者'),
('ja', 'memory_book.print_section_subscriptions', 'サブスクリプション & 会員'),
('ja', 'memory_book.print_section_vehicle', '車両 & 交通'),
('ja', 'memory_book.print_title', 'メモリーブック'),
('ja', 'memory_book.provider_primary_badge', 'プライマリ'),
('ja', 'memory_book.provider_primary_label', 'プライマリ'),
('ja', 'memory_book.provider_save_btn', 'プロバイダーを保存'),
('ja', 'memory_book.readonly_notice', 'このセクションへの閲覧アクセス権があります。変更できるのはチームオーナーのみです。'),
('ja', 'memory_book.role_member', '介護者'),
('ja', 'memory_book.role_owner', '主介護者'),
('ja', 'memory_book.role_resident', '利用者'),
('ja', 'memory_book.save_changes', '変更を保存'),
('ja', 'memory_book.section_preferences', '好き & 嫌い'),
('ja', 'memory_book.social_add_first_btn', '最初のアカウントを追加'),
('ja', 'memory_book.social_count_many', 'ファイルに{count}件のアカウント'),
('ja', 'memory_book.social_count_one', 'ファイルに1件のアカウント'),
('ja', 'memory_book.social_edit_heading', 'アカウントを編集'),
('ja', 'memory_book.social_empty_desc', '必要なときに家族が管理できるよう、ソーシャルメディアのプロフィール、メールアカウント、およびその他のオンラインサービスを記録してください。'),
('ja', 'memory_book.social_empty_title', 'まだオンラインアカウントが追加されていません'),
('ja', 'memory_book.social_new_heading', '新しいアカウント'),
('ja', 'memory_book.social_title', 'ソーシャルメディア & オンラインアカウント'),
('ja', 'memory_book.sub_cat_delivery', '配達'),
('ja', 'memory_book.sub_cat_health', '健康 & ウェルネス'),
('ja', 'memory_book.sub_cat_music', '音楽'),
('ja', 'memory_book.sub_cat_news', 'ニュース'),
('ja', 'memory_book.sub_cat_other', 'その他'),
('ja', 'memory_book.sub_cat_software', 'ソフトウェア'),
('ja', 'memory_book.sub_cat_streaming', 'ストリーミング'),
('ja', 'memory_book.sub_cat_utility', 'ユーティリティ'),
('ja', 'memory_book.subs_add_btn', 'サブスクリプションを追加'),
('ja', 'memory_book.subs_add_first_btn', '最初のサブスクリプションを追加'),
('ja', 'memory_book.subs_count_many', 'ファイルに{count}件のサブスクリプション'),
('ja', 'memory_book.subs_count_one', 'ファイルに1件のサブスクリプション'),
('ja', 'memory_book.subs_edit_heading', 'サブスクリプションを編集'),
('ja', 'memory_book.subs_empty_desc', 'テレビサービス、雑誌の購読、会員、およびその他の定期的なサービスを追跡して何も失効しないようにしてください。'),
('ja', 'memory_book.subs_empty_title', 'まだサブスクリプションが追加されていません'),
('ja', 'memory_book.subs_new_heading', '新しいサブスクリプション'),
('ja', 'memory_book.subs_title', 'サブスクリプション & 会員'),
('ja', 'memory_book.subscription_cat_magazine', '雑誌'),
('ja', 'memory_book.subscription_cat_membership', '会員'),
('ja', 'memory_book.subscription_cat_other', 'その他'),
('ja', 'memory_book.subscription_cat_tv', 'テレビ / ストリーミング'),
('ja', 'memory_book.subscription_save_btn', 'サブスクリプションを保存'),
('ja', 'memory_book.subscriptions_add_first_btn', '最初のサブスクリプションを追加'),
('ja', 'memory_book.subscriptions_count_many', 'ファイルに{count}件のサブスクリプション'),
('ja', 'memory_book.subscriptions_count_one', 'ファイルに1件のサブスクリプション'),
('ja', 'memory_book.subscriptions_edit_heading', 'サブスクリプションを編集'),
('ja', 'memory_book.subscriptions_empty_desc', 'テレビサービス、雑誌の購読、会員、およびその他の定期的なサービスを追跡して何も失効しないようにしてください。'),
('ja', 'memory_book.subscriptions_empty_title', 'まだサブスクリプションが追加されていません'),
('ja', 'memory_book.subscriptions_new_heading', '新しいサブスクリプション'),
('ja', 'memory_book.subscriptions_subtitle', 'テレビ、雑誌、会員、およびその他の定期的なサービス'),
('ja', 'memory_book.toast_contact_added', '連絡先が追加されました'),
('ja', 'memory_book.toast_contact_failed', '連絡先の保存に失敗しました'),
('ja', 'memory_book.toast_contact_remove_failed', '削除に失敗しました'),
('ja', 'memory_book.toast_contact_removed', '連絡先が削除されました'),
('ja', 'memory_book.toast_contact_required', '連絡先名が必要です'),
('ja', 'memory_book.toast_contact_updated', '連絡先が更新されました'),
('ja', 'memory_book.toast_finances_saved', '財務情報が保存されました'),
('ja', 'memory_book.toast_identity_saved', 'アイデンティティが保存されました'),
('ja', 'memory_book.toast_insurance_saved', '保険情報が保存されました'),
('ja', 'memory_book.toast_medical_saved', '医療情報が保存されました'),
('ja', 'memory_book.toast_prefs_saved', '好みが保存されました'),
('ja', 'memory_book.toast_provider_added', 'プロバイダーが追加されました'),
('ja', 'memory_book.toast_provider_failed', 'プロバイダーの保存に失敗しました'),
('ja', 'memory_book.toast_provider_name_required', 'プロバイダー名が必要です'),
('ja', 'memory_book.toast_provider_remove_failed', 'プロバイダーの削除に失敗しました'),
('ja', 'memory_book.toast_provider_removed', 'プロバイダーが削除されました'),
('ja', 'memory_book.toast_provider_required', 'プロバイダー名が必要です'),
('ja', 'memory_book.toast_provider_updated', 'プロバイダーが更新されました'),
('ja', 'memory_book.toast_social_added', 'アカウントが追加されました'),
('ja', 'memory_book.toast_social_platform_required', 'プラットフォームが必要です'),
('ja', 'memory_book.toast_social_removed', 'アカウントが削除されました'),
('ja', 'memory_book.toast_social_updated', 'アカウントが更新されました'),
('ja', 'memory_book.toast_sub_added', 'サブスクリプションが追加されました'),
('ja', 'memory_book.toast_sub_removed', 'サブスクリプションが削除されました'),
('ja', 'memory_book.toast_sub_required', 'サブスクリプション名が必要です'),
('ja', 'memory_book.toast_sub_updated', 'サブスクリプションが更新されました'),
('ja', 'memory_book.toast_subscription_added', 'サブスクリプションが追加されました'),
('ja', 'memory_book.toast_subscription_failed', 'サブスクリプションの保存に失敗しました'),
('ja', 'memory_book.toast_subscription_name_required', 'サブスクリプション名が必要です'),
('ja', 'memory_book.toast_subscription_remove_failed', 'サブスクリプションの削除に失敗しました'),
('ja', 'memory_book.toast_subscription_removed', 'サブスクリプションが削除されました'),
('ja', 'memory_book.toast_subscription_updated', 'サブスクリプションが更新されました'),
('ja', 'memory_book.toast_vehicle_added', '車両が追加されました'),
('ja', 'memory_book.toast_vehicle_failed', '車両の保存に失敗しました'),
('ja', 'memory_book.toast_vehicle_name_required', '車両のメーカー/モデルが必要です'),
('ja', 'memory_book.toast_vehicle_remove_failed', '車両の削除に失敗しました'),
('ja', 'memory_book.toast_vehicle_removed', '車両が削除されました'),
('ja', 'memory_book.toast_vehicle_required', '車両のメーカー/モデルが必要です'),
('ja', 'memory_book.toast_vehicle_updated', '車両が更新されました'),
('ja', 'memory_book.vehicle_add_first_btn', '最初の車両を追加'),
('ja', 'memory_book.vehicle_count_many', 'ファイルに{count}台の車両'),
('ja', 'memory_book.vehicle_count_one', 'ファイルに1台の車両'),
('ja', 'memory_book.vehicle_edit_heading', '車両を編集'),
('ja', 'memory_book.vehicle_empty_desc', 'すぐに参照できるよう、車両の詳細、ナンバープレート、登録期限、サービスプロバイダーを記録してください。'),
('ja', 'memory_book.vehicle_empty_title', 'まだ車両が追加されていません'),
('ja', 'memory_book.vehicle_new_heading', '新しい車両'),
('ja', 'memory_book.vehicle_reg_due_soon', '登録期限が近づいています'),
('ja', 'memory_book.vehicle_reg_overdue', '登録が期限切れです'),
('ja', 'memory_book.vehicle_reg_soon', '登録期限が近づいています'),
('ja', 'memory_book.vehicle_save_btn', '車両を保存'),
('ja', 'memory_book.vehicle_subtitle', '車の詳細、登録、サービス情報'),
('ja', 'memory_book.vehicles_add_btn', '車両を追加'),
('ja', 'memory_book.vehicles_add_first_btn', '最初の車両を追加'),
('ja', 'memory_book.vehicles_count_many', 'ファイルに{count}台の車両'),
('ja', 'memory_book.vehicles_count_one', 'ファイルに1台の車両'),
('ja', 'memory_book.vehicles_edit_heading', '車両を編集'),
('ja', 'memory_book.vehicles_empty_desc', 'すぐに参照できるよう、車両の詳細、ナンバープレート、登録期限、サービスプロバイダーを記録してください。'),
('ja', 'memory_book.vehicles_empty_title', 'まだ車両が追加されていません'),
('ja', 'memory_book.vehicles_new_heading', '新しい車両'),
('ja', 'memory_book.vehicles_title', '車両 & 交通'),
('ja', 'memory_book.viewing_as', '閲覧中：')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
('ja','why.adl_1','入浴・身の回りの衛生'),
('ja','why.adl_2','着替え・身だしなみ'),
('ja','why.adl_3','食事・飲み物'),
('ja','why.adl_4','トイレ・排泄管理'),
('ja','why.adl_5','移動・移乗'),
('ja','why.adl_6','安全意識'),
('ja','why.adl_title','日常生活活動'),
('ja','why.careplan_body','CarerViewのケアプランは重要なすべての側面をカバーします — ケア受益者のニーズだけでなく、チームのキャパシティ、法的権限構造、そしてプランを最新に保つメカニズム。各セクションは、家族が数ヶ月後に必要だったと気づく質問をします。'),
('ja','why.careplan_eyebrow','ケアプラン'),
('ja','why.careplan_title','家族のために構築されたプロフェッショナルグレードのフレームワーク'),
('ja','why.cta_begin','今すぐ観察を始める'),
('ja','why.cta_signin','サインイン'),
('ja','why.cta_trend_body','CarerViewはすべての家族ケアラーに構造化されたフレームワーク、調整ハブ、そすべてを最新に保つ観察を提供します。無料で始められます — クレジットカード不要。'),
('ja','why.cta_trend_title','プランを構築。チームを調整。重要なことを追跡。'),
('ja','why.custom_note','観察はカスタマイズ可能なので、CarerViewはあなたの家族の現実に合わせられます。'),
('ja','why.engine_body','ケアプランを構築するにつれて、CarerViewのデシジョンエンジンが不足しているものを読み取り、深刻度別にフラグを立てます。重要なギャップ — 医療権限の不備やバックアップケアラーの不在など — が最初に表示されます。重要なギャップ — 未割り当ての責任など — が続きます。プランは後で心配することではなく、最初に何をすべきかを教えてくれます。'),
('ja','why.engine_title','デシジョンエンジン：危機になる前にギャップを発見'),
('ja','why.faq6_a','デシジョンエンジンは、構築中のケアプランをスキャンして不足または不完全なセクションを特定する組み込みの分析ツールです。深刻度別にギャップをフラグ立てします — 重要（今すぐ対処）、重要度高（近いうちに対処）、要監視（注意を払い続ける）。これは医療ツールではなく — チームが最も重要なことに集中するための調整ツールです。'),
('ja','why.faq6_q','CarerViewのデシジョンエンジンとは何ですか？'),
('ja','why.faq7_a','ケアプランダッシュボードには、セクションと深刻度別にグループ分けされた検出されたギャップのサマリーが表示されます。各ギャップにはリスクの短い説明と推奨アクションステップが含まれます。最も緊急なギャップが上部にハイライトされます。任意の順序でギャップに取り組めます — プランはそれらに対処するにつれてリアルタイムで更新されます。'),
('ja','why.faq7_q','CarerViewはどのようにプランにギャップがあることを教えてくれますか？'),
('ja','why.hero_title','介護の組織化はストレスです！'),
('ja','why.hero_title_line2','CarerViewが調和をもたらします…'),
('ja','why.how1_body','日常生活活動のコア項目について、数分で今日の様子をメモしましょう。簡単なチェックインや完全な観察をいつでも作成できます。'),
('ja','why.how1_title','シンプルな観察'),
('ja','why.how2_body','明確な言葉 — 医療専門用語なし — 家族が理解できる作業療法のベストプラクティスに基づいています。'),
('ja','why.how2_title','簡単な1〜5スケール'),
('ja','why.how3_body','今日の感じだけでなく、日数・週数・月数にわたる変化を観察します。観察されたトレンドがルーティンやサポートを調整するタイミングを示します。'),
('ja','why.how3_title','信頼できるトレンド'),
('ja','why.how4_body','家族や臨床医と個人の観察を共有して、同じ定義とデータから議論を始めます。'),
('ja','why.how4_title','みんなを一致させる'),
('ja','why.iadl_1','服薬管理'),
('ja','why.iadl_2','食事・買い物'),
('ja','why.iadl_3','家事・洗濯'),
('ja','why.iadl_4','財務・事務処理'),
('ja','why.iadl_5','コミュニケーション・記憶'),
('ja','why.iadl_6','交通・買い物'),
('ja','why.iadl_title','手段的活動'),
('ja','why.newcarer_body','無料の8モジュールケアラーガイドは、家族介護のすべての側面を説明します — 役割が実際に何を含むかを理解することから、持続可能な長期計画を立てることまで。登録前に使用するか、ケアシステムを構築しながらCarerViewとともに使用してください。'),
('ja','why.newcarer_cta','CarerView無料の新しいケアラーガイドを探索する'),
('ja','why.newcarer_title','介護が初めての方へ。ここから始めてください。'),
('ja','why.persona1_b1','一か所で更新を見る — 情報を探し回る必要なし。'),
('ja','why.persona1_b2','電話や訪問の準備のためにトレンドを確認する。'),
('ja','why.persona1_b3','各人が見る必要があるものだけを共有する。'),
('ja','why.persona1_quote','「外出中です。状況から取り残されるのが嫌でした。CarerViewで電話する前に最新の観察を確認できます。」'),
('ja','why.persona1_title','遠距離家族の調整'),
('ja','why.persona2_b1','起きたことをリアルタイムで記録する。'),
('ja','why.persona2_b2','実際のメモから診察用サマリーを作成する。'),
('ja','why.persona2_b3','共有コンテキストでより落ち着いた決断をする。'),
('ja','why.persona2_quote','「子供たちと母の診察の間に詳細を忘れてしまいます。CarerViewがパターンを記録するので、医師に明確なメモを持参できます。」'),
('ja','why.persona2_title','サンドイッチ世代のケアラー'),
('ja','why.persona3_b1','初日から責任が割り当てられ — 誰も取り残されない'),
('ja','why.persona3_b2','観察がすぐに始まり — 何か変化があれば早期警告'),
('ja','why.persona3_b3','フォローアップ診察で共有するための臨床医向けサマリー'),
('ja','why.persona3_quote','退院日は圧倒されました。CarerViewは大量の指示書を本物の計画に変えるのを助けてくれました — 48時間以内に全員が自分の役割を把握しました。'),
('ja','why.persona3_title','退院の管理'),
('ja','why.persona4_b1','ストレスレベルが追跡され、ケアラーだけでなくチーム全体に見える'),
('ja','why.persona4_b2','限界点の前にバックアップケアラーが特定され計画が文書化される'),
('ja','why.persona4_b3','事実に基づいて公平に — 口論ではなく — 責任が再分配される'),
('ja','why.persona4_quote','一人ですべてをやっていて、誰にも見えていませんでした。CarerViewが私の状況を家族の他のメンバーに見えるようにしてくれました — そしてそのとき、ようやく物事が変わり始めました。'),
('ja','why.persona4_title','燃え尽きそうなプライマリケアラー'),
('ja','why.personas_title','本物の介護状況のために構築された'),
('ja','why.shared_lang_title','4つの柱。1つの調整されたケアシステム。'),
('ja','why.sustainability_body','ケアラーの燃え尽きは家族介護における最大のリスクの一つ — 通常、手遅れになるまで見えません。CarerViewの持続可能性セクションはプライマリケアラーのストレスレベル、バックアップカバー、レスパイト計画を追跡します。プランがリスクをフラグ立てすると、危機が会話を強制する前にチームが知ります。'),
('ja','why.sustainability_eyebrow','ケアラーの健康'),
('ja','why.sustainability_title','CarerViewはケア受益者だけでなく、ケアラーも追跡します'),
('ja','why.track_body','実際の日常生活を反映するシンプルな生活カテゴリー'),
('ja','why.track_title','観察する内容')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- new_obs namespace
('ja','new_obs.choose_type','記録する観察の種類を選択してください。'),
('ja','new_obs.create_title','新しい観察を作成'),
('ja','new_obs.email_missing','アカウントのメールアドレスが見つかりません。プロフィールを更新してください。'),
('ja','new_obs.loading','新しい観察を準備しています…'),
('ja','new_obs.no_team','最初にファミリーサークルを作成してください。'),
('ja','new_obs.page_title','新しい観察'),
('ja','new_obs.quota_reached','チームクォータに達しました（100回/年）。'),
('ja','new_obs.remaining_prefix','今年の残り観察回数：'),
('ja','new_obs.seat_frozen','シートが凍結されています。オーナーに請求管理を依頼してください。'),
-- obs_edit namespace
('ja','obs_edit.adl_label','日常生活（ADL）'),
('ja','obs_edit.comp_label','総合的評価'),
('ja','obs_edit.fetching','観察を取得しています…'),
('ja','obs_edit.form_adl','ADL'),
('ja','obs_edit.form_comprehensive','総合的評価'),
('ja','obs_edit.form_iadl','IADL'),
('ja','obs_edit.frozen_notice','アカウントが停止されています。現在、観察を編集できません。'),
('ja','obs_edit.iadl_label','生活スキル（IADL）'),
('ja','obs_edit.invalid_type','観察に無効なフォームタイプがあります：'),
('ja','obs_edit.loading','観察を読み込んでいます…'),
('ja','obs_edit.missing_id','URLに観察IDがありません。'),
('ja','obs_edit.observation_label','観察'),
('ja','obs_edit.readonly_notice','あなたは作成者ではないため、この観察を読み取り専用モードで閲覧しています。'),
('ja','obs_edit.render_error','この観察の読み込み中に問題が発生しました。'),
('ja','obs_edit.render_error_detail','ページを更新するか、ダッシュボードに戻ってください。'),
-- obs_form namespace
('ja','obs_form.adl_label','日常生活活動'),
('ja','obs_form.adl_type_label','日常生活動作'),
('ja','obs_form.autosave_hint','少なくとも1つの項目にスコアを入力すると自動保存されます'),
('ja','obs_form.cat_notes_label','{category}のメモ（任意）'),
('ja','obs_form.cat_notes_ph','{category}に関する具体的なメモ…'),
('ja','obs_form.cat_notes_placeholder','このカテゴリーに関する具体的なメモを追加…'),
('ja','obs_form.category_scored','{scored}/{total} スコア済み'),
('ja','obs_form.comprehensive_label','総合的評価（ADL＋IADL）'),
('ja','obs_form.contact_support','この問題が続く場合は、サポートにお問い合わせください。'),
('ja','obs_form.date_invalid','MM/DD/YYYY形式で有効な日付を入力してください'),
('ja','obs_form.date_label','観察日'),
('ja','obs_form.date_placeholder','MM/DD/YYYY'),
('ja','obs_form.date_required','観察日は必須です'),
('ja','obs_form.err_email','アカウントのメールアドレスが見つからないか無効です。サインアウトして再度サインインしてください。'),
('ja','obs_form.err_no_score','保存する前に少なくとも1つのスコアを選択してください。'),
('ja','obs_form.error_loading','観察の質問を読み込めませんでした。もう一度お試しください。'),
('ja','obs_form.form_type_comp','総合的評価（ADL＋IADL）'),
('ja','obs_form.guidance','好きなだけ多く、または少なく記入してください。すべての質問に答える必要はありません — 少数のスコアでも役立ちます。少なくとも1つのスコアを入力すると、45秒ごとに自動保存されます。'),
('ja','obs_form.guidance_bold','ヒント：'),
('ja','obs_form.iadl_label','生活スキル'),
('ja','obs_form.iadl_type_label','手段的日常生活活動'),
('ja','obs_form.last_saved','{time}に最後に保存'),
('ja','obs_form.last_saved_at','最後に保存した時刻'),
('ja','obs_form.loading','観察フォームを読み込んでいます…'),
('ja','obs_form.mode_in_person','対面'),
('ja','obs_form.mode_label','どのように観察しましたか？'),
('ja','obs_form.mode_video','ビデオ通話'),
('ja','obs_form.mode_voice','音声通話'),
('ja','obs_form.more_help','より多くのサポートが必要'),
('ja','obs_form.more_indep','より自立している'),
('ja','obs_form.no_questions','利用可能な質問がありません'),
('ja','obs_form.no_score_hint','この観察を保存するには、上記の少なくとも1つの質問にスコアをつけてください。'),
('ja','obs_form.notes_ph','今日の訪問に関する一般的な観察…'),
('ja','obs_form.patient_label','観察対象者'),
('ja','obs_form.patient_ph','その方のお名前'),
('ja','obs_form.resident_edit_link','編集'),
('ja','obs_form.resident_no_profile_hint','まだ入居者プロファイルが設定されていません。'),
('ja','obs_form.resident_no_profile_link','入居者プロファイルを設定する'),
('ja','obs_form.resident_placeholder','その方のお名前'),
('ja','obs_form.save_changes','変更を保存'),
('ja','obs_form.save_continue','保存して続ける'),
('ja','obs_form.save_failed','自動保存に失敗しました'),
('ja','obs_form.save_obs','観察を保存'),
('ja','obs_form.saved','保存済み'),
('ja','obs_form.saving','保存中…'),
('ja','obs_form.score_ref_header','スコア参照 — 各質問の番号をタップして観察を記録してください'),
('ja','obs_form.scored_count','{scored}/{total} スコア済み'),
('ja','obs_form.title_edit','観察を編集'),
('ja','obs_form.title_new','新しい観察'),
-- obs_list namespace
('ja','obs_list.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','obs_list.delete_title','観察を削除しますか？'),
('ja','obs_list.empty_body','最初の観察を作成して始めましょう。'),
('ja','obs_list.empty_title','観察がまだありません'),
('ja','obs_list.export_csv','CSVとしてエクスポート'),
('ja','obs_list.export_docx','DOCXとしてエクスポート'),
('ja','obs_list.guest_badge','ゲスト'),
('ja','obs_list.load_failed','観察の読み込みに失敗しました'),
('ja','obs_list.loading','観察を読み込んでいます...'),
('ja','obs_list.observed_on','{date}に観察'),
('ja','obs_list.unnamed_resident','名前のない入居者'),
-- view_obs namespace
('ja','view_obs.back_list','リストに戻る'),
('ja','view_obs.caregiver','ケアラー'),
('ja','view_obs.comp_label','総合的評価（ADL＋IADL）'),
('ja','view_obs.csv_label','スプレッドシート（.csv）'),
('ja','view_obs.delete_generic','この観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_msg','{date}の「{name}」の観察を削除しますか？この操作は取り消せません。'),
('ja','view_obs.delete_title','観察を削除しますか？'),
('ja','view_obs.details_title','観察の詳細'),
('ja','view_obs.docx_label','Wordドキュメント（.docx）'),
('ja','view_obs.load_error','観察を読み込めませんでした。もう一度お試しください。'),
('ja','view_obs.load_failed','観察の読み込みに失敗しました'),
('ja','view_obs.loading','観察を読み込んでいます...'),
('ja','view_obs.mode','観察方法'),
('ja','view_obs.no_resp_body','この観察には記録された回答がありません。'),
('ja','view_obs.no_responses','回答なし'),
('ja','view_obs.not_found','観察が見つかりません'),
('ja','view_obs.notes','メモ'),
('ja','view_obs.obs_date','観察日'),
('ja','view_obs.obs_type','観察タイプ'),
('ja','view_obs.patient_name','患者名'),
('ja','view_obs.print','印刷'),
('ja','view_obs.resident_name','入居者名')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- pricing
('ja','pricing.cta_begin','今すぐ観察を始める'),
('ja','pricing.faq_title','よくある質問と回答'),
('ja','pricing.faq1_a','四半期請求は課金の煩わしさを軽減しながら、シンプルな週次観察のリズムをサポートします。次回の請求日はチェックアウト時に表示されます。'),
('ja','pricing.faq1_q','なぜ四半期請求なのですか？'),
('ja','pricing.faq2_a','すべての履歴は保持されます。上限はただ安定した現実的なペースを促すものです。必要に応じて後でプランを変更できます。'),
('ja','pricing.faq2_q','観察上限に達した場合はどうなりますか？'),
('ja','pricing.faq3_a','はい。無料、プライマリ、ファミリーサークル間でアップグレードまたはダウングレードできます。変更は次回の請求日から有効になります。'),
('ja','pricing.faq3_q','後でプランを切り替えることはできますか？'),
('ja','pricing.faq4_a','オブザーバーは家族の更新を閲覧し、年間最大3回のメモを追加できます。プライマリケアラーが招待と公開範囲を管理します。'),
('ja','pricing.faq4_q','無料オブザーバーはすべてを閲覧できますか？'),
('ja','pricing.faq5_a','ファミリーサークルは最大3名のケアラーをサポートします。大家族の場合、2つ目のファミリーサークルプランを追加することが多いです。'),
('ja','pricing.faq5_q','家族に3名以上のケアラーが必要な場合は？'),
('ja','pricing.hero_body','1人のケアラーでも複数でも、何が変化しているかの明確な記録が残ります — 曖昧な記憶ではなく、事実から会話を始められます。'),
('ja','pricing.hero_tagline','「不確かさが減り、安心感が増します。」'),
('ja','pricing.hero_title','より良い介護のためのシンプルなプラン'),
('ja','pricing.plan_family_cta','ファミリーサークルを選ぶ'),
('ja','pricing.plan_family_desc','みんなのメモ、一つの共有されたストーリー。最大3名のケアラーが摩擦なく協力します。'),
('ja','pricing.plan_family_f1','最大3名のケアラー'),
('ja','pricing.plan_family_f2','年間100回の観察（共有）'),
('ja','pricing.plan_family_f3','共有週次ダイジェスト＆リマインダー'),
('ja','pricing.plan_family_f4','プライマリプラン3つより33%節約'),
('ja','pricing.plan_family_feat5','ケアプランビルダー（6セクション）— チーム全体で共有'),
('ja','pricing.plan_family_feat6','デシジョンエンジン — チーム全体の共有ギャップアラート'),
('ja','pricing.plan_family_feat7','メモリーブック — すべてのチームメンバーが即座にアクセス可能'),
('ja','pricing.plan_family_feat8','ケアハブ — 家族全体のための完全な調整ワークスペース'),
('ja','pricing.plan_family_name','ファミリーサークル'),
('ja','pricing.plan_family_price','25.50 USD/四半期（月額9ドル未満）'),
('ja','pricing.plan_free_cta','無料で始める'),
('ja','pricing.plan_free_desc','招待でケアチームに参加。更新を閲覧し、観察をフォローし、時々メモを追加できます。常に無料。'),
('ja','pricing.plan_free_f1','年間3回の観察'),
('ja','pricing.plan_free_f2','ケアラーからの招待で参加'),
('ja','pricing.plan_free_f3','家族タイムラインで更新を閲覧'),
('ja','pricing.plan_free_name','コミュニティオブザーバー'),
('ja','pricing.plan_free_price','常に無料'),
('ja','pricing.plan_primary_bill','3ヶ月ごとに請求。次回の請求日はチェックアウト時に表示されます。'),
('ja','pricing.plan_primary_cta','プライマリを選ぶ'),
('ja','pricing.plan_primary_desc','1人のケアラー、1つの明確な記録。年間30回の観察でトレンドを可視化し、ケアプランを軌道に乗せます。'),
('ja','pricing.plan_primary_f1','年間30回の観察（約週1回）'),
('ja','pricing.plan_primary_f2','シングルケアラーシート'),
('ja','pricing.plan_primary_f3','トレンドレポート＆PDFサマリー'),
('ja','pricing.plan_primary_f4','メールリマインダー＆ストリークサポート'),
('ja','pricing.plan_primary_feat5','ケアプランビルダー（6セクション）'),
('ja','pricing.plan_primary_feat6','デシジョンエンジン — 深刻度別ギャップ検出'),
('ja','pricing.plan_primary_feat7','メモリーブック — 大切な方の完全なケアプロファイル'),
('ja','pricing.plan_primary_feat8','ケアハブ — 一か所で3つのツールすべてを調整'),
('ja','pricing.plan_primary_name','プライマリケアラー'),
('ja','pricing.plan_primary_price','12.50 USD/四半期（週額1ドル未満）'),
('ja','pricing.recommended','おすすめ'),
-- dementia
('ja','dementia.about_p1','バリー・ライスバーグ博士が開発したグローバル劣化スケール（GDS）は、アルツハイマー病などの原発性変性認知症を患う方の認知機能の段階についての概要をケアラーに提供します。'),
('ja','dementia.about_p2','スケールは認知機能低下なしから非常に重篤な認知機能低下まで7段階を定義します。GDSはアルツハイマー病の方に最も関連し、他の認知症の形態には適用されない場合があります。'),
('ja','dementia.about_title','グローバル劣化スケール（GDS）について'),
('ja','dementia.disclaimer_body','このスケールは情報提供のみを目的とした臨床参照ツールです。専門的な医療アドバイス、診断、または治療の代替ではありません。医療上の懸念については資格を持つ医療提供者に相談してください。'),
('ja','dementia.disclaimer_label','免責事項：'),
('ja','dementia.expected_duration','予想期間'),
('ja','dementia.not_applicable','該当なし'),
('ja','dementia.note_4','この段階では、本人は自分の困難を認識していますが、それを隠したり最小化しようとします。医師は臨床インタビューを通じて問題を検出できます。'),
('ja','dementia.note_5','本人はもはや何らかの支援なしには生活できません。主な個人的事実（自分の名前、子供の名前）の知識は保持していますが、住所や電話番号を忘れている場合があります。'),
('ja','dementia.note_6','本人は最近の出来事や経験にほとんど気づいていません。日常生活のすべての活動に大幅な支援が必要で、常時監督が必要な場合があります。'),
('ja','dementia.note_7','この段階を通じてすべての言語能力が失われます。基本的な精神運動スキルが失われ、寝たきりになります。快適さに重点を置いたケアが優先されます。'),
('ja','dementia.page_title','認知症参照スケール'),
('ja','dementia.s1_name','認知症なし'),
('ja','dementia.s1_title','認知機能低下なし'),
('ja','dementia.s2_name','非常に軽度'),
('ja','dementia.s2_title','非常に軽度の認知機能低下'),
('ja','dementia.s3_name','軽度'),
('ja','dementia.s3_title','軽度の認知機能低下'),
('ja','dementia.s4_name','中等度'),
('ja','dementia.s4_title','中等度の認知機能低下'),
('ja','dementia.s5_name','中等度〜重度'),
('ja','dementia.s5_title','中等度〜重度の認知機能低下'),
('ja','dementia.s6_name','重度'),
('ja','dementia.s6_title','重度の認知機能低下'),
('ja','dementia.s7_name','非常に重度'),
('ja','dementia.s7_title','非常に重度の認知機能低下'),
('ja','dementia.seven_stages','7つの段階'),
('ja','dementia.signs_symptoms','サインと症状'),
('ja','dementia.stage_4','ステージ4'),
('ja','dementia.stage_4_desc','初期認知症'),
('ja','dementia.stage_7','ステージ7'),
('ja','dementia.stage_7_desc','末期認知症'),
('ja','dementia.stages_13','ステージ1〜3'),
('ja','dementia.stages_13_desc','認知症なし'),
('ja','dementia.stages_56','ステージ5〜6'),
('ja','dementia.stages_56_desc','中期認知症'),
-- common
('ja','common.account_disabled','アカウントが無効化されています。'),
('ja','common.and','および'),
('ja','common.auth_required','認証が必要です。'),
('ja','common.back_dashboard','ダッシュボードに戻る'),
('ja','common.complete','完了'),
('ja','common.contact_support','この問題が続く場合はサポートにお問い合わせください。'),
('ja','common.copied','コピーしました！'),
('ja','common.copy','コピー'),
('ja','common.creating','作成中…'),
('ja','common.deleting','削除中…'),
('ja','common.download','ダウンロード'),
('ja','common.error_generic','問題が発生しました。もう一度お試しください。'),
('ja','common.go_back','戻る'),
('ja','common.go_home','ホームに移動'),
('ja','common.incomplete','未完了'),
('ja','common.invite','招待'),
('ja','common.open','開く'),
('ja','common.opening','開いています...'),
('ja','common.optional','任意'),
('ja','common.or','または'),
('ja','common.print','印刷'),
('ja','common.profile_not_found','プロファイルが見つかりません。サポートにお問い合わせください。'),
('ja','common.required','必須'),
('ja','common.result_here','ここに結果が表示されます'),
('ja','common.save_failed','保存に失敗しました'),
('ja','common.saved','保存済み'),
('ja','common.send','送信'),
('ja','common.sign_in','サインイン'),
('ja','common.sign_out','サインアウト'),
('ja','common.skip','スキップ'),
('ja','common.start','開始'),
('ja','common.unnamed_patient','名前のない患者'),
('ja','common.unnamed_resident','名前のない入居者'),
('ja','common.view','表示'),
-- choose_plan
('ja','choose_plan.activate_failed','無料プランを有効にできませんでした。もう一度お試しください。'),
('ja','choose_plan.already_active','すでにアクティブなプランをお持ちです！'),
('ja','choose_plan.auth_required','プランを選択するにはサインインが必要です。'),
('ja','choose_plan.back_dashboard','← ダッシュボードに戻る'),
('ja','choose_plan.cancelled','チェックアウトがキャンセルされました。請求は行われていません。'),
('ja','choose_plan.current_sub','現在のサブスクリプション'),
('ja','choose_plan.current_sub_title','現在のサブスクリプション'),
('ja','choose_plan.free_activated','無料プランが正常に有効になりました！'),
('ja','choose_plan.free_failed','無料プランの有効化に失敗しました。もう一度お試しください。'),
('ja','choose_plan.loading','サブスクリプション情報を読み込んでいます...'),
('ja','choose_plan.manage_billing','請求を管理する'),
('ja','choose_plan.manage_billing_open','開いています...'),
('ja','choose_plan.manage_title','プランを管理する'),
('ja','choose_plan.must_sign_in','プランを選択するにはサインインが必要です。'),
('ja','choose_plan.need_help','選択にお困りですか？サポートチームにお問い合わせください。'),
('ja','choose_plan.no_sub_title','アクティブなサブスクリプションなし'),
('ja','choose_plan.payment_cancelled','お支払いがキャンセルされました。いつでも再試行できます。'),
('ja','choose_plan.payment_success','お支払いが成功しました！サブスクリプションがアクティブになりました。'),
('ja','choose_plan.plan_label','プラン：'),
('ja','choose_plan.renews_on','更新日：'),
('ja','choose_plan.select_below','以下のプランを選択してCarerViewを始めてください。'),
('ja','choose_plan.status_active','アクティブ'),
('ja','choose_plan.sub_cancelled','サブスクリプションがキャンセルされました。'),
('ja','choose_plan.sub_default','サブスクリプションがアクティブではありません。続けるには以下のプランを選択してください。'),
('ja','choose_plan.sub_past_due','サブスクリプションの支払いが延滞しています。'),
('ja','choose_plan.subtitle','介護ニーズに最適なプランを選択してください。'),
('ja','choose_plan.title_choose','プランを選択する'),
('ja','choose_plan.title_manage','サブスクリプションを管理する'),
-- auth
('ja','auth.create_account_link','アカウントを作成'),
('ja','auth.create_account_tab','アカウントを作成'),
('ja','auth.email_first','まず上のメールアドレスを入力してください。'),
('ja','auth.email_label','メールアドレス'),
('ja','auth.err_email_first','まず上のメールアドレスを入力してください。'),
('ja','auth.err_invalid_creds','メールアドレスまたはパスワードが正しくありません。認証情報を確認するか、パスワードをリセットしてください。'),
('ja','auth.err_password_short','パスワードは8文字以上である必要があります。'),
('ja','auth.failed','問題が発生しました。もう一度お試しください。'),
('ja','auth.free_disclaimer','無料プランあり。試すのにクレジットカードは不要です。'),
('ja','auth.free_note','無料プランあり。試すのにクレジットカードは不要です。'),
('ja','auth.get_started','始める'),
('ja','auth.invalid_credentials','メールアドレスまたはパスワードが正しくありません。認証情報を確認するか、パスワードをリセットしてください。'),
('ja','auth.password_label','パスワード'),
('ja','auth.reset_failed','リセットメールの送信に失敗しました。もう一度お試しください。'),
('ja','auth.reset_sending','送信中…'),
('ja','auth.reset_sent','そのメールアドレスがシステムに存在する場合、リセットリンクが送信されました。'),
('ja','auth.sending_reset','送信中…'),
('ja','auth.sign_in_tab','サインイン'),
('ja','auth.signin_failed','サインインに失敗しました。もう一度お試しください。'),
('ja','auth.signup_body','プランを選択してケアラーアカウントを設定してください — 1分ほどかかります。'),
('ja','auth.signup_prompt','プランを選択してケアラーアカウントを設定してください — 1分ほどかかります。'),
('ja','auth.tab_create','アカウントを作成'),
('ja','auth.tab_signin','サインイン'),
('ja','auth.tagline','より明確に、みんなで介護を。'),
('ja','auth.welcome_to','へようこそ'),
-- checkout
('ja','checkout.activating','プランを有効化しています…'),
('ja','checkout.all_set','準備完了'),
('ja','checkout.contact_support_prefix','サポートが必要な場合は、こちらにお問い合わせください：'),
('ja','checkout.finalizing','サブスクリプションを確定しています…'),
('ja','checkout.payment_received','お支払いを受け付けました'),
('ja','checkout.plan_active','{planLabel}プランがアクティブになりました。'),
('ja','checkout.plan_active_gen','プランがアクティブになりました。'),
('ja','checkout.plan_active_named','{plan}プランがアクティブになりました。'),
('ja','checkout.redirecting','ダッシュボードにリダイレクトしています…'),
('ja','checkout.sign_in_btn','サインイン'),
('ja','checkout.sign_in_prompt','サブスクリプションを確認するために再度サインインしてください。'),
('ja','checkout.sign_in_required','サインインが必要です'),
('ja','checkout.signin_body','サブスクリプションを確認するためにサインインしてください。'),
('ja','checkout.signin_required','サインインが必要'),
('ja','checkout.taking_long','予想より時間がかかっています…'),
-- create_account
('ja','create_account.agree_prefix','アカウントを作成することで、以下に同意します'),
('ja','create_account.already_have','すでにアカウントをお持ちですか？'),
('ja','create_account.always_free','常に無料'),
('ja','create_account.cancel_note','。いつでもキャンセルできます。'),
('ja','create_account.choose_plan','プランを選択する'),
('ja','create_account.confirm_email_info','メールを確認してアカウントを認証し、チェックアウトを完了するためにここに戻ってください。'),
('ja','create_account.email_confirm_required','受信トレイを確認してメールを認証してください。ファミリーサークルへの参加を完了するためにここに戻ります。'),
('ja','create_account.email_required','メールアドレスとパスワードが必要です。'),
('ja','create_account.email_taken','そのメールアドレスのアカウントが既に存在します。サインインしてください。'),
('ja','create_account.incomplete_setup_notice','アカウントは作成されましたが、セットアップが完了していません。続けるには以下のプランを選択してください。'),
('ja','create_account.loading','読み込み中…'),
('ja','create_account.name_label','氏名'),
('ja','create_account.name_placeholder','フルネーム'),
('ja','create_account.obs_family','無制限の観察、最大5名のケアラー'),
('ja','create_account.obs_free','年間3回の観察'),
('ja','create_account.obs_primary','無制限の観察、ケアラー1名'),
('ja','create_account.password_placeholder','パスワードを作成'),
('ja','create_account.password_too_short','パスワードは8文字以上である必要があります。'),
('ja','create_account.per_quarter','四半期あたり'),
('ja','create_account.plan_missing_price','このプランは現在購入できません。サポートにお問い合わせください。'),
('ja','create_account.promo_label','プロモコード'),
('ja','create_account.promo_placeholder','プロモコードを入力'),
('ja','create_account.promo_prefix','プロモ：'),
('ja','create_account.section_title','アカウント詳細'),
('ja','create_account.selected_plan','選択したプラン：'),
('ja','create_account.signup_failed','サインアップに失敗しました。もう一度お試しください。'),
('ja','create_account.submit_btn','アカウントを作成'),
-- delete_acct
('ja','delete_acct.body','これにより、アカウントとすべてのデータが完全に削除されます。この操作は取り消せません。'),
('ja','delete_acct.confirm_btn','アカウントを削除'),
('ja','delete_acct.confirm_yes','はい、アカウントを削除します'),
('ja','delete_acct.danger_zone','危険ゾーン'),
('ja','delete_acct.description','アカウントとすべての関連データを完全に削除します。この操作は取り消せません。'),
('ja','delete_acct.dialog_msg','本当によろしいですか？すべての観察、データ、サブスクリプションが完全に削除されます。'),
('ja','delete_acct.dialog_title','アカウントを削除しますか？'),
('ja','delete_acct.failed','アカウントの削除に失敗しました。もう一度お試しください。またはサポートにお問い合わせください。'),
('ja','delete_acct.item_obs','すべての観察と回答'),
('ja','delete_acct.item_profile','プロファイルとアカウント情報'),
('ja','delete_acct.item_sub','サブスクリプションと請求記録'),
('ja','delete_acct.item_team','チームとすべてのケアラー招待'),
('ja','delete_acct.team_block','あなたはアクティブなメンバーがいるチームのオーナーです。アカウントを削除する前に、チームからすべてのメンバーを削除してください。'),
('ja','delete_acct.will_delete','アカウントを削除すると、以下が完全に削除されます：'),
-- subscription
('ja','subscription.active','アクティブ'),
('ja','subscription.cancelled','キャンセル済み'),
('ja','subscription.free','無料'),
('ja','subscription.inactive','非アクティブ'),
('ja','subscription.past_due','支払い延滞'),
('ja','subscription.status_label','サブスクリプション状況'),
-- inactive
('ja','inactive.body','プランが非アクティブです。観察の作成を続けるにはプランを選択してください。'),
('ja','inactive.cta','プランを選択する'),
('ja','inactive.just_paid','支払い済みですか？'),
('ja','inactive.no_sub','アクティブなサブスクリプションがありません。始めるにはプランを選択してください。'),
('ja','inactive.status_error','サブスクリプション状況を読み込めませんでした。'),
('ja','inactive.title','プランが非アクティブ'),
-- guest_invite
('ja','guest_invite.button_label','ゲストケアラー観察を招待'),
('ja','guest_invite.button_tooltip','ゲスト（例：訪問家族）を1回の観察に招待する'),
('ja','guest_invite.copied','コピーしました！'),
('ja','guest_invite.copy_btn','コピー'),
('ja','guest_invite.copy_link_label','このリンクをゲストと共有してください'),
('ja','guest_invite.email_hint','招待リンクがこのアドレスに送信されます。'),
('ja','guest_invite.err_email','有効なメールアドレスを入力してください。'),
('ja','guest_invite.err_generic','問題が発生しました。もう一度お試しください。'),
('ja','guest_invite.err_no_resident','このチームの入居者プロファイルが見つかりません。'),
('ja','guest_invite.err_no_team','アクティブなチームが見つかりません。'),
('ja','guest_invite.form_adl','ADL'),
('ja','guest_invite.form_comprehensive','ADL＋IADL'),
('ja','guest_invite.form_iadl','IADL'),
('ja','guest_invite.form_type_label','観察タイプ'),
('ja','guest_invite.guest_email_label','ゲストのメールアドレス'),
('ja','guest_invite.guest_email_placeholder','guest@example.com'),
('ja','guest_invite.guest_name_label','ゲストの名前'),
('ja','guest_invite.guest_name_placeholder','例：田中花子'),
('ja','guest_invite.link_expires_hint','このリンクは72時間後に失効し、1回のみ使用できます。'),
('ja','guest_invite.no_resident','入居者が設定されていません'),
('ja','guest_invite.resident_label','入居者'),
('ja','guest_invite.send_btn','招待を送信'),
('ja','guest_invite.sent_body','{email}に観察リンク付きのメールが送信されました。'),
('ja','guest_invite.sent_fallback_body','メールを自動的に送信できませんでした。以下のリンクをコピーして、ゲストに直接共有してください。'),
('ja','guest_invite.sent_fallback_title','リンクが作成されました'),
('ja','guest_invite.sent_title','招待が送信されました！'),
('ja','guest_invite.subtitle','一回限りの観察リンクを送信'),
('ja','guest_invite.title','ゲストオブザーバーを招待')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- caregiver
('ja','caregiver.dashboard_title','ダッシュボード'),
('ja','caregiver.delete_failed','観察の削除に失敗しました'),
('ja','caregiver.dementia_desc','グローバル劣化スケール（GDS）— 認知機能低下の7段階'),
('ja','caregiver.dementia_scale','認知症スケール参照'),
('ja','caregiver.export_failed','観察のエクスポートに失敗しました。'),
('ja','caregiver.loading','ケアラーダッシュボードを読み込んでいます...'),
('ja','caregiver.new_observation','新しい観察'),
('ja','caregiver.no_obs_selected','観察が選択されていません'),
('ja','caregiver.obs_deleted','観察が正常に削除されました'),
('ja','caregiver.obs_empty','まだ観察が記録されていません。'),
('ja','caregiver.obs_empty_cta','最初の観察を記録する →'),
('ja','caregiver.obs_view_all','すべての{count}件の観察を見る →'),
('ja','caregiver.payment_success','お支払いが成功しました！サブスクリプションがアクティブになりました。'),
('ja','caregiver.subscriber_tools_heading','サブスクライバーツール'),
('ja','caregiver.subtitle_care_plan','以下にケアプランの進捗が表示されます。'),
('ja','caregiver.subtitle_default','現在のケア活動の概要です。'),
('ja','caregiver.subtitle_memory_book','以下にケアプラン、メモリーブック、観察の進捗が表示されます。'),
('ja','caregiver.subtitle_observations','最近の観察が以下に表示されます。'),
('ja','caregiver.upsell_cp_desc','チームを調整 — 役割、権限、持続可能性'),
('ja','caregiver.upsell_mb_desc','本人を知る — アイデンティティ、健康、好み、連絡先'),
('ja','caregiver.upsell_upgrade_cta','アップグレードしてアクセス'),
('ja','caregiver.view_arrow','表示 →'),
('ja','caregiver.your_obs_body','ケアラーの観察を追跡・管理する'),
('ja','caregiver.your_obs_title','あなたの観察'),
-- dashboard
('ja','dashboard.mb_section_contacts','連絡先'),
('ja','dashboard.mb_section_daily_living','日常生活＆好み'),
('ja','dashboard.mb_section_identity','アイデンティティ'),
('ja','dashboard.mb_section_medical','医療'),
('ja','dashboard.mb_sections_have_content','{total}セクションのうちコンテンツあり'),
('ja','dashboard.mb_subtitle','本人を知る'),
('ja','dashboard.mb_title','メモリーブック'),
('ja','dashboard.medical_allergies','アレルギー'),
('ja','dashboard.medical_conditions','疾患'),
('ja','dashboard.medical_hearing','聴力'),
('ja','dashboard.medical_medications','服薬'),
('ja','dashboard.medical_subtitle','メモリーブックより'),
('ja','dashboard.medical_title','医療サマリー'),
('ja','dashboard.medical_view_link','メモリーブックを見る'),
('ja','dashboard.medical_vision','視力'),
('ja','dashboard.resident_age','{age}歳'),
('ja','dashboard.resident_complete_cta','入居者プロファイルを完成させる →'),
('ja','dashboard.resident_known_as','「{name}」として知られている'),
('ja','dashboard.resident_profile_pct','プロファイル{pct}%完了'),
('ja','dashboard.resident_subtitle','ケアの中心にいる方'),
('ja','dashboard.resident_title','入居者'),
-- admin
('ja','admin.active_caregivers','アクティブなケアラー'),
('ja','admin.admin_label','管理者'),
('ja','admin.admins_only','管理者のみ。'),
('ja','admin.auth_required','認証が必要です。'),
('ja','admin.avg_score','カテゴリー平均スコア'),
('ja','admin.avg_scores_by_category','カテゴリー別平均スコア'),
('ja','admin.checking','セッションを確認中…'),
('ja','admin.delete_user_title','管理者：メールでユーザーを削除'),
('ja','admin.email_ph','user@example.com'),
('ja','admin.error_aggregate','集計データの読み込みに失敗しました'),
('ja','admin.loading','管理者ダッシュボードを読み込んでいます...'),
('ja','admin.loading_aggregate','集計データを読み込んでいます…'),
('ja','admin.loading_editor','翻訳エディターを読み込んでいます…'),
('ja','admin.manage_caregivers','ケアラーを管理する'),
('ja','admin.no_data','データがありません'),
('ja','admin.profile_required','プロファイルが見つかりません。'),
('ja','admin.signed_in_as','サインイン中：'),
('ja','admin.this_week','今週'),
('ja','admin.total_obs','総観察数'),
('ja','admin.trans_empty','翻訳キーが見つかりません。'),
('ja','admin.trans_en_col','英語'),
('ja','admin.trans_es_col','スペイン語'),
('ja','admin.trans_key_col','キー'),
('ja','admin.trans_save_err','保存に失敗しました'),
('ja','admin.trans_saved','保存済み'),
('ja','admin.trans_search_ph','キーまたは値を検索…'),
('ja','admin.trans_title','翻訳管理'),
-- tutorial
('ja','tutorial.bottom_cta','ケアプランを開始する'),
('ja','tutorial.bottom_title','CarerViewサポートの旅を始める'),
('ja','tutorial.callout_body','ガイド付きCarerViewチュートリアルを受けて、ケアプランからメモリーブックまでツールがどのように機能するかを正確に確認してください。約5分かかります。'),
('ja','tutorial.callout_heading','CarerViewを実際に見る'),
('ja','tutorial.cta_restart','チュートリアルを再スタート'),
('ja','tutorial.cta_start','ツアーを開始する'),
('ja','tutorial.nav_step_preview','アプリ機能のガイドツアーを受ける'),
('ja','tutorial.page_subtitle','家族ケアラーのために構築されたコアツールの5ステップクイックウォークスルー。'),
('ja','tutorial.page_title','CarerViewプロセス'),
('ja','tutorial.public_description','数分でメモリーブック、ケアプラン、観察、チームツールをウォークスルー。'),
('ja','tutorial.skip','ツアーをスキップ'),
('ja','tutorial.skip_aria','チュートリアルをスキップ'),
('ja','tutorial.skip_btn','ツアーをスキップ'),
('ja','tutorial.step_label','ステップ {current}/{total}'),
('ja','tutorial.step5_body','ケアはより多くの手で機能します。家族やその他のケアラーをファミリーサークルに追加して、全員が情報を共有し負担を分担できるようにします。'),
('ja','tutorial.step5_title','チームを招待する'),
-- policy (long-form — use abbreviated Japanese summaries for key privacy sections)
('ja','policy.back_home','ホームに戻る'),
('ja','policy.being_finalized','このポリシーは確定中です。近日中にご確認ください。'),
('ja','policy.data_notice','このデータポリシーは、CarerViewがアプリケーションに入力したケアデータ — 観察、評価、ケアを受ける方の個人情報を含む — をどのように扱うかを説明します。このデータの所有権は常にあなたに帰属します。CarerViewはあなたに代わってデータ処理者として機能し、あなたのケアデータをサービス運営以外の目的に使用することは決してありません。このポリシーはプライバシーポリシーとともにお読みください。'),
('ja','policy.data_s1_body','CarerViewで作成するケアデータ — 日々の観察、活動スコア、メモ、評価の回答、ケア受益者に関して記録する個人・医療情報を含む — はあなたのものです。あなたはこのコンテンツのデータ管理者です。CarerViewはあなたの指示にのみ従って処理します。CarerViewはケア記録の内容を商業目的で読んだり、分析したり、使用したりしません。ケアデータが健康または障害に関連する場合、英国GDPR第9条の特別カテゴリーデータとして扱われ、追加の技術的保護措置とアクセス制御で保護されます。'),
('ja','policy.data_s1_title','あなたが作成するデータ'),
('ja','policy.data_s2_body','CarerViewはあなたのケアデータを第三者に販売、賃貸、またはライセンスすることは決してありません。ただし以下の場合を除き、外部組織とケアデータを共有しません：(a) サービス提供に厳密に必要な範囲でサブプロセッサー（ホスティングプロバイダー等）と、拘束力のあるデータ処理契約の下で；(b) あなたがアカウントに招待した他のチームメンバーへのアクセスを明示的に許可した場合；(c) 裁判所命令または規制当局によって法的に強制される場合（この場合、法律の許す範囲でお知らせします）。個人またはケア受益者が特定できない完全に匿名化された集計統計データを、社内サービス改善目的のみに使用する場合があります。'),
('ja','policy.data_s2_title','データの共有'),
('ja','policy.data_s3_body','あなたのケアデータは、CarerViewアカウントがアクティブな間保持されます。アカウントを削除すると、アカウント閉鎖後30日以内に関連するすべてのケアデータを永久かつ取り消し不能で削除します。ただし、法的義務を遵守するために長期間特定の記録を保持する必要がある場合を除きます（例：サブスクリプションに関連する財務記録）。特定のデータの早期削除を希望する場合は、CarerView@GrifDigi.comまでお問い合わせください。バックアップは30日ローリングサイクルで削除され、削除開始後最大30日間残留コピーが存在する場合があります。'),
('ja','policy.data_s3_title','データの保持'),
('ja','policy.data_s4_body','CarerViewに入力したすべてのケアデータの完全でポータブルなコピーを受け取る権利があります。アカウント設定エリアからいつでもデータの完全なエクスポートを生成してダウンロードできます。エクスポートは構造化された形式（DOCX）で提供されます。エクスポートの頻度に制限はなく、費用はかかりません。エクスポートファイルはオンデマンドで生成され、ダウンロード後はサーバーに保存されません。別の形式でのエクスポートが必要な場合や、セルフサービスエクスポートに問題がある場合は、CarerView@GrifDigi.comまでお問い合わせください。'),
('ja','policy.data_s4_title','データのエクスポート'),
('ja','policy.data_s5_body','CarerViewはケア観察および記録ツールです。EU医療機器規則2017/745、英国MDR 2002、またはそれに相当する法律の下での登録済み医療機器、臨床意思決定支援システム、または診断機器ではありません。CarerViewに記録される情報はケアラーによる観察を反映しており、臨床評価または医学的診断として解釈されるべきではありません。CarerView内のいかなる内容も医療アドバイスを構成しません。アプリケーション内の評価スケールおよびスコアリングツールは情報補助としてのみ提供されており、臨床またはケアの決定の唯一の根拠として使用してはなりません。ケアを受ける方に関する医療指導については、常に資格を持つ医療専門家に相談してください。'),
('ja','policy.data_s5_title','健康情報免責事項'),
('ja','policy.priv_notice','このプライバシーポリシーは、CarerView（GrifDigi Ltdが運営）がサービスを使用する際に個人データをどのように収集、使用、保存、保護するかを説明します。英国一般データ保護規則（UK GDPR）および2018年データ保護法に準拠して発行されています。GrifDigi Ltdはあなたが提供する個人データに関してデータ管理者として機能します。このポリシーについてご質問がある場合は、CarerView@GrifDigi.comまでお問い合わせください。'),
('ja','policy.priv_s1_body','以下のカテゴリーの個人データを収集します：(a) アカウントデータ — 登録時の名前、メールアドレス、パスワード；(b) ケア観察データ — ケアを受ける方について入力した構造化観察、メモ、スコア、評価；(c) チームとプロファイルデータ — アカウントに関連するケアラーとケア受益者について提供する情報；(d) 使用・技術データ — サービスの運営と改善のために自動的に収集されるIPアドレス、ブラウザタイプ、デバイス識別子、ログデータ。処理の合法的根拠：契約の履行（サービス提供）；正当な利益（サービスセキュリティの維持と不正防止）；健康関連ケアデータが入力された場合、UK GDPR第9条の要件に従ったあなたの明示的な同意。'),
('ja','policy.priv_s1_title','収集するデータ'),
('ja','policy.priv_s2_body','個人データを以下の目的に使用します：(a) アカウントの作成・管理とアイデンティティ認証；(b) ケア観察の保存・表示を含むCarerViewサービスの提供；(c) アカウント確認、パスワードリセット、サブスクリプション通知などのトランザクションコミュニケーションの送信；(d) 決済プロセッサーStripeを通じた安全な決済処理；(e) サービスパフォーマンスの監視と改善、技術的問題の診断、新機能の開発；(f) 規制当局や法執行機関からの合法的な要求への対応を含む法的義務の遵守。あなたに法的またはそれに類する重大な影響を与える自動意思決定やプロファイリングに個人データを使用することはありません。'),
('ja','policy.priv_s2_title','データの使用方法'),
('ja','policy.priv_s3_body','あなたのデータはSupabase, Inc.が提供するインフラストラクチャに保存され、欧州経済地域と英国内のAmazon Web Services（AWS）データセンターでホストされています。すべてのデータはTLS 1.2以上を使用して転送中に暗号化され、AES-256を使用して保存中に暗号化されます。個人データへのアクセスは、必要最小限の原則に基づいて権限を持つ人員に制限され、多要素認証で保護されています。不正アクセス、偶発的な損失、破壊、変更から保護するための適切な技術的・組織的措置を維持しています。あなたの権利と自由にリスクをもたらす可能性のある個人データ漏洩が発生した場合、漏洩を認識してから72時間以内に情報委員会（ICO）に通知し、法律で要求される場合は速やかにあなたに伝達します。'),
('ja','policy.priv_s3_title','データの保存とセキュリティ'),
('ja','policy.priv_s4_body','UK GDPRの下で、個人データに関して以下の権利を有します：(a) アクセスの権利 — 保有する個人データのコピーを要求できます；(b) 修正の権利 — 不正確または不完全なデータの修正を求めることができます；(c) 消去の権利 — 処理を継続する正当な理由がない場合に個人データの削除を要求できます；(d) 制限の権利 — 特定の状況においてデータの処理制限を求めることができます；(e) データポータビリティの権利 — 構造化された、一般的に使用される、機械可読形式で個人データを受け取ることができます；(f) 異議申し立ての権利 — 正当な利益に基づく処理に異議を申し立てることができます；(g) 自動化意思決定に関する権利 — あなたに重大な影響を与える完全に自動化された決定に従わない権利があります。これらの権利を行使するには、CarerView@GrifDigi.comにお問い合わせください。また、適用法に従ってデータが取り扱われていないと判断した場合、ico.org.ukでICOに苦情を申し立てる権利があります。'),
('ja','policy.priv_s4_title','あなたの権利'),
('ja','policy.priv_s5_body','CarerViewはトラッキング、広告、または分析Cookieを使用しません。サードパーティのCookieをデバイスに配置しません。認証サービスがアクティブなセッション中のサインイン状態を維持するためだけに、厳密に必要なセッションCookieが設定される場合があります。これらはブラウザを閉じるかサインアウトすると削除されます。Cookieを通じて第三者に個人データが送信されることはなく、このポリシーの結果としてCookieの同意バナーは必要ありません。'),
('ja','policy.priv_s5_title','Cookie'),
('ja','policy.questions','ご質問は以下にお問い合わせください'),
-- about
('ja','about.body_p4','私たちの目標は、介護に伴うストレス、孤立、そして静かな圧倒感を和らげることです。ケアラーに明確さがあれば、ケアを受ける方はより良く、より一貫した、より思いやりのある注目を受けられると信じています — そして家族は最も重要なことに集中できます：一緒に過ごす時間に。'),
('ja','about.body_p5','CarerViewは単なるツール以上のものです。母の記憶を称え、同じ旅を歩む他の方々を助けることで、どの家族も一人でそれを乗り越えなくていいようにするための私たちの方法です。'),
('ja','about.cta_body','より明確に、より自信を持ち、より孤立せずに介護をするためにCarerViewを使用している家族に参加してください。新しいケアラーの旅を始め、メモリーブックを構築し、観察を追跡し始めましょう — すべて一か所で。'),
('ja','about.cta_button','始める'),
('ja','about.feature1_body','家族ケアラーになって初めて気づくことは、ガイドがないということです。CarerViewの新しいケアラーガイドは、重要な決断、連絡先、文書、介護手配について説明します — 圧倒的な最初の数週間に重要なことが見落とされないように。'),
('ja','about.feature1_title','新しいケアラーのスタート'),
('ja','about.feature2_body','ケアを受ける方の生きた記録 — アイデンティティ、生い立ち、日常の好み、医療背景、そして彼らにとって重要なルーティン。すべての家族と専門ケアラーが、診断だけでなく、この人が誰であるかという同じ理解から始められます。'),
('ja','about.feature2_title','メモリーブック'),
('ja','about.feature3_body','医療専門家が使用するのと同じADLおよびIADLスケールを使用した、毎日または毎週の構造化されたチェックイン。時間とともに、個々のエントリーが意味のあるトレンド記録を構築します — かかりつけ医、専門家、またはケアチームと共有して、実際に何が変化しているのか、いつから始まったのかを示すことができます。'),
('ja','about.feature3_title','観察'),
('ja','about.features_heading','3つのツール。1つの明確な全体像。'),
('ja','about.origin_heading','CarerViewの始まり'),
('ja','about.page_title','CarerViewについて'),
-- accept_invite
('ja','accept_invite.error_consumed_body','この招待リンクはすでに使用されています。別のチームに参加するつもりだった場合は、新しいリンクを依頼してください。'),
('ja','accept_invite.error_consumed_title','招待がすでに使用済み'),
('ja','accept_invite.error_expired_body','この招待リンクは期限切れです。チームオーナーに新しいリンクを送ってもらってください。'),
('ja','accept_invite.error_expired_title','招待リンクが期限切れ'),
('ja','accept_invite.error_title','参加できません'),
('ja','accept_invite.failed','チームへの参加中に問題が発生しました。もう一度お試しください。'),
('ja','accept_invite.invalid','招待トークンがないか無効です'),
('ja','accept_invite.joining','チームに参加しています…'),
('ja','accept_invite.return_home','ホームに戻る'),
('ja','accept_invite.success','チームへの参加に成功しました。リダイレクトしています…')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- account_menu
('ja','account_menu.billing','請求を管理する'),
('ja','account_menu.delete_acct','アカウントを削除'),
('ja','account_menu.manage','アカウントを管理する'),
('ja','account_menu.manage_account','アカウントを管理する'),
('ja','account_menu.restart_tutorial','チュートリアルを再スタート'),
('ja','account_menu.sign_out','サインアウト'),
('ja','account_menu.tutorial','チュートリアルを再スタート'),
-- active_cg
('ja','active_cg.loading','管理者ビューを読み込んでいます…'),
-- auth_callback
('ja','auth_callback.verifying','リンクを確認しています…'),
-- community_banner
('ja','community_banner.tagline_after','経験を共有し、質問をして、実践的な知恵を見つけましょう。'),
('ja','community_banner.tagline_before','家族と在宅ケアラーのために。'),
-- community
('ja','community.help_type_desc.emotional_support','聞いてもらったり、気持ちを認めてもらいたい'),
('ja','community.help_type_desc.practical_tips','うまくいくアドバイスや戦略を探している'),
('ja','community.help_type_desc.question','助けが必要な具体的な質問がある'),
('ja','community.help_type_desc.resource','役立つものを見つけたので共有したい'),
('ja','community.help_type_desc.similar_experiences','同じような経験をした人はいますか？'),
('ja','community.join.benefit.anonymous','プライバシーが必要なときに匿名で投稿'),
('ja','community.join.benefit.connect','本当に理解してくれるケアラーとつながる'),
('ja','community.join.benefit.share','経験を共有してピアサポートを得る'),
('ja','community.join.inline.description','コミュニティに参加して投稿し、他のケアラーとつながりましょう。'),
('ja','community.loading','コミュニティを読み込んでいます…'),
('ja','community.new_post.anonymous_active_desc','ハンドルは他のユーザーに表示されません。モデレーションのためにアイデンティティは内部で記録されます。'),
('ja','community.new_post.anonymous_desc','コミュニティハンドルが表示されます。他のユーザーから隠すにはトグルしてください。'),
('ja','community.profile.avatar_preview','アバターのプレビュー'),
('ja','community.reply_anon_active_title','匿名モードがオン'),
('ja','community.reply_anon_inactive_title','匿名で投稿'),
-- export
('ja','export.csv_resident_name','入居者名'),
('ja','export.unnamed_resident','名前のない入居者'),
-- family_setup
('ja','family_setup.body','ファミリーサークルプランには最大3名のケアラーが含まれます。共有チームを作成して始めましょう。'),
('ja','family_setup.create_btn','ファミリーサークルを作成'),
('ja','family_setup.creating','作成中…'),
('ja','family_setup.loading','読み込み中…'),
('ja','family_setup.resident_label','誰のケアをしていますか？'),
('ja','family_setup.resident_placeholder','例：お母さん、お父さん、田中さん'),
('ja','family_setup.resident_required','ケアをする方の名前を入力してください。'),
('ja','family_setup.team_name_ph','家族チーム名'),
('ja','family_setup.title','ファミリーサークルを設定する'),
-- footer
('ja','footer.about_link','CarerViewについて'),
('ja','footer.copyright','© {year} CarerView.com | 全著作権所有 | GrifDigi社'),
('ja','footer.location_nz','ニュージーランド、クライストチャーチ'),
('ja','footer.location_us','コロラド州デンバー、USA'),
('ja','footer.locations','所在地：'),
('ja','footer.policies','ポリシー'),
('ja','footer.pricing_link','料金プラン'),
('ja','footer.resources_heading','リソース'),
('ja','footer.suggestions','ご提案・ご質問？'),
('ja','footer.tutorial_link','CarerViewチュートリアル'),
-- lang
('ja','lang.current','言語'),
('ja','lang.switch_aria','言語を切り替える'),
-- nav
('ja','nav.family_circle','ファミリーサークル'),
('ja','nav.home_aria','CarerViewホーム'),
('ja','nav.logo_aria','CarerViewロゴ'),
('ja','nav.manage_billing','請求を管理する'),
('ja','nav.memory_book_short','メモリーブック'),
('ja','nav.toggle_menu','ナビゲーションメニューを切り替える'),
('ja','nav.tutorial_short','チュートリアル'),
('ja','nav.welcome','ようこそ'),
('ja','nav.why_carerview','CarerViewについて'),
-- plan_pill
('ja','plan_pill.family','ファミリーサークル'),
('ja','plan_pill.primary','プライマリ'),
-- reset_pw
('ja','reset_pw.confirm_ph','新しいパスワードを再入力'),
('ja','reset_pw.err_mismatch','パスワードが一致しません。もう一度お試しください。'),
('ja','reset_pw.err_too_short','パスワードは8文字以上である必要があります。'),
('ja','reset_pw.new_pw_label','新しいパスワード'),
('ja','reset_pw.new_pw_ph','新しいパスワードを入力'),
('ja','reset_pw.no_token','リカバリートークンが見つかりませんでした。新しいパスワードリセットを要求してください。'),
('ja','reset_pw.submit_btn','パスワードを更新'),
('ja','reset_pw.submitting','更新中…'),
('ja','reset_pw.success','パスワードが正常に更新されました！サインインにリダイレクトしています...'),
-- scale
('ja','scale.1','完全自立'),
('ja','scale.2','困難だが自立'),
('ja','scale.3','サポートありで自立'),
('ja','scale.4','常時共同作業'),
('ja','scale.5','全介助'),
-- team_guard
('ja','team_guard.upgrade_body_default','ファミリーサークルプランでは、共有ケアチームを構築し、家族を招待し、全員を同じページに保つことができます。'),
('ja','team_guard.upgrade_body_primary','プライマリケアラープランはソロケアラーに最適です。ファミリーサークルプランにアップグレードして、家族を招待し、介護の旅を共に分かち合いましょう。'),
('ja','team_guard.upgrade_cta','ファミリーサークルにアップグレード'),
('ja','team_guard.upgrade_title','ファミリーサークルはチーム機能です'),
-- team
('ja','team.caregivers_title','ケアラー'),
('ja','team.copy_link_note','今すぐメールにコピーしてください。'),
('ja','team.invite_email_ph','caregiver@email'),
('ja','team.invite_expires_on','このリンクは{date}に失効します。その後、新しい招待を生成する必要があります。'),
('ja','team.invite_link_label','招待リンク：'),
('ja','team.loading','読み込み中…'),
('ja','team.no_members','メンバーがまだいません。'),
('ja','team.no_team','最初にファミリーサークルを作成してください。'),
('ja','team.title','ファミリーサークル'),
-- welcome
('ja','welcome.dismiss_aria','ウェルカムメッセージを閉じる')
ON CONFLICT (locale, namespace, key) DO NOTHING;

INSERT INTO ui_translations (locale, key, value) VALUES
-- billing
('ja','billing.loading','請求情報を読み込んでいます…'),
('ja','billing.manage_btn','請求を管理する'),
('ja','billing.not_active','アクティブなサブスクリプションなし'),
('ja','billing.period_ends','現在の期間終了'),
('ja','billing.portal_failed','請求ポータルを開けませんでした。もう一度お試しください。'),
('ja','billing.status_label','ステータス：'),
('ja','billing.title','請求とサブスクリプション'),
-- public.caregiver_resources
('ja','public.caregiver_resources.bridge_heading','あなたは一人ではありません'),
('ja','public.caregiver_resources.bridge_intro_1','多くのケアラーは同じ場所から始まります — 不確かで、圧倒され、方向を探しています。'),
('ja','public.caregiver_resources.bridge_intro_2','ガイドを読むことも役立ちますが、同じ経験をしている人々の声を聞くことも助けになります。'),
('ja','public.caregiver_resources.bridge_view_discussion','ディスカッションを見る'),
('ja','public.caregiver_resources.final_cta_body','他の方から学んでください。そして、CarerViewで自分のケアプランをコントロールしましょう。'),
('ja','public.caregiver_resources.final_cta_heading','読むだけでなく — ケアの整理を始めましょう'),
('ja','public.caregiver_resources.final_cta_primary_btn','始める'),
('ja','public.caregiver_resources.final_cta_secondary_btn','コミュニティを探索する'),
('ja','public.caregiver_resources.hero_heading','認知症・記憶ケアのためのケアラーリソース'),
('ja','public.caregiver_resources.hero_intro_1','記憶障害や認知症のある方のケアが初めての場合、圧倒されるかもしれません。すべてを自分で解決する必要はありません。'),
('ja','public.caregiver_resources.hero_intro_2','以下は、何を期待するか、先を計画する方法、サポートを受ける方法を理解するのに役立つ信頼できる組織と政府リソースです。'),
('ja','public.caregiver_resources.how_to_bullet_1','政府ガイドから始めて状態を理解する'),
('ja','public.caregiver_resources.how_to_bullet_2','サポートと現実世界の助けのために非営利団体を利用する'),
('ja','public.caregiver_resources.how_to_bullet_3','準備ができたら地域のサービスとサポートグループを探す'),
('ja','public.caregiver_resources.how_to_closing','一度にすべてを使用する必要はありません。1つから始めて積み重ねていってください。'),
('ja','public.caregiver_resources.how_to_heading','これらのリソースの使い方'),
('ja','public.caregiver_resources.how_to_intro','各リソースは異なる目的に役立ちます：'),
('ja','public.caregiver_resources.meta_desc','認知症・記憶ケアのための信頼できるケアラーリソース。新しいケアラーが始めるためのシンプルなガイド、サポート団体、計画ツール。'),
('ja','public.caregiver_resources.mid_cta_body','ガイドは役立ちますが、実際の経験も重要です。他のケアラーが何を質問し、共有しているかを見てください。'),
('ja','public.caregiver_resources.mid_cta_btn','コミュニティを探索する'),
('ja','public.caregiver_resources.mid_cta_heading','他のケアラーから学ぶ'),
('ja','public.caregiver_resources.page_title','認知症・記憶ケアのためのケアラーリソース | CarerView'),
('ja','public.caregiver_resources.res1_desc','認知症ケアが初めての方向けに設計された米国政府ウェブサイト。何を期待するか、どのように準備するか、どこでサポートを受けるかを説明します。次に何をすべきかわからない場合に最適な出発点の一つです。'),
('ja','public.caregiver_resources.res1_domain','alzheimers.gov'),
('ja','public.caregiver_resources.res1_title','Alzheimers.gov'),
('ja','public.caregiver_resources.res2_desc','アルツハイマーと記憶に関する疾患について、明確で研究に基づいた情報を提供します。介護、健康変化、ケアラーとしての自己ケアに関する実用的なガイドが含まれています。'),
('ja','public.caregiver_resources.res2_domain','nia.nih.gov'),
('ja','public.caregiver_resources.res2_title','米国老年医学研究所'),
('ja','public.caregiver_resources.res3_desc','ケアラーサポート、教育、24時間365日のヘルプラインを提供する主要な非営利団体。地域のサポートグループを見つけ、いつでも誰かと話し、ケアの異なる段階のステップバイステップガイドにアクセスできます。'),
('ja','public.caregiver_resources.res3_domain','alz.org'),
('ja','public.caregiver_resources.res3_title','アルツハイマー協会'),
('ja','public.caregiver_resources.res4_desc','教育、記憶スクリーニング、コミュニティプログラムを含むケアラーへの実用的なサポートに焦点を当てています。実践的なガイダンスと精神的サポートを求める家族に役立ちます。'),
('ja','public.caregiver_resources.res4_domain','alzfdn.org'),
('ja','public.caregiver_resources.res4_title','アメリカアルツハイマー財団'),
('ja','public.caregiver_resources.res5_desc','認知症のある方のケアを含むすべてのタイプのケアラーへのサポートを提供します。長期計画、ケアラーの権利、時間をかけたストレス管理に強い焦点を当てています。'),
('ja','public.caregiver_resources.res5_domain','caregiver.org'),
('ja','public.caregiver_resources.res5_title','家族ケアラーアライアンス'),
-- public.community
('ja','public.community.join_modal_body','無料アカウントを作成して、質問をし、経験を共有し、他のケアラーとつながりましょう。'),
('ja','public.community.join_modal_create_btn','無料アカウントを作成'),
('ja','public.community.join_modal_signin_btn','サインイン'),
('ja','public.community.join_modal_title','コミュニティに参加する'),
('ja','public.community.popular_topics_heading','人気のスタータートピック'),
('ja','public.community.popular_topics_intro','ケアラーが始めたばかりのときに最もよく聞く質問。'),
('ja','public.community.topic1_excerpt','突然、記憶障害のある親の責任を負うことになり、何を最初に優先すべきかわかりません。'),
('ja','public.community.topic1_title','ケアラーになったばかりです。どこから始めればいいですか？'),
('ja','public.community.topic2_excerpt','自宅での管理と外部の助けを得ることの間で決断しようとしています。'),
('ja','public.community.topic2_title','より多くのケアが必要なタイミングをどうやって知ることができますか？'),
('ja','public.community.topic3_excerpt','振り返ってみると、もっと早く計画しておけばよかったと思うことは何ですか？'),
('ja','public.community.topic3_title','新しいケアラーとして何に驚きましたか？'),
('ja','public.community.topics_browse_all','すべてを閲覧'),
('ja','public.community.topics_see_resources','リソースを見る')
ON CONFLICT (locale, namespace, key) DO NOTHING;
-- Add why.faq1-5 and FAQ section heading keys that were hardcoded in WhyCarerView.tsx
-- English rows (canonical source text)
INSERT INTO ui_translations (locale, key, value) VALUES
  ('en', 'why.faq_section_title', 'Frequently Asked Questions'),
  ('en', 'why.faq_section_subtitle', 'Common questions about CarerView, care planning, and coordination.'),
  ('en', 'why.faq1_q', 'What is an Activities of Daily Living (ADL) assessment?'),
  ('en', 'why.faq1_a', 'An Activities of Daily Living (ADL) assessment measures how well a person can perform basic self-care tasks such as bathing, dressing, eating, and moving around. CarerView uses a simple 1-5 scale so family caregivers can track these changes consistently over time and share meaningful reports with healthcare providers.'),
  ('en', 'why.faq2_q', 'How does CarerView help family caregivers track changes in a loved one?'),
  ('en', 'why.faq2_a', 'CarerView provides structured observation forms covering ADL and IADL activities. You record a quick 1-5 score and optional notes for each check-in. Over time, these build into a clear picture of what''s changing — so you can spot trends, adjust care plans, and arrive at doctor appointments with specific, documented observations rather than vague impressions.'),
  ('en', 'why.faq3_q', 'Can multiple family members use CarerView together?'),
  ('en', 'why.faq3_a', 'Yes. The Family Circle plan allows you to invite siblings, spouses, or professional in-home carers to a shared care view. Everyone sees the same observations and can add their own. This eliminates the friction that commonly causes stress in families sharing caregiving responsibilities.'),
  ('en', 'why.faq4_q', 'Can I share CarerView observation reports with doctors or care professionals?'),
  ('en', 'why.faq4_a', 'Yes. CarerView can export your observation history as a DOCX or CSV file that you can bring to GP appointments, specialist consultations, or care reviews. Having a written record of changes over weeks and months is far more useful to healthcare providers than trying to recall how things were three months ago.'),
  ('en', 'why.faq5_q', 'How is CarerView different from a general care notes app?'),
  ('en', 'why.faq5_a', 'CarerView is a full care coordination system — not just a notes app. It includes a structured Care Plan with six sections, a Decision Engine that flags missing pieces by severity, a Memory Book that gives every team member instant context, and an observation framework based on the ADL and IADL scales used by healthcare professionals.')
ON CONFLICT (locale, namespace, key) DO NOTHING;

-- Japanese translations
INSERT INTO ui_translations (locale, key, value) VALUES
  ('ja', 'why.faq_section_title', 'よくある質問'),
  ('ja', 'why.faq_section_subtitle', 'CarerView、ケアプランニング、コーディネーションに関するよくある質問。'),
  ('ja', 'why.faq1_q', '日常生活動作（ADL）評価とは何ですか？'),
  ('ja', 'why.faq1_a', '日常生活動作（ADL）評価は、入浴・着替え・食事・移動などの基本的なセルフケア動作をどの程度できるかを測定するものです。CarerViewでは1〜5のシンプルなスケールを使い、家族介護者が経時的に変化を一貫して記録し、医療従事者に意味のある報告書を共有できます。'),
  ('ja', 'why.faq2_q', 'CarerViewは、家族介護者が愛する人の変化を追跡するのにどのように役立ちますか？'),
  ('ja', 'why.faq2_a', 'CarerViewは、ADLとIADL活動を対象とした構造化された観察フォームを提供します。チェックインごとに1〜5のスコアと任意のメモを記録します。時間の経過とともに何が変化しているかの明確な全体像が形成され、傾向の把握、ケアプランの調整、そして漠然とした印象ではなく具体的な記録を持って医師の予約に臨むことができます。'),
  ('ja', 'why.faq3_q', '複数の家族がCarerViewを一緒に使用できますか？'),
  ('ja', 'why.faq3_a', 'はい。ファミリーサークルプランでは、兄弟姉妹、配偶者、または専門の在宅介護者を共有のケアビューに招待できます。全員が同じ観察記録を見て、それぞれが追加することもできます。これにより、介護の責任を分担する家族間でよく起こる摩擦をなくすことができます。'),
  ('ja', 'why.faq4_q', 'CarerViewの観察レポートを医師や介護専門家と共有できますか？'),
  ('ja', 'why.faq4_a', 'はい。CarerViewは観察履歴をDOCXまたはCSVファイルとしてエクスポートでき、かかりつけ医の予約、専門医の診察、またはケアレビューに持参できます。数週間から数ヶ月にわたる変化の書面記録は、3ヶ月前の状態を思い出そうとするよりも、医療従事者にとってはるかに役立ちます。'),
  ('ja', 'why.faq5_q', 'CarerViewは一般的なケアメモアプリとどう違うのですか？'),
  ('ja', 'why.faq5_a', 'CarerViewは単なるメモアプリではなく、総合的なケアコーディネーションシステムです。6つのセクションからなる構造化されたケアプラン、欠けている部分を重要度別にフラグ立てするデシジョンエンジン、チームメンバー全員に即座にコンテキストを提供するメモリーブック、そして医療専門家が使用するADLおよびIADLスケールに基づいた観察フレームワークが含まれています。')
ON CONFLICT (locale, namespace, key) DO NOTHING;
